valora-inc/wallet

scripts/key_placer.sh

Fix warning about missing file when running `yarn keys:decrypt`
`yarn keys:decrypt` doesn't show warning about missing file.
Yes

Fix warning in key_placer script

---

packages/blockchain-api/src/blockscout.ts
packages/blockchain-api/src/events/Any.ts
packages/blockchain-api/src/transaction/TransactionAggregator.ts

When a transaction can't be properly classified based on the list of transfers, it should be reported rather than silently ignored. Fixes celo-org/celo-monorepo#6997.
Yes.
Yes. The invalid transaction is still being ignored, this change improves logging and visibility on data issues.

Throw error when handling unknown transaction types

---

packages/mobile/locales/en-US/walletFlow5.json
packages/mobile/locales/es-419/walletFlow5.json
packages/mobile/locales/pt-BR/walletFlow5.json
packages/mobile/src/app/actions.ts
packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/firebase/notifications.test.ts
packages/mobile/src/firebase/notifications.ts
packages/mobile/src/navigator/Navigator.tsx
packages/mobile/src/transactions/CeloTransferFeedItem.tsx
packages/mobile/src/transactions/TransactionReview.test.tsx
packages/mobile/src/transactions/TransactionReview.tsx
packages/mobile/src/transactions/TransferConfirmationCard.tsx
packages/mobile/src/transactions/TransferFeedItem.tsx
packages/mobile/src/transactions/actions.ts
packages/mobile/src/transactions/utils.ts
packages/mobile/test/schemas.ts

As part of the Coinbase advanced earn campaign they'll be sending CELO to user's addresses, so we're making some tweaks to the review screen and adding an educational screen to educate them on what we're building
The changes wanted (and future oens) are documented on this doc: https://docs.google.com/document/d/1GYSiFKtwMguQxZtoZvOgJfdI7XyX--gFwdm5pmSY4T8/edit?ts=601b43e1#
- Refactored the way feature flags are fetched from Firebase to make it easier to add new ones.
- The header of the review screen was being calculated and sent as a prop to the review screen, which made little sense. Moved it to the review screen where it belongs.
Manually
- Fixes #6
N/A

Small UI changes to CELO deposit review screen

---

packages/mobile/src/fiatExchanges/RampScreen.tsx
packages/moonpay-auth/src/index.ts

We needed to use `encodeURIComponent` instead of `encodeURI` to properly encode our redirect links.
N/A
Manually
N/A
Yes

Fix CICO provider redirect bug

---

packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/home/NotificationBox.tsx

Adding this id to this event will allows us to know engagement with each individual notification. Right now we have only a generic 'remote_notification' type.
Manually.
- Fixes #62
No, we won't be able to track clicks by individual notification in previous versions of the app.

Add notification id to analytics event HomeEvents.notification_select

---

packages/mobile/android/app/proguard-rules.pro

InAppBrowser was crashing. The error was this: https://sentry.io/organizations/celo/issues/2241119154/?project=1250733&query=is%3Aunresolved&statsPeriod=14d
which matches what someone else was seeing here: https://github.com/proyecto26/react-native-inappbrowser/issues/174 and the solution was to add the proguard rules.
N/A
No. My Android device is not working properly right now 😓  I'll keep trying, but if someone can test this in release mode that would be great.
- Fixes https://github.com/celo-org/wallet/issues/70
N/A

Add proguard rules for InAppBrowser on Android

---

packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
packages/mobile/src/utils/time.ts

In this version, we had added a `nextDistribution` field to Firebase. For some reason, it was under the `content` item, which made no sense and caused the app to crash in older versions because it was expecting a string before.
This `nextDistribution` was the date when the next CELO rewards distribution would be made. This is always the following Monday, since that's the cutoff date, so instead of having that value on Firebase now we are just calculating it in the client directly. This will make sure it's always up to date and we don't forget to update it as well.
Manually.
- Fixes #64
Yes

Change the way cutoff for rewards is calculated

---

packages/blockchain-api/src/blockscout.ts
packages/blockchain-api/src/events/EscrowReceived.ts
packages/blockchain-api/src/events/EscrowSent.ts
packages/blockchain-api/src/events/Faucet.ts
packages/blockchain-api/src/events/TokenReceived.ts
packages/blockchain-api/src/events/TokenSent.ts
packages/blockchain-api/src/events/Verification.ts
packages/blockchain-api/src/helpers/EventBuilder.ts
packages/blockchain-api/src/schema.ts
packages/blockchain-api/test/blockscout.test.ts
packages/blockchain-api/test/mockTokenTxs.ts

Adds the new `account` field that exposes the account address associated with the wallet address currently returned in the `address` field.
Fixes #6268 and https://github.com/celo-org/blockscout/pull/171
Relevant blockscout changes: https://github.com/celo-org/blockscout/pull/178 and https://github.com/celo-org/blockscout/pull/210
Yes.

Added the account field

---

packages/mobile/scripts/sync_branding.sh

I merged another PR with an error on the branding repo :( Fixed on the other one and by changing the hash here.
This should have probably been caught by CI, I assume it didn't because CI runs with the celo branding rather than the valora branding. Maybe there's something we could do there to avoid this in the future.

Fix hash from branding repo

---

.circleci/config.yml
packages/blockchain-api/test/blockscout.test.ts
packages/notification-service/test/firebase.test.ts

After moving out of the monorepo, looks like tests for packages other than mobile were not running. Added those tests again.
N/A
See that the tests are running now under `general-test`
- N/A
N/A

Add tests for non-wallet packages to CI

---

packages/mobile/src/components/FeeDrawer.tsx

Currently, the font size of the lines on the dropdown menu for fees in the Send confirmation screen is `small` (14px). Present PR changes this font size to `regular` (16px).
This alters every FeeDrawer instance, including confirmation screens during the Exchange, Withdraw, and Transfer flows.
Note that TotalLineItem.tsx has not been altered, and the conversion-rate line below totals remains size `small` as requested.
Tested by sight on the simulator app. Examined both the confirmation screen in the Send flow and the Transaction Review screen from the home feed.
- Fixes #111 
N/A

Changed font size in FeeDrawer to regular (#111)

---

packages/mobile/locales/en-US/fiatExchangeFlow.json
packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/app/selectors.ts
packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/flags.ts
packages/mobile/src/utils/countryFeatures.test.ts
packages/mobile/test/schemas.ts

Added two new cash in/out providers for Brazil. These integrations are just a link to a WebView for those providers like the ones we have for Ponto and Kotani.
N/A
Manually by using a  BR number (and checking it doesn't show up for other countries)
- Fixes #7449
N/A

Add Bitfy and FlowBTC as providers for Brazil

---

packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx
packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeOptions.test.tsx.snap
packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
packages/mobile/src/fiatExchanges/utils.tsx

This PR allows all users to cash-in CELO (previously it was only allowed if Moonpay was enabled in their region).
- Sorts provider options by availability
- Comments out Transak as we've yet to clear its KYB check
Manual - more to be added in subsequent PR
- Fixes #144 
Yes

Enable CELO cash-in for all users

---

packages/mobile/locales/en-US/walletFlow5.json
packages/mobile/src/invite/saga.test.ts
packages/mobile/src/invite/saga.ts

When an escrow payment is sent to an unverified number, the transaction now shows the contact name (will still display `Unknown` if phone number used is not in contacts, this will be fixed with the CIP8 PRs). Previously, these transactions were showing as `Unknown` because we weren't storing invitee information when the `ESCROW_WITHOUT_CODE` feature flag is set.
changed default escrow payment comment to "Invite Sent"
yes, on Android
- Fixes #46 
Yes

Display escrow payment details

---

packages/mobile/locales/en-US/fiatExchangeFlow.json
packages/mobile/src/fiatExchanges/CashInSuccess.tsx
packages/mobile/src/fiatExchanges/__snapshots__/CashInSuccess.test.tsx.snap

Copy + formatting changes to CICO success screen

Edits to CICO success screen

---

packages/notification-service/src/blockscout/transfers.ts
packages/notification-service/src/firebase.ts

There are two changes here:
- Reduce the number of blocks we look back at to wait for blockscout indexing from 600 (50 minutes) to 80 (6.6 minutes).
- Make the fetching of payment requests and registrations more efficient by only fetching what's new or changed instead of everything all the time.
N/A
Locally and in Alfajores.
- Fixes #193
N/A

Make some performance improvements to notification-service

---

packages/mobile/locales/en-US/accountScreen10.json
packages/mobile/src/account/Settings.tsx
packages/mobile/src/account/StoreWipeRecoveryScreen.tsx
packages/mobile/src/account/__snapshots__/Settings.test.tsx.snap
packages/mobile/src/account/actions.ts
packages/mobile/src/account/reducer.ts
packages/mobile/src/account/saga.ts
packages/mobile/src/account/selectors.ts
packages/mobile/src/analytics/Events.tsx
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/import/ImportWallet.test.tsx
packages/mobile/src/import/ImportWallet.tsx
packages/mobile/src/import/saga.test.ts
packages/mobile/src/import/saga.ts
packages/mobile/src/navigator/Navigator.tsx
packages/mobile/src/navigator/Screens.tsx
packages/mobile/src/navigator/types.tsx
packages/mobile/src/onboarding/registration/NameAndPicture.tsx
packages/mobile/src/pincode/PincodeEnter.tsx
packages/mobile/src/pincode/authentication.ts
packages/mobile/src/utils/accountChecker.ts
packages/mobile/test/schemas.ts

When we detect that there is no account stored on the Redux store but there is one on the geth wallet, it means that the Redux store was unexpectedly wiped. To recover from this situation, this PR adds a new screen notifying the user that there's been a user and letting them know that they'll need to input their name and phone number again.
We'll be able to skip the name step in the future when CIP-8 lands.
https://user-images.githubusercontent.com/6062888/113381557-a6826a00-9355-11eb-8291-3d983c9b5b6f.mov
- Added an option to the hidden dev settings to erase the Redux store in order to be able to test this.
Manually using the hidden dev setting.
- Fixes #189
N/A

Add flow for recovering access to account if Redux store is wiped

---

packages/mobile/src/account/StoreWipeRecoveryScreen.tsx
packages/mobile/src/navigator/types.tsx
packages/mobile/src/utils/accountChecker.ts
packages/mobile/src/utils/contentTranslations.ts

There was an error caused by the language not being reset after the store wipe recovery flow. This PR redirects the user to the language selection screen if we can't autodetect the language when on the store wipe recovery flow.
Manually
- Fixes #189
N/A

Choose language before starting recovery flow

---

packages/mobile/src/navigator/DrawerNavigator.tsx

Analytics event `drawer_navigation` was using a localized value for `navigateTo` which made analysis difficult.
It's now using the actual programmatic screen name.
Yes
- Fixes https://github.com/celo-org/celo-monorepo/issues/7651
No, might break existing reporting.

Fix analytics `drawer_navigation` event

---

.circleci/config.yml
package.json
packages/mobile/.gitignore
packages/mobile/e2e/config.json
packages/mobile/package.json
yarn.lock

Add [jest-html-reporter](https://www.npmjs.com/package/jest-html-reporter "Jest HTML Reporter") and [jest-junit](https://www.npmjs.com/package/jest-junit) reporters for easier analysis of the e2e test runs.
- Modified `packages/mobile/e2e/config.json` to utilize additional features of both reporters.
- Modified `packages/mobile/.gitignore` to prevent tracking of test result files.
Changes were tested by running the iOS and Android e2e test suites and checking the test reporter outputs in the `wallet/packages/mobile/test-results` folder.
These changes should have no affect on the wallet repo outside of running e2e tests.

test: add jest-html and jest-junit reporters

---

package.json
yarn.lock

A new vulnerability was published recently in the y18n package: https://www.npmjs.com/advisories/1654
I tried in PR https://github.com/celo-org/wallet/pull/177 to upgrade the packages that are using the old version of y18n but it quickly went out of control to the point where the codegen library would break other parts of the code. I've spent some time trying to upgrade everything except for the codegen lib (which is needed in the notification service) but the change became really messy. So, I decided to just use the force resolution mechanism for now.
None
Build and run tests locally.
- Fixes #174 
Yes.

Force y18n version 5.0.5

---

packages/mobile/src/exchange/reducer.ts
packages/mobile/src/firebase/saga.ts
packages/mobile/src/redux/migrations.test.ts
packages/mobile/src/redux/migrations.ts
packages/mobile/src/redux/store.ts

We had a bug in the fetching of the exchange rates that made us fetch the whole thing every time there was an update, which is every 30 minutes. The number of elements to fetch each time depended on how much time it passed since the last use of the app, for new users and for users that didn't open the app in a couple months we would load all the history for three months.
We were also fetching the whole exchange rate history from Firebase and filtering it in memory instead of only fetching the latest three months. We tried to filter, but we were sending `1` as `startAt` which returns everything.
With the current changes, we load everything since the max between the last update and three months ago and then we listen only for new items, we don't reload everything again.
- Added a migration …

Fix the fetching of exchange rates

---

packages/notification-service/src/config.ts
packages/notification-service/src/firebase.ts
packages/notification-service/src/invites/invites.ts
packages/notification-service/src/polling.ts

Some users were receiving a large number of push notifications when someone they invited joined Valora.
The reason is that we were not updating the `lastInviteBlockNotified` correctly if the notified block was the last notified + 1. This issue was introduced recently here: https://github.com/celo-org/wallet/pull/244
Added a `type` for invite redeemed notifications.
Manually
- Fixes #278
N/A

Fix sending of "invite received" notification

---

.circleci/config.yml

Fix `general-tests` randomly failing on CircleCI with exit code 137.
This happened on `celo-monorepo` too: https://github.com/celo-org/celo-monorepo/commit/d2bcf42cb96c6a23bf08dd9f21dec7948aeb188f
`general-tests` is green on CircleCI.
Yes.

Bump `resource_class` to `large` to fix `general-tests` randomly failing with exit code 137

---

packages/mobile/src/analytics/Events.test.tsx
packages/mobile/src/analytics/Events.tsx

Fix incorrect analytics event sent when choosing restore account.
See Slack thread: https://celo-org.slack.com/archives/CL7BVQPHB/p1620135124192500
Added a test to ensure this won't happen in the future.
On the `Welcome` screen with the `Create` and `Restore` buttons, tapping the `Restore` button should log an analytic event stating `restore_account_start`.
N/A

[Wallet] Fix incorrect analytics event sent when choosing restore account

---

packages/mobile/src/config.ts
packages/mobile/src/escrow/EscrowedPaymentListScreen.tsx
packages/mobile/src/escrow/__mocks__.ts
packages/mobile/src/escrow/reducer.ts
packages/mobile/src/home/NotificationBox.tsx
packages/mobile/src/home/selectors.ts

In this PR: https://github.com/celo-org/wallet/commit/f0fc5e55a3d10568253a878abb555b7beb76f6b3 we started showing escrow invites as soon as they are sent. However, this brings an issue because it can't be reclaimed immediately, you need to wait at least one hour.
N/A
Manually, I invited people and they don't show up on the invite box for one hour.
Invite someone and see that they don't show up in the invite box. After one hour they should appear and the payment must be reclaimable.
- Fixes #350
N/A

Don't show invites until they can be reclaimed

---

packages/mobile/src/account/profileInfo.test.ts
packages/mobile/src/account/profileInfo.ts
packages/mobile/src/send/saga.ts
packages/mobile/src/web3/dataEncryptionKey.ts

If the account address of the recipient is known, use that address to grant CIP8 profile access
not tested

Use account address when giving CIP8 profile access

---

packages/mobile/src/analytics/ValoraAnalytics.ts

There was an error about missing Google services plist when running `yarn test:e2e:ios` locally with decrypted secrets.
This was because the analytics class tried to initialize Firebase even when `FIREBASE_ENABLED` was `false`, which is the case for the e2e run.
Note: This didn't happened on CI because the secrets are not decrypted there and the analytics class was not trying to do anything (`SEGMENT_API_KEY` being empty).
`yarn test:e2e:ios` works locally.
N/A
Yes

Fix error running iOS e2e test locally

---

packages/mobile/src/identity/securityCode.test.ts
packages/mobile/src/identity/securityCode.ts

Fix `getAttestationCodeForSecurityCode` not logging error details.
Also handle case where no matching issuer is found and add unit tests.
Added unit tests.
1. Start verification process
2. Manually input incorrect verification codes on purpose
3. Check app logs and ensure `identity/verification@attestationCodeReceiver :: Error processing attestation code` shows the real error and NOT `unknown`
- Fixes #371
Yes

[Wallet] Fix `getAttestationCodeForSecurityCode` not logging error details

---

packages/mobile/src/analytics/ValoraAnalytics.ts
packages/mobile/src/identity/securityCode.test.ts
packages/mobile/src/identity/securityCode.ts
packages/mobile/src/identity/verification.ts

- Add logging of error message for `tryRevealPhoneNumber`. This will add more context for the `Status code: 422` errors in the logs
- Standardize error messaging of `tryRevealPhoneNumber`for analytics purpose. Including issuer URL in the analytics error was making it difficult to group identical errors that were happening across several different issuers
N/A
N/A
N/A
N/A
Yes

Add logging for `tryRevealPhoneNumber`

---

packages/mobile/src/identity/securityCode.ts
packages/mobile/src/identity/verification.ts
packages/mobile/src/verify/saga.ts

- Set the MTW during onboarding so that it can be used to reclaim escrow (and other things probably).
- Make a delay a bit larger to avoid race condition.
- Avoid calling the verification saga more than once by not calling `fetchOnChainData` when an attestation is completed.
- Make sure a lock is released when an error happens.
- Add more logs in general.
N/A
Manually, I invited myself and reclaimed a few times. I temporarily changed the code of the send flow a bit to allow me to invite my phone number even though I already have an account.
- Invite a new phone number to join Valora
- Redeem the invite and reclaim the funds.
- Fixes #357
- Fixes #313
N/A

Verification fixes

---

packages/mobile/src/identity/actions.ts
packages/mobile/src/identity/reducer.ts
packages/mobile/src/identity/smsRetrieval.ts
packages/mobile/src/identity/verification.ts

When codes are autopasted on Android, they were sometimes being duplicated. I fixed this in two places:
- In the SMS receiver listener.
- In the reducer so as to prevent other duplication issues in the future. This code really needs a big refactoring to make it more consistent.
N/A
Locally. It's hard to reproduce consistently so I changed the code temporarily to test so that the paste code callback is called with the same code 3 times and made sure that only the first one is handled.
Verify using Android and make sure that the autopasted codes are not repeated.
- Fixes #390
N/A

Prevent repeated code from being pasted in Android

---

packages/mobile/src/fiatExchanges/FiatExchangeAmount.test.tsx
packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
packages/mobile/src/fiatExchanges/FiatExchangeOptions.tsx
packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap

Fixes a bug in which users that had the app set to a currency besides cUSD were erroneously being shown an error message stating they were attempting to cash out an amount smaller than they had as a balance. This was because we were incorrectly handling conversions between cUSD and the user's in-app currency.
- Eliminated ability for user to select `Bank account` as a withdrawal option if they select `CELO` as the currency to cash out
- Fixed a bug in which `crypto` amount that was being passed to `ProviderOptionsScreen` was incorrect when the cash-out asset was `cUSD`. We were erroneously passing through the amount the user inputted to cash out, which was the local currency not `cUSD`. This was put in place for future use and wasn't causing any live issues
Add many unit tests to cover …

Fix cash-out limit balance calculation with non-USD currencies

---

packages/mobile/scripts/run_app.sh

Fork-exec to try to start terminal, falling back to running packager in existing terminal. This fixes the previous behavior
which blocked until the newly created terminal process returned.
Manually on Linux.

Fix Linux support in run_app.sh

---

packages/mobile/src/walletConnect/saga.ts

- implements `eth_signTypedData`
- adds minimal additional error handling which should now be propagated as a response
- Manually via `use-contractkit` and by extending the `run-in-memory-client.ts` script in the `celo-monorepo` (in [this small PR](https://github.com/celo-org/celo-monorepo/pull/7951))
- Fixes celo-org/celo-monorepo#7514
cc @medhak1 as this changes some of the structure in the `acceptRequest` function in `../saga.ts`, assuming that will be relevant for `personal_decrypt` or the other json RPC methods you're implementing!

[WalletConnect] implement eth_signTypedData

---

packages/mobile/src/account/RaiseLimitScreen.tsx
packages/mobile/src/account/__snapshots__/RaiseLimitScreen.test.tsx.snap
packages/mobile/src/firebase/firebase.ts

The description text in the `RaiseLimitScreen` was flipped for verified and unverified users. Not it isn't
N/A
Manually, went to the screen (see screenshots)
Go to the raise limit screen and check that the text there makes sense with your verification status.
- Fixes #407
N/A

Update text of RaiseLimitScreen

---

packages/mobile/src/recipients/recipient.test.ts
packages/mobile/src/recipients/recipient.ts

See https://github.com/celo-org/wallet/issues/34.
Updated unit tests and ad hoc testing in an emulator.
* Add a phone number with a country code.  E.g., `+41 044 668 18 00`.
* Phone number should render the same as it was entered instead of the international format.  E.g., `+41 044 668 18 00` instead of `044 668 18 00`.`
Fixes https://github.com/celo-org/wallet/issues/34

Display contact phone numbers in the same format they are saved in

---

package.json
yarn.lock

The vulnerabilities check has been failing lately. Updated a few packages to make it pass.
N/A
CI passes
Make sure everything in general works well
- Fixes #
N/A

Update resolutions to fix vulnerabilities

---

packages/blockchain-api/src/blockscout.ts

The argument parameter was incorrect as according to the doc it should be `AddressHash`. The new version of blockscout is stricter and validates it.
Tested on rc1.
Copy the whole query and test it on the graphql page of blockscout https://explorer.celo.org/graphiql.
n/a
Yes.

Fixed the blockscout query parameter type

---

packages/mobile/src/verify/revealAttestations.ts
packages/mobile/src/verify/saga.ts

The banner informing the user of how many text messages were being resent was based on the count of non-completed attestations, which can be greater than the number of attestations required to confirm a phone number.
Time of `lastRevealAttempt` was being updated even when no new attestations were being revealed. This resulted in the user having to wait 1 min to re-request a text message if even none were on the way.
Manually
- Ensure the banner shows the right number of text messages requested
- If the confirmation process is started (i.e., the user reaches the `VerificationCodeInputScreen`), then the user leaves the flow and resumes the confirmation process, ensure that the user is not forced to wait 1 min before requesting more attestations 
- Fixes #458
Yes

Fix miscount in attestation rerequest banner

---

.circleci/config.yml
.github/workflows/checks.yml
SETUP.md
packages/blockchain-api/test/blockscout.test.ts
packages/cloud-functions/package.json
packages/dev-utils/package.json
packages/indexer/package.json
packages/komencikit/package.json
packages/moonpay-auth/package.json
packages/notification-service/package.json

Node 10 is end of life, therefore upgrading to 12.
I had to run yarn test -u to upgrade the snapshots, which is a bit worrying. Still looking into why.
Update: I am pretty sure this is caused by this change https://v8.dev/features/stable-sort, which makes array.sort stable.
I will not make any more changes to this PR but I will follow up with a new one that makes the mock timestamps unique, so we avoid this type of confusion in the future.
This affects the app as well as these packages: notification-service, moonpay-auth, komencikit, indexer, dev-utils, cloud-functions.
Of course it's hard to make sure nothing breaks so we should proceed carefully.
First, people need to upgrade to node 12 locally. Something like:
`nvm install 12.22.1 && nvm use 12.22.1`
Then, just to be safe I would do a: …

Upgrade to node 12

---

packages/mobile/ios/Podfile.lock
packages/mobile/package.json
yarn.lock

Update `@celo/client` to v1.3.2-stable (https://github.com/celo-org/celo-blockchain/commit/91993404cdf69ff4dad810bae8ac02763ae667d8) to address a [security issue](https://github.com/celo-org/celo-blockchain/releases/tag/v1.3.2).
Can sync and send transaction on mainnet and alfajores.
- Disable "Data Saver Mode" in the settings and check the app works as expected with the blockchain (can send transactions, exchange CELO, etc).
- Fixes #337
Yes

[Wallet] Update @celo/client to v1.3.2-stable

---

.github/workflows/checks.yml

This PR implements the vulnerability check from CircleCI to GitHub Actions. Later PR will implement caching and other optimizations. 
This is replacing the CircleCI config. As long as it does the same thing and passes it doesn't need to be tested further.
No testing needed, just need to verify it passes.
- Implements #522.
GitHub Actions will be replacing CircleCI.

Add vulnerability check to GitHub Actions

---

packages/notification-service/app.alfajores.yaml
packages/notification-service/app.mainnet.yaml
packages/notification-service/locales/en.json
packages/notification-service/src/blockscout/transfers.ts
packages/notification-service/src/firebase.ts
packages/notification-service/src/util/utils.ts
packages/notification-service/test/transfers.test.ts

Added cEUR support to the notification service so that a notification is sent when a cEUR transfer is made.
Updated the node env to 12.
Manually using two phones.
Send cEUR to another device. Check that you receive a push notification in the recipient's device.
- Fixes #652
N/A

Add cEUR transfer support to notification service

---

packages/mobile/locales/en-US/consumerIncentives.json
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx

From the issue description:
```
https://github.com/celo-org/wallet/blob/main/packages/mobile/locales/en-US/consumerIncentives.json#L3
should say
"summary": "Starting now, you’ll earn up to {{percent}}% annually on your cUSD balance.",
instead of
"summary": "Starting {{date}}, you’ll earn {{percent}}% annually on your cUSD balance.",
```
N/A
Manually (See screenshot)
Check that the correct text shows up in the rewards screen
- Fixes #https://github.com/celo-org/celo-monorepo/issues/8197
N/A

Update text on rewards screen

---

packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
packages/mobile/src/components/CurrencyDisplay.tsx
packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
packages/mobile/src/send/SendConfirmation.test.tsx
packages/mobile/src/transactions/TransactionFeedItem.tsx
packages/mobile/src/transactions/TransferFeedItem.test.tsx
packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
packages/mobile/src/utils/formatting.ts
packages/mobile/test/utils.ts

Changed the behavior of `CurrencyDisplay` so that it can show an extra decimal if the amount is lower than 0.01 for stable currencies.
The rules for this are [in this Figma file](https://www.figma.com/file/31HUGhIHLXEm1qwVpHV1QR/CELO-Rewards?node-id=1401%3A45988), copying here for simplicity:
```
Rewards under $0.01:
We can expand to three decimal places if the reward is less than $0.01. 
If the amount is below $0.001, then display “+<$0.001”.
Note: It would be ideal to apply this scheme to all transaction amounts in the Home Feed. We currently show $0.00 for small amounts.
```
N/A
Added unit test and manually (see screenshot)
Make transactions to yourself for values between 0.01 and 0.001 and for values lower than 0.001 and see that the expected behavior is observed. To do this, one …

Show more decimals in feed for values lower than 0.01

---

packages/mobile/src/transactions/transferFeedUtils.ts

This change is fixing this crash:
https://sentry.io/organizations/celo/issues/2499735012/?project=1250733&query=is%3Aunresolved
The crash was introduced on this PR: https://github.com/celo-org/wallet/pull/656 when switching to redux toolkit. The new toolkit uses `immer` under the hood which makes the objects immutable and  we were using Object.assign in some places 
N/A
Manually
Use the app to send to some people so that the recipients cache is populated and then just try to send to someone. The app should never crash.
- Fixes #837
N/A

Fix crash due to redux immutability

---

packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.test.ts
packages/blockchain-api/src/currencyConversion/CurrencyConversionAPI.ts

Fixed regression introduced in #259 causing Valora clients to get an error loading their transaction feed when the local currency is set to `EUR` and they have `CELO` transactions in their history that were done before May.
Specifically, when converting from `EUR` to `CELO` (or vice versa), it tried to use the `cEUR/cGLD` (or `cGLD/cEUR`) rate we store in firebase.
However we only have data for these pairs since May or so, and hence can't use that for `EUR` to `CELO` prior to that date.
The fix implemented here is simple. An improvement would be to check the requested timestamp to determine whether we can use the `cEUR/cGLD` (or `cGLD/cEUR`) rate or fallback to the current fix.
Tested on Alfajores.
Have some `CELO` transactions in your feed created before May and local currency set to …

[BlockchainApi] Fix feed error when local currency is EUR

---

packages/mobile/src/exchange/ExchangeScreenHeader.tsx

Fix for this issue found by QA: https://github.com/celo-org/wallet/issues/851
In short, in the exchange amount screen, when a user has the keyboard open to input an amount and they tap on the header the balance picker was showing below the keyboard. We're now hiding the keyboard when the header is tapped.
N/A
On iOS and Android
Go to the exchange screen and try to change the currency to do the exchange with. The keyboard should close when tapping on the header.
- Fixes #851
N/A

Hide keyboard when selecting currency to exchange

---

packages/mobile/src/account/__snapshots__/FiatExchange.test.tsx.snap
packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
packages/mobile/src/import/__snapshots__/ImportWallet.test.tsx.snap
packages/mobile/src/utils/formatting.ts

Fix for this issue: https://github.com/celo-org/wallet/issues/850
In short, if the user has exactly 0 balance, we now show 0.00 instead of <0.000.
The issue was introduced in this PR: https://github.com/celo-org/wallet/pull/659
N/A
Manually
Create a new account. See that the balance shows up as exactly 0.
- Fixes #850
N/A

Show 0.00 instead of <0.000 when an amount is exactly 0

---

packages/mobile/e2e/init.js
packages/mobile/e2e/src/usecases/OffRamps.js
packages/mobile/e2e/src/usecases/OnRamps.js
packages/mobile/e2e/src/usecases/SecureSend.js
packages/mobile/e2e/src/usecases/Send.js
packages/mobile/scripts/run_e2e.sh

Skip failing assertions on send comments & wait for providers to display. Errors from these tests can be seen on [this run](https://github.com/celo-org/wallet/actions/runs/1012122805).
Tests run locally on iOS and Android. Ci Tests runs observed in GitHub Actions.
Observe test results on PR's and check for test flake

E2E test improvements / CI fixes

---

packages/mobile/src/components/AccountNumber.tsx
packages/mobile/src/components/__snapshots__/AccountNumber.test.tsx.snap
packages/mobile/src/fiatExchanges/ExternalExchanges.tsx
packages/mobile/src/navigator/DrawerNavigator.tsx
packages/mobile/src/transactions/UserSection.tsx

If `touchDisabled` is not true in the Account Number component, a touchable `Tap to Copy` link is automatically shown below the account number.

Make account number Tap to Copy link touchable

---

packages/mobile/src/app/saga.test.ts
packages/mobile/src/walletConnect/walletConnect.ts

As a safe guard, decode URL encoded WalletConnect deep links.
N/A
By opening these deep links.
https://use-contractkit.vercel.app or with the `scripts/run-in-memory-client.ts` script in the monorepo.
N/A
URI decoding is backwards compatible 👍

chore: decodeURIComponent for WalletConnect deep links

---

packages/mobile/src/exchange/ExchangeScreenHeader.tsx
packages/mobile/src/exchange/ExchangeTradeScreen.tsx
packages/mobile/src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap

When a user doesn't have a cEUR balance, if they try to sell CELO they can now sell the CELO for cEUR as well.
The issue with the title not saying 'Sell CELO' is also fixed with this change.
Manually
With an account that has no cEUR balance, go to the CELO tab and press `Sell`. See that you can tap on the header so that you sell CELO for cEUR.
- Fixes #872
- Fixes #865
N/A

Allow selling CELO for cEUR even if user doesnt have a balance

---

packages/mobile/src/utils/time.ts

Looking at the logs provided in https://github.com/celo-org/wallet/issues/544 I noticed that when the clock sync check fails the drift is always 20 seconds. Then looking at the ntp library we are using here https://github.com/artem-russkikh/react-native-ntp-client/blob/master/lib/ntp-client.js it looks like the default timeout for the request is 10 seconds. Because we attempt 2 requests to 2 different ntp servers these add up to 20 seconds. Then the check fails because we want to be within 4 seconds. So if something is wrong with the network such as packet loss or udp port being blocked (which is pretty common on mobile devices) the check would always fail. Now it would be interesting to see what actually caused the timeout in this case.
The fix sets the ntp timeout to 2 seconds.
Of …

Fix clock sync

---

packages/cloud-functions/package.json
packages/cloud-functions/src/cico/composeProviderUrl.ts
packages/mobile/ios/Podfile.lock
packages/mobile/package.json
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/fiatExchanges/CashInSuccess.tsx
packages/mobile/src/fiatExchanges/saga.ts
yarn.lock

Add a `cash_in_success` analytics event to the CICO success screen. Also addressed a bug where the provider name was not being capitalized.
- Updated the `webview` and `firebase functions` packages
- Added to the Xanpool url to specify that it's being displaying in a webview
- Added an `externalTransactionId` to the Moonpay url to allow for higher data fidelity
Manually
N/A
- Fixes #888
Yes

Add CICO success event

---

.vscode/launch.json

Remove VSCode configs for packages no longer in the repo.
No.
N/A.
N/A.
N/A.
N/A.

Remove VSCode configs for packages no longer in the repo

---

.github/workflows/test.yml
packages/mobile/package.json

This PR implements the mobile tests check from CircleCI to GitHub Actions. Later PR will implement caching and other optimizations. Mobile tests from Circle has also been broken into two actions, one for mobile tests and one for vulnerability check.
This is replacing the CircleCI config. As long as it does the same thing and passes it doesn't need to be tested further.
No testing needed, just need to verify it passes.
- Implements #521.
- Replaces #518.
GitHub Actions will be replacing CircleCI.

Add mobile check

---

packages/mobile/README.md
packages/mobile/scripts/sync_branding.sh

The `valora-app-branding` repo was moved from `clabs-co` to `valora-inc`. This PR reflects this.

Update references to `valora-app-branding` location on GitHub

---

packages/cloud-functions/src/bigQuery.ts
packages/cloud-functions/src/cico/Moonpay.ts
packages/cloud-functions/src/cico/Ramp.ts
packages/cloud-functions/src/cico/Simplex.ts
packages/cloud-functions/src/cico/Transak.ts
packages/cloud-functions/src/cico/Xanpool.ts
packages/cloud-functions/src/cico/fetchProviders.ts
packages/cloud-functions/src/cico/fetchUserLocationData.ts

Reduce the number of `console.error` calls so that it happens at most once per failed quote request. This will allow for better log filtering and reporting.
N/A
N/A
N/A
- Fixes #444 
N/A

Edit CICO quote failure logging for better alerting

---

packages/cloud-functions/src/cico/Moonpay.test.ts
packages/cloud-functions/src/cico/Moonpay.ts
packages/cloud-functions/src/cico/Ramp.test.ts
packages/cloud-functions/src/cico/Simplex.ts
packages/cloud-functions/src/cico/Transak.test.ts
packages/cloud-functions/src/cico/Transak.ts
packages/cloud-functions/src/cico/Xanpool.test.ts
packages/cloud-functions/src/cico/Xanpool.ts
packages/cloud-functions/src/config.ts

This PR does two things to make make the quote fetching cloud-function handle errors a little better:
1. Add an explicit check for an error from the Simplex quote endpoint. It appears that Simplex doesn't always properly change the response status code to reflect an error so we need to explicitly check for an error object
2. Short circuit cEUR quote fetching for providers that don't support cEUR
N/A
Yes
N/A
N/A
Yes

Modify quote fetching for better error handling

---

packages/mobile/src/exchange/WithdrawCeloReviewScreen.tsx

A small fix for #939 to prevent the user from being able to tap withdrawal twice triggering a double withdrawal.
Tested locally on iOS and Android Emulators
1. Start a withdrawal and attempt to tap the button multiple times to trigger a double withdrawal
2. Start a withdrawal and when prompted for the pin entry click bank and see that withdrawal becomes enabled again.
- Fixes #939
This is a minor change and should be backward compatible

Use isLoading to disable withdrawal button

---

packages/mobile/locales/en-US/walletFlow5.json
packages/mobile/src/config.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/recipients/reducer.ts
packages/mobile/src/recipients/saga.ts
packages/mobile/src/transactions/TransactionReview.tsx
packages/mobile/src/transactions/TransferFeedItem.tsx
packages/mobile/src/transactions/transferFeedUtils.ts
packages/mobile/test/schemas.ts

We are now fetching the list of `inviteRewardsSenders` from Firebase to show the correct name/description from transactions coming from addresses used to distribute invite rewards.
- Changed `CELO_LOGO_URL` to use a jpeg with a white background.
Manually
- Invite someone to Valora (in alfajores only for now) 
- Verify with their phone number and claim the money sent
- Check that you received the reward in the account you used to send the invitation
- Verify that the sender of the invite reward says "CELO Network" and the description "Reward received"
- Fixes #986

Label invite rewards correctly in the feed

---

packages/mobile/locales/en-US/walletFlow5.json
packages/mobile/src/escrow/EscrowedPaymentListItem.test.tsx
packages/mobile/src/escrow/EscrowedPaymentListItem.tsx
packages/mobile/src/escrow/ReclaimPaymentConfirmationScreen.tsx
packages/mobile/src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
packages/mobile/src/escrow/saga.ts
packages/mobile/src/tokens/saga.ts

Add support for cEUR invites in pending invites. The pending invites flow (showing, reminding and reclaiming) had cUSD hard-coded, now it correctly uses the invite token.
N/A
Manually
- Invite someone using cEUR. 
- See that the invite in the pending invitations list shows up with the correct amount.
- Check that the copy when pressing 'Remind' says 'Celo Euros'
- Check that you can reclaim the invite correctly.
- Fixes #977
N/A

Some cEUR invite fixes

---

.vscode/launch.json

Remove komencikit VSCode config since komenci has been removed from this repo.
No.
N/A.
N/A.
N/A.
N/A.

Remove komencikit VSCode config

---

packages/mobile/fastlane/Fastfile

Add prepare_testflight_and_upload lane to Fastfile to upload iOS builds to TestFlight in release-bundler.
No.
Tested in https://github.com/valora-inc/release-bundler/actions/runs/1175084552.
Unneeded.
N/A.
N/A.

Add prepare_testflight_and_upload lane to Fastfile

---

packages/mobile/src/onboarding/registration/RegulatoryTerms.tsx

This updates the terms of service link shown during onboarding.
See https://valora-app.slack.com/archives/CL7BVQPHB/p1630331670018800
This is cherry-picked from the [1.18.1 release branch](https://github.com/valora-inc/wallet/tree/release/wallet/1.18.1).

Use valora terms of service link

---

packages/mobile/src/walletConnect/saga.ts
packages/mobile/src/web3/saga.ts

In the WalletConnect integration we are returning the MTW address instead of the EOA. This is super dangerous! Users that connect using WalletConnect might end up making transactions to the MTW address and recovering the funds might be a bit painful (they wouldn't be lost, but it would be annoying).
N/A
Using [use-contractkit](http://use-contractkit.vercel.app/)
Hard to test because [the public version of use-contractkit](http://use-contractkit.vercel.app/) doesn't work (I tested with a local version with some minor changes). If it did work one could simply connect your account in that website and check that the address listed is the EOA.
- Fixes #1075
N/A

Return EOA address on WalletConnect

---

packages/mobile/locales/en-US/consumerIncentives.json
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap

Just copy changes to the rewards screen
N/A
Manually
Go to the rewards screen and make sure you see the right copy.
- Fixes #998
N/A

Change copy of rewards screen

---

packages/mobile/fastlane/Fastfile

Ruby why. I didn't know that there was a difference between single and double quotes in Ruby but apparently single quotes removes the ability to do string interpolation. Undoing a driveby change from #1039.
Just this.
Will be tested shortly but should work.
N/A.
N/A.
N/A.

Fix Ruby String Interpolation 

---

packages/mobile/locales/en-US/nuxVerification2.json
packages/mobile/src/verify/VerificationLoadingScreen.tsx
packages/mobile/src/verify/__snapshots__/VerificationLoadingScreen.test.tsx.snap

Collaborated with Lukas and Nitya to change the copy during phone number verification so that it's clear to the user that they should not background the app while waiting for phone number verification
manually tested
- Fixes #12

#12 change copy on phone verification screen

---

packages/mobile/fastlane/Fastfile

Fix path to Apple Connect p8 certificate. This was depending on a file in the release-automation repo but is going to be created dynamically during the build using Google Secrets Manager. This is preparing for that.
No.
N/A.
N/A.
N/A.
N/A.

Fix path to Apple Connect p8 certificate

---

packages/mobile/fastlane/Fastfile

Adopt Google Secrets Manager for key id and issuer id. This PR depends on https://github.com/valora-inc/release-automation/pull/14.
No.
https://github.com/valora-inc/release-automation/runs/3615862714?check_suite_focus=true
N/A.
N/A.
N/A.

Adopt Google Secrets Manager for key id and issuer id

---

packages/mobile/locales/en-US/walletConnect.json
packages/mobile/src/navigator/NavigationService.ts
packages/mobile/src/navigator/Navigator.tsx
packages/mobile/src/navigator/Screens.tsx
packages/mobile/src/navigator/types.tsx
packages/mobile/src/qrcode/utils.ts
packages/mobile/src/walletConnect/screens/Loading.tsx
packages/mobile/src/walletConnect/screens/Result.tsx
packages/mobile/src/walletConnect/v1/saga.ts
packages/mobile/src/walletConnect/v2/saga.ts
packages/mobile/src/walletConnect/walletConnect.ts

Added a loading screen and an error screen for the WalletConnect flow and a success message when everything goes well.
Figma file: https://www.figma.com/file/U1Xd3uOPGFfcZnYeLMhx0o/Wallet-Connect-Fixes?node-id=606%3A291
There are a few differences with the designs:
- When running into an error, there is no 'retry' button. The retry needs to be done from the dapp, so it's just a 'go back' button (and therefore removed the 'Cancel' button since it does the same thing).
- In the success case, instead of creating a screen I am showing a success message using the top notification thing. The reason for this is that when using dapps we're often signing a lot of things and having that screen there all the time might get annoying. There were two buttons in the mockup, 'Manage connections' and …

Add Loading & success/error messages for WalletConnect

---

packages/mobile/fastlane/Fastfile

Related to https://github.com/valora-inc/release-automation/pull/15. Switching certificate path to environment variable stored in Google Secrets Manager.
No.
Not needed.
N/A.
N/A.
N/A.

Switch certificate path to environment variable

---

packages/mobile/e2e/src/usecases/Support.js

A few small fixes to the E2E tests to make them less flakey:
- Add wait to hamburger menu item for support tests
- Ran locally and in CI - [Results for this PR in the actions tab
](https://github.com/valora-inc/wallet/actions/workflows/e2e.yml?query=branch%3Atomm%2Fe2e-fixes)
This change is to e2e tests only and is backwards compatible.

Fix for Flakey E2E Test

---

packages/mobile/e2e/src/Exchange.spec.js
packages/mobile/e2e/src/usecases/ExchangeCelo.js
packages/mobile/e2e/src/usecases/OffRamps.js
packages/mobile/e2e/src/utils/utils.js
packages/mobile/src/transactions/TransactionFeed.tsx
packages/mobile/src/transactions/__snapshots__/TransactionFeed.test.tsx.snap
packages/mobile/src/transactions/__snapshots__/TransactionsList.test.tsx.snap

More deterministic e2e tests for CELO exchange
- Check for total balance update
- Better check that error message is not thrown
- Check that new feed item is present
- Retries x4 - Once #1043 is resolved this should be able to be removed.
- Added a utility method for checking for the error banner.
- Update `OffRamps.spec.js` `Then Send To Address` test to used better assertion method.
- Update `OffRamps.spec.js` to use bbd syntax.
Tests run locally & observed in CI.
N/A
This change is backwards compatible.

Update Exchange e2e tests

---

packages/mobile/locales/en-US/onboarding.json
packages/mobile/src/account/Profile.tsx
packages/mobile/src/import/ImportWallet.tsx
packages/mobile/src/navigator/Navigator.tsx
packages/mobile/src/navigator/types.tsx
packages/mobile/src/onboarding/registration/NameAndPicture.tsx
packages/mobile/src/pincode/PincodeSet.tsx
packages/mobile/src/verify/VerificationEducationScreen.tsx
packages/mobile/src/verify/VerificationInputScreen.tsx
packages/mobile/src/verify/VerificationLoadingScreen.tsx

Create new account flow has a total of 3 onboarding steps while restoring account has an additional onboarding step of importing the wallet. Therefore, fixing the title of the onboarding flow. 
Manually tested, see screenshot attached
- Fixes #394

fixing create account steps

---

packages/mobile/locales/en-US/walletConnect.json
packages/mobile/src/app/ErrorMessages.ts
packages/mobile/src/walletConnect/saga.ts
packages/mobile/src/walletConnect/screens/ActionRequest.tsx
packages/mobile/src/walletConnect/screens/SessionRequest.tsx

- Disable WalletConnect v2 since it's not working anyways and it was causing a crash when scanning QR codes on Android
- Fix a UI glitch when pressing the `X` button in the WC approval screens.
N/A
Manually on Android
- Connect on https://celo-walletconnect.vercel.app/ and see that you're able to without problems.
- Try to connect on https://use-contractkit.vercel.app/ and see that you get an error code message.
- Fixes #1186
N/A

WalletConnect fixes

---

packages/mobile/src/analytics/Events.tsx
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/dappkit/DappKitAccountScreen.tsx
packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
packages/mobile/src/dappkit/dappkit.ts

This PR adds tracking events for the DappKit flow.
Checked correct analytics events were triggered when using [Moola](https://moola.market/) and [Ubeswap](https://ubeswap.org/)
No need to test this.
- Fixes #1198
Yes

Add analytics events for DappKit

---

packages/mobile/.eslintrc.js
packages/mobile/tsconfig.eslint.json

A few of our linter options require a full AST. So even though we don't compile
all the ts files we still need to tell eslint how to generate an AST.
This is most relevant to developers using an IDE plugin the linting.

Tweak mobile's .eslintrc.js config to parse all the ts{x} files

---

packages/mobile/src/home/WalletHome.test.tsx
packages/mobile/src/home/WalletHome.tsx
packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
packages/mobile/src/home/selectors.ts

Cleaned up the logic to decide when the `NotificationBox` should show up or not. The logic was already implemented in the `NotificationBox` itself but was repeated with a bug on the `WalletHome`. I just removed the check from `WalletHome`.
Removed some old code around section headers (none of them have headers)
Manually locally.
Dismiss all non-remote notifications and check that remote notifications still show up.
You should also go through the CELO education screens since that was also required before for remote notifications not to show up 🍝  
- Fixes #1230
N/A

Clean up in-app notification showing logic

---

packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
packages/mobile/e2e/src/usecases/OnRamps.js
packages/mobile/e2e/src/usecases/ResetAccount.js
packages/mobile/e2e/src/usecases/SetAccountKey.js
packages/mobile/fastlane/metadata/android/en-US/full_description.txt
packages/mobile/src/analytics/Events.tsx
packages/mobile/src/backup/BackupComplete.tsx
packages/mobile/src/backup/BackupIntroduction.tsx
packages/mobile/src/backup/selectors.test.ts
packages/mobile/src/backup/utils.ts
packages/mobile/src/import/ImportWallet.tsx

Replace `account key` with `Recovery Phrase` in error messages, comments, tests, etc.

Replace "account key" with "Recovery Phrase" throughout the codebase

---

packages/mobile/android/app/build.gradle

Adds [Leak Canary](https://square.github.io/leakcanary) to Android Dev builds to help spot memory leaks.
N/A
Android Dev build running and Leak Canary reporting results.
1. Run Valora on Android in Dev Mode.
2. Navigate to device home screen and open 'Leaks'.
N/A
- Fixes #1344
Leak canary only runs in dev builds and is backwards compatible.

Add Leak Canary

---

.github/workflows/test.yml
packages/cloud-functions/package.json
packages/notification-service/package.json

- Adjust test command in notification-service and cloud-functions to produce coverage reports.
- Fixes path to coverage reports from notification-service, cloud-functions and react-components packages. 
- These coverages should now be tracked by Codecov.
Tests run locally with `yarn run lerna --ignore @celo/mobile run test` from the wallet root.
N/A
This change is backwards compatible as it only impacts the creation and uploading of coverage reports.

Add more coverage reports

---

packages/mobile/locales/en-US/fiatExchangeFlow.json
packages/mobile/src/transactions/TransferFeedItem.test.tsx
packages/mobile/src/transactions/__snapshots__/TransferFeedItem.test.tsx.snap
packages/mobile/src/transactions/transferFeedUtils.ts

Fixes issue where cEUR purchases from providers were displaying with cUSD text.
- Added snapshot test for cEUR received.
- Unit test added and run.
Using [Ramp Staging](https://ri-widget-staging.firebaseapp.com/) select cEUR and follow the default purchase flow. When selecting payment options select 'manual bank transfer'. If issue arise refer to [Releasing Purchases Manually](https://ri-widget-staging.firebaseapp.com/).
- Fixes https://github.com/valora-inc/support-issues/issues/37
This change is backwards compatible.

CEUR display from providers

---

packages/mobile/src/send/SendConfirmationLegacy.tsx

Load the balance only once for the SendConfirmationScreen so that it doesn't pick up any balance changes from completed transactions and potentially throw an error.
I couldn't come up with an easy way to add a unit test for this bug, suggestions welcome! 
Manually test by following the repro steps on https://github.com/valora-inc/wallet/issues/1341 and seeing that the bug no longer repros. 
- Fixes # https://github.com/valora-inc/wallet/issues/1341
The balance is never refreshed during this flow anyways, so there should be no unintended side effects from only loading it once.

Fix SendConfirmation screen insufficient funds bug

---

packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/app/selectors.ts
packages/mobile/src/firebase/featureFlagDefaults.e2e.ts
packages/mobile/src/firebase/featureFlagDefaults.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/flags.ts
packages/mobile/src/redux/migrations.ts
packages/mobile/src/redux/store.ts
packages/mobile/src/send/Send.tsx
packages/mobile/src/send/saga.test.ts
packages/mobile/src/send/utils.test.ts
packages/mobile/src/send/utils.ts
packages/mobile/test/schemas.ts

Added three feature flags to remote config:
- multiTokenShowHomeBalances: If enabled, the total balance will be shown in the home screen, including all supported tokens.
- multiTokenUseSendFlow: If enabled, the send flow will use the new flow that supports multiple tokens except for payment requests
- multiTokenUseUpdatedFeed: If enabled, the feed will use the new feed using the new endpoints.
For now only `multiTokenUseSendFlow` works, `multiTokenShowHomeBalances` needs the changes in #1294 and `multiTokenUseUpdatedFeed` is still a WIP
Changed the firebase remote config fetch time to 0 since we are already waiting an hour to call that function from outside.
Manually
No need for QA to test this specifically I think since they don't have access to Firebase but to test you need to change …

Add feature flags to use for some multi-token support features

---

packages/mobile/src/tokens/saga.test.ts
packages/mobile/src/tokens/saga.ts

We're querying for user balances even if there's no address in the store (address === null). This is causing errors in `blockchain-api` since you can't query the endpoint with a `null` address.
N/A
unit test
No need to test this specifically
- Fixes #1424
N/A

Don't try to fetch user balances if there's no address in the store

---

packages/mobile/README.md

When I was setting up the project locally, I found that we don't really need access to celo-testnet and there is a broken link for instructions on logging in with google credentials - I added the official google cloud docs for this as I couldn't find the corresponding readme in the celo project (I found those were helpful enough to get me started, but please let me know if there is a better link to use!)
N/A
N/A
N/A
N/A
N/A

update mobile readme google cloud instructions

---

packages/mobile/src/paymentRequest/PaymentRequestConfirmation.tsx

Changes payment request confirmation from a class based component to a functional component.
N/A
Locally tested on iOS and Android and existing unit tests are passing.
Requester: account making the request
Giver: account receiving the request
1. From requester send a payment request to the giver - no comment.
2. On requester see that the request is populated in the requests call to action (CTA).
3. From giver see that the request is received.
1. From requester add a comment and send payment request.
2. On requester see that the request is populated in the requests call to action (CTA).
3. From giver see that the request is received.
1. From requester go back from the payment request screen
2. Request amount input loads.
Prerequisite for - #1395
This change is backwards compatible.

Convert Payment Request Confirmation to Functional Component

---

packages/mobile/src/exchange/ExchangeConfirmationCard.test.tsx
packages/mobile/src/exchange/ExchangeConfirmationCard.tsx
packages/mobile/src/exchange/__snapshots__/ExchangeConfirmationCard.test.tsx.snap
packages/mobile/src/transactions/GoldTransactionFeedItem.test.tsx
packages/mobile/src/transactions/GoldTransactionFeedItem.tsx
packages/mobile/src/transactions/__snapshots__/GoldTransactionFeedItem.test.tsx.snap

This improves our resilience to currencylayer API outages / or missing exchange rate data preventing currency conversion to happen in blockchain-api.
Now Valora gracefully degrades and tries to do currency conversions locally using the cached rate of the day.
And if there's no cached rate, it just displays `-` or nothing at all, which is not great but at least it doesn't crash.
This should be improved even more with the switch to the new transaction feed with multiple tokens where the actual underlying token would always be displayed.
Added new unit tests.
This is hard to test manually because it needs a local test instance of the blockchain-api which wouldn't return the local amount.
Or an actual outage from currencylayer.
- See [discussion on …

Fix crash when no local amount is returned by the blockchain-api

---

packages/mobile/src/navigator/Navigator.tsx

The SendConfirmation was refactored into `SendConfirmation` (multi token) and `SendConfirmationLegacy` (previous impl).
However `SendConfirmationModalLegacy` was not added back. This fixes it.
Manually.
Bidali payment modal is displayed.
- Fixes #1521
Yes

Fix bidali modal not triggered

---

packages/mobile/e2e/src/utils/consts.js

Changed the `DEFAULT_RECIPIENT_ADDRESS` to the e2e test faucet address. This should help e2e tests from running low on funds.
N/A
Tested with CI.
N/A - only impacts e2e tests no need for QA to test.
N/A
These changes only impact e2e tests and are backwards compatible.

Replace default recipient wallet address with e2e test faucet address

---

packages/mobile/locales/de/translation.json
packages/mobile/locales/en-US/translation.json
packages/mobile/locales/es-419/translation.json
packages/mobile/locales/pt-BR/translation.json

I found that I had mistyped the translation key for the customer incentives screen title and summary 🥲

fix incorrect translation key name in consumer incentives screen

---

packages/mobile/src/walletConnect/constants.ts
packages/mobile/src/walletConnect/screens/ActionRequest.tsx
packages/mobile/src/walletConnect/screens/SessionRequest.tsx

Pass the `t` function from components to the static functions used to generate translations, to prevent translated strings from being initialised before the i18n instance is initialised and empty strings being rendered. 
N/A
Manually
- Fixes https://github.com/valora-inc/wallet/issues/1557
N/A

Fix missing translations in ActionRequest

---

packages/mobile/src/account/Profile.tsx
packages/mobile/src/account/ShakeForSupport.tsx
packages/mobile/src/components/CommentTextInput.tsx
packages/mobile/src/components/OptionsChooser.tsx
packages/mobile/src/exchange/ExchangeScreenHeader.tsx
packages/mobile/src/navigator/DrawerNavigator.tsx
packages/mobile/src/navigator/NavigatorWrapper.tsx
packages/mobile/src/notifications/NotificationList.tsx
packages/mobile/src/onboarding/registration/NameAndPicture.tsx
packages/mobile/src/pincode/PincodeSet.tsx
packages/mobile/src/send/SendAmount/SendAmountHeader.tsx
packages/mobile/src/send/SendAmountLegacy/SendAmountHeader.tsx
packages/mobile/src/send/SendConfirmationLegacy.tsx
packages/mobile/src/send/SendSearchInput.tsx
packages/mobile/src/tokens/TokenBalances.tsx

We should avoid calling the `t` function from i18n directly, because the imported `i18n` instance could be uninitialised depending on when it was imported. This causes empty or raw translation keys to be rendered in edge cases (see https://github.com/valora-inc/wallet/issues/1557 and https://github.com/valora-inc/wallet/pull/1561)
This PR makes the easy changes, to use the `t` function from the useTranslation hook when possible. We will need to find some ways of handling places where we do translations in .ts files and static functions (like navigation options) in the future.
N/A
Manually tested the affected screens to see translations are still coming through
Same as above
N/A
N/A

remove direct calls to i18n.t when useTranslation hook is available

---

packages/mobile/README.md
packages/mobile/src/i18n/i18n.test.ts
packages/mobile/src/i18n/index.ts

During development you may need to add a new translation key as part of your new feature. While this feature/new translation key is not merged to main, it will not be registered in Crowdin and will therefore not come through as part of the OTA translations. As a result you'll see raw translation keys during development which doesn't give confidence that the feature is working correctly.
In this PR, when loading the resources, use the bundled translations as the base and merge cached OTA translations on top so that we can pick up the OTA changes but also have new translation keys that were added in the app.
Note that this means we always load the bundled resource for the selected language (as opposed to before when we could save this resource load if there are cached translations)
N/A …

merge bundled translations with cached OTA translations on app load

---

packages/mobile/locales/base/translation.json
packages/mobile/src/account/ConnectPhoneNumberScreen.tsx
packages/mobile/src/account/Settings.test.tsx
packages/mobile/src/account/Settings.tsx
packages/mobile/src/navigator/Navigator.tsx
packages/mobile/src/navigator/Screens.tsx
packages/mobile/src/navigator/types.tsx

Design: https://www.figma.com/file/DAcpLsmPdeHT9Gt4eXhtWe/Finclusive-(US)?node-id=952%3A18424
Adding a UI screen for link bank account page when phone number is not verified.
unit tested
- Fixes #1553

Adding phone number not verified UI for link bank account page

---

packages/mobile/src/utils/accountChecker.test.ts
packages/mobile/src/utils/accountChecker.ts

Follow up to #1539, I missed the case where the state is undefined on the first app launch.
This would have caused seeing a lot of false positive Sentry exceptions around this.
Updated unit tests.
N/A
- #729
Yes

Avoid capturing an exception when the state is undefined

---

.github/workflows/check.yml
.github/workflows/e2e-android.yml
.github/workflows/e2e-ios.yml
.github/workflows/test.yml

Cancel in progress runs of workflows to avoid building outdated code.
This should help speed up CI runs a little when commits are pushed before the last run finished.
See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
Note: also formatted the yaml files with prettier.

Cancel in progress runs of workflows to avoid building outdated code

---

packages/mobile/e2e/scripts/fund-e2e-accounts.ts
packages/mobile/e2e/src/usecases/NewAccountPhoneVerification.js
packages/mobile/e2e/src/usecases/OffRamps.js
packages/mobile/src/verify/VerificationLearnMoreDialog.tsx
packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap

Add a testID to the verification learn more model and assert based on testID presence or absence instead of displayed text which can change in Crowdin.
- Updated snapshots.
- E2E tests will now fail prior to running if balance of the e2e test wallet is below 10 for any currency prior to running the e2e tests. This should allow e2e test runs to fail prior to running Detox.
E2E Tests and unit tests run locally.
This does not need to be tested by QA.
N/A
Yes

Misc E2E: Test ID's and update to fund-e2e-accounts.sh

---

packages/mobile/e2e/scripts/fund-e2e-accounts.ts
packages/mobile/e2e/src/DeepLinkSend.spec.js
packages/mobile/e2e/src/usecases/HandleDeepLinkSend.js

- Removes error catch in`fund-e2e-accounts.ts`.
- Enables additional deep link send tests for iOS.
N/A
Tested locally and in CI.
This does not need to best tested by QA.
N/A
Yes

Throw Error for Low E2E Funds & iOS tests for deep link send

---

packages/mobile/ios/Podfile.lock
packages/mobile/package.json
yarn.lock

This PR updates Sentry to the latest version. According to the migration docs, there were no changes needed from our side (there were very few breaking changes and we are not using the changed features). 
https://docs.sentry.io/platforms/react-native/migration/
Rebuilt both iOS and Android apps, manually (created and) triggered an error and verified that it came through in Sentry.
There should be no change to the app behaviour with this PR, so verify that Sentry is working as expected. Errors that you trigger should be received by Sentry as usual.
Prepares for #1461

Update Sentry to latest version

---

packages/mobile/src/i18n/index.ts

When loading the translations on app start, we try to prevent resources for all languages from loading upfront. This is to ensure only the language that is needed is loaded into memory.
When introducing the OTA translations, we wanted to ensure that developers can still add new translations during development. Therefore, when loading the resources, we do a `merge` of the OTA translations and bundled translations for the given language. This is done via the `get` function for each resource language.
Unfortunately the `get` function is called each time a key is translated, and therefore the `merge`. This introduced a noticeable lag for physical Android devices (not noticed during testing on simulators, physical iOS devices, Android emulators). For more context, refer …

prevent translations resource merging for every translation key

---

packages/mobile/src/analytics/selectors.ts
packages/mobile/src/tokens/selectors.ts

We had a bad token in Firebase which caused the total balance to return `NaN`. This should avoid it from crashing the app.
N/A
Locally
Open the app, make sure it doesn't crash.
- Fixes #1671
N/A

Make sure totalBalanceUsd is not NaN

---

packages/mobile/src/fees/hooks.ts
packages/mobile/src/fees/saga.test.ts
packages/mobile/src/fees/saga.ts
packages/mobile/src/send/SendConfirmation.test.tsx
packages/mobile/src/send/SendConfirmation.tsx

There were a couple of issues.
First, the token to use as fee currency was being chosen at random. Not a huge deal I guess, but switched back to using the token with highest balance for consistency.
The more important issue is that we were sending to the `FeeDrawer` the `totalFee` in USD but also sending the fee currency and the exchange rate, so in the end we were transforming the value and ended up showing something inaccurate. Since we're already calculating the fee in USD, we are not just passing the currency as `Currency.Dollar` and letting the `FeeDrawer` component transform it into the local currency normally (`CurrencyDisplay` ends up doing that).
N/A
I did a TDD approach here, if you run the new test with the old code it fails, but after the changes it works.
Try to send using …

Fix fee calculation for non cUSD tokens

---

crowdin.yml

Update i18n config to include type i18next_json to enable multiple pluralisation
N/A
None
None
N/A
N/A

Add i18next json type to crowdin config to enable multiple pluralisation

---

.mergify.yml

Based on #1578, and enables the merge queue with `batch_size: 3`.
This should speed up merging PRs when multiple PRs are ready. 
For instance, when there are 3 PRs in the queue, we'll only need to wait for ~30mins (e2e checks) instead of 1h30mins 
See details in the config.
One important detail though with this:
> With speculative checks, pull requests are tested against the base branch within another temporary pull request. This requires the branch protection settings `Require branches to be up to date before merging` to be disabled.
See https://docs.mergify.com/actions/queue/#speculative-checks
I assume this applies to `batch_size` too given how it works. I haven't yet made this config change on the repo. 
I'll observe this to confirm it's needed. 
In that case I'll probably make it a …

Enable mergify's merge queue

---

packages/mobile/locales/base/translation.json
packages/mobile/src/analytics/Events.tsx
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.e2e.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.ts
packages/mobile/src/home/CashInBottomSheet.test.tsx
packages/mobile/src/home/CashInBottomSheet.tsx
packages/mobile/src/home/WalletHome.tsx
packages/mobile/src/home/__snapshots__/CashInBottomSheet.test.tsx.snap
packages/mobile/src/redux/migrations.ts
packages/mobile/src/redux/store.ts
packages/mobile/test/schemas.ts

**Still needs Tests**
The experiment compares the existing Cash In Bottom sheet which goes through typical CICO flow to a new one that links directly to Ramp. The goal is to drive up Cash In engagement.
[Zenhub](https://app.zenhub.com/workspaces/acquisition-squad-sprint-board-6010683afabec1001a090887/issues/valora-inc/wallet/1687)
[Experiment Design
](https://www.notion.so/Experiment-2-Change-CTA-to-Add-cUSD-cEUR-10-cbb3e82e2c2c4687a3bc7c42defe5cd9)
_Describe any minor or "drive-by" changes here._
_Brief explanation of why these …

feat(CashInBottomSheet): Setup a new experiment linking directly to ramp

---

yarn.lock

follow-redirects pages has security vulnerabilities and is used as a subdependency of `crowdin/ota-client`
The latest patch fixes the vulnerabilities. 
As a result, our ci_check_vulnerabilities script has been failing and thus blocking new commits, eg this execution => https://github.com/valora-inc/wallet/runs/4797782357?check_suite_focus=true
This PR upgrades follow-redirects  to latests version
ci_check_vulnerabilities passes now

upgrade follow-redirects to latest version

---

packages/mobile/src/walletConnect/request.test.ts
packages/mobile/src/walletConnect/request.ts

Fix WalletConnect sign/send now failing with Espresso hardfork nodes when it needs to call `estimateGas` when gas is not provided.
This fixes our E2E tests failing in the WalletConnect suite.
Note: I still need to asses whether existing Valora versions will actually be impacted by forno switching to version [1.5.0 of Geth](https://github.com/celo-org/celo-blockchain/releases/tag/v1.5.0). Initial thought is most dapps already set `gas` so this shouldn't be a real problem.
- E2E test works again
Dapps using WalletConnect can still sign/send transactions.
- Discussed on [Slack](https://valora-app.slack.com/archives/CL7BVQPHB/p1642105337052600)
Yes.

Fix WalletConnect sign/send now failing with Espresso hardfork nodes

---

packages/mobile/src/dappsExplorer/DAppsExplorerScreen.tsx

This will allow some dApps to open with the user already 'connected'. The motivating example is CeloTracker, where you can put the address in the URL like `https://celotracker.com/?address={{address}}` and it will show that address's balance.
N/A
Manually
No way for QA to test this at this time, but whenever Celo Tracker shows up in the Dapps screen then it should open with the user's account already set when opened
- Fixes #1821
N/A

Replace user address in dapp URLs

---

packages/mobile/src/consumerIncentives/analyticsEventsTracker.ts
packages/mobile/src/navigator/DrawerNavigator.tsx

I realized when setting up the experiment that if the user opens the Supercharge screen from an option in the side menu then we were not firing the `rewards_screen_opened` event. Added the event for that as well.
N/A
Manually
No need for QA to test.
- Fixes #1686
N/A

Fire analytics event when selecting Supercharge in the side menu

---

package.json
yarn.lock

Our vulnerabilities CI has identified node-fetch as a new vulnerability and recommends to upgrade to version 2.6.7. This is the error identified https://github.com/advisories/GHSA-r683-j2x4-v87g
Example of the error in CI: https://github.com/valora-inc/wallet/runs/4918866732?check_suite_focus=true
Version 2.6.7 of node-fetch is a security patch update: https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
Most of our dependencies are using version 2 of node-fetch already so this resolution is low risk. Note that only `graphql-codegen` depended on node-fetch version 1.x.x, it is only used for the `build:gen-graphql-types` script but as far as I know this isn't being actively used.
We need to resolve this to make our CI green again 🟢
N/A
N/A
Does not need to be tested
N/A
Yes

Resolve node-fetch to version 2.6.7 which contains security patch to fix CI

---

packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.e2e.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.ts
packages/mobile/src/navigator/DrawerNavigator.tsx
packages/mobile/src/redux/migrations.ts
packages/mobile/test/schemas.ts

`dappsExplorerEnabled` is removed, now we check if `dappListApiUrl` is defined to show the Dapps Screen. (see: https://github.com/valora-inc/wallet/pull/1784#discussion_r789935054)
Locally in the emulator.

refactor: Removing extra feature flag for dapps screen

---

packages/mobile/src/analytics/ValoraAnalytics.test.ts
packages/mobile/src/analytics/selectors.test.ts
packages/mobile/src/analytics/selectors.ts

The totalCount property was counting tokens with 0 balance, which is not what we wanted. Now it counts the tokens that do actually have a balance.
See this thread for details: https://valora-app.slack.com/archives/C02N2BJ03QA/p1643232123019100
N/A
With unit tests
Don't
- Fixes #1868
N/A

Count only tokens with balance in analytics

---

packages/mobile/src/services/ReactNativeLogger.ts

Previously we were checking only the `error` argument of the logger error function for network errors, we should also check the `message` argument. As a consequence, some network errors were still being sent to Sentry.
The `message` argument of `Logger.error` is supposed to be a string but it sometimes receives an object. Typescript does not complain about calling `try {...} catch (error) { Logger.error(TAG, error) }` because `error` has type `any`. So I've added a `.toString()` before checking the value for network errors.
N/A
Manually
No testing needed by QA
N/A
Yes

Fix some network errors still incorrectly being sent to Sentry

---

.github/workflows/e2e-android.yml
package.json
yarn.lock

Our vulnerabilities CI has identified simple-get as a new vulnerability and recommends to upgrade to version 4.0.1. This is the error identified https://github.com/advisories/GHSA-wpg7-2c88-r8xv
Example of the error in CI: https://github.com/valora-inc/wallet/runs/4988071468?check_suite_focus=true
The simple-get releases are not well documented so it is difficult to know which (breaking) changes are in which release. Several of our dependencies are using version 2 and 3 of simple-get (komenci, wallet connect, several celo projects) so we are relying on manual regression tests and the e2e CI to verify that resolving simple-get to v4 works for us.
We need to resolve this to make our CI green again 🟢
N/A
N/A
Does not need to be tested explicitly (implicitly covered during regression tests) …

Resolve simple-get to version 4.0.1 which contains security patch to fix CI

---

packages/mobile/src/pincode/authentication.test.ts
packages/mobile/src/pincode/authentication.ts

Add delay in biometry get/set functions so that the native animations can run fully before moving the user on. Without the delay, the animation can be running while the app is navigating to the next screen already.
With a 800ms delay, the animation runs like this:
https://user-images.githubusercontent.com/20150449/152314145-9f21302e-1f6f-4123-823b-889b1930b645.MP4
N/A
Unit tests and manually
In the onboarding flow when enabling biometrics, and in flows where you need biometry to get the pin (recovery phrase screen, send flow, change pin, etc.) see that the biometric verification animation run to the end before the app moves on.
N/A
N/A

Add some delay for biometry authentication to allow native verification animation to run fully

---

packages/mobile/src/dappsExplorer/DAppsExplorerScreen.tsx

- Use the hamburger icon since this page is navigated from the drawer menu.
- Line separating the navigation header from the scrolling content is animated (same as on the WalletHome).
- Prevent clipping at the bottom. 
- Full layout at the bottom. Nicer on devices with a home bar. 
- Make sure the last item can be interacted with fully on devices with a home bar.
**before/after (iOS)**
**before/after (Android)**
See screenshots
Discussed on [Slack](https://valora-app.slack.com/archives/C029Z1QMD7B/p1643640224807469).
Yes

Tweak Dapps page layout

---

packages/mobile/src/app/App.tsx

Got annoyed having the bottom part of the screen covered with warnings in dev mode.
No more warnings when launching the app in dev mode.
N/A
N/A
Yes

Fix warnings

---

yarn.lock

`pathval` needed to be upgraded because of a vulnerability.
See example CI run which failed: https://github.com/valora-inc/wallet/runs/5149764789?check_suite_focus=true
There's no direct impact to the wallet security.
`pathval` is being transitively included: `@celo/utils>bls12377js>chai>pathval`
And is actually a `devDependency` that was incorrectly set as a runtime dependency.
This was fixed in https://github.com/celo-org/bls12377js/pull/15
But we haven't upgraded the Celo SDK yet which should reference the updated version.
Vulnerability check passes.
N/A
N/A
Yes

Bump pathval from 1.1.0 to 1.1.1

---

.github/workflows/e2e-android.yml
.github/workflows/e2e-ios.yml
packages/mobile/ios/Podfile.lock
packages/mobile/ios/celo.xcodeproj/project.pbxproj

We unexpectedly committed changes to `Podfile.lock` that were incorrect in https://github.com/valora-inc/wallet/pull/1896
This now makes sure `yarn.lock` (well, this one was already checked via the [`check.yml` workflow](https://github.com/valora-inc/wallet/blob/545f1974cb663b13eca4972968d0b62d503ef689/.github/workflows/check.yml)), `Gemfile.lock` and `Podfile.lock` are up-to-date.
It does that by checking there are no git differences after running the corresponding `install` commands.
I also considered using tool specific command line options (like [`yarn install --frozen-lockfiles`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile)) to fail during the install phase if there would be differences with the lock files.
However for `CocoaPods` it also …

Fail CI if lock files are not up-to-date

---

packages/mobile/src/account/profileInfo.ts

We get a raft of Errors from this code in Sentry and we ignore all of them. This
implies they're expected failures and should probably be Warns.

Convert some Logger.errors to Logger.warns in profileInfo.ts

---

package.json
packages/mobile/e2e/src/usecases/Send.js
yarn.lock

Resolve ethers to 5.0.5 to fix nomspace lookups - [Relevant ethers thread](https://github.com/ethers-io/ethers.js/issues/1316).
- Added an e2e tests for Nomspace lookups.
Tested locally on Android. E2E tests run on iOS and Android in CI.
On Alfajores or Mainnet search for `Hello.nom` in either the send or request flow, a recipient should be populated.
- Fixes #2005
Yes

Nomspace Fix

---

packages/mobile/src/config.ts
packages/mobile/src/sentry/Sentry.ts

This is a tentative to avoid the environment pollution we currently see in Sentry.
See [Slack discussion](https://valora-app.slack.com/archives/C025V1D6F3J/p1645782671954849?thread_ts=1645758296.049519&cid=C025V1D6F3J).
- Sentry init is skipped if bundle id doesn't match the one set at build time
N/A
N/A
Yes

Disable Sentry if bundle id doesn't match the one set at build time

---

package.json
yarn.lock

As above, update plist dependency to fix vulnerability and make CI green again
n/a
Manually
This does not need to be tested by QA
n/a
n/a

Resolve plist to version 3.0.4 which contains security patch to fix CI 

---

packages/mobile/src/navigator/DrawerNavigator.tsx

This fixes an edge case with the Dapps page which would keep the same displayed featured dapp until the app is actually fully closed and relaunched.
And fixes the same problem with the Supercharge screen when accessed via the menu item.
- The Dapps list is refetched and `dapp_screen_open` is triggered every time the user navigates to the Dapps page.
- The Supercharge screen is reloaded when accessed via the menu item
- Ensure you see the loading indicator every time you navigate to the Dapps page.
- Ensure you see the loading indicator every time you navigate to the Supercharge screen via the menu item (this is under a feature flag).
Discussed on [Slack](https://valora-app.slack.com/archives/C02UAE4MGUF/p1646163385968329).
Yes

Reload Dapps and Supercharge screens every time the user navigates to them

---

packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/locales/index.ts

Add language support for Ukrainian 🇺🇦
N/A
Manually
The app correctly displays in Ukrainian if you select that as your language.
The app is launched in Ukrainian for a new user with device language uk-UA
- Fixes #2069 
Yes

Add language support for Ukrainian

---

packages/mobile/locales/base/translation.json
packages/mobile/src/analytics/Events.tsx
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/api/slice.ts
packages/mobile/src/config.ts
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
packages/mobile/src/consumerIncentives/analyticsEventsTracker.ts
packages/mobile/src/consumerIncentives/saga.test.ts
packages/mobile/src/consumerIncentives/saga.ts
packages/mobile/src/geth/networkConfig.ts
packages/mobile/src/home/NotificationBox.test.tsx
packages/mobile/src/home/NotificationBox.tsx
packages/mobile/src/home/WalletHome.test.tsx
packages/mobile/src/home/__snapshots__/NotificationBox.test.tsx.snap
packages/mobile/src/home/__snapshots__/WalletHome.test.tsx.snap
packages/mobile/src/redux/reducers.ts
packages/mobile/src/redux/store.ts
packages/mobile/src/transactions/transferFeedUtils.ts
packages/react-components/components/Button.tsx
packages/react-components/components/SimpleMessagingCard.tsx

Changes to Supercharge include:
- Add a Valora icon to the "claim rewards" button.
- Change copy of the disclaimer in the Supercharge screen if the user has more than the max balance or if they have rewards available to claim.
- Add a couple of analytics events.
- Change Supercharge icon in the feed to a bolt.
- Fix error message if loading rewards fails.
- Add an in-app card if the user has rewards available in the first place with a CTA to claim.
N/A
Manually
Some of these changes are hard to test but try opening the rewards screen and making sure it looks as expected? Just test that screen generally like you already do.
- Fixes #2082
- Fixes #2084
N/A

Some changes to Supercharge self-claim

---

packages/mobile/src/analytics/ValoraAnalytics.test.ts
packages/mobile/src/analytics/selectors.test.ts
packages/mobile/src/analytics/selectors.ts

cReal was only tracked in `otherTenTokens` which made targeting cReal users more difficult.
This fixes it and makes it future proof when other core tokens are added.
N/A
Discussed on [Slack](https://valora-app.slack.com/archives/C02N2BJ03QA/p1644871855329069).
Yes

Track all core tokens balances

---

package.json
packages/mobile/src/identity/privateHashing.ts
packages/mobile/src/paymentRequest/OutgoingPaymentRequestListItem.test.tsx
packages/mobile/src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
yarn.lock

This PR upgrades typescript to the current major version. It is a stepping stone to having it up-to-date. Next step will be (from >= 4.2 yield typings are handled differently) to fix all the `yield` typings.
Minor types fixes
Relying on automated tests
- Unblocks #1976 
Should be fully compatible.

Upgrade typescript to 4.1.6

---

.github/scripts/create_app_version_pr.sh
.github/workflows/bump-app-version.yml
packages/mobile/scripts/pre-deploy.sh

A few things needed to be ironed out after seeing this script in the wild:
- as this job is triggered by a tag, by default the repo is checked out with the tag as reference - need to avoid this as the tag is on the release branch which could contain extra commits (like in the case of 1.28.0) => checkout with `ref: main`
- the disclaimer part of the pre-deploy script executes asynchronously and was still ongoing while the next script step (push branch) was executing => add opt out for disclaimer. it's also nice to separate the disclaimer anyway because we will remove it from the pre-deploy script soon.
- the create PR api request was failing with error 
```
"message": "Validation Failed",
"errors": [
***
"resource": "Issue",
"code": "missing_field",
"field": "title"
***
], …
```

Fix auto version bump script failure

---

package.json
yarn.lock

The vulnerabilities CI is failing due to https://github.com/advisories/GHSA-xvch-5gv4-984h. 
This PR resolves the minimist package to 1.2.6 to fix this vulnerability. (Even though there isn't an official patched version on the above report, 1.2.6 does seem to include a fix for it https://github.com/substack/minimist/issues/164#issuecomment-1074384679 &  https://github.com/substack/minimist/issues/164#issuecomment-1074670410)
N/A
N/A
N/A
N/A
N/A

Resolve minimist version to 1.2.6 to resolve vulnerability

---

packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/analytics/types.ts
packages/mobile/src/app/saga.test.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/app/selectors.ts
packages/mobile/src/app/utils.ts
packages/mobile/src/dappkit/DappKitAccountScreen.tsx
packages/mobile/src/dappkit/DappKitSignTxScreen.tsx
packages/mobile/src/dappkit/dappkit.ts
packages/mobile/src/walletConnect/v1/saga.ts
packages/mobile/src/walletConnect/v2/saga.ts
packages/mobile/src/walletConnect/walletConnect.ts

This adds a `dappRequestOrigin` prop for all WC/DappKit events so we know if they came from our in-app WebView or were external (system browser or other apps).
Manually and updated unit tests
N/A
- Fixes #2104 
Yes

Add dapp request origin prop to WC/DappKit analytics events

---

packages/mobile/package.json
yarn.lock

Changes Detox version to `19.5.1` from `19.5.7`.
N/A
Tested in CI.
This does not need to be tested by QA.
- Fixes #2250
Yes

Change Detox Version

---

packages/mobile/android/app/src/main/res/values/styles.xml

Solves the issue of the dev menu (and a couple of other places that use `<Text>` with no styling) appearing white on a white background for android devices with dark mode enabled.
These lines were changed as part of the react native 66 upgrade, reverting them back to the original here. I had followed the react native upgrade guide and thought that day/night mode could not hurt us, however our app does not respond to day/night. If the app background doesn't change, it makes no sense for the text color to change according to system preferences.
context: https://valora-app.slack.com/archives/C025V1D6F3J/p1648221666751949
N/A
Manually
N/A
N/A
N/A

Android fix sometimes white text on white background in dark mode

---

packages/mobile/locales/base/translation.json
packages/mobile/src/send/InviteRewardsBanner.tsx

Update the invite rewards banner on the send screen for the v2 experiment. For short experiments, we do not want to have the T&C's link. https://valora-app.slack.com/archives/C038A310CEL/p1648222238888949?thread_ts=1648198994.077819&cid=C038A310CEL
N/A
Manually
Verify that on the send screen, the invite rewards banner is no longer clickable
- Relates #2203
Yes

Update copy and remove learn more link for invite rewards v2

---

packages/mobile/src/components/BottomSheet.tsx

The bottom sheet was not displaying a second time after being dismissed as described in #2245. This aims to fix that issue on wherever the `BottomSheet.tsx` is used such as the Dapps page and token bottom sheet.
N/A
Tested locally on Android 10 & Android 5 in dev and release mode.
Follow the reproduction steps for #2245 and ensure that the issue does not reproduce.
Follow the reproduction steps for #1973 and ensure that the issue does not reproduce.
Follow the testing steps for #2230.
- Fixes #2245
Yes

fix: bottom sheet not displaying second time after dismiss

---

packages/mobile/locales/base/translation.json
packages/mobile/src/merchantPayment/MerchantPaymentScreen.tsx
packages/mobile/src/merchantPayment/hooks.ts

This changes the way the `abort` method is called when the component unmounts. Right now it actually sends an abort after each success which isn't ideal..
Fixed a typo in the english translation
via ios ismulator
The payment shouldn't be aborted after a success

fix: manage the abort callback more elegantly

---

packages/mobile/locales/base/translation.json
packages/mobile/src/account/LinkBankAccountScreen.test.tsx
packages/mobile/src/account/LinkBankAccountScreen.tsx
packages/mobile/src/account/Persona.tsx
packages/mobile/src/account/Settings.test.tsx
packages/mobile/src/account/Settings.tsx
packages/mobile/src/account/actions.ts
packages/mobile/src/account/reducer.ts
packages/mobile/src/account/selectors.ts
packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/app/selectors.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.e2e.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.ts
packages/mobile/src/redux/createMigrate.test.ts
packages/mobile/src/redux/migrations.test.ts
packages/mobile/src/redux/migrations.ts
packages/mobile/src/redux/store.test.ts
packages/mobile/src/redux/store.ts
packages/mobile/src/utils/supportedRegions.test.tsx
packages/mobile/src/utils/supportedRegions.ts
packages/mobile/test/RootStateSchema.json
packages/mobile/test/schemas.ts

- Fixes #1999 
Finclusive doesn't have license in NY and TX yet. After collecting information from persona, we should prevent user from connecting a bank account if their residence is in NY or TX. 
WIP:
- finalize the copy/design with Nitya
- add tests
WIP

Block finclusive unsupported geos 

---

packages/mobile/locales/base/translation.json

Updates the dapps bottom screen text to be appropriate for the in app browser.
N/A
Tested locally. 
From the Dapps page tap a Dapp and observe bottom sheet text. It should read:  `{{dappName}} is an external application`.
N/A
Yes

Update dapps bottom screen text

---

packages/mobile/locales/base/translation.json

There is a banner text for in app dapp connection success, it was added in #2178 but removed accidentally in #2209 - not sure what happened, but #2209 was open for a long time (broken CI maybe) so probably a bad crowdin sync somewhere along the way.
N/A
N/A
N/A
N/A
N/A

Fix missing translation for in app dapp connection success banner

---

.github/scripts/automergeCrowdinPr.js
.github/workflows/automerge-crowdin.yml

The Crowdin translation PR should not modify the base translations. Sometimes when the Crowdin branch is open for a long time and there are new PRs merged that modify the base translations, weird things happen and the base translations are wrongly updated. e.g. https://github.com/valora-inc/wallet/pull/2276
In this PR, check that only the translated languages are modified before automerging. Otherwise, leave a "changes requested" review so that it is easier to see that manual intervention is needed.
N/A
Manually
N/A
N/A
Yes

Ensure automerge Crowdin translations automation does not modify base translations

---

packages/mobile/src/account/__snapshots__/Licenses.test.tsx.snap
packages/mobile/src/components/WebView.tsx
packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap
patches/react-native-webview+11.6.5.patch

On slower/older Android devices, connecting to Dapps from the in-app WebView would display an error and fail.
This is because the Android WebView mechanism to decide whether to load new urls has a default timeout of 250ms for the JS side to return a value. See https://github.com/react-native-webview/react-native-webview/blob/5e73b2089fc80c2be7aa6eff291b18c81ad4030d/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L921-L967
This PR increases the timeout to 60secs which should be way more than enough for slower/older Android devices to respond.
This patch should probably be contributed to [react-native-webview](https://github.com/react-native-webview/react-native-webview) once we confirm it's working as expected on more devices.
I've also added a log to capture …

fix(dapps): WebView error when connecting dapps with slow Android devices

---

package.json
yarn.lock

Resolves to use async version `3.2.2` to address [Prototype Pollution in async](https://github.com/advisories/GHSA-fwr7-v2mv-hh25).
N/A
Tested in CI.
This does not need to be tested by QA.
N/A
Yes

Async vulnerability Fix

---

packages/mobile/src/account/__snapshots__/Licenses.test.tsx.snap
packages/mobile/src/components/WebView.tsx
packages/mobile/src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap

On iOS, scrolling WebViews wasn't feeling natural, decelerating too fast. This fixes it.
This should be the default in [react-native-webview](https://github.com/react-native-webview/react-native-webview).
**before**
https://user-images.githubusercontent.com/57791/163124078-bc00af14-298f-4574-babe-442b3d37ce13.mp4
**after**
https://user-images.githubusercontent.com/57791/163124206-402f7b43-bb04-4315-909c-c27347741e7b.mp4
The scroll behavior in WebViews should match normal ScrollViews, as seen in the video above.
N/A
Yes

fix: change WebView scroll decelerationRate on iOS to match UIScrollView's behavior

---

packages/mobile/src/app/WebViewScreen.tsx

Title says it all, during page load the title is never empty for Android but is empty for iOS. Needed to update the display title condition so that iOS correctly displays "Loading"
N/A
Manually on iOS and Android
N/A
N/A
Yes

Fix webview crash on iOS due to missing page title during loading

---

.github/scripts/uploadE2eBuildToEmerge.ts

Quick follow up to #2317 to avoid showing `undefined` in the Emerge dashboard for non PR builds.
Once it lands on main.
N/A
N/A
Yes

ci(emerge): fix PR number sent as "undefined" for non PR builds

---

.github/workflows/e2e-ci.yml

Emerge runs were failing on scheduled e2e work flows. This would also be the case with manual workflow dispatches. This PR sets Emerge to only run on pull requests and pushes. [Sample failing scheduled run](https://github.com/valora-inc/wallet/runs/6068125862?check_suite_focus=true).
N/A
Tested in CI.
This does not need to be tested by QA. Reviewers should observe the following actions.
- [Dispatched](https://github.com/valora-inc/wallet/runs/6103161398)
N/A
Yes

Only run emerge on pull request and push

---

.mergify.yml

Mergify's merge queue is failing, removing the batching to see if it helps. We don't really need it.
Waiting to use `automerge` on this one.
N/A
- Discussed on [Slack](https://valora-app.slack.com/archives/C02E2FE98P2/p1651713285259739).
Yes

chore(mergify): try fix merge queue

---

packages/mobile/src/app/WebViewScreen.tsx

The Webview sometimes displays incorrect information in the header during loading. e.g. the video below.
https://user-images.githubusercontent.com/20150449/167415173-b57cfcfb-674e-4771-abaf-74120d6eda86.mov
This PR adds a loading state to the header on navigation state change, so that this mismatch does not happen. e.g. the video below.
https://user-images.githubusercontent.com/20150449/167414622-6b7c1c53-0750-4e99-860a-ce114d7b65fd.mov
TECHNICAL NOTE:
We are using `onNavigationStateChange` to update the screen header information. This seems to be [unreliable](https://stackoverflow.com/a/50137971 ) depending on the implementation of the particular web page displayed. A symptom of this problem is outlined in #2339 but it does not affect all dapps (navigation back from external links in …

Fix mismatch in WebView page title and host

---

package.json
src/components/PhoneNumberInput.test.tsx
yarn.lock

Updates [google-libphonenumber](https://www.npmjs.com/package/google-libphonenumber) to `3.2.27`
Added a unit test in `PhoneNumberInput.test.tsx` for Côte d’Ivoire phone numbers.
Tested locally on iOS and with unit tests.
1. Navigate to `Connect your phone number` select the Côte d’Ivoire flag - 🇨🇮
2. Observe correct place holder - `00 00 0 00000`
3. Enter in a valid Côte d’Ivoire phone number e.g. `21 23 4 56789` and tap next.
4. Should begin phone verification - no need to complete but ensure that it starts.
- Fixes: [Côte divoire 10 digit phone # instead of 8 digit #104](https://github.com/valora-inc/support-issues/issues/104)
Yes

Côte d’Ivoire Phone Number Fix

---

src/sentry/Sentry.ts

Use domain names / hostnames instead of URLs.
Testing locally by using a mainnetdev config, hard coding `tracesSampleRate` to 1.0, running in an Android emulator, and then checking Sentry.
No QA testing needed.

Fix Sentry tracing

---

src/account/SupportContact.test.tsx
src/account/SupportContact.tsx

Include connection status in logs, as requested by support team. Currently our L1 team asks users to go to Settings and take a screenshot to see if Valora thinks their phone number is connected, having this info upfront will save them some time.
N/A
N/A
N/A
- Fixes #1826 
Yes

Include number verified state in support logs

---

e2e/src/usecases/OnRamps.js

E2E test [started failing consistently in the OnRamps test](https://valora-app.slack.com/archives/CL7BVQPHB/p1654240204274729).
- E2E passes again
N/A
N/A

e2e: fix incorrect identifier in OnRamps test

---

src/config.ts
src/services/ReactNativeLogger.ts
src/utils/Logger.ts
src/utils/LoggerLevels.ts

With the default (debug) the logs can be impenetrable during "normal" local
development.
By default this change shouldn't impact the previous logging behavior.
This doesn't require additional testing.

Add configurable logging levels

---

babel.config.js
package.json
yarn.lock

- Upgrade `@celo/utils` to fix vulnerability in `@umpirsky/country-list`: https://github.com/advisories/GHSA-hj79-42mx-m4gr
- The upgraded `@celo/utils` caused a new parsing error with hermes as it [doesn't support named capture groups in RegEx](https://github.com/facebook/hermes/issues/696). It was solved by adding `@babel/plugin-transform-named-capturing-groups-regex` to our babel transforms.
- Upgrade `shell-quote` to fix vulnerability: https://github.com/advisories/GHSA-g4rg-993r-mgx7
N/A
The app + phone verification should work as expected
Please test the phone verification and confirm that it works as expected (there should be no change as a result of this PR)
Discussed on [Slack](https://valora-app.slack.com/archives/CL7BVQPHB/p1655807207073809).
Yes

Fix known vulnerabilities

---

ios/celo/Info.plist
ios/celo/celo.entitlements

Cleanup on the `celo.org` domain prompted this. We're not using it anywhere anymore.
No need to test this.

chore: remove obsolete `l.celo.org` dynamic link

---

src/flags.ts

I noticed Poland had an incorrect [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. It was set to `PO` instead of `PL`.
So I fixed + completed it from a https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_Europe.
Not tested.
No need to test this.
Yes

fix: list of countries in Europe

---

android/app/build.gradle
src/qrcode/QRScanner.tsx
src/qrcode/utils.ts

When scanning a QR code that only contains an address, we will now convert it to a deep link by prefixing the address with: `celo://wallet/pay?address=`. From home screen and "Send" screen, scanning this QR code leads to payment UI. When scanning from the "Receive" UI, it attempts to send a receive request to the given request.
None
Manually tested on phone using both release and non-release builds. 
Scan a blockscout QR code, and verify that the address in the "review" page matches the address in blockscout. (eg. https://explorer.celo.org/address/0x55D0B67dBFcEcF218E498Ac29F1A851eF90f1CB8/)
- Related to #2678. Previous fix only handled dev builds (not release)
N/A

feat: Support "address only" QR codes in release builds 

---

src/fiatExchanges/quotes/FiatConnectQuote.test.ts
src/fiatExchanges/quotes/FiatConnectQuote.ts
src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx
src/fiatconnect/clients.test.tsx
src/fiatconnect/clients.ts
src/fiatconnect/index.test.ts
src/fiatconnect/index.ts

There can be multiple quotes for the same provider (when quote expires or a transfer is retried), this allows reusing the same FiatConnectClient instance across quotes.
Moved `getSigningFunction` to src/fiatconnect/clients.tsx since it's only used here
unit tests
N/A
- For [ACT-277](https://linear.app/valora/issue/ACT-277/initiate-transfer-out-implementation) and [ACT-349](https://linear.app/valora/issue/ACT-349/fc-return-user-flow)
Yes

refactor(fiatconnect): move client creation outside quote class

---

src/redux/store.ts

This allows viewing fiatConnect state in flipper redux debugger
N/A
N/A
N/A
N/A
N/A

chore(flipper): add fiatConnect to stateWhitelist

---

src/firebase/db-rules.json

Allow IHL to read and write fiatConnect node to track kyc and transfer status via webhook
N/A
N/A
N/A
- Related to ACT-39
N/A

chore(firebase): allow IHL to write to fiatconnect node

---

src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/transactions/feed/queryHelper.ts
test/schemas.ts

Applies the schema changes and fixes from the 1.36.1 and 1.37.1 patches.
N/A 
Tested locally on iOS.
N/A
N/A
For users - Yes.
For developers who have been working off main a reinstall of the app my be needed, due to changes in redux migrations.

chore: apply code from 1.36.1 and 1.37.1 patches

---

src/account/Profile.test.tsx
src/account/Profile.tsx

Prevents users from saving empty names on edit profile screen.
N/A
Tested locally on iOS
When attempting to save an empty name on edit profile an error banner should be served with the text, 'Name cannot be empty'
- Fixes #2741
Yes

fix: prevent saving empty name

---

src/fiatExchanges/quotes/FiatConnectQuote.ts
src/fiatconnect/FiatDetailsScreen.tsx

Fixes the following import cycle:
src/navigator/types -> src/fiatExchanges/quotes/FiatConnectQuote -> src/fiatconnect/FiatDetailsScreen -> src/navigator/types
This was also causing the test failure on #2760
N/A
N/A
N/A
N/A
N/A

fix(fiatconnect): move exported consts to avoid cyclic dependency

---

locales/base/translation.json
src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx

Currently, the error message shows up immediately on typing the AccountNumber field. This updates so that the error message shows up after a 1.5s delay after typing or the field loses focus. Also, this doesn't clear the error message on a blank field. 
https://user-images.githubusercontent.com/5062591/183801146-d7fc81ce-0021-4079-9677-0b8861d438d8.mp4
https://user-images.githubusercontent.com/5062591/183801159-e1bbb052-6043-4609-98bc-45a7c3a2d61a.mp4
- Use indexes for error state instead of field names
- Use memo for schema
- Removed error for bank name as this is never displayed
1. Ensure you've not already linked a bank account with Valora test provider
2. Navigate to Withdraw flow on Alfajores
3. Select Bank Account with Valora test provider and click on Continue
4. …

feat(fiatconnect): show validation errors after typing is complete

---

src/fiatconnect/FiatDetailsScreen.tsx

Before:
After:
N/A
Manual
1. Ensure you've not already linked a bank account with Valora test provider
2. Navigate to Withdraw flow on Alfajores
3. Select Bank Account with Valora test provider and click on Continue
4. Type on the Bank Name and Account Number text fields and ensure clear button is aligned to the center of the field
- Fixes ACT-181
Yes

fix(fiatconnect): clear button position on fiat details screen

---

locales/base/translation.json
src/fiatconnect/ReviewScreen.test.tsx
src/fiatconnect/ReviewScreen.tsx

Change copy of payment method header
N/A
Go through the withdraw flow with the test provider on Alfajores and check copy of the payment method header
- Fixes ACT-181
Yes

fix(fiatconnect): review screen copy updates

---

src/transactions/feed/TransactionFeed.test.tsx
src/transactions/feed/queryHelper.ts

Context: https://valora-app.slack.com/archives/C018VLA3YAK/p1660091022594799
The solution chosen for this issue is to continue to fetch transactions from the client until a minimum threshold is met (currently 10) so that the section list is filled and the user can scroll to load more.
In this PR:
- To ensure no weird bugs and avoid concurrency issues, i refactored the state variables to keep the cumulative transactions + pageInfo in the same state variable so that they are always in sync. 
- Added a hook to refetch transactions until we have 10, and refetch transactions if the returned page is empty
N/A
Manually and with unit tests
Please try this with many accounts that have varying number of transactions - load the app (from a fresh install, and from cold start) and …

fix(homefeed): ensure that users can scroll to load more

---

src/transactions/feed/queryHelper.ts

Annoyingly, the `onEndReached` callback is triggered on the SectionList used to render the transaction feed when navigating away from the screen on iOS, when the transaction list is too short. This causes the "no more transactions" toast to appear on the next page that is navigated to, but only once. 
This check for length of transactions used to exist, and I had removed it thinking it was strange https://github.com/valora-inc/wallet/pull/2779#discussion_r944308531 - but it seems like we need it.
N/A
Manually
N/A
N/A
Yes

fix(homefeed): avoid showing 'no more transactions' toast when too few transactions

---

src/verify/VerificationEducationScreen.tsx

When navigating to the connect phone number with an existing account users were being served 'Failed to create your wallet' screen due to a dispatch to initialize wallet. This PR checks via the walletAddressSelector returns null prior to attempting to initialize the wallet.
N/A
Tested locally on iOS.
1. Re-install with new account.
2. Restart-app.
3. Attempt to connect phone number from the home card, settings, or supercharger card.
4. Pin Entry is not served.
5. Tapping back takes user back to the previous screen and failed to create your wallet screen is not served.
- Fixes #2511
Yes

fix: navigating to connect phone number with existing wallet

---

locales/base/translation.json
src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/app/types.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/onboarding/registration/NameAndPicture.test.tsx
src/onboarding/registration/NameAndPicture.tsx
src/onboarding/welcome/Welcome.test.tsx
src/onboarding/welcome/Welcome.tsx
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

This is a simple copy test controlled by remote config `createAccountCopyTestConfig`.
There are three conditions:
Control: `createAccountCopyTestConfig` = "ACCOUNT"
- CTA text: “Create new account” / “Restore my account”
- Step 1 title: “Create account”
Treatment 1: `createAccountCopyTestConfig` = "WALLET"
- CTA text: “Create new wallet” / “Restore wallet”
- Step 1 title: “Create profile”
Treatment 2: `createAccountCopyTestConfig` = "ALREADY_HAVE_WALLET"
- “Create new wallet” / “I already have a wallet”
- Step 1 title: “Create profile”
N/A
With iOS emulator
- https://linear.app/valora/issue/RET-363/onboarding-create-account-copy-test
Yes

feat(Onboarding): create account copy test (RET-363)

---

package.json
src/components/TokenBalance.tsx
yarn.lock

Update to [Detox 19.10.0](https://github.com/wix/Detox/releases/tag/19.10.0)
Don't display out of Sync Banner during e2e tests.
Tested in CI.
- Reviewers: check [E2E actions on this branch](https://github.com/valora-inc/wallet/actions/workflows/e2e-ci.yml?query=branch%3Atomm%2Fdetox-19.10.0) - First one was prior to removing out of sync banner.
- QA: N/A
N/A
Yes

build(deps): update detox to 19.10.0

---

package.json
src/dapps/saga.ts
yarn.lock

Fixes the issue where the dapp list wasn't loading on initial navigation after creating or restoring an account.
Updates [@redux-toolkit](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.8.5) to v1.8.5.
Tested locally on iOS.
1. Create or restore an existing account.
2. Navigate to the dapps list.
3. Dapps list loads.
4. Close the app.
5. Reopen and navigate to the dapps list.
6. Dapps list loads.
- Fixes #2754, RET-390
Yes

fix: dapp list loads on initial navigation from create or restore

---

src/dapps/saga.ts
yarn.lock

This PR continues from https://github.com/valora-inc/wallet/pull/2811
On initial account creation/restore, the fetch dapp list action is dispatched too early (before the remote config variable for the dapps list url and the account address are loaded) - the lack of dapps list url causes the saga to hang and subsequent calls to it are not processed.
This PR:
- return early when remote config for dapps list url is not available
- fetch dapps list on account set
Tidies up the yarn.lock from the previous update
Manually
Verify that https://github.com/valora-inc/wallet/issues/2754 cannot be reproduced
- Fixes #2754 
Yes

fix: handle dapplist fetch correctly on account load

---

locales/base/translation.json
src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/navigator/types.tsx
src/onboarding/registration/EnableBiometry.test.tsx
src/onboarding/registration/EnableBiometry.tsx
src/onboarding/registration/NameAndPicture.test.tsx
src/onboarding/registration/NameAndPicture.tsx
src/onboarding/welcome/Welcome.test.tsx
src/onboarding/welcome/Welcome.tsx
src/pincode/Pincode.tsx
src/pincode/PincodeSet.tsx
src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Reverts #2817 due to:
- The onboarding text was displayed in non onboarding pin displays.
- Empty Scroll view was causing unexpected shifts to pincode entry layout.
</p>
N/A
Tested locally on iOS
Devs: Please double check my changes to the migrations.
QA: Check that Pin Entry Functions as expected and displays correctly during onboarding, viewing recovery phrase, and on Pin Change.
N/A
Yes - Devs may need a fresh install due to redux changes.

revert: feature flag for guided onboarding copy

---

.github/workflows/e2e-ci.yml

Adjust the worker group that Android E2E tests run on. [A planned change back](https://github.com/valora-inc/wallet/pull/2834/files#diff-3def5e5f7860c0ac8aa24d252fe222524431c9cbac2ba536e1a2185a9dd2be81R30-R31) as the CI machines have been update to use Java 11.
N/A
Tested in CI by first switching all the machines over to the test group.
No need for QA - Reviewers should double check that the Android E2E tests are passing.
N/A
Yes

test(e2e): android test group

---

patches/@react-native-firebase+app+11.5.0.patch

Fixes crash on Connect Phone Number screen. https://valora-app.slack.com/archives/C018VLA3YAK/p1662991289862839
The latest `@react-native-firebase/app` package fixes this, but upgrading it has pods conflict on iOS between segment and firebase packages. This patches `@react-native-firebase/app` to just bump `play-services-auth` version that fixes this issue.
An alternative fix is to just include the `play-services-auth` in build.gradle, but opted for this as it is easier to cleanup when we eventually upgrade `@react-native-firebase/*` packages
N/A
Manually
- Launch app on Android version 12 with an account without a connected phone number
- Navigate to settings -> Connect phone number (or supercharge -> Connect phone number)
- App should not crash on the phone number screen
Yes

fix(deps): make @react-native-firebase/app API level 31 compatible

---

src/components/InviteOptionsModal.tsx
src/tokens/TokenBalances.tsx

As the title says
Vertical padding on the NFT banner. Before -> after
Manually
Verify that https://github.com/valora-inc/wallet/issues/2852 cannot be reproduced.
- Fixes #2852 
Yes

fix: invite modal display on android not taking up whole screen height

---

src/components/header/CustomHeader.tsx
src/exchange/ExchangeScreenHeader.tsx
src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
src/navigator/Headers.tsx
src/send/SendAmount/SendAmount.test.tsx
src/send/SendAmount/SendAmountHeader.tsx
src/send/__snapshots__/Send.test.tsx.snap
src/send/__snapshots__/SendConfirmation.test.tsx.snap
src/send/__snapshots__/SendConfirmationLegacy.test.tsx.snap

Currently the app does not handle large fonts very well. In the CustomHeader component, the title is absolutely positioned and for users with large fonts enabled, the title breaches the device native status bar. This shouldn't be allowed.
Current:
It's pretty hard to optimise headers with large text and 2 lines. I tested how Apple handles this natively in the Photos app and it appears that they do not allow font scaling in the headers. I took this approach as it seems sensible enough and technically simple, and at a later stage we can revisit this if we want to optimise for large fonts. Open to other ideas about how to handle this scenario.
Updated:
N/A
Manually
N/A
N/A
Yes

fix: prevent text overlapping the device status bar

---

.github/workflows/e2e-ci.yml

Sets BASH_ENV, which source's the ~/.profile file to pick the correct ruby version that works with xcode 13.1. This is required for #2855 
N/A
CI
N/A
N/A
Yes

chore(e2e): use xcode 13.1 for iOS

---

.github/workflows/e2e-ci.yml

Use BASH_ENV to load profile instead of source command on each step
N/A
CI
N/A
N/A
N/A

chore(e2e): use BASH_ENV for android

---

src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx
src/fiatconnect/saga.test.ts
src/fiatconnect/saga.ts
src/fiatconnect/selectors.ts
src/fiatconnect/slice.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

While working on checking KYC after submitting a Fiat Account, the FiatDetails screen was becoming really cluttered, and figured it would be a good idea to take care of the TODO there to pull the logic out to a saga. No new functionality here, just porting the logic over to a saga. KYC stuff will come in a subsequent PR for ease of review.
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
_Describe any minor or "drive-by" changes here._
- …

refactor(fiatconnect): Refactor fiat account submission to saga

---

src/components/InviteOptionsModal.tsx
src/invite/InviteModal.test.tsx
src/invite/InviteModal.tsx

As the title, this component can be reused by both variants of the invite experiment
N/A
Unit tests and manually
N/A
N/A
Yes

refactor: abstract InviteModal component so that it can be reused

---

android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/app/App.tsx
src/app/saga.test.ts
src/app/saga.ts
src/config.ts
src/invite/Invite.test.tsx
src/invite/Invite.tsx
src/invite/InviteModal.tsx
src/invite/hooks.tsx
src/invite/utils.ts
src/navigator/DrawerNavigator.tsx

This PR adds a new drawer navigation item "Invite". Users can open the Invite screen to get a deep link directing other users to the app.
- Grabbing the share link kicks off an analytics event and on iOS, the results of the share (if it was abandoned, or what app was used for the sure) are attached as properties. On Android the results are not available.
- Users opening the app via the invite link also kicks off an analytics event, with the inviter's wallet address as a property.
These steps were followed on each platform:
Link creation:
1. Click the `Invite` link in the drawer navigator
2. The `Invite` button should initially be disabled, as the link is being created
3. When the `Invite` button is enabled, click it.
4. The native share drawer should appear, with a short message including …

feat: Add share URL flow

---

src/send/ValidateRecipientAccount.tsx
src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap

Removes the nested SafeAreaView and replaces it with a View to avoid adding an extra margin on top of the nested view.
Removes vertical padding on View element.
https://user-images.githubusercontent.com/26950305/194951320-9dbb00a8-0524-4901-952e-529e4b903c85.mov
N/A
Tested locally on Android
1. On Alfajores Send to attempt to send to `12057368924`.
2. Enter amount and tap 'Confirm Account Address'
3. Observe padding at the top matches other screens.
4. Observe button not hidden behind keyboard.
N/A
Yes

fix: use view instead of nested SafeAreaView to prevent extra top space

---

src/verify/VerificationCodeInputScreen.test.tsx
src/verify/hooks.ts

Ensure that users who are already verified can restore their accounts and verify again. We can consume the new phone number lookup endpoint, but this PR achieves feature parity for now.
Video: https://linear.app/valora/issue/RET-389#comment-a119f794
N/A
Manually, unit test
Verify a phone number against an account. Restore the account, and verify the same phone number. 
- Fixes RET-389
- 
Yes

feat: handle number already verified for CPV

---

src/components/CodeRow.tsx
src/identity/contactMapping.test.ts
src/identity/contactMapping.ts
src/identity/saga.ts
src/send/ValidateRecipientAccount.test.tsx
src/send/ValidateRecipientAccount.tsx
src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
src/web3/networkConfig.ts

As the title, this PR updates only the send flow to work with CPV.
If no addresses are found with the lookupPhoneNumbers endpoint, then the decentralised mapping is used to maintain backwards compatibility while users are still migrating.
N/A
Manually, unit tests
In Alfajores, sending to phone numbers should work as before. Including the secure send flow when sending to a phone number that has multiple addresses
Fixes RET-389
Yes

feat: use centralised phone number lookup in send flow

---

.github/workflows/e2e-android.yml
.github/workflows/e2e-ci.yml
.github/workflows/e2e-main.yml
.github/workflows/e2e-pr.yml

I split `e2e-ci.yml` into three workflows:
1. A re-usable workflow to run Android E2E tests (`e2e-android.yml`).
2. A workflow that runs E2E tests on one device on iOS and one device on Android, whenever a PR into `main` is opened. It utilizes the re-usable Android workflow.
3. A workflow that runs E2E tests on one device on iOS and on multiple devices on Android. This workflow is called whenever a commit is pushed to `main`, the workflow is called manually from the Github UI, and once per day on a schedule. It also utilizes the re-usable Android workflow
Do note, the iOS side of things is still a WIP. My next PR will break out the copied iOS steps into their own reusable workflow, like Android, and will allow running on multiple iOS versions. I'm also looking into getting it working on …

Run E2E Suite on Multiple Android Versions

---

src/account/saga.test.ts
src/account/saga.ts
src/app/actions.ts
src/web3/networkConfig.ts

When initialising (restoring) wallet, check if there is a phone number already verified for this wallet. If so, store the verified phone number in redux so that the user correctly displays as verified in the app.
Note that the signed message is required for making the address lookup query, and this is generated potentially after the restore saga finishes so that's why it's in the initializeAccount saga now... 
N/A
Manually + unit tests.
Verify a phone number against an address. Reinstall the app and restore this account - the app should know that your number is verified.
- Fixes RET-451
Yes

feat: restore phone verification status when restoring wallet

---

src/fiatconnect/FiatDetailsScreen.test.tsx

For https://github.com/valora-inc/wallet/pull/2979#discussion_r993412171
N/A
unit tests
N/A
N/A
N/A

test(FiatDetailsScreen): use getBy* over queryBy*

---

src/web3/networkConfig.ts

On Valora alfajores, tapping on "View on CeloExplorer" from a swap detail screen should open the explorer showing the transaction details.
See above.
- RET-440
Yes

chore: update blockscout/explorer alfajores url to avoid redirect

---

.github/scripts/automergeCrowdinPr.js
.github/workflows/automerge-crowdin.yml

I found the automerge job sometimes leaves the "changes requested" review when the Crowdin PR does not contain any unexpected changes. I suspect that it is because the review is done before the branch is properly updated. e.g. https://github.com/valora-inc/wallet/pull/2982
In this PR
- wait for a few seconds after updating the branch, to do the review
- make the logging more explicit so that we can see which files are causing the incorrect review
N/A
Tested https://github.com/valora-inc/wallet/actions/runs/3243609016/jobs/5318572378
N/A
N/A
Yes

fix: crowdin automerge job sometimes leaves incorrect reviews

---

__mocks__/react-native-device-info.ts
src/account/SupportContact.test.tsx
src/account/SupportContact.tsx
src/app/__snapshots__/Debug.test.tsx.snap

This was a request from the support team, this can be helpful for debugging.  e.g. in RET-445.
N/A
Manually
Shake to contact support. When the email appears, see that the expect values of device brand and model are present in the email body.
N/A
N/A

chore: add device brand and model to contact support log information

---

src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Removes the unused swapFeeEnabled and swapFeePercentage from redux and remote config. A follow up PR to #2977 based on https://github.com/valora-inc/wallet/pull/2977#discussion_r993054558.
N/A
Tested in CI.
Ensure that the app loads.
N/A
Yes

chore: remove swapFeeEnabled and swapFeePercentage

---

e2e/src/usecases/SecureSend.js
src/components/KeyboardAwareScrollView.tsx
src/components/__snapshots__/ReviewFrame.test.tsx.snap
src/exchange/__snapshots__/ExchangeTradeScreen.test.tsx.snap
src/exchange/__snapshots__/WithdrawCeloScreen.test.tsx.snap
src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap
src/identity/__snapshots__/PhoneNumberLookupQuotaScreen.test.tsx.snap
src/import/__snapshots__/ImportWallet.test.tsx.snap
src/paymentRequest/__snapshots__/PaymentRequestConfirmation.test.tsx.snap
src/paymentRequest/__snapshots__/PaymentRequestConfirmationLegacy.test.tsx.snap
src/send/ValidateRecipientAccount.tsx
src/send/__snapshots__/SendConfirmation.test.tsx.snap
src/send/__snapshots__/SendConfirmationLegacy.test.tsx.snap
src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap
src/verify/__snapshots__/VerificationInputScreen.test.tsx.snap

- Adds a testID to `KeyboardAwareScrollView`. 
- Uses test util `scrollIntoView` from `e2e/src/utils/utils.js` to scroll the submit button into view.
N/A
Tested locally on Android and in CI.
N/A
N/A
Yes

test(e2e): add scroll in secure send

---

locales/base/translation.json
src/fiatconnect/kyc/KycDenied.tsx
src/fiatconnect/kyc/KycExpired.tsx
src/fiatconnect/kyc/KycPending.tsx
src/fiatconnect/kyc/getNavigationOptions.tsx

Talked over all changes w/ Nitya & Laura
1. X button in the top left goes to home now
2. Bring the content up so it looks more centered ([Videos of the old ones where the content looks a little low](https://github.com/valora-inc/wallet/pull/2921))
3. Copy change around Re-try kyc button
Manually went through[ KYC flows](https://docs.google.com/document/d/1tVSk6KfJu0_I8fTTFMn1WRb-PCuZr4bKNeIyKpa8DAo/edit#) with the changes

fix(fiatconnect): Small changes to copy/style/function of kyc status screens

---

src/components/CodeInput.tsx
src/verify/VerificationCodeInputScreen.tsx

As the title
N/A
Manually
See that the sms verification code input is automatically focused when going through the CPV flow.
N/A
Yes

feat: auto focus on code input for CPV verification

---

src/backup/BackupIntroduction.tsx
src/backup/BackupPhrase.tsx
src/backup/__snapshots__/BackupPhrase.test.tsx.snap

Header was double height - less visible in the screenshots, but on smaller screens it was evident. Most of the lines are from a new snapshot.
Fixes the header display for the recovery phrase quiz.
Fixes the header display for the recovery phrase display.
</p>
</p>
Snapshots updated.
Tested locally in iOS and Android
1. Navigate to Recovery Phrase Quiz - either from reset or from onboarding.
2. Check Headers and layout.
3. Complete quiz.
4. After completing the Recovery Phrase Quiz check the headers and layout.
N/A
Yes

fix: recovery phrase display

---

.github/workflows/check.yml

It looks like this one was just missed when we originally switched all the checks to node 16 in https://github.com/valora-inc/wallet/pull/2474/files

chore(ci): Use node 16 for the licenses check

---

package.json
src/fiatconnect/index.test.ts
src/fiatconnect/index.ts
src/fiatconnect/saga.test.ts
src/fiatconnect/saga.ts
yarn.lock

Related to https://github.com/valora-inc/valora-rest-api/pull/183. 
Changed deprecated currentAccountSelector to walletAddressSelector in fiatconnect/saga.ts
Unit tests, manual by running the app and checking the request includes address on flipper
1. Navigate to Add or Withdraw
2. Select withdraw funds
3. Choose any currency and enter any amount
4. Ensure "Bank Account" shows up in the Select Provider screen
N/A
N/A

fix(fiatconnect): pass address to getQuotes

---

src/app/App.tsx

Removes a duplicate block of code for handling Deep Links on iOS. I believe it was added via a bad merge.
When @kathaypacific was testing the analytics around the invite link, I believe she reported seeing some duplicate events. This is likely the cause.
N/A
N/A
I would appreciate some help testing on iOS, as I don't have an iOS device to test on.
N/A
N/A

fix(deep link): Remove duplicate block handling dynamic links on iOS

---

src/backup/BackupIntroduction.tsx

After #3014 the initial header for the recovery phrase the hamburger menu icon was outside of the safe area boundaries boundaries.
</p>
N/A
Tested locally on iOS
Prerequisite:  a new wallet
1. Navigate to recovery phrase quiz.
2. Ensure that the menu icon is within the safe area boundaries. 
N/A
Yes

fix: header on initial recovery phrase screen

---

src/home/CashInBottomSheet.tsx

https://user-images.githubusercontent.com/8432644/198121473-82d2dda3-786b-46f8-b012-3a588af89d99.mp4
Fixes https://valora-app.slack.com/archives/C02N3AR2P2S/p1666741437531239
I narrowed down the exact time to use by replacing the entire useAsync function with a `sleep(<time>)` function and adjusted time until the issue consistently didn't reproduce. 1000 was the lowest It could go. 
On an iOS simulator/device on *main build* attempt to onboard all the way to the Home screen. Verify that the screen is not frozen AND the cash in bottom sheet shows up
> you may have to turn on the cash in bottom sheet feature flag to see it
- Fixes https://valora-app.slack.com/archives/C02N3AR2P2S/p1666741437531239

fix(home): Fix frozen home screen on iOS

---

src/firebase/notifications.test.ts
src/firebase/notifications.ts
src/notifications/types.ts

Navigates to ReviewScreenWrapper on KycApproved notification. Builds on #3036 
Refactored handling `AppAlreadyOpen` at a more generic place instead of every handler
Unit tests and manually by sending a notification. Could only test app opened state, since notifications are not showing up on the emulator. Will test app closed state once this is merged and available on the nightly build.
Not ready for testing
- Fixes ACT-491
Yes

feat(notifications): handle kyc approved notification

---

src/invite/InviteModal.tsx
src/send/SendAmount/index.tsx

Invite modal display was had incorrect headers for Android devices documented in #3059.
N/A
Tested locally on Android
Check that the invite screen from the side menu and send flow render correctly.
- Fixes #3059
Yes

fix: invite modal display for android

---

package.json
src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/fiatconnect/clients.test.tsx
src/fiatconnect/clients.ts
src/fiatconnect/selectors.ts
src/fiatconnect/slice.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/in-house-liquidity/client.test.ts
src/in-house-liquidity/client.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts
yarn.lock

react-native's fetch implementation doesn't have a default timeout option and requests can hang for a long time. This PR uses the latest fiatconnect-sdk (which supports timeouts) to set a timeout on all fiatConnect and IHL requests. The timeout is configurable through firebase remote config
N/A
Unit tests, manually by setting a low value for timeout (500ms) and checking if selecting a quote for a provider, which should trigger a login with the provider, errors out with an AbortError .
N/A
- Fixes ACT-499
Yes

feat(fiatconnect): add timeout to fiat connect requests

---

src/verify/VerificationStartScreen.test.tsx
src/verify/VerificationStartScreen.tsx

Context: https://valora-app.slack.com/archives/C044B8ULVC0/p1667413326982599
This PR introduces a loading state to the phone verification start button while the signed message is not available. Previously on android this can fail: 
- during onboarding the "initialise account" action is dispatched on this screen load
- the signed message is only generated after the account has been generated, but this is an asynchronous action
- if the user navigates to the next CPV step before the previous step is complete, there is no signed message for authentication with CPV, so the verification will always fail here.
N/A
Manually + unit tests. 
On android device:
- create a new account + verify phone number. it should succeed
N/A
Yes

fix: failed CPV during onboarding due to missing signed message

---

src/fiatExchanges/PaymentMethodSection.tsx

Previously, we were getting a warning when rendering the `SelectProvider` screen after fetching quotes:
```
INFO  [1667836533196] Warning: Cannot update a component (`SelectProviderScreen`) while rendering a different component (`PaymentMethodSection`). To locate the bad setState() call inside `PaymentMethodSection`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
in PaymentMethodSection (at SelectProvider.tsx:229)
in RCTScrollContentView (at ScrollView.js:1674)
in RCTScrollView (at ScrollView.js:1792)
in ScrollView (at ScrollView.js:1818)
in ScrollView (at SelectProvider.tsx:228)
in SelectProviderScreen (at SceneView.tsx:130)
```
This was due to the fact that when rendering the `PaymentMethodSection` component within `SelectProvider` screen, it would …

fix(fiatconnect): Fix state warning on `SelectProvider` screen

---

src/fiatExchanges/FiatExchangeAmount.test.tsx
src/fiatExchanges/FiatExchangeAmount.tsx
src/fiatconnect/saga.test.ts
src/fiatconnect/saga.ts
src/fiatconnect/slice.ts

* Check that fiatAccountSchema for the account on file matches the fiatAccountSchema for the cached quote in the return user flow.
This work was mostly already done by @jophish in https://github.com/valora-inc/wallet/pull/3040 . This is just connecting part of what he already built.
Unit tests
N/A
https://linear.app/valora/issue/ACT-402/ensure-that-fiat-account-schema-is-eligible-in-return-user-flow
Previous incompatible cached accounts were handled in joe's previous pr

fix(fiatconnect): check fiatAccountSchema in return user flow

---

src/fiatconnect/FiatDetailsScreen.tsx

Currently, if a user submits fiat details, and the submission fails, they will be brought back to the Fiat Details screen, and a memory leak warning will be logged:
```
INFO  [1667838148077] Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in FormField (at FiatDetailsScreen.tsx:203)
```
I believe this warning was coming from the fact that it was possible that the `setTimeout` in `FormField` had neither fired nor been cleared by the time that the user had clicked submit. (Our timeout fires after 1.5 seconds atm, so this is very possible.) If the `setTimeout` fires after the user has hit submit, we attempt to …

fix(fiatconnect): Fix memory leak warning on Fiat Details screen

---

src/fiatExchanges/FiatExchangeAmount.test.tsx
src/fiatExchanges/FiatExchangeAmount.tsx

Pretty short and sweet. We used to check that the cashed fiat account use matches on flow, but now we do not.
Additional unit tests
N/a
https://linear.app/valora/issue/ACT-401/re-use-fiat-accounts-between-cash-in-and-cash-out

feat(fiatconnect): re-use existing fiatAccounts between cash-in and cash-out

---

src/verify/VerificationStartScreen.test.tsx
src/verify/VerificationStartScreen.tsx

As the title - perhaps fixes this error https://valora-app.slack.com/archives/C044B8ULVC0/p1668449338531799
N/A
Unit tests
N/A
N/A
Yes

fix: ensure CPV start button is disabled when signed message unavailable

---

src/app/saga.test.ts
src/app/saga.ts

For users who created their accounts before app version 1.32 and have never entered their pincode, they will not have a signed message to use for authentication. This PR skips the CPV migration for these users, since it will always fail.
N/A
Unit tests
N/A
Fixes RET-490
Yes

chore: skip ASv1 CPV migration for users who have no signed message

---

src/send/ValidateRecipientAccount.tsx
src/send/__snapshots__/ValidateRecipientAccount.test.tsx.snap

Adjust the header hight for `ValidateRecipientAccount.tsx`.
</p>
N/A
Tested locally on iOS and Android
Check screenshots
N/A
Yes

fix: secure send header height

---

e2e/src/Rewards.spec.js
e2e/src/usecases/NewAccountOnboarding.js
e2e/src/usecases/NewAccountPhoneVerification.js
e2e/src/usecases/RestoreAccountOnboarding.js
e2e/src/utils/utils.js
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/pincode/PincodeSet.tsx
src/redux/store.test.ts
src/verify/VerificationStartScreen.tsx

Komenci has been shut down and the onboarding pincode screen checks for it's uptime before navigating to the phone verification screen. This is not necessary with CPV, this PR adds this logic.
Update test id's - rather than update the tests i updated the test id of the component :/ didn't think it mattered to much
Run CI, test manually
Create a new account, you should see phone verification in the onboarding flow
n/a
Y

fix: use CPV with e2e tests after komenci sunset

---

e2e/src/usecases/FiatConnectTransferOut.js

Dismiss bottom sheet before asserting home screen element after return user flow, which should fix occasional failures on the fc transfer out tests
N/A
CI
N/A
N/A
N/A

test(e2e): dismiss bottom sheet on home screen for fc tests

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/fiatconnect/TransferStatusScreen.test.tsx
src/fiatconnect/TransferStatusScreen.tsx
src/web3/networkConfig.ts

Repurposed SuccessSection in the TransferStatusScreen to also include a transaction processing state, since they both are similar.
https://user-images.githubusercontent.com/5062591/202879707-f03272ec-a397-459a-99f7-329a9a2bb6d0.mp4
N/A
N/A
- Resolves ACT-533
Yes

feat(fiatconnect): add transaction processing screen

---

locales/base/translation.json
src/fiatconnect/TransferStatusScreen.test.tsx
src/fiatconnect/TransferStatusScreen.tsx

If the transfer is taking a while, shows some text.
na
added unit test
used hacks to get the screen to display locally. here's what it looks like:
video version to show the timeout behavior:
https://user-images.githubusercontent.com/7979215/203195993-f3f1d083-98d8-4371-a584-eefdb8e146c7.mp4
compare to designs:
https://www.figma.com/file/PJptgCmZjQ6TMIfRYvgRjw/Withdraw-Status?node-id=2%3A1451&t=frjLRFll8bk6xTAj-4
na
fixes https://linear.app/valora/issue/ACT-532/show-text-under-transfer-out-spinner-after-some-timeout-is-reached
na

feat(fiatconnect): transfer status loading description

---

ios/Podfile.lock
package.json
src/app/Debug.tsx
src/backup/BackupPhraseContainer.tsx
src/components/AccountNumber.test.tsx
src/components/AccountNumber.tsx
src/components/SessionId.tsx
src/components/WithPasteAware.tsx
src/utils/useClipboard.ts
src/walletConnect/screens/RequestContentRow.tsx
yarn.lock

The upstream version includes our changes:
* Our changes: https://github.com/react-native-clipboard/clipboard/compare/master...valora-inc:clipboard:master
* Commit pulling in our changes: https://github.com/react-native-clipboard/clipboard/commit/a83fce847e2e1e2895bc1e45658b886d01bef8bc

chore: switch to upstream version of @react-native-clipboard/clipboard

---

.depcheckrc

So this isn't flagged by depcheck
N/A
Using yarn depcheck 
N/A
N/A
N/A

chore(deps): add react-native-fast-crypto to .depcheckrc

---

.depcheckrc

https://github.com/microsoft/tslib#tslib
After this, only remaining unused dependency is @komenci/contracts which is removed in #3160
N/A
yarn depcheck
N/A
N/A
N/A

chore(deps): add tslib to .depcheckrc

---

src/fiatExchanges/ExchangeQR.tsx
src/qrcode/QRCode.tsx
src/qrcode/StyledQRCode.tsx
src/qrcode/utils.test.tsx
src/qrcode/utils.ts

Old QR screens were already updated to be able to handle address, new screen needs it too. 
Exchange QR screen should always encode address.
Tested by updating the code locally to display the Exchange QR Code screen and successfully scanned the QR code with metamask and coinbase. 
https://linear.app/valora/issue/ACT-543/update-qr-code-within-qr-code-screen

fix(qrcode): Switch the Exhange QR code screen to encode address

---

locales/base/translation.json
src/analytics/constants.ts
src/fiatExchanges/SelectProvider.test.tsx
src/fiatExchanges/SelectProvider.tsx
src/fiatExchanges/types.ts

Actually uses the experiment params and implements the experiment variant to use the appropriate text and navigate to the right screen.
https://user-images.githubusercontent.com/5062591/207996690-6e1d6836-7a74-47ca-a740-d0d80bfbeb2a.mp4
Renamed enums to exactly match screen names
Unit, manual by setting up overrides in statsig
1. Add your wallet address to the appropriate variant of the [experiment in statsig](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/experiments/add_funds_crypto_exchange_qr_code/setup)
2. Navigate to Add funds, select any currency and enter any amount
3. Ensure external exchanges section is visible on the "Select Payment Method" screen with the appropriate text ("Deposit From" for variant, "Cryptocurrency Exchange" for control)
4. Click on exchanges section and …

feat(cico): use add funds crypto exchange experiment params

---

src/dappsExplorer/useDappFavoritedToast.tsx

Tried it locally, seems is covering what we need.
The toast always stays for the full duration after every favoriting action.

Proposal to simplify timeout management

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/exchange/CeloNewsFeed.test.tsx
src/exchange/CeloNewsFeed.tsx

Since the Celo News feed is currently displayed in the existing `ExchangeHomeScreen` screen, it would have been more difficult to differentiate users having been exposed to it vs the existing CELO transaction feed.
Hence the dedicated event.
- Fixes RET-519
Yes

feat(celo-news): add analytics event when the feed is mounted

---

src/navigator/DrawerNavigator.tsx

From the [experiment design](https://www.notion.so/valora-inc/Celo-news-feed-43e09037425949b38f2fdc79812a62e3) we learned users tapping the CELO menu item drop at the Celo education carousel.
So when Celo News is enabled, we now skip it too.
Note: I slightly refactored the menu item thing so we don't have to repeat ourselves.
- When Celo News is enabled, tapping the CELO menu item should directly show the news feed, without the Celo education carousel.
Discussed on [Slack](https://valora-app.slack.com/archives/C0494B52JTH/p1671805415760139).
Yes

feat(celo-news): skip Celo education carousel when celo news is enabled

---

src/analytics/ValoraAnalytics.test.ts
src/analytics/ValoraAnalytics.ts

Use wallet address instead of account address for statsig user
Unit tests
N/A
Yes

fix(statsig): use wallet address instead of account address

---

src/analytics/ValoraAnalytics.test.ts
src/analytics/selectors.test.ts
src/analytics/selectors.ts
src/app/selectors.test.ts
src/app/selectors.ts
src/web3/selectors.ts

Remove accountAddressSelector to prevent bugs like the one Jean fixed [here](https://github.com/valora-inc/wallet/pull/3294/files#diff-8d33cbb0da323fba8e3986c827ba5c2d362c018756e78445f3b6c0606f413780R137). 
The name of the accountAddressSelector introduces high risk of mistaking it for a wallet address selector, but in reality, it selects MTW address and uses wallet address as a fallback. We have largely discontinued use of the MTW address, so this selector should not be needed anymore. 
added unit tests
na
should be backwards compatible. assumed in 1 place that wallet address is always non-null if MTW address is non-null-- see code comment in `app/selectors.test.ts` for details

chore(mtwAddress): remove accountAddress selector to prevent bugs

---

android/app/src/main/java/org/celo/mobile/MainApplication.java
android/app/src/main/java/org/celo/mobile/UserAgentClientFactory.java
android/app/src/main/java/org/celo/mobile/UserAgentInterceptor.java

PR for Android to unify the `User-Agent` header for all network requests.
Tested the new `User-Agent` is used for all requests (fetch, Images, etc) using [Proxyman](https://proxyman.io/).
Examples:
- forno: <img width="1143" alt="Screenshot 2023-01-06 at 12 34 07" src="https://user-images.githubusercontent.com/57791/211006338-a5c88d14-9257-4b7e-b865-6b17bf64974d.png">
- an image: <img width="1141" alt="Screenshot 2023-01-06 at 12 43 31" src="https://user-images.githubusercontent.com/57791/211006365-fc5ce5a4-284d-4c47-a42d-40c906a573bf.png">
Browsing in our WebView keeps the default User-Agent, as expected, here with Bidali:
- Fixes RET-558
No, services depending on the existing `User-Agent` need to be updated.

feat!: new User-Agent header on Android

---

src/home/DappsCarousel.test.tsx
src/home/DappsCarousel.tsx

During the refactor to create the dapps carousel, the maximum number of dapps got lost :( This PR fixes that, and adds tests. The remote config variable is a bit confusingly named now since it is not specific to recently used dapps, i can change this including the actual remote config variable in a follow up PR. 
Added unit tests, tested manually
N/A
Y

fix: ensure max number of dapps in dapps carousel

---

src/dappsExplorer/DAppsExplorerScreen.tsx

Requested by Reed, this PR makes the dapps screen horizontal margins consistent. Reed and Nitya have decided on 24px margins going forward. Notice in the "before" screenshot how the left edge of "Explore ways to use your crypto" is indented compared to the dapps cards.
Before:
After:
n/a
n/a
Y

chore: align dapps screen horizontal margins

---

ios/Podfile.lock
package.json
yarn.lock

Upgrade ua-parser-js for [ReDoS Vulnerability in ua-parser-js version <0.7.33 / <1.0.33](https://github.com/faisalman/ua-parser-js/security/advisories/GHSA-fhg7-m89q-25r3).
CI.
N/A
Yes

build(deps): upgrade ua-parser-js

---

ios/Podfile.lock
package.json
patches/react-native-shake+5.1.1.patch
src/account/ShakeForSupport.tsx
yarn.lock

The breaking change is only in the syntax of the shake subscription https://github.com/Doko-Demo-Doa/react-native-shake#usage. Unfortunately the newest version overrides [the fix for xcode 12 compatibility](https://github.com/Doko-Demo-Doa/react-native-shake/commit/b275ce3c77fe56cb05d2426b45b8b36fceca7c05) so i added a patch.
This flow is covered by e2e tests
- Fixes RET-566
Y

chore: upgrade react-native-shake to v5

---

src/transactions/send.test.ts
src/transactions/send.ts

We've seen a case in testing where a user got this error in their logs
```
info [2023-01-23T17:15:17.387Z] FiatConnectSaga :: Transaction failed: c2ba9fc0-4f75-4526-b383-b59e947fc981 :: Failed to check for transaction receipt:
{} in _fireError@/private/var/containers/Bundle/Application/DA4D4DB7-095F-4CFC-A18B-4162D7E9283D/celo.app/ :: network connected true
```
and was presented with the option to retry the FiatConnect transfer, but when they retried, they ended up with 2 transfers. 
If we get that tx error, we should avoid allowing the user to retry their transfer, since it may still be confirmed.
unit tested. not sure we can reproduce this one manually.
na
yes

fix(fiatconnect): avoid allowing user to retry if tx might still be pending

---

src/navigator/DrawerNavigator.test.tsx
src/navigator/DrawerNavigator.tsx

- Added new tests
- Manually by setting an empty `dappListApiUrl` and seeing the crash before the fix
- Fixes RET-585
Yes

fix: crash when dappListApiUrl is empty

---

src/analytics/types.ts
src/fiatExchanges/SelectProvider.tsx
src/onboarding/registration/NameAndPicture.tsx
src/statsig/constants.ts
src/statsig/types.ts

minor cleanup to move statsig types and constants out of analytics files
existing automated tests and build ci should cover this
na
na

refactor(statsig): move constants and types to statsig dir

---

e2e/src/usecases/DappListDisplay.js
scripts/sync_branding.sh
src/dappsExplorer/useDappInfoBottomSheet.tsx
src/webview/WebViewScreen.tsx

I forgot to update the branding hash after I added the new dapps support link, the CI was passing with [silent errors](https://github.com/valora-inc/wallet/actions/runs/4053160940/jobs/6973448494) in my branch, which i didn't notice. the CI correctly fails on [main](https://github.com/valora-inc/wallet/actions/runs/4053379964/jobs/6973931410).
n/a
- Fixes RET-550
Y

fix: broken dapps support url

---

e2e/src/usecases/WalletConnectV2.js
locales/base/translation.json
src/dappkit/DappKitSignTxScreen.tsx
src/walletConnect/screens/ActionRequest.test.tsx
src/walletConnect/screens/ActionRequest.tsx
src/walletConnect/screens/DappsDisclaimer.tsx
src/walletConnect/screens/RequestContent.tsx

This PR adds the dapps disclaimer to the dapps bottom sheet for the variant group of the dapps disclaimer experiment.
Added a unit test for the happy flow, that seemed like the most important one. Screenshot:
- Fixes RET-551
Y

feat: display dapps disclaimer on dapps bottom sheet

---

src/swap/saga.test.ts
src/swap/saga.ts
src/web3/networkConfig.ts

We are calling 0x api twice, one to get the details of the swaps (the amounts and prices) and another to confirm everything is ready to execute the swap. This increases how long the swaps take to complete, two fetches instead of one and produces errors with the guaranteed price when the buy amount is set. To simplify we are now using the transaction object returned from the `/approveSwap` endpoint instead of subsequently calling the `/executeSwap` endpoint and using the swap transaction present in that response. This is more inline with the [0x API docs](https://docs.0x.org/0x-api-swap/guides/swap-tokens-with-0x-api) and will make future swap router implementations easier.
Tested locally on Android and saga tests updated.
- Fixes RET-572
Yes

fix: low allowance swap issues

---

e2e/src/usecases/SecureSend.js

Temporarily disable this test while we determine what to do with Odis. 
https://valora-app.slack.com/archives/C025V1D6F3J/p1676979118551299
y

chore(ci): Disable secure send e2e test

---

package.json
yarn.lock

This resolution was added to fix a vulnerability (#455), which occurred because react-native-svg had css-what@^3.2.1 as a downstream dependency. However, react-native-svg now has css-what@^6.0.1 as a downstream dependency, so this resolution is unnecessary.
CI
N/A
Yes

chore(deps): remove css-what resolution

---

src/components/ValidatedTextInput.tsx

Context: https://valora-app.slack.com/archives/C029MMTD529/p1677719177909599, https://valora-app.slack.com/archives/C025V1D6F3J/p1678194369634539?thread_ts=1677719863.631589&cid=C025V1D6F3J
We use the value in the phone number text input to do the phone number validation, but as soon as the validation succeeds, we add the country code to the text input. Subsequent validations are performed with a phone number that includes the country code, which always fails. This PR fixes this issue.
This phone number can now be validated:
https://user-images.githubusercontent.com/20150449/223467814-ae6beaeb-6ccd-4dfb-8ca7-77c9fcb376e9.mp4
We can also backspace on a validated number:
https://user-images.githubusercontent.com/20150449/223469228-5e1232c3-de01-49d8-9cee-4020ad71a903.mp4
- Fixes RET-553, …

fix: phone number format not recognised on verification screen

---

e2e/src/usecases/SecureSend.js
e2e/src/usecases/Send.js
src/send/Send.tsx

See [this Slack thread](https://valora-app.slack.com/archives/C04B61SJ6DS/p1678289764167129) for more context.
Currently, on the send flow, it's possible for the keyboard to be present _on top_ of the bottom sheet under certain circumstances. This PR explicitly dismisses the keyboard when the bottom sheet is made visible.
Manual tested and sort-of-e2e tested. Video below:
https://user-images.githubusercontent.com/569401/223771083-e8f97839-1b80-4a6d-93d2-d470d3c8e6ae.mp4
Yes.

fix(send): Dismiss keyboard on Send screen bottom sheet

---

src/dappsExplorer/DappCard.tsx
src/styles/fonts.tsx

Following https://github.com/valora-inc/wallet/pull/3499, the dapps screen didn't look good anymore.
Plus, added an `xsmall` font style for places where we need 12px text.
Following the 
- Discussed with Reed on Slack
Yes

fix(dapps): tweak dapps title and description to match the designs

---

.vscode/settings.json

This avoids seeing incorrect TS issues in VS Code.
Taken from https://github.com/valora-inc/typescript-app-starter/pull/33

chore: use the project's TypeScript version instead of the one bundled with VS Code

---

src/utils/Logger.ts
src/utils/stylize.ts

Some improvements:
- Use time instead of timestamp: simpler for us, humans :)
- Aligned times: easier to parse visually
- Add device model with darker color: avoids confusion when multiple devices are connected to the packager. The darker color helps with visual parsing too.
**Packager logs (before)**
**Packager logs (after)**
- Fixes RET-648
Yes

feat: better packager logs

---

src/walletConnect/v1/saga.ts
src/walletConnect/v2/saga.test.ts
src/walletConnect/v2/saga.ts

This PR fixes the issue observed where any unhandled error in a WC action handler would cancel all other listeners for WC actions. The only way to recover was to restart the app.
It uses the `safely` helper added in #3526.
Note: there are other places in the codebase suffering from the same issue. We can open additional PRs for them.
- Added unit test
- Fixes RET-654
Yes

fix(wc): prevent unhandled errors from cancelling all WC action handlers

---

src/pincode/Pincode.tsx
src/pincode/PincodeSet.tsx

We need to ensure that the pincode screen content fits on the screen, or else users could be blocked from entering their pincode for transactions.
This PR is a quick solution for now - 
- make the pincode keyboard always available
Tested with iPhone SE (I could repo the original problem with this screen size) with slightly larger device font.
https://user-images.githubusercontent.com/20150449/225001593-4f12f240-e128-44cb-ba86-ad55d492c895.mp4
https://user-images.githubusercontent.com/20150449/225001599-d796f0c7-0cee-43c5-ba87-a7b2dae2bb9b.mp4
https://user-images.githubusercontent.com/20150449/225003939-980fa63f-f633-425d-8da6-9704cbd33370.mp4
- Fixes SUP-62
Y

fix: ensure pincode buttons fit on all screen sizes

---

src/utils/Logger.test.ts
src/utils/Logger.ts

Long time issue finally fixed 😅 
Letting `console` do its job is better.
See also: #3546
**before**
```
DEBUG  [08:35:39.590Z] iPhone 13 TEST/This is Logger.debug, [object Object]
INFO   [08:35:39.591Z] iPhone 13 TEST/This is Logger.info, [object Object]
WARN   [08:35:39.591Z] iPhone 13 TEST/This is Logger.warn, [object Object]
ERROR  [08:35:39.595Z] iPhone 13 TEST :: This is Logger.error :: Test error in rootSaga$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&ru :: network connected true
```
**after**
```
DEBUG  [08:37:33.787Z] iPhone 13 TEST This is Logger.debug {"someVal": "test"}
INFO   [08:37:33.792Z] iPhone 13 TEST This is Logger.info {"someVal": "test"}
WARN   [08:37:33.793Z] iPhone 13 TEST This is Logger.warn {"someVal": "test"}
ERROR …
```

fix(logger): `[object Object]` logged instead of the serialized data

---

src/analytics/ValoraAnalytics.ts
src/consumerIncentives/saga.ts
src/dappkit/dappkit.ts
src/fiatconnect/saga.ts
src/firebase/firebase.ts
src/redux/sagas.ts
src/send/saga.ts
src/tokens/saga.ts
src/transactions/feed/queryHelper.ts
src/transactions/send.ts
src/walletConnect/v1/saga.ts
src/web3/KeychainSigner.ts
src/web3/contracts.ts

Following #3545, we no longer need to stringify objects passed to our logger.
- Manually checked logs have all the info needed
- Fixes RET-648
Not entirely as the data in log file will change a bit, this shouldn't affect anything though.

chore(logs): remove unnecessary stringification

---

src/consumerIncentives/slice.ts
src/redux/store.ts

To ensure that remote config values in the store are persisted (and we don't always hit the v1 supercharge endpoint for no reason once v2 is enabled.)
Manually tested
n/a
Y

chore: remove supercharge from redux persist blacklist

---

src/home/WalletHome.test.tsx
src/home/WalletHome.tsx
src/statsig/constants.ts
src/statsig/types.ts

Fixes ACT-702. Adds in some statsig boilerplate/defaults for the home screen actions experiment, and hides the nav bar on the home screen if the `showHomeNavBar` parameter is set to `false`.
Unit and manual tested.
- Fixes ACT-702.
Yes.

feat(home): Hide nav bar in home screen actions experiment

---

__mocks__/src/analytics/ValoraAnalytics.ts
src/app/App.tsx
src/app/AppInitGate.test.tsx
src/app/AppInitGate.tsx
src/statsig/index.ts

Currently statsig initializes asynchronously (part of ValoraAnalytics.init) and the home screen requests experiments before initialization completes, resulting in loading the default experience and then switching to the appropriate variant. This makes analytics init a blocking call before rendering the first screen (home / onboarding)
Unit test and manual. Also ensured the below `getExperimentParams` warn log doesn't show up:
```
getExperimentParams Error getting experiment params [Error: Call and wait for initialize() to finish first.] 
```
Before:
https://user-images.githubusercontent.com/5062591/229637645-73c24b62-61d9-475a-9459-a74d2e928c0d.mp4
After:
https://user-images.githubusercontent.com/5062591/229638156-244bcac9-9199-4593-bc05-ae194a40ab2d.mp4
N/A
Yes

fix(statsig): initialize before home screen requests experiments

---

src/backup/selectors.test.ts
src/backup/selectors.ts
src/navigator/NavigatorWrapper.test.tsx
src/navigator/NavigatorWrapper.tsx

for the backup in onboarding experiment, we want to turn off forced backup if the experiment param says to do so
automated tests
should have been done in https://linear.app/valora/issue/ACT-643/set-up-statsig-experiment-determine-bucketing-in-wallet-disable-forced
na

fix(forced-backup): disable forced backup if experiment param says to

---

src/components/BottomSheet.tsx
src/dappsExplorer/useDappInfoBottomSheet.tsx

Noticed when working on #3599. Currently if the keyboard is visible the when `openSheet` is called the bottom sheet will display behind the keyboard. If there is no keyboard visible on the screen, then the `Keyboard.dismiss()` method will not have any effect.
- `openSheet` from `src/dappsExplorer/useDappInfoBottomSheet.tsx`
- `src/components/BottomSheet.tsx`
https://user-images.githubusercontent.com/26950305/230246866-57bd2246-cb55-4d79-9672-6712e071fb9b.mov
https://user-images.githubusercontent.com/26950305/230247068-85bc3ada-f6dc-4302-9537-e0e30c3c2642.mov
Tested locally on iOS and Android
N/A
Yes

fix: dismiss keyboard on bottom sheet open

---

src/account/actions.ts
src/account/reducer.ts
src/account/selectors.ts
src/analytics/ValoraAnalytics.ts
src/navigator/Navigator.tsx
src/navigator/initalRoute.test.tsx
src/navigator/initialRoute.tsx
src/onboarding/registration/OnboardingRecoveryPhrase.test.tsx
src/onboarding/registration/OnboardingRecoveryPhrase.tsx
src/onboarding/registration/ProtectWallet.test.tsx
src/onboarding/registration/ProtectWallet.tsx
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Currently if the user bails on recovery phrase screen in onboarding, the next time the app is launched, the user lands on the PN verification screen. This updates it so that for the experiment variant, the user lands on the recovery phrase screen.
Manual and unit
Control:
https://user-images.githubusercontent.com/5062591/230488403-ea89bb01-9e4a-4e87-9dfa-0b6fae786730.mp4
V1 - backup on onboarding
https://user-images.githubusercontent.com/5062591/230488682-7d4721f9-81c9-46f1-8a01-2152d1cce103.mp4
V2 - fake door
https://user-images.githubusercontent.com/5062591/230488716-0f2c3317-6b03-4bbe-8292-9e5689df15c8.mp4
- Fixes ACT-700
Yes

fix(onboarding): land on the correct screen if bailed on recovery phrase

---

src/navigator/DrawerNavigator.test.tsx
src/navigator/DrawerNavigator.tsx

fix: check verification status before displaying phone number on drawer

---

src/app/saga.ts
src/dapps/saga.test.ts
src/dapps/saga.ts
src/dapps/selectors.ts
src/dapps/slice.ts
src/dappsExplorer/filter/DAppsExplorerScreenFilter.test.tsx
src/dappsExplorer/search/DAppsExplorerScreenSearch.test.tsx
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/navigator/DrawerNavigator.tsx
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/statsig/types.ts
test/RootStateSchema.json
test/schemas.ts

As the title. This PR adds the statsig experiment and removes the remote config setup, but the config variable names rename the same.
Tested locally
- Fixes RET-679
Y

chore: move dapps filters and search experiment to statsig

---

android/app/src/main/java/org/celo/mobile/MainApplication.java
android/app/src/main/java/org/celo/mobile/UserAgentClientFactory.java
src/consumerIncentives/saga.test.ts
src/consumerIncentives/saga.ts
src/consumerIncentives/slice.ts

This PR expects that a `cache-control: max-age=X` will be returned in the response header for the fetch supercharge service.
After claiming rewards, refresh the cache. 
Checking that cache-control works:
1. Load the app - verify that the server has been hit, the response is stored
2. Reload the app - verify that the server is not hit again
Checking that the refresh works (after modifying the response on the server):
3. After dispatching an action that triggers the force refresh: verify that the server has been hit, the new response is stored
4. Reload the app - verify that the server is not hit again, and the response in step 3 (instead of 1) is stored
- Fixes RET-707
Y

chore: add cache control for fetching supercharge rewards

---

.github/workflows/check.yml
.github/workflows/test.yml
patches/react-native+0.66.4.patch

Backports a fix for a yoga build error in [react-native](https://github.com/facebook/react-native) for XCode 14 - [Related GitHub Issue](https://github.com/facebook/yoga/issues/1224) - [React Native Fix](https://github.com/facebook/yoga/commit/f174de70afdde2492e8677bd0e716eb41bf64469)
Adds the patches folder to the cache path to avoid a cache hit when only a patch file has changed.
Tested locally on iOS.
N/A
Yes

fix: yoga build issue with XCode 14

---

src/navigator/Navigator.tsx

Noticed this warning when running in dev mode a lot. Applied the recommended fix from [here](https://github.com/react-navigation/react-navigation/issues/8517#issuecomment-663838298).
```Looks like you're passing an inline function for 'component' prop for the screen 'DappKitSignTxScreen' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.```
Tested locally on iOS by swapping cUSD to Ethix on Ubeswap.
N/A
Yes

chore: resolve warning for bottom sheet navigator

---

src/swap/SwapAmountInput.tsx
src/swap/SwapScreen.tsx

- Adds input validation that takes into account using either the decimal separator `,` or `.`.
- Changes the keyboard type to `decimal-pad`.
https://user-images.githubusercontent.com/26950305/232643065-9ad1d143-5f95-4d0c-b08b-37dd42afbe0f.mov
</p>
Tested locally on Android and iOS.
Keyboard tested with `,` and `.` variants by setting device region on iOS to France.
- #3074
Yes

feat(swap): input validation and decimal keyboard type

---

src/app/saga.ts
src/fiatExchanges/navigator.test.tsx
src/fiatExchanges/navigator.tsx
src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx
src/fiatconnect/RefetchQuoteScreen.test.tsx
src/fiatconnect/RefetchQuoteScreen.tsx
src/fiatconnect/ReviewScreen.tsx

The Add/Withdraw (FiatExchange) screen doesn't exist if the "Add & Withdraw" drawer menu item is not shown. This PR modifies all places to navigate to home screen instead.
With Add & Withdraw hidden:
https://user-images.githubusercontent.com/5062591/235029218-b49e3456-06b7-42c8-9bd5-7b1486d33ac5.mp4
With Add & Withdraw shown:
https://user-images.githubusercontent.com/5062591/235029225-11f85303-41ea-417d-abbc-55e7b2ec596e.mp4
- Fixes ACT-751
Yes

fix(cico): navigate to home on cancel/failure if add withdraw menu item is hidden

---

src/recipients/RecipientPicker.tsx

This helps for cases where typing in a local number (and eliding the country code).

feat: send recipient as e.164 (if possible) to resolveId endpoint

---

ios/Podfile
ios/Podfile.lock

I forgot that the upgrade RN 67 branch had automerge enabled, and it was merged before I could tidy this up.
There was some change in RN 67 where OpenSSL was no longer part of the release build. This causes a crash on app start. This [article](https://medium.com/@devsalaar/dyld-library-not-loaded-error-on-ios-react-native-fix-guide-bb0b6a91e85a) was helpful for debugging why this happens - it seems that the use_flipper script adds the OpenSSL pod only for debug configurations. Maybe there is a better solution here but it seems like we just need to manually add OpenSSL. 
n/a
- Fixes RET-683
y

chore: remove duplicate openssl pod

---

src/dapps/saga.test.ts
src/dapps/saga.ts

As the title. Context: https://valora-app.slack.com/archives/C02N3AR2P2S/p1683084313143099
Updated unit tests
n/a
y

fix: skip fetching dapplist during onboarding flow

---

src/home/WalletHome.tsx

The transaction feed was truncated at the bottom when home actions are enabled.
It now takes the full height.
N/A
Yes

fix: transaction feed truncated at the bottom when home actions are enabled

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/verify/hooks.ts

The firebase dynamic link (referral link) is consumed on app open, which is (mostly) before there is a wallet address created.  To make the association between invitee and inviter more reliably, add the inviter address to the verification success event.
n/a
n/a
Y

fix: ensure inviter and invitee is present in the same event

---

src/components/TokenBalance.test.tsx
src/home/WalletHome.test.tsx
src/navigator/DrawerNavigator.test.tsx
src/positions/selectors.test.ts
src/positions/selectors.ts

I noticed the total balance was still including the positions after enabling and then disabling the feature flag for positions.
This fixes it.
N/A
Yes

fix(positions): don't include positions in total balance if the feature is disabled

---

src/fiatExchanges/PaymentMethodSection.tsx

otherwise languages with longer words for 'new' look bad
before:
English:
Portuguese:
after:
English:
Portuguese:

fix(cico): avoid wrapping 'new' tag on select providers screen

---

renovate.json5

dep dashboard was warning of a failure to parse the schedule
ci and look at dashboard after merge to see if it still errors out
na
na

fix(renovate): schedule

---

src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx

For ACT-810. Hides the swap action for home screen actions experiment when it's disabled. This check uses the same flag that we use to [determine swap eligibility on the drawer navigator](https://github.com/valora-inc/wallet/blob/main/src/navigator/DrawerNavigator.tsx#L224).
Unit and manual tested.
- Fixes ACT-810.
Yes.

feat(actions): Hide swap action when disabled

---

src/tokens/TokenBalances.tsx

Context https://valora-app.slack.com/archives/C029Z1QMD7B/p1684931810127659
https://github.com/valora-inc/wallet/assets/20150449/61937fb0-3ef7-4c40-b0ba-8744cbc8036e
- Fixes RET-732
Y

fix(tokens): ensure header component is above scrollbar on overscroll

---

src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx
src/icons/BackChevron.tsx
src/navigator/QRNavigator.test.tsx
src/navigator/QRNavigator.tsx
src/navigator/types.tsx
src/qrcode/QRTabBar.tsx
src/send/Send.test.tsx
src/send/Send.tsx
src/send/SendHeader.tsx
src/send/__snapshots__/SendConfirmation.test.tsx.snap
src/send/__snapshots__/SendConfirmationLegacy.test.tsx.snap

The animation for back chevron is broken on the QR screen. After talking to Nitya, we decided to revert the icon to X on the send, receive (QR) and request actions. Swap, Add and Withdraw still use back. Also reverts the Animated change on the BackChevron component since it wasn't working anyway.
https://github.com/valora-inc/wallet/assets/5062591/cf2e5816-f05d-4246-9047-489f6f6788f2
- Fixes ACT-811
Yes

fix(home-actions): use X instead of back for some actions

---

src/app/saga.ts

`this` object was not bound correctly causing analytics events to not fire since https://github.com/valora-inc/wallet/pull/3672 which went in on 1.57.0
Manually, by enabling analytics on dev build
Before, ValoraAnalytics.track was bailing here https://github.com/valora-inc/wallet/blob/ffb97d37a158a78b61dd4a507b3d7dad5b168fa5/src/analytics/ValoraAnalytics.ts#L249-L252
After the fix, confirmed with logs that events are successfully sent to segment
N/A
N/A

fix(analytics): invoke ValoraAnalytics.init correctly

---

src/tokens/AssetItem.test.tsx
src/tokens/AssetItem.tsx

This updates the display of positions with a negative balance (upcoming Moola position hook), or 0 balance.
- show the negative balance
- positions with a 0 balance show a `-` (dash). 
- This can happen if a position has an underlying token for which we have no USD price yet. 
- Also this way the placement of the token amount remains stable when available, as a sub text.
(Faking the negative and 0 positions here).
- Fixes RET-739
Yes

feat(positions): update display of positions with 0 or negative balance

---

android/app/build.gradle
patches/react-native-fast-crypto+2.0.0.patch

This PR fixes the build issue we see [here](https://github.com/valora-inc/release-automation/actions/runs/5350577625/jobs/9708127671#step:17:95). it seems to indicate that there were some changes in the maven dependencies.
This PR:
- applies https://github.com/EdgeApp/react-native-fast-crypto/commit/35f2106bb6904afc4e936b201ff1c46afd56b3f5 as a patch. unfortunately i tried* but failed to make the latest version of react-native-fast-crypto compatible with android 6 and 7, so in the interest of time the patch seems the best option.
- upgrades the exoplayer versions - after resolving the fast-crypto error, i saw the build error below. the version added here is what is recommended in the clevertap-react-native [docs](https://developer.clevertap.com/docs/react-native-quick-start-guide#add-depen …

fix: android release build failure

---

e2e/src/FiatConnectTransferOut.spec.js
e2e/src/usecases/FiatConnectTransferOut.js

See [here](https://valora-app.slack.com/archives/C025V1D6F3J/p1687900991663059) for more context. In order to get builds to pass, temporarily disabling these tests while we fix the source of the issue.
N/A
N/A
Yes.

test(e2e): Skip FC cash out tests for time being on android

---

e2e/src/FiatConnectTransferOut.spec.js

#3923 added conditional test logic that creates an empty suite on Android which causes a test fail, but CI still passes. This PR skips those tests on android instead of conditionally excluding them on Android: [action run](https://github.com/valora-inc/wallet/actions/runs/5397315841/jobs/9802794612).
```
FAIL e2e/src/FiatConnectTransferOut.spec.js
● Test suite failed to run
Your test suite must contain at least one test.
```
Tested locally on Android
https://github.com/valora-inc/wallet/pull/3411
Yes

test(e2e): prevent empty test suite on android

---

src/components/PhoneNumberInput.tsx
src/components/__snapshots__/PhoneNumberInput.test.tsx.snap

This is my "perennial problems" hackathon project.
On iOS, the user's phone number is now suggested, when prompted to enter it. Tapping it above the keyboard fills the input.
This is something I wanted to do for as long as I can remember.
This one line change was made possible following the fixes made by @kathaypacific in https://github.com/valora-inc/wallet/pull/3507
- Tested locally
- N/A
Yes

feat: phone number keyboard suggestion on iOS

---

e2e/src/QRScanner.spec.js

Skip e2e QR scanner tests on android until we tackle some [tech debt with upgrading react-native-animated.](https://linear.app/valora/issue/ENG-76/[wallet]-update-react-native-reanimated-to-v3)
https://linear.app/valora/issue/ACT-821/update-qr-tab-bar-e2e-tests
https://linear.app/valora/issue/ENG-76/[wallet]-update-react-native-reanimated-to-v3

chore(e2e): Don't run QR Scanner e2e tests on Android

---

e2e/src/usecases/DappListDisplay.js
e2e/src/usecases/DappListRecent.js

Specifies [impactMarket](https://www.impactmarket.com/) as the dapp tested in the recent dapp flow. Bidali became the dapp at the top of list replacing Ubeswap when many dapps were disabled in https://github.com/valora-inc/dapp-list/pull/469 and due to it's unique flow the tests started failing.
Tested locally on iOS and both Android and iOS with CI.
N/A
Yes

test(e2e): use impactMarket in dapp tests

---

src/swap/SwapExecuteScreen.test.tsx
src/swap/SwapExecuteScreen.tsx

After investigating the issue (see [issue](https://linear.app/valora/issue/RET-772/[wallet]-[bug]-swap-again-button-doesnt-work-as-expected)), the problem seems to be that when the app goes again to the `SwapReviewScreen` is reusing the `SwapReviewScreen` component from the previous swap, and then is using the already fetched values.
I'm missing the technical details in react of why this exactly happens, I guessed it was because the swap again button goes to the `SwapScreenWithBack`, keeping the component in the tree? I checked on Flipper, and this was happening.
So, I changed it to use the `SwapScreen` without the back button (which I also think is the best experience) and the bug seems to be fixed.
Another solution could be to change the `SwapReviewScreen` code to support multiple uses. …

fix(swap): Fix swap again flow

---

e2e/src/usecases/DappListDisplay.js

Follow up to https://github.com/valora-inc/wallet/pull/3937, where impactMarket was used in all the Dapp tests; however, that domain appears slow to load and is causing failures in our e2e test suites. Instead we should test again a domain we control such as the NFT viewer.
Tested locally on Android and in CI.
N/A
Yes

test(e2e): use nft viewer instead of impactMarket in dapp display tests

---

src/nfts/NftImage.tsx

Nft images in the transaction feed could get into a persisted loading state on Android.
https://github.com/valora-inc/wallet/assets/26950305/c867fb86-2cff-4dd4-bc56-06da9ebc766d
https://github.com/valora-inc/wallet/assets/26950305/af022787-6784-45f0-a97b-de4142035e89
Tested locally on Android 
- #3903
Yes

fix(nft-image): use unique key in dependency array and remove use memo

---

locales/base/translation.json
src/fiatExchanges/CoinbasePaymentSection.tsx
src/fiatExchanges/PaymentMethodSection.test.tsx
src/fiatExchanges/PaymentMethodSection.tsx
src/fiatExchanges/SelectProvider.tsx
src/fiatExchanges/quotes/ExternalQuote.test.ts
src/fiatExchanges/quotes/ExternalQuote.ts
src/fiatExchanges/quotes/FiatConnectQuote.test.ts
src/fiatExchanges/quotes/FiatConnectQuote.ts
src/fiatExchanges/quotes/NormalizedQuote.ts
src/fiatExchanges/quotes/normalizeQuotes.test.ts
src/fiatExchanges/quotes/normalizeQuotes.ts
src/fiatExchanges/utils.test.ts

Show receive amount instead of fees on the SelectProvider page, behind a statsig feature gate. Includes some styling changes to match new designs, which aren't behind the gate.
With feature gate false:
https://github.com/valora-inc/wallet/assets/5062591/f15793b7-0a30-48bb-855e-1e04d83a3e84
With feature gate true:
https://github.com/valora-inc/wallet/assets/5062591/3fa3ed00-ccc3-4063-b5f1-465c3e4c5967
With feature gate false:
https://github.com/valora-inc/wallet/assets/5062591/1e25fee1-6310-4a2f-8fbc-b19b36a605b1
With feature gate true:
https://github.com/valora-inc/wallet/assets/5062591/09d2040a-e5b0-4b3a-80b2-d41e94575c96
- Fixes ACT-842
Yes

feat(SelectProvider): show receive amount instead of fees

---

locales/base/translation.json
src/navigator/NavigatorWrapper.tsx
src/positions/HooksPreviewModeBanner.test.tsx
src/positions/HooksPreviewModeBanner.tsx
src/positions/saga.ts
src/positions/selectors.ts
src/positions/slice.ts
test/RootStateSchema.json

This adds a banner when hooks preview mode is enabled.
Tapping it allows to disable preview mode.
The background color changes based on the fetch status for hooks (both positions and shortcuts)
- idle/loading -> grey
- success -> green
- error -> red
https://github.com/valora-inc/wallet/assets/57791/c0cfa79e-c95a-46d7-a426-e54d384e11d9
- Fixes RET-750
Yes

feat: hooks preview mode banner

---

android/app/src/debug/res/xml/network_security_config.xml
android/app/src/main/res/xml/network_security_config.xml
package.json
src/positions/saga.test.ts
src/positions/saga.ts
yarn.lock

Unlike iOS, Android doesn't allow loading cleartext content from a local server.
Preventing to load hooks from a local dev server.
To allow this, `*.sslip.io` was added to the exception list.
https://sslip.io/ is a handy DNS service which resolves domains like `192.168.0.42.sslip.io` to `192.168.0.42`.
- Added unit test
- Manual test confirming Android can now load hooks from a local dev server:
- Fixes RET-750
Yes

fix: allow loading hooks from preview server on Android

---

locales/base/translation.json
src/app/ErrorMessages.ts
src/dapps/DappShortcutsRewards.test.tsx
src/dapps/DappShortcutsRewards.tsx
src/home/saga.ts
src/positions/saga.test.ts
src/positions/saga.ts
src/positions/selectors.test.ts
src/positions/selectors.ts
src/positions/slice.ts
src/positions/types.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

This PR does 2 things (that made sense to test together)
1. add a saga for triggering a shortcut
2. add some redux state management to display available / claiming / claimed statuses on the rewards screen
The logic for 2 is a little more hefty than I originally planned, i may have overthought the scenario. What i wanted to cater for is:
1. a user claims a reward successfully
2. their balance and positions are refreshed in the background while the user remains on the rewards screen
3. they should see that their reward was claimed, but the positions may refresh and the claimable parts removed. so the screen essentially tracks all the data it was loaded with, and if any rewards go "missing" from the redux store then we mark it as "claimed".
4. to make this a little robust for rewards that …

feat: enable trigger shortcuts

---

src/dapps/DappShortcutsRewards.tsx

When a shortcut is claimed, we refetch the positions. When the positions data is updated, the claimable rewards could either disappear or the value could change (i.e. there is a new reward to claim). In the latter scenario, we need to also refresh the value of the reward displayed on the UI - this change makes the UI rely only on positions data in redux when available, and use the locally stored state only if the claimable position disappears.
https://github.com/valora-inc/wallet/assets/20150449/6a316091-f02c-49e9-9704-61479e7a5fb5
- Fixes RET-733
Y

fix: ensure dapp shortcut rewards value is refreshed

---

src/account/saga.ts
src/ethers/ValoraEthersWallet.ts
src/fiatconnect/clients.ts
src/fiatconnect/index.ts
src/walletConnect/request.ts
src/web3/ValoraCeloWallet.ts
src/web3/contracts.ts
src/web3/dataEncryptionKey.ts
src/web3/saga.ts
src/web3/types.ts
test/values.ts

Currently, the `ValoraWallet` interface expects Celo-specific types to be used for the `signTransaction` method. The input/output types are not easily transformed between Ethers/Celo-specific types, however, which means that we will not be able to implement `ValoraEthersWallet` using the Celo types (or modify `ValoraCeloWallet` to use Ethers types). To sidestep this, this PR genericizes the `ValoraWallet` interface such that either Celo _or_ Ethers types can be used for `signTransaction`. When we decide to switch the primary wallet within the app to a `ValoraEthersWallet` implementation, all we'll need to do is change a single type (`PrimaryValoraWallet`) and update the call sites of `signTransaction` throughout the app to use Ethers-specific types. Since all the other method signatures …

feat(wallet): Genericize ValoraWallet interface

---

locales/base/translation.json
src/keylessBackup/WalletSecurityPrimer.test.tsx
src/keylessBackup/WalletSecurityPrimer.tsx
src/navigator/DrawerNavigator.tsx
src/navigator/Screens.tsx
src/navigator/types.tsx
test/RootStateSchema.json

Change the "Recovery Phrase" drawer item to "Wallet Security" and navigate to the WalletSecurityPrimer screen. Currently behind a dummy flag
Manual
https://github.com/valora-inc/wallet/assets/5062591/89df7565-3e0b-469f-98ab-5c735849d70e
- Fixes ACT-836
Yes

feat(keyless-backup): show wallet security on drawer

---

src/components/__snapshots__/SelectionOption.test.tsx.snap
src/icons/RadioButton.tsx

Fixes the Android only issue where the button is filled with black color when unselected
Before:
https://github.com/valora-inc/wallet/assets/5062591/1381e584-38b3-45a6-816b-4856e5032676
After:
https://github.com/valora-inc/wallet/assets/5062591/a1c3de43-2183-48e4-aa6c-4977f5b77059
- N/A
Yes

fix(radio-button): use none for unselected instead of undefined

---

src/navigator/DrawerNavigator.tsx

As the title. With the revoke phonenumber work, the top padding on the phone number was removed without testing this scenario.
n/a
Y

fix: ensure drawer menu header padding is consistent

---

src/keylessBackup/WalletSecurityPrimer.tsx
src/navigator/Navigator.tsx

This makes it consistent with the back buttons on other screens
| <img src="https://github.com/valora-inc/wallet/assets/5062591/b35c6968-e92a-4c5d-920a-63c37af09f5b" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/61872db6-4746-4fc5-92bc-f63cbe8743ca" width="250" /> | 
N/A
Yes

fix(keyless-backup): use shared header for back button

---

e2e/src/usecases/DappListRecent.js
e2e/src/utils/dappList.js

Dapp e2e tests broke again with https://github.com/valora-inc/dapp-list/pull/485, which made Moola the first dapp and broke assumptions about the position of `impactMarket` dapp. This updates the recently used dapps test to always scroll to and pick impactMarket
CI
N/A
Yes

test(e2e): fix recently used dapps test

---

locales/base/translation.json
src/components/Warning.tsx
src/dappkit/DappKitAccountScreen.tsx
src/dappkit/DappKitSignTxScreen.tsx
src/dapps/DappShortcutTransactionRequest.tsx
src/navigator/types.tsx
src/swap/SwapScreen.tsx
src/walletConnect/saga.test.ts
src/walletConnect/saga.ts
src/walletConnect/screens/ActionRequest.test.tsx
src/walletConnect/screens/ActionRequest.tsx
src/walletConnect/screens/Logos.tsx
src/walletConnect/screens/RequestContent.tsx
src/walletConnect/screens/SessionRequest.tsx

This improves connecting to dapps which either don't specify the Celo chain in the required namespaces or have it only in the optional namespaces.
Curve, Toucan and Cred Protocol fall into this.
The typical issue was that the dapp was reporting the wallet couldn't switch network.
Specifically with Curve, the Ethereum network was selected in the dropdown and it was impossible to switch it.
Previously we were allowing any chain. Now we only only EVM chains, even if not Celo.
We then clearly warn if the dapp tries to perform an action on an unsupported chain, and reject it.
I've left a note to also update the connect experience to show a warning when the requested chain/method/event aren't supported. This will be done in a follow up PR.
- Manually tested connecting to all …

fix(wc): better compat with unsupported chains

---

.github/workflows/automerge-crowdin.yml
.github/workflows/automerge-translation.yml
.github/workflows/bump-app-version.yml
.github/workflows/update-licenses-disclaimer.yml

These workflows were missed in #3994 
`credentials` is no longer supported in `google-github-actions/get-secretmanager-secrets@v1`
These changes work correctly on the e2e-ios workflow
N/A
N/A

ci: fix workflows using new version of google secrets GHA

---

src/keylessBackup/KeylessBackupPhoneInput.tsx

Remove extra padding on the back button to make it consistent with other screens
| <img src="https://github.com/valora-inc/wallet/assets/5062591/efafd843-13f4-4840-ba84-0a74183d984a" width="270" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/c625a3b3-7804-4888-a68f-b73282eef9c3" width="270" /> | 
N/A
yes

fix(keyless-backup): remove extra padding on phone input screen

---

src/nfts/NftGallery.tsx
src/nfts/NftImage.test.tsx
src/nfts/NftImage.tsx
src/nfts/NftsInfoCarousel.test.tsx

As the title. Currently on pull to refresh, only the data is refreshed but the images states are not.
Also, fix pet peeve of mine...the error image and nft image had different border radiuses....
(Notice the broken images at the start of the video vs the end)
https://github.com/valora-inc/wallet/assets/20150449/3a74d9b2-33de-456f-acc9-56821526cd14
- Fixes RET-793
Y

fix: try to reload nft images that failed to load on data refresh

---

src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx

Currently we are showing all supported swap tokens in the swap flow, but the original intention was to exclude the tokens we don't have a usd price for. We should be referencing `swappableTokens` rather than `supportedTokens` in the swap screen.
https://github.com/valora-inc/wallet/assets/20150449/00faad28-c42b-4a9e-bc3d-aea1719cca23
n/a
Y

fix: swappable tokens should have usd price

---

src/components/Button.tsx
src/keylessBackup/SignInWithEmail.test.tsx
src/keylessBackup/SignInWithEmail.tsx

Show a spinner on google sign in during the period when auth0 flow completes and credentials are loading
iOS:
https://github.com/valora-inc/wallet/assets/5062591/9b6edbbb-3518-4f48-948d-078eed0d7126
Android:
https://github.com/valora-inc/wallet/assets/5062591/779e387b-aaac-420c-b4a2-6b97015cea5e
- Fixes ACT-822
Yes

feat(keyless-backup): show spinner on google sign in

---

src/app/saga.test.ts
src/walletConnect/walletConnect.ts

Previously the presence or absence of `?` was used to determine if a walletconnect deeplink was a pairing request or not; however, this is not the case for v2 urls. Instead we should use the presence or absence of the `symKey`.
Tested locally on Android with the following dapps:
- Fixes RET-818
Yes

fix(wc): use symkey presence to determine pairing uri

---

src/analytics/Properties.tsx
src/swap/saga.test.ts
src/swap/saga.ts

Verify properties in analytics backends.

chore: add estimated USD value to swap analytics events

---

src/account/Settings.test.tsx
src/account/Settings.tsx
src/keylessBackup/utils.ts
src/navigator/DrawerNavigator.test.tsx
src/navigator/DrawerNavigator.tsx
src/statsig/constants.ts
src/statsig/types.ts

Setup two feature gates, one for [setup](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/show_cloud_account_backup_setup) and one for [restore](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/show_cloud_account_backup_restore) and used the setup feature gate to show / hide backup. restore feature gate will be used eventually when recovery flow is implemented
Manually by using statsig overrides and unit tests
- Fixes ACT-771
N/A

feat(keyless-backup): add feature gate

---

android/app/src/main/AndroidManifest.xml

The [nightly build](https://github.com/valora-inc/release-automation/actions/runs/6007413531/job/16293507460) picked up this issue - to continue using Adjust (which uses AD_ID) we need to declare it in the AndroidManifest.xml as well as complete the Advertising ID form in the google play console.
[Apparently we are still using Adjust.](https://valora-app.slack.com/archives/C0257HQBWF8/p1690892743484089)
n/a
- Fixes RET-792
Y

fix: add AD_ID permission for android 12+

---

src/home/NotificationCenter.test.tsx

The proposal is to group tests by the notification they are testing for better readability / file navigation. Currently [NotificationCenter.test.tsx](https://github.com/valora-inc/wallet/blob/main/src/home/NotificationCenter.test.tsx) contains a flat list of 19 test cases for different notifications, and more to come. Better to split them into smaller meaningful groups.
| ![Screenshot 2023-08-29 at 13 15 23](https://github.com/valora-inc/wallet/assets/2737872/e317397a-8ea8-46a9-b82e-539a7d130cf3) | ![Screenshot 2023-08-29 at 13 14 57](https://github.com/valora-inc/wallet/assets/2737872/4602d707-6528-4b29-8ec1-529e2d900dfb) | 
Nothing is changed besides wrapping test cases into groups.
N/A
- Prepares for RET-801
Yes

chore(notifications): group tests by notification

---

package.json
src/app/App.tsx
src/navigator/DrawerNavigator.tsx
src/qrcode/QRScanner.tsx
yarn.lock

Updates @react-navigation/drawer to v6 and enables freeze for performance improvements. Some prop changes were needed to maintain existing styles and behavior.
Freeze works as follows:
> ...Using Suspense mechanism introduced in React 17. The main use case of this library is to avoid unnecessary re-renders of parts of the app that are not visible to the user at a given moment. The frozen components are not unmounted when they are replaced with a placeholder view, so their React state and corresponding native view instances are retained during the freeze (DOM elements for react-dom or platform-native views for React Native apps) keeping things like scroll position, input state, or loaded images (for <img> components) unchanged. [source](https://github.com/software-mansion/react-freeze).
| …

feat(nav-drawer): upgrade to v6 and enable freeze

---

src/web3/KeychainSigner.ts
src/web3/KeychainWallet.test.ts

This fixes always failing transactions for accounts created or imported after #3920 and used after #4098.
The bug was introduced in https://github.com/valora-inc/wallet/blob/f7b3a2cc7c2689a17b7eb50edfdb1b8743f441d1/src/web3/KeychainAccountManager.ts#L63-L71
It caused the private key to be stored without the 0x prefix.
At the time it was harmless because unlocking the account would then normalize the private key https://github.com/valora-inc/wallet/blob/f7b3a2cc7c2689a17b7eb50edfdb1b8743f441d1/src/web3/KeychainAccountManager.ts#L111
But when #4098 was merged, reverting #3920, this wasn't the case anymore and made the problem apparent.
- Added unit test
- Manually confirmed by importing an account with 1d9939fe7615591e1b7c79fcb73583b0c3bc8f70 and ensuring it can still be used after …

fix: ensure private keys stored without the 0x prefix can be used for signing

---

src/exchange/CeloGoldHistoryChart.tsx
src/exchange/ExchangeHomeScreen.tsx
src/localCurrency/hooks.ts
src/localCurrency/selectors.ts

Minor refactor to remove the deprecated `getLocalCurrencyToDollarsExchangeRate` selector.
Note that we'll remove `localCurrencyExchangeRatesSelector` soon too.
- Unit tests pass
- Fixes RET-830
Yes

refactor: remove deprecated `getLocalCurrencyToDollarsExchangeRate` selector

---

src/web3/KeychainLock.test.ts
src/web3/KeychainLock.ts

[Viem's account.address](https://github.com/valora-inc/wallet/blob/main/src/viem/getLockableWallet.ts#L59) returns checksummed address, which doesn't work with KeychainLock, which uses lowercased addresses. This PR updates KeychainLock to support address args with any casing. 
We could also update the viem action to pass lowercased addresses, but seems safest to do it in KeychainLock
Unit tests
- Part of ACT-786
Yes

fix(KeychainLock): support address args with any casing

---

docs/connecting-dapps.md

Removes outdated recommendation for dapps to use react-celo which is now end of life and instead recommends @celo/rainbowkit-celo and web3modal. Also replaces a dead link for WalletConnect Docs.
N/A
[react-celo end-of-life (EOL) process #364
](https://github.com/celo-org/react-celo/issues/364)
Yes

docs: remove react-celo and update walletconnect v2 link

---

src/components/SimpleMessagingCard.tsx
src/home/NotificationBox.test.tsx
src/home/NotificationBox.tsx
src/home/NotificationCenter.test.tsx
src/home/NotificationCenter.tsx
src/home/WalletHome.tsx
src/home/reducers.ts
test/RootStateSchema.json

This ended up requiring very few changes.
Also for now P0 notifications are hidden from the notification center screen. I'll check this is what we want.
**When the notification center is enabled**
With a single notification marked with `showOnHomeScreen: true`:
With multiple notifications marked with `showOnHomeScreen: true`:
Note that this isn't a case we'll do on purpose. But since it allowed to reuse `<NotificationBox />` with minimal changes I left it this way. The highest priority notification is still displayed first.
**When the notification center is disabled**
This is same as before this PR.
- Fixes RET-800
Yes

feat: show P0 notifications only on the home screen

---

src/transactions/actions.ts
src/transactions/reducer.ts
src/transactions/send.ts
src/viem/saga.test.ts
src/viem/saga.ts

Implement the equivalent of the existing [sendAndMonitorTransaction](https://github.com/valora-inc/wallet/blob/955ea9dda0c8e9ca8b8e079097c74b307adf45f1/src/transactions/saga.ts#L151) method using contract kit. 
Unit tests, manually by enabling the dummy flag and running through the send flow
- Fixes ACT-786
N/A

feat(viem): implement sendAndMonitorTransaction

---

src/app/reducers.ts

This was a bug from https://github.com/valora-inc/wallet/pull/3603 :( 
manually tested
n/a
Y

fix: bypass ODIS EOL for phone number lookup

---

e2e/src/utils/consts.js

We want to create some tests around CPV and verified the existing 12 word seed phrase wallet against a new number but this broke the existing test since it's expecting a different set of onboarding steps. This PR creates a new wallet for the 12 word seed phrase test and saves the existing wallet for the upcoming CPV tests.
Context: https://valora-app.slack.com/archives/C02E2FE98P2/p1695025073879669
I've funded the account with 5 of each celo native token.
n/a
Y

ci: update sample wallet address

---

src/styles/fonts.tsx

Removes the the text style prop `paragraphSpacing` that is not supported by [react-native](https://reactnative.dev/docs/text-style-props).
N/A
N/A
Yes

fix: remove paragraphSpacing as not supported by react native

---

src/send/utils.test.ts
src/send/utils.ts

This fixes a regression with `celo://wallet/pay?...` deeplinks which happened when we switched to support multi token a long time ago.
This got uncovered working on https://github.com/valora-inc/wallet/pull/4230, blocking the e2e tests there.
Only the unit tests needed to be updated here.
The e2e tests couldn't uncover this bug because of the hardcoded cUSD price there ([1 cUSD is 1 USD](https://github.com/valora-inc/wallet/blob/2e91e5b8749114ea77fa46d7f969e2ad0223b050/src/tokens/e2eTokens.ts#L18)), and the local currency selected being USD (maybe we should change that?).
With the following deeplink:
```
celo://wallet/pay?address=0xC0509a7dcc69a0B28c7Ca73feD2FF06b9d59E5b9&amount=0.1&currencyCode=USD&token=cUSD&displayName=TestFaucet&comment=sending+usd:+0.1+to+my+wallet
```
The expected …

fix: pay deeplinks showing and sending incorrect amounts

---

src/analytics/ValoraAnalytics.test.ts
src/components/TokenBalance.test.tsx
src/components/TokenDisplay.test.tsx
src/dapps/DappShortcutsRewards.test.tsx
src/fees/hooks.test.tsx
src/fees/saga.test.ts
src/fiatExchanges/FiatExchangeAmount.test.tsx
src/fiatExchanges/PaymentMethodSection.test.tsx
src/fiatconnect/ReviewScreen.test.tsx
src/home/NotificationBox.test.tsx
src/home/NotificationCenter.test.tsx
src/home/WalletHome.test.tsx
src/merchantPayment/MerchantPaymentScreen.test.tsx
src/send/SendAmount/SendAmount.test.tsx
src/send/SendAmount/SendAmountHeader.test.tsx
src/send/SendConfirmation.test.tsx
src/swap/SwapReviewScreen.test.tsx
src/swap/SwapScreen.test.tsx
src/tokens/saga.test.ts
src/tokens/selectors.test.ts
src/tokens/selectors.ts
src/transactions/feed/TransferFeedItem.test.tsx
src/transactions/send.test.ts
src/walletConnect/request.test.ts

Fixes an issue where non-Celo tokens can possibly be returned by legacy selectors, leaking multi-chain features in unintended places. [Slack thread with context.](https://valora-app.slack.com/archives/C02KBT0DAHJ/p1695763773794809)
Unit tested
N/A
Yes.

fix(multichain): Filter out non-Celo tokens in legacy token selectors

---

.github/workflows/e2e-ios.yml

See example PR [failing](https://github.com/valora-inc/wallet/actions/runs/6402571572/job/17384661694?pr=4255).

ci: unblock dependabot PRs failing because of missing secrets

---

src/localCurrency/hooks.test.tsx
src/tokens/selectors.ts

a toy example of where we can use strategy 3 for [this doc](https://www.figma.com/file/iiPCJG2cA18ysZrLAZI80d/Multichain-refactor-strategies?type=whiteboard&node-id=4-181&t=E6ENxluAmHAfiloW-0) (vertical refactor with DRY helper) and cut down on duplicated code as we do multichain refactors
obviously nothing earth-shattering here, but I'd like us to keep a lookout for opportunities to do more of this to avoid adding duplication and complexity as we add multichain features
existing coverage makes sure the bridge names are in the token name and ethereum is filtered out, so I think we're good
na
yes

refactor: make tokensByAddressSelector more DRY

---

src/components/BackButton.tsx
src/send/__snapshots__/SendConfirmation.test.tsx.snap

Increased back button hit area, which was too small and almost impossible to hit.
I'm not too happy about the manual padding added, I would have preferred the [hitSlop](https://github.com/valora-inc/wallet/blob/ede52965f035ce263c38e83839be64c7412cb3bb/src/navigator/TopBarButton.tsx#L47) to work, but somehow it doesn't.
We can investigate this more later. But for now this should be good enough.
Showing with the ripple effect:
Note: it would be nice for the ripple effect to not be cut off on the left, but this would mean moving the button more toward the right, and then not be aligned anymore with the content. We can discuss that with design later on.
- See Slack [thread](https://valora-app.slack.com/archives/C025V1D6F3J/p1696953791346979?thread_ts=1696932462.287309&cid=C025 …

fix: back button hit area too small

---

src/tokens/selectors.test.ts
src/tokens/selectors.ts

Taking another crack at this -- see [here](https://valora-app.slack.com/archives/C02898GN22V/p1697100246829169?thread_ts=1697040837.299889&cid=C02898GN22V).
See [this documentation](https://github.com/reduxjs/reselect/blob/master/README.md#defaultmemoizefunc-equalitycheckoroptions--defaultequalitycheck) for a bit more info. Confusingly, `equalityCheck` is called once for each argument, so we need to use a type guard to determine when to use deep equality (for `networkIds`) versus the default reference equality (for state).
Unit and manual tested.
N/A
Yes.

fix(redux): Actually fix memoization on parameterized selectors

---

yarn.lock

Update [@babel/traverse](https://www.npmjs.com/package/@babel/traverse) to 7.23.2
CI tests pass 
- Fixes [failing security check](https://github.com/valora-inc/wallet/actions/runs/6536682061/job/17748903302)
- [Vulnerability details](https://github.com/babel/babel/security/advisories/GHSA-67hx-6x53-jw92)
Yes

fix: update @babel/traverse to 7.23.2

---

src/tokens/slice.ts

TokenBalanceWithAddress type had the key labelled as tokenId but actually used tokenAddress to key, changed the label.
ci
https://linear.app/valora/issue/ACT-944/create-new-send-confirmation-screen
na

chore: Change key label for TokenBalanceWithAddress

---

src/swap/SwapReviewScreen.tsx
src/swap/saga.test.ts
src/swap/saga.ts
src/transactions/reducer.ts

When the swap quote comes from 0x, the buy token is "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee". We need to turn this into something we recognise to get the related token info.
This PR does a few things:
1. given the sell and buy tokens from the swap quote, get the token id's and use those to get the token info
2. map "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" to the native token. it'd be nice to avoid this in the wallet but we'll need similar logic for ETH.
3. use the sell and buy tokens directly in the swap saga (instead of the buy and sell token addresses from the swap quotes)
4. create the standby swap transaction before submitting the swap, and manually add the tx hash.
5. fix typo for variable name in reducer
(This quote wasn't from 0x, I tried many times but couldn't get one …

fix: swaps using CELO sometimes not working

---

src/tokens/TokenDetails.test.tsx
src/tokens/TokenDetails.tsx
src/tokens/TokenDetailsMoreActions.test.tsx
src/tokens/TokenDetailsMoreActions.tsx

Per feedback from Nitya, update withdraw to navigate to the WithdrawSpend screen to allow either using Spend or Withdraw.
Unit tests & manual
https://github.com/valora-inc/wallet/assets/5062591/03bb80b9-e9d8-4b08-8e34-cdc152ef3162
N/A
Yes

fix(token-details): update withdraw to navigate to WithdrawSpend screen

---

src/swap/saga.test.ts
src/swap/saga.ts

As the title.
It's not nice that we're dispatching 2 consecutive actions here, but this will change in the future.
Swap transactions should be already confirmed before the next blockchain-api poll.
https://github.com/valora-inc/wallet/assets/20150449/6ab8e4b5-dba8-444b-ae25-68189cda0c42
- Fixes RET-894
Y

fix: add confirmed state for swap standby transaction

---

package.json
yarn.lock

Sets a resolution for `browserify-sign` for a new [CVE](https://github.com/browserify/browserify-sign/security/advisories/GHSA-x9w5-v3q2-3rhw).
N/A
Yes

fix(deps): set browserify-sign resolution to 4.2.2

---

src/swap/saga.test.ts
src/swap/saga.ts

This PR fixes incorrect logic for pending swap tx values when the swap pair has different number of decimals. For example, the swap to value for a cEUR -> USDT on the pending transaction was too large by a factor of 12. 
Tested manually
Fixes RET-894
Y

fix: incorrect pending swap values

---

package.json

Enhance the visibility of the ability to run the dev mode against the mainnet by placing it to the dev scripts.
It is indispensable to debug/manually test features available only on the mainnet, e.g. swaps.
Shoutout to @MuckT for providing this env option.
Tested manually on iOS and Android emulators
Y

chore: add dev mainnet scripts

---

renovate.json5

Adds WalletConnect dependencies to [renovate's ignoreDeps list](https://docs.renovatebot.com/configuration-options/#ignoredeps).
N/A
N/A
Yes

chore(deps): add WalletConnect to renovate ignore list

---

src/analytics/Properties.tsx
src/swap/SwapReviewScreen.tsx
src/swap/getSwapTxsAnalyticsProperties.tsx
src/swap/saga.test.ts
src/swap/saga.ts
src/swap/useSwapQuote.ts
src/transactions/send.test.ts
src/viem/prepareTransactions.test.ts
src/viem/prepareTransactions.ts

I started using the "gas cost" terminology in https://github.com/valora-inc/wallet/pull/4368 which is also mentioned a few times in https://ethereum.org/en/developers/docs/gas
But I think we should use "gas fee" to be more clear maybe? Which is referred more commonly in that same doc.
https://github.com/valora-inc/wallet/pull/4402#discussion_r1376416923

chore: rename "gas cost" -> "gas fee"

---

src/fiatExchanges/saga.test.ts
src/send/actions.ts
src/send/reducers.ts
src/send/saga.ts

Addressing a todo from #4370 to complete the last used token id feature
Manually by doing a send and checking that the token defaults to the last sent token on the new send amount screen and also checked the redux state on flipper
- na
Yes

feat(send): set last used token id

---

src/viem/estimateFeesPerGas.test.ts
src/viem/estimateFeesPerGas.ts
src/viem/prepareTransactions.test.ts

We initially got the [recommendation](https://valora-app.slack.com/archives/CNJ7KTHQU/p1697718182062359?thread_ts=1697647756.662059&cid=CNJ7KTHQU) to only set `maxFeePerGas` to the result of `eth_gasPrice` and that the difference between it and the base fee would be the tip distributed to the validator.
However after testing, we noticed that if we leave `maxPriorityFeePerGas` to `undefined` (or if we don't specify it), the final serialized tx has is set to `0`.
Resulting to `0` tip being effectively distributed to the validator. Which doesn't look right for validators 😄 
So here we bring back the original implementation I was originally [proposing](https://github.com/valora-inc/wallet/pull/4335/commits/ec11ae7f4c2d50e93eee7122a407d58b08c08386) where we set it to the result of …

fix(fees): set tip on Celo from `eth_maxPriorityFeePerGas`

---

src/swap/useSwapQuote.ts
src/viem/prepareTransactions.test.ts
src/viem/prepareTransactions.ts

I realized a bit too late that the changes in https://github.com/valora-inc/wallet/pull/4432 broke the swap flow where we want to prepare transactions when the spend amount is greater than the balance.
This is because we want users to be able to try any amount to see the quote (and associated fee).
- N/A
Yes

fix(prepare-transactions): add `throwOnSpendTokenAmountExceedsBalance` option

---

src/swap/SwapReviewScreen.tsx

This PR fixes mismatching units for gas fee on the swap review screen. The unit should be in token units rather than fiat.
n/a
n/a
Y

fix: ensure swap review screen displays gas fee in correct units

---

src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx

As the title. As we think about marketing expanded swap assets, it'll be important to be able to distinguish the bridge of any wrapped tokens.
Related to  RET-865
Y

feat: show bridge info in swap token bottom sheet

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/recipients/RecipientPickerV2.test.tsx
src/recipients/RecipientPickerV2.tsx
src/send/SendSelectRecipient.test.tsx
src/send/SendSelectRecipient.tsx

On clicking the "Send crypto to your friends", open the contacts page if permissions are granted. Also made a V2 RecipientPicker which uses the V2 recipient item.
Showing valora icon, showing permissions modal and navigation on selecting recipients will be in follow up PRs
https://github.com/valora-inc/wallet/assets/5062591/23fa3d60-355f-4acf-b5e1-2e487f0c0265
Note that the Get started box pins to the bottom, this is the behavior on main and will be fixed in a separate PR
- Part of ACT-952
N/A

feat(send): show contacts on new recipient screen

---

src/recipients/RecipientItemV2.test.tsx
src/recipients/RecipientItemV2.tsx
src/recipients/RecipientPickerV2.test.tsx

Show valora icon for phone number contacts if we can map it to an address. Showing the Send / Invite button and showing icon for address contacts will be in a follow up PR
Video recording: https://drive.google.com/file/d/1DaMreLTRTGjxRtWUnzaLBdwuzRNPg79j/view?usp=sharing
Includes clicking 3 types of contacts in order:
1. Contact which has never been lookup before and mapped to an address
2. Contact with no phone number mapping 
3. Contact which already has a mapping - momentarily removes the icon and then brings it back up once the lookup is complete
- Part of ACT-952
N/A

feat(send): show valora icon for phone number recipients

---

src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx
src/swap/selectors.ts
src/swap/slice.ts
test/RootStateSchema.json
test/schemas.ts

Remove redundant property `swapUserInput` from the `swapSlice` as not used.
Note: this is a sub-PR to https://github.com/valora-inc/wallet/pull/4481
* Updated unit tests
* Migration tested manually
- Related to RET-909
Y

chore: remove `swapUserInput` from the `swap` slice

---

src/swap/SwapAmountInput.tsx

When a user starts typing with a leading `,`, prevent showing NaN fiat value.
https://github.com/valora-inc/wallet/assets/20150449/6a3a0ee4-7ab1-40ff-bf6d-529dd05d317d
https://github.com/valora-inc/wallet/assets/20150449/90f83994-4ea3-4213-bb13-39319500bd05
Relates to RET-928
Y

fix(swap): do not display fiat values that are 0 or NaN

---

src/swap/SwapScreen.tsx

Context https://valora-app.slack.com/archives/C04B61SJ6DS/p1700841917661059
A change was made to require users to dismiss the keyboard before proceeding with the swap, to ensure all warnings are visible. As a side effect, dismissing the keyboard => the textinput is not focused => cannot clear the input using the clear button. This PR adds the prop to allow actions to be handled on tap.
https://github.com/valora-inc/wallet/assets/20150449/8fd10e6f-0a46-49e8-8dd2-020b76a5cc32
n/a
Y

fix(swaps): ensure clear button works on swap input

---

src/analytics/Properties.tsx
src/send/saga.test.ts
src/send/saga.ts

add network id to send_tx_complete
added check to jest test
cc https://linear.app/valora/issue/ACT-992/ability-to-group-analytics-events-by-network-id
na

chore(analytics): add networkId to send_tx_complete

---

src/app/MultichainBeta.test.tsx
src/app/MultichainBeta.tsx
src/app/selectors.ts
src/statsig/index.test.ts
src/statsig/index.ts

Add `multichainBetaStatus` prop to statsig user whenever the user opts in / out of multichain beta. This prop is used in this [dynamic config](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/dynamic_configs/multi_chain_features) to select network ids based on this custom prop. Included a loading state when statsig updateUser is invoked, which makes a network request to fetch all gate / config evaluations for the updated user. 
Unit tests, manually
| Opt In | Opt out |
| <video src="https://github.com/valora-inc/wallet/assets/5062591/db096a15-f640-4cd2-9e1a-9d874da69c6b"/> | <video src="https://github.com/valora-inc/wallet/assets/5062591/ec47afea-b8da-4fdb-b3d8-61e6dcc0f7c8" /> | 
- Fixes ACT-982
yes

feat(multichain): add beta status property to statsig user

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/swap/SwapScreen.tsx
src/swap/SwapTransactionDetails.test.tsx
src/swap/SwapTransactionDetails.tsx

This PR:
- add an info bottom sheet for slippage tolerance
- add analytics for the info bottom sheets
This was in the [design](https://www.figma.com/file/YxVf7jqvALnHfzr1Vgz5uV/Swap-2.0?node-id=752%3A20371&mode=dev) but I missed it because I was working from an outdated design.
- Fixes RET-865
Y

feat: add slippage tolerance info bottom sheet to swap screen

---

src/transactions/reducer.ts

In my last [PR](https://github.com/valora-inc/wallet/pull/4580), I introduced a bug.
After the refactor the `status` that the reducer receives is already a `TransactionStatus`. So it was always setting the transactions as `Complete`
Locally in a emulator

fix(standby-txs): Setting the failed transactions status correctly.

---

src/send/SendSelectRecipient.test.tsx
src/send/SendSelectRecipient.tsx

Builds on #4586, uses the verification status to show the unknown address info notification.
https://github.com/valora-inc/wallet/assets/5062591/cc15480d-2411-4d88-a656-51dee5e051d9
- Fixes ACT-979
Yes

feat(send): use verification status for showing unknown address info

---

src/fees/hooks.test.tsx
src/fees/hooks.ts
src/send/SendEnterAmount.test.tsx
src/send/SendEnterAmount.tsx
src/swap/useSwapQuote.ts
src/tokens/selectors.test.ts
src/tokens/selectors.ts

Pulling this part out of #4585. Currently we have a hook for getting the fee currencies given a network, but for the wallet connect work, we will need to prepare the transactions / get the fee currency from sagas so we need a selector instead. I don't think we need both a selector and a hook, so in this PR I've replaced the existing hook with a selector.
I got a bit of analysis paralysis doing this work so I think there might be a way simpler solution that I've overlooked. I wanted to keep the interface the same - consumers should be able to fetch a list of fee currencies for one networkId, however selectors have only 1 memoized value. The simplest option I could think of was to have 1 (unexported) selector calculate fee currencies for all networks upfront, and then have a selector that …

chore: refactor getting fee currencies from selector instead of hook

---

src/viem/prepareTransactions.test.ts
src/viem/prepareTransactions.ts

Previously, in cases where we were attempting to estimate gas for a TX where `gas + amount > balance`, we would _throw_ rather than returning a null estimation. This had the downstream effect of causing the gas estimation on the SendEnterAmount screen to spin forever, _without_ a warning to the user telling them to enter a lower amount. This change catches that case, and sets the gas estimate to null, causing the appropriate warning to appear to the user.
Manual and unit tested. See video below:
https://github.com/valora-inc/wallet/assets/569401/e012637f-45fd-4ad6-87a8-03cf8319d0b5
N/A
Yes

fix(viem): Fix Viem gas estimation bug

---

locales/base/translation.json
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx
src/tokens/selectors.test.ts
src/tokens/selectors.ts

This shows the MAX amount warning for ETH too.
Also it tweaks the logic on Celo, so it only displays the warning if there's only 1 fee currency with a balance.
For instance if the user only has cUSD and tries to swap the MAX amount of cUSD, the warning is also shown.
- Manual tests:
|  **before**  | **after**   |
|---|---|
| ![image](https://github.com/valora-inc/wallet/assets/57791/05eabaa4-551d-4f45-9ece-384ca8c0f369)   |  ![image](https://github.com/valora-inc/wallet/assets/57791/ff25f66b-ca98-4e5a-bc77-f9fe6d763fee) |
Warning when only cUSD is left to pay for gas and MAX amount is chosen:
- Fixes RET-946
Yes

feat(swap): update max fee currency warning

---

locales/base/translation.json
src/components/AccountNumber.tsx
src/components/__snapshots__/AccountNumber.test.tsx.snap
src/navigator/DrawerNavigator.test.tsx
src/navigator/DrawerNavigator.tsx
src/web3/networkConfig.ts

Adds the supported networks in the drawer navigator also some minor spacing adjustments to match the mocks.
| iOS One Network | iOS Two Networks | iOS Three Networks | iOS Three Networks Large Font |
| ----- | ----- | ----- | ----- |
| ![](https://github.com/valora-inc/wallet/assets/26950305/4030a3ed-243d-461b-aa17-739d025eb268 "iOS One Network") | ![](https://github.com/valora-inc/wallet/assets/26950305/fc3abdfa-13b7-4cdd-aaeb-7237832fe1ac "iOS Two Networks") | ![](https://github.com/valora-inc/wallet/assets/26950305/db3c0141-98e6-434d-aa54-c0f6ceb64830 "iOS Three Networks") | ![](https://github.com/valora-inc/wallet/assets/26950305/90b99277-f264-457c-bd38-161bcdcdc363 "iOS Three Networks Large Font") |
- Unit tests added
- Fixes ACT-1001
Yes

feat: add supported networks to navigation drawer

---

src/recipients/recipient.test.ts
src/recipients/recipient.ts
src/send/SendSelectRecipient.test.tsx
src/send/SendSelectRecipient.tsx
src/send/hooks.test.tsx
src/send/hooks.ts
src/send/useFetchRecipientVerificationStatus.ts

This PR adjusts the behavior of recipients on the Send flow in order to fix a handful of bugs. Really, it's trading in very undesirable behavior for somewhat less undesirable behavior.
Functionally, this fixes the following issues:
* Fixes an issue where you revoke your phone number and can no longer send to addresses associated with phone numbers that were previously cached on your device. Searching for such an address now will allow you to send to that address.
* Fixes V icon behavior with recipients from above.
* If your phone number becomes unlinked, we do _not_ show contact recipients anywhere. Since contact recipients are always considered `RecipientType.PhoneNumber`, we would always attempt to perform a CPV lookup, which we _cannot do_ since the user's wallet is unlinked. If you …

fix(send): Assorted Send recipient bugfixes

---

renovate.json5

This tweaks our revonate config to allow updating node automatically.
This should keep us on the current LTS version for now (node 20.x, and not 21.x). But I'll make sure it's the case.
Note: it's disabled in our [shared config](https://github.com/valora-inc/renovate-config/blob/27a6002970c6bfe4a04be4837a9f16b75f089d9e/base.json5#L52-L56) as it could cause issues in other projects which may not support newly released node versions soon after they are released (for instance GCP not supporting the latest node patch update directly). And the node version being used in production is set in the workflow. But maybe we could improve that too.

chore(renovate): allow updating node

---

src/web3/dataEncryptionKey.test.ts
src/web3/dataEncryptionKey.ts

previously, anyone who sent with a comment after verifying their own phone number with CPV would erroneously encrypt the comment with their own DEK, rather than that of the recipient. The comment appeared as "Comment Unavailable" for the recipient, who failed to decode it.
- fixed unit test that will now provide regression coverage
- manually tested. sent a transaction from a wallet with a verified phone number and confirmed it can be decoded now by another wallet (and that it is still encoded on chain). tx is here https://celoscan.io/tx/0xe766b83c0798880aa233b74da1a0c1a3c9c7296f97119d869d6ee15bba29635d . 
na
na

fix: look up the recipient DEK, not your own DEK

---

src/account/zendesk.test.ts
src/account/zendesk.ts

This should fix logs failing to be attached when sent to Zendesk.
Instead of using `react-native-fs` to read the logs in chunk, we now create a `Blob` which is kept on the native side,
then it's uploaded. 
The advantage is the data doesn't need to be copied in JS memory and we should avoid the utf8 read error.
So more performant and will work better with large files.
Note: I noticed my log files are rather large (30-40MB!), we should address this too. Either by compressing or reducing the unnecessary noise they contain.
- Manually tested
- Fixes RET-948
Yes

fix(logs): logs sometimes cannot be attached

---

src/account/SupportContact.test.tsx
src/account/SupportContact.tsx

Lisa asked us to put the user's multichain beta opt-in/out status in the support email headers
ci
na
yes

chore(multichain-beta): add multichainBetaStatus to support email

---

src/identity/actions.ts
src/identity/contactMapping.test.ts
src/identity/contactMapping.ts
src/identity/reducer.ts
src/identity/saga.ts
src/identity/selectors.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/statsig/types.ts
src/web3/networkConfig.ts
test/RootStateSchema.json
test/schemas.ts

Invoke identity-service API to save contacts on app load and whenever contacts are imported. Only makes requests if phone number is verified, contacts permission is given and contacts have changed since the last post. Also behind a [statsig feature gate](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/save_contacts)
Unit tests, manually tested by enabling feature gate
- Fixes ACT-994
N/A

feat(identity): save contacts

---

src/analytics/Properties.tsx
src/firebase/firebase.ts
src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx
src/swap/saga.test.ts
src/swap/saga.ts
src/swap/slice.ts
src/swap/types.ts
src/swap/useSwapQuote.ts
test/RootStateSchema.json
test/schemas.ts

This refactors swaps to simplify a few things around the data structures used.
It contains the following changes:
- stop passing and using `rawSwapResponse`
- instead we pass the fields that are needed
- made `estimatedPriceImpact` consistent by being always between 0 and 100
- previously the unit was either between 0 and 1 or 0 and 100 depending on the swap event
- made the swap `amount` analytics property always decimal
- previously it was either in token smallest unit or in decimal depending on the event
- the standby in/out values are now the same as what we display in the swap screen
- it doesn't use the `guaranteedPrice` anymore, we should use `guaranteedSwapPriceEnabled` if we want to avoid surprises, or make it the default as @kathaypacific is proposing in [this …

refactor(swap): data structures simplifications

---

src/consumerIncentives/saga.test.ts
src/consumerIncentives/saga.ts

To potentially reduce pressure on the backend from empty wallets this PR proposes not make a backend request for fetching available rewards, if the wallet doesn't have any token with balance greater than [TOKEN_MIN_AMOUNT](https://github.com/valora-inc/wallet/blob/d5149c7e0b8d3e948c45ddf606f657aa50c23a15/src/config.ts#L59).
Potentially it could save several thousands requests per day in peak periods like reward campaigns.
Data: [unique users with 0 tokens](https://mixpanel.com/project/2786968/view/3321744/app/insights#n4zbVy2TMznC)
Context: https://valora-app.slack.com/archives/C029Z1QMD7B/p1702630218806749
* Updated unit tests
- Fixes RET-951
Y

chore(supercharge): skip fetching rewards for empty wallets

---

src/app/saga.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/redux/migrations.test.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/swap/selectors.ts
src/swap/slice.ts
src/swap/useSwapQuote.ts
test/RootStateSchema.json
test/schemas.ts

Removing the `guaranteedSwapPriceEnabled` experiment as it was never used.
- Tests pass
- Fixes RET-950
Yes

chore(swap): cleanup guaranteedSwapPriceEnabled experiment

---

src/identity/contactMapping.test.ts
src/identity/contactMapping.ts

Per the latest [changes on the API side](https://github.com/valora-inc/identity-service/commit/3a891f7caeda69dc780f8fcb8cae8c13bb3599d6) 
Tested manually on alfajores with a successful save. 
https://linear.app/valora/issue/ACT-995/identity-service-api-endpoint-for-users-contacts

fix(saveContacts): add deviceId to saveContacts call

---

e2e/src/usecases/Send.js

An un related error, supercharge, is being served during the send flow tests and causing CI to error. This uses the error message text to assert instead of the present of an error banner.
CI.
N/A
Yes

test(e2e): check for error message text instead of presence

---

ios/Podfile.lock
patches/react-native+0.71.12.patch

iOS builds started [failing](https://valora-app.slack.com/archives/C02D08P412Q/p1704714465137749) in the `pod install` phase.
This is a workaround for the problem.
See https://github.com/facebook/react-native/issues/42180 for more details.
Manually tested `bundle exec pod install` without cached pods now works.
N/A
Yes

fix(deps): workaround pod install failure with boost

---

src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx

Moves testId to the parent card custom component so that we are always passing the testId down to a view.
Detox: [Pass testID to your native components](https://wix.github.io/Detox/docs/guide/test-id#pass-testid-to-your-native-components).
Tested locally on Android.
Tested in CI.
N/A
Yes

chore: move home action test id to parent custom component

---

src/walletConnect/request.ts
src/walletConnect/saga.test.ts
src/walletConnect/saga.ts

Fixes unable to correctly send/sign transactions with some dapps when using viem.
Although Valora was able to successfully sign/send the TX from its point of view, it was actually producing a TX with a really high `nonce` value, when the dapp was providing the `nonce` value as a hex string.
This was the problematic case:
1. Dapp asks to send a TX with `nonce` set to `"0x19"` which is a valid format
2. Valora receives it and keeps the `nonce` as is while [normalizing](https://github.com/valora-inc/wallet/blob/ed4d4266e2e5bfb87297fabab8e497b9a11eb8f1/src/walletConnect/saga.ts#L360)
3. However the output of the normalization should be a fully valid viem TX, which expects some fields as `bigint` and `nonce` as a `number`.
4. Then later when we call the viem client to send or sign, it uses the …

fix(wc): incorrect normalization of transaction fields

---

src/recipients/RecipientPicker.tsx
src/send/hooks.test.tsx
src/send/hooks.ts

A new debounce instance was created every time in the new send flow, which caused a resolveId request to be made for every letter typed in the search box. This updates it so that only one request is made within the debounce interval. Also updated resolveId function to make a request only if searched item is not an empty string
Unit tests, manually by checking the requests made on flipper
N/A
Yes

fix(send): debounce resolveId requests correctly

---

src/fiatExchanges/CoinbasePaymentSection.test.tsx
src/fiatExchanges/CoinbasePaymentSection.tsx
src/fiatExchanges/SelectProvider.tsx

Makes the coinbase pay module more flexible for adding ETH specifically and other assets in the future.
https://github.com/valora-inc/wallet/assets/8432644/94ef56b7-d3e1-4354-9c4d-ef8f26739054
Walked through manually. see screenshots
https://linear.app/valora/issue/ACT-899/fetch-quotes-from-remaining-external-providers

feat(cash-in): add multichain support to coinbasepay

---

src/viem/prepareTransactions.ts

Currently, the error strings we check for when estimating gas are not sufficient to catch all types of errors we care about. Basically, what was happening was when a user tries to send MAX balance of some gas-payable asset A, we try to prepare the transaction using asset A (and other gas-payable assets) as gas, and estimation fails when using asset A as gas since gas + transfer amount exceeds balance. This error during estimation wasn't being caught by the `cause` strings we were looking at. This caused gas estimation to hang forever, preventing the user from continuing with the transfer. This PR adds in a new cause string to fix that.
In general, it appears as if this cause string is determined _by the blockchain_ itself, i.e., not by `viem`, and therefore may be liable to change in the …

fix(sends): Fix error checking when estimating gas

---

locales/base/translation.json
src/send/SendSelectRecipient.test.tsx
src/send/SendSelectRecipient.tsx

Per Laura's request. Updated this button on selecting a recipient with address to Continue instead of Send. Also, made specific translation keys so this can be updated OTA
N/A
Yes

refactor(send): update button text from send to continue on recipient selection

---

src/viem/estimateFeesPerGas.test.ts
src/viem/estimateFeesPerGas.ts
src/web3/networkConfig.ts

This gets us another ~40% decrease in estimated gas fee on Celo.
Typical `baseFeePerGas` with CELO as a `feeCurrency` is `5 gwei`, when the recommended `maxFeePerGas` is
typically `12 gwei` (10 (`gasPrice`) + 2 (`maxPriorityFeePerGas`)).
So `1 - 7 / 12 = ~0.41`
Of course it's already less than a cent, but now it's right 🤓 
|--------|-------|
| ![image](https://github.com/valora-inc/wallet/assets/57791/4d4280c4-b351-46f4-8ec4-868d9020282a) | ![image](https://github.com/valora-inc/wallet/assets/57791/7a3be268-27df-4fb8-9d52-2abe0fccc287) |
- Fixes RET-991
Yes

feat(fees): get proper baseFeePerGas on Celo for the estimated gas fee

---

src/jumpstart/jumpstartLinkHandler.test.ts
src/jumpstart/jumpstartLinkHandler.ts
src/statsig/constants.ts
src/statsig/types.ts
src/web3/networkConfig.ts

Get WalletJumpstart contract address from dynamic config rather than hardcode it.
Updated unit test.
- Fixes RET-999
Y

feat(jumpstart): get jumpstart contract address from dynamic config

---

src/tokens/Assets.test.tsx
src/tokens/Assets.tsx

The old NftGallery screen loads nfts on opening the screen. This was missed on the new Assets screen
Unit tests, manually by ensuring a request is made on screen load
N/A
Yes

feat(assets): fetch nfts on load

---

src/fiatExchanges/saga.test.ts
src/fiatExchanges/saga.ts
src/send/SendConfirmation.tsx
src/send/SendEnterAmount.tsx
src/send/usePrepareSendTransactions.test.ts
src/send/usePrepareSendTransactions.ts
src/send/utils.test.ts
src/send/utils.ts

Bidali and deeplink payments were broken with the new send flow because a prepared transaction object wasn't passed to the SendConfirmation screen. This prepares a transaction and passes it on to the SendConfirmation screen. If a transaction is not possible, it still navigates to the screen, but the Send button would be disabled (In the old send flow, if a tx is not possible, Send was still clickable, but the tx will fail)
Unit tests, manual. Also E2E tests currently failing in #4845 passes with this fix
Payment deeplink:
https://github.com/valora-inc/wallet/assets/5062591/4774c91c-557a-40f3-916c-4f8c33c87952
Bidali payment:
https://github.com/valora-inc/wallet/assets/5062591/aaeb8b80-471c-4e12-a83c-5aa17710d284
Exceeds balance:
https://github.com/valora-inc/wallet/assets/5062591/4373dae8- …

fix(payments): create and pass a preparedTx to confirmation screen

---

locales/base/translation.json
src/walletConnect/saga.test.ts
src/walletConnect/saga.ts
src/walletConnect/screens/ActionRequest.test.tsx
src/walletConnect/screens/ActionRequest.tsx
src/walletConnect/screens/ActionRequestPayload.tsx

This PR handles errors happening while preparing transactions coming from WC.
- `chainId` is now stripped (we don't need it and it was causing an RPC error on Celo)
- `prepareTransactions` is now wrapped in a try/catch and we now surface the error in the `ActionRequest` bottom sheet
- Manually tested by transacting with the following dapps: Staked Celo, Moola, ChurritoFi
- New error message if transaction preparation fails, with the underlying error message, to help users/builders understand the problem
Note: the underlying error message won't be translated, but I think it's better than hiding it.
- Fixes RET-1013
Yes

fix(wc): handle errors while preparing transactions

---

src/RevokePhoneNumber.tsx
src/account/Settings.tsx
src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
src/home/NotificationBox.test.tsx
src/home/NotificationBox.tsx
src/home/NotificationCenter.test.tsx
src/keylessBackup/LinkPhoneNumber.test.tsx
src/keylessBackup/LinkPhoneNumber.tsx
src/navigator/types.tsx
src/onboarding/steps.test.ts
src/onboarding/steps.ts
src/send/SelectRecipientButtons.test.tsx
src/send/SelectRecipientButtons.tsx
src/send/Send.tsx
src/verify/VerificationStartScreen.test.tsx
src/verify/VerificationStartScreen.tsx

Fixes a bug introduced in #4834 , where VerificationStartScreen defaulted to being not in onboarding. This causes an issue if a user bails on the screen during onboarding. On restart, the screen is loaded in the already onboarded mode where the back button does nothing and there's no option to skip (see before video below). This PR reverts the default to be in onboarding as it doesn't seem trivial to pass props on the initialRoute.
Unit tests and manual
Before:
https://github.com/valora-inc/wallet/assets/5062591/496876ec-4adf-48b8-8a12-72d9030f3e37
After:
https://github.com/valora-inc/wallet/assets/5062591/8d345432-4fcb-439f-b63a-03806d5959e0
N/A
Yes

fix(onboarding): revert default of CPV screen to be in onboarding

---

src/nfts/NftsInfoCarousel.tsx
src/shared/conts.ts
src/transactions/feed/TransactionDetailsScreen.tsx

...instead of values known only at runtime. This would make it easier to run static extraction of translatable strings later if we want. 
Meant to address pr comment from @jeanregisser [here](https://github.com/valora-inc/wallet/pull/4842/files#r1484091599)
ci
na
na

refactor(i18n): use static translation keys

---

src/walletConnect/screens/SessionRequest.tsx

Fixing `Warning: Each child in a list should have a unique “key” prop.`
CI
NA
Y

fix(dapps): add `key` property to network chips

---

WALLET.md

Updates docs to recommend using the latest Xcode 15.2.
- Tested the app locally building with Xcode 15.2
- E2E tests run using Xcode 15.2
N/A
N/A
N/A

docs: recommend xcode 15.2 install

---

.github/actions/yarn-install/action.yml

I was playing with arm64 runners and noticed using a `node_modules` cache from a different arch could cause issues.
- Tests pass
N/A
Yes

ci: use runner arch in cache key to avoid issues

---

src/transactions/saga.ts

The error log was triggered in some normal use cases, generating a lot of noise.
With the new condition, if the error log is present it really means there's some unexpected behavior in the app.
Y
Y

chore(logs): Removing noisy error log from transaction watcher

---

src/firebase/db-rules.json

Updates `src/firebase/db-rules.json` which is the  "source of truth" for what is being used in Alfajores and Mainnet: [Slack Thread](https://valora-app.slack.com/archives/C025V1D6F3J/p1638958161157300); related PR for cloud functions: https://github.com/valora-inc/cloud-functions/pull/288.
- Fixes ACT-940
Yes
N/A

chore: update pending requests firebase node read only

---

.github/workflows/check.yml
.github/workflows/e2e-pr.yml
.github/workflows/semantic-pr.yml
.github/workflows/test.yml

Adds the required trigger for Github Action Merge Queue: [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).
- Test in CI.
N/A
Yes
N/A

ci(merge-queue): add required trigger for github actions

---

.github/workflows/e2e-main.yml

It's failing all the time. See Slack [thread](https://valora-app.slack.com/archives/C02E2FE98P2/p1709116393221949).
Disabling to avoid the wasted cost of 25 mins with namespace on each run.
Will investigate and try to re-enable later.

ci: disable Android e2e test for API level 24 on main

---

.github/workflows/check-translation-files-pr.yml
.github/workflows/check.yml
.github/workflows/e2e-pr.yml
.github/workflows/test.yml

Prevents concurrency checks from cancelling earlier jobs in the merge queue. Follow up to: #4998, #4999 and #5002.
Test in CI.
N/A
N/A
N/A

ci: adjust concurrency checks to support a merge queue

---

src/send/SendConfirmation.test.tsx
src/send/SendConfirmation.tsx

Changes include:
- Dropping useInputAmounts - was only applicable for the old send flow where amount could be entered in local amount, also dropped convertToMaxPrecision, which was hardcoded to 18 decimals. The prepared tx hook uses the appropriate decimals based on token
- Dropping useRecipientToSendTo - was only applicable for the old send flow where secure send flow was just before the screen. The new send flow guarantees an address in the recipient object and we have typing that ensures this as well
- Trimming comment on send - If a comment is typed and send is immediately pressed, the send payment action will be dispatched before onBlur updates the comment, this leads to the standby tx having an untrimmed comment
CI, manual
Part of ACT-1049
Yes
If a new NetworkId and/or Network are …

refactor(send): cleanup confirmation screen

---

.github/workflows/check-translation-files-pr.yml
.github/workflows/check.yml
.github/workflows/e2e-pr.yml
.github/workflows/test.yml

Prevents concurrency checks from cancelling jobs in the merge queue. Follow up to: #4998, #4999, #5002 and #5015🤞. 
Test in CI.
N/A
N/A
N/A

ci: prevent merge queue jobs from being cancelled from concurrency

---

.github/workflows/check-translation-files-pr.yml
locales/en-US/translation.json

Crowd-in PR (#5014) fails the check since the branch name on merge queue doesn't match the expected branch name (https://github.com/valora-inc/wallet/pull/5014#event-11973800593). We can skip this check on merge queue requests and just let it pass. Any incorrect pushes will be flagged by the pull request run so don't need another check on the merge queue
Ensured this still fails on PRs https://github.com/valora-inc/wallet/pull/5020/commits/0243c61f521ea895f7fde6b0848a617b18210ef0 , ensure #5014 merges after this merges
N/A
N/A

ci(check-translation-files): don't run on merge group events

---

src/send/SendConfirmation.test.tsx
src/send/SendConfirmation.tsx

Fixes an edge case where the send confirmation address displays the incorrect address if a user attempts to send to an address tied to a phone number connected with multiple addresses and a different address was chosen in a previous secure send flow. It always displays the address chosen for secure send. This updates it so that for any phone number recipient with multiple addresses, the address currently being sent to is shown.
Unit tests, manually tested the following scenarios:
1. Send to phone number with multiple addresses (A, B), first time pick address A on secure send, ensure send confirmation screen displays A
2. Send to address B, ensure send confirmation displays phone number contact with address B
3. Send to phone number with single address, ensure confirmation screen displays …

fix(send): show correct address in confirmation screen

---

.github/workflows/check.yml
.github/workflows/e2e-main.yml
.github/workflows/test.yml

Now that we have merge queue enabled for main, every PR runs checks at least twice, once on the PR before being added to the queue and once on the merge queue. The commit on the merge queue is the same commit that lands on main, so we don't need to run checks again on main that have already run on the merge queue (see image below on checks running twice on commits on main). This disables `check` and `test` workflows on main, and updates the `e2e-main` workflow to only run tests on OS that have not already run on the merge queue. This should save us some CI time, especially on E2E machines. 
CI
N/A
N/A
N/A

ci: don't run jobs on main that already run on the merge queue

---

src/home/NotificationBox.test.tsx
src/home/NotificationBox.tsx
src/keylessBackup/LinkPhoneNumber.test.tsx
src/keylessBackup/LinkPhoneNumber.tsx

* Homecard should not be shown if the user restored with keylessBackup
* If verification is skipped after keylessbackup, set the state correctly so the user isn't shown verification next time they open the app
Unit tests, manual test

fix(keylessBackup): fix hasSeenVerification for linkPhone number and when homecard is shown

---

src/home/selectors.test.ts
src/home/selectors.ts
src/nfts/saga.test.tsx
src/nfts/saga.ts
src/statsig/constants.ts
src/statsig/types.ts

We want to show the nft reward bottom sheet to a slightly different audience than the nft celebration. So, the reward bottom sheet should be gated with its own feature flag.
Context: https://valora-app.slack.com/archives/C06NA9MBJSG/p1709747619306969
* Updated unit tests
- Related to RET-1002
Y
NA

feat: nft reward feature gate

---

src/backup/utils.ts
src/web3/saga.test.ts
src/web3/saga.ts

Wallets created when the users language was set to Spanish or Portuguese had mnemonics that were in Spanish or Portuguese. This causes interoperability issues for Valora users who wish to try other wallets: [Slack Thread](https://valora-app.slack.com/archives/C02KBT0DAHJ/p1709917662991769).
- Unit tests updated
N/A
Yes - Users with Spanish and Portuguese mnemonics are still able to restore into Valora.
N/A

fix: new wallets only created with english mnemonics

---

locales/base/translation.json
src/components/TokenBalance.test.tsx
src/components/TokenBalance.tsx
src/navigator/Screens.tsx
src/navigator/TabNavigator.tsx
src/navigator/types.tsx
src/tokens/AssetList.test.tsx
src/tokens/AssetList.tsx
src/tokens/Assets.test.tsx
src/tokens/Assets.tsx

Adds a temporary isWalletTab param to Assets screen and its sub components to support the wallet tab screen.
Unit tests, manual on both iOS and Android
https://github.com/valora-inc/wallet/assets/5062591/eb619ae3-ca86-4f44-8a8a-b250997fb510
Ignore header for now, will be addressed in a follow up issue
- Fixes ACT-1104
Yes

feat(bottom-tabs): extend assets screen to support wallet tab

---

e2e/src/usecases/FiatConnectTransferOut.js

FiatConnect e2e tests have been failing with a non enough funds for transfer out message. This is because the estimated fee seems to be higher than the balance - amount withdrawn, even though eventually the actual fee used falls within the balance. So bumping the funded amount for gas for now to unblock. 
We should eventually switch FC to use viem (and get better fee estimates) and revert this change
Local, CI
- N/A
N/A

test(e2e): increase funded amount for FC tests

---

locales/base/translation.json
src/home/ActionsCarousel.tsx
src/home/WalletHome.test.tsx
src/home/WalletHome.tsx
src/navigator/TabNavigator.tsx
src/navigator/types.tsx

Updating WalletHome component to take a prop denoting whether we're in the tab view, and if so display appropriate components.
https://github.com/valora-inc/wallet/assets/5062591/eb19a647-783c-42ca-91e1-878fe0cd1ac2
Couple of things out of scope for this PR
- Header - will be done in a separate issue
- Horizontal padding - inconsistent between different portions of the home screen, will be in a follow up PR
- Notification bell spotlight - disabled for now for tab view, confirming with product that if we need to carry it forward
- Fixes ACT-1105
Yes

feat(bottom-tabs): extend wallet home to support home tab

---

src/home/celebration/NftReward.test.tsx
src/home/celebration/NftReward.tsx

On the iOS production build the NFT reward bottom sheet unexpectedly reappears after CTA button is pressed.
The hypothesis is that `onChange` event isn't fired for some reason when the bottom sheet is closed programmatically.
The fix is to fire `dispatch` on CTA press handler instead of relying on `onChange` event.
Another possible option is to rely on `onClose` event. But unfortunately it is called when component unmounts on Android.
Tested manually on:
* Android emulator
* iOS simulator
* dev iOS build on device
Planing to additionally test on the nightly iOS build.
- Related to  RET-1002
Y
NA

fix: the NFT reward bottom sheet unexpectedly reappears after CTA button is pressed

---

src/home/GetStarted.tsx
src/home/WalletHome.tsx

Use 16 for padding all home elements to be consistent. Also adjusted a style on the Get Started header
Manual
| <img width="300" src="https://github.com/valora-inc/wallet/assets/5062591/f27a26cf-d954-42d1-b090-31dc7497a9bc" /> | <img width="300" src="https://github.com/valora-inc/wallet/assets/5062591/45f63fe0-c80e-4f68-af54-6a94e7db6fd6" /> | 
- Part of ACT-1105
Yes
N/A

fix(home): consistent padding for all home elements

---

src/account/Profile.tsx
src/account/Settings.tsx
src/account/__snapshots__/Profile.test.tsx.snap
src/components/InLineNotification.test.tsx
src/components/InLineNotification.tsx
src/jumpstart/JumpstartEnterAmount.tsx
src/qrcode/QRCode.tsx
src/send/EnterAmount.tsx
src/send/SendSelectRecipient.tsx
src/swap/SwapScreen.tsx
src/tokens/TokenImport.tsx
src/walletConnect/screens/ActionRequest.tsx
src/walletConnect/screens/SessionRequest.tsx

Visual tweaks to accommodate current [design variants](https://www.figma.com/file/erFfzHvSTm5g1sjK6jWyEH/Working-Design-System-Components?type=design&node-id=1144-35&mode=design&t=kUIyzJiXtW1ebQAL-0):
* added `Success` variant (green background)
* added icon override: can provide alternative icon or `null` to render without one
Renames:
* `Severity` -> `NotificationVariant` because from my standpoint it's better aligned with all options it contains
* `Informational` -> `Info` just because it's shorter
* Added unit test for icon override 
- Related to RET-1004
Y
NA

chore: inline notification visual tweaks

---

src/import/ImportWallet.test.tsx
src/import/ImportWallet.tsx

Fixes a bug with back navigation on wallet restores.
Prerequisites: Cloud Account Backup (CAB) enabled.
1. Select "I already have a wallet"
2. Enter Pin
3. Select "From recovery phrase"
4. Tap Cancel
5. Select "From recovery phrase"
6. Enter recovery phrase and attempt to restore
7. Observe error.
Workarounds: Close and reopen the app.
- Unit tests added
N/A
Yes
N/A

fix(cab): import wallet back fix

---

src/jumpstart/JumpstartEnterAmount.test.tsx
src/jumpstart/JumpstartEnterAmount.tsx
src/jumpstart/usePrepareJumpstartTransactions.test.ts
src/jumpstart/usePrepareJumpstartTransactions.ts
src/navigator/types.tsx
src/statsig/constants.ts
src/transactions/saga.test.ts
src/transactions/saga.ts

We were using an incorrect address for the jumpstart contract previously so didn't catch these issues. This PR:
- fixes some approval transactions not added to the prepared transactions. the enter amount screen was passing the user input token amount to prepare transactions, however it needs to be the token amount in smallest units. the incorrect units were causing the approval transaction to never be added because the spend amount would get rounded to 0 for entered values under 1.
- add dynamic config for the transaction gas estimate, since we cannot estimate gas for a transaction without approval
No visual changes, manually verified that the transactions created are using the expected values.
- Related to RET-994
Y
Y

fix(jumpstart): ensure that jumpstart transactions are prepared correctly

---

src/firebase/dynamicLinks.ts

As the title, we should use a long dynamic link to make sure that the links are not stored on a central server / valora should not have access to the links.
Tested that the deep links can be correctly consumed still
- Fixes RET-994
Y
Y

fix(jumpstart): use long dynamic link

---

src/RevokePhoneNumber.tsx
src/alert/AlertBanner.tsx
src/components/Toast.test.tsx
src/components/Toast.tsx
src/components/ToastWithCTA.test.tsx
src/components/ToastWithCTA.tsx
src/dappsExplorer/useDappFavoritedToast.tsx
src/styles/styles.ts

Updates the Toast component to match [recent designs](https://www.figma.com/file/erFfzHvSTm5g1sjK6jWyEH/Working-Design-System-Components?type=design&node-id=1144-35&mode=design&t=kUIyzJiXtW1ebQAL-0).
List of changes:
* leverages visual styling of [`InLineNotifcation`](https://github.com/valora-inc/wallet/blob/main/src/components/InLineNotification.tsx) and properties set of the [`BottomSheetInLineNotification`](https://github.com/valora-inc/wallet/blob/main/src/components/BottomSheetInLineNotification.tsx)
* (optional) user can dismiss it by swiping
* (optional) may open in modal mode with a dimmed backdrop
Potential future development:
* enables implementation of escrow reclaim status UI: 
* [element 1](https://www.figma.com/file/6sJ4fCxCptTybHB6ZZ7Pqi/Escrow-Feature?type=design&node-id=2 …

chore: update Toast component to match recent designs

---

src/account/GoldEducation.tsx
src/navigator/NavigationService.ts

Navigate to home instead of the drawer celo screen from the gold education screen when using tab navigator
Manual
With gate off:
https://github.com/valora-inc/wallet/assets/5062591/6ae3892d-6445-4eed-ad22-44bc71f085b2
With gate on:
https://github.com/valora-inc/wallet/assets/5062591/d98c32a0-d785-4ccd-b112-60faaf34175f
- Part of ACT-1110
Yes
N/A

feat(bottom-tabs): navigate gold education completion to home

---

src/jumpstart/selectors.test.ts
src/jumpstart/selectors.ts
src/jumpstart/slice.test.ts
src/jumpstart/slice.ts

As the title
CI
- Related to RET-1004
Y
NA

chore(jumpstart): add `claim` to the names of claim-related actions and selectors

---

e2e/src/Assets.spec.js
e2e/src/usecases/Assets.js
e2e/src/usecases/AssetsDrawer.js
src/navigator/TabNavigator.tsx

Update assets test to run against the tab navigator. Retains a subset of tests on the drawer for any regression while we are in process of rolling this out.
CI
- Part of ACT-1113
Yes
N/A

test(e2e): run assets tests against tab navigator

---

src/onboarding/ChooseYourAdventure.tsx
src/onboarding/steps.ts
src/send/SendEnterAmount.tsx
src/tokens/TokenDetails.tsx
src/tokens/hooks.test.tsx
src/tokens/hooks.ts

Also snuck in some onboarding warning fixes - 
- `onboardingPropsSelector` was returning a new value each time, causing unnecessary rerenders
- the pesky "unique key" warning on the CYA screen
A wallet with no balance should be able to enter the send amount screen
n/a
Y
Y

fix: ensure send flow does not crash when user has no balance

---

src/navigator/ProfileMenu.tsx

[Figma](https://www.figma.com/file/EkJ8MVKoc6QVrrdKYFBARw/Navigation-Strategy?type=design&node-id=2722-7691&mode=design&t=bcpx3QA2KQAsxWsG-0)
| <img src="https://github.com/valora-inc/wallet/assets/5062591/91ebccf5-e63e-49f5-b934-2d6ba6085ec6" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/0512e887-4283-4dd4-9163-725623121a16" width="250" /> |
N/A
Yes
N/A

fix(profile-menu): use 16 for horizontal margin

---

src/jumpstart/jumpstartLinkHandler.test.ts
src/jumpstart/jumpstartLinkHandler.ts
src/jumpstart/saga.test.ts
src/jumpstart/saga.ts

Fix bugs causing error in claim status despite the claim itself succeeds:
* wrong assumption about `jumpstartClaim` cloud function result format
* use of non-lowercased addresses
* Tested manually
* Updated unit rests
- Related to [RET-1004](https://linear.app/valora/issue/RET-1004)
Y
No. 
Jumpstart works only for Celo. See also RET-1019.

fix(jumpstart): fix jumpstart claim

---

src/jumpstart/JumpstartSendConfirmation.test.tsx
src/jumpstart/JumpstartSendConfirmation.tsx

As the title - prevent triggering the send action again while there is a transaction inflight by disabling the button while loading.
n/a
n/a
Y
Y

fix(jumpstart): prevent possibility of sending multiple transactions

---

e2e/src/AccountManagement.spec.js
e2e/src/Pin.spec.js
e2e/src/usecases/NewAccountPhoneVerification.js
e2e/src/usecases/PINChange.js
e2e/src/usecases/PINRequire.js
e2e/src/usecases/ResetAccount.js
e2e/src/usecases/RestoreAccountOnboarding.js
e2e/src/usecases/Settings.js
e2e/src/usecases/Support.js
e2e/src/usecases/WalletConnectV2.js
e2e/src/utils/utils.js

Updates the following tests
- AccountManagement.spec.js - updates to run against both variants
- Pin.spec.js - updates to run against both variants
- Verify.spec.js - updated to run against tab navigator (no need for drawer here since there's sufficient coverage against drawer settings)
- WalletConnect.spec.js - still runs agains the drawer (hard to override statsig gate since app launched from deeplink in some cases) but reuses the `navigateToSettings` helper so its easier to update when tab is rolled out
CI
- Part of ACT-1113
N/A
N/A

test(e2e): update tests to run against tab navigator

---

e2e/src/AccountSetup.spec.js
e2e/src/usecases/NewAccountOnboarding.js
e2e/src/usecases/NewAccountOnboardingDrawer.js
e2e/src/utils/utils.js
package.json
yarn.lock

Renames existing NewAccountOnboarding test to NewAccountOnboardingDrawer and updates NewAccountOnboarding to run against tab navigator and cloud backup
CI
- Part of ACT-1113
N/A
N/A

test(e2e): add new account creation test for new tab and cloud backup

---

src/tokens/TokenImport.tsx
src/tokens/saga.test.ts
src/tokens/saga.ts
src/tokens/selectors.ts

Accepting network ids as an array would mean that the selector recomputes the result even if the same list of network ids are passed and returns a new result, resulting in unnecessary rerenders. This updates it so that the selector returns all network id's icons. An alternative approach would be to set `memoizeOptions` like `tokenIdsSelector`, but there doesn't seem to be any harm in returning all network's icon in the function. The consumer of this selector can pick the required networks' icon from the object
CI, ensured the below warning doesn't show in #5148 when merged with this change
N/A
Yes

refactor(tokens): update networksIconSelector to return all icons

---

src/components/IconWithNetworkBadge.tsx
src/transactions/feed/NftFeedItem.tsx
src/transactions/feed/SwapFeedItem.tsx
src/transactions/feed/TokenApprovalFeedItem.test.tsx
src/transactions/feed/TokenApprovalFeedItem.tsx
src/transactions/feed/TransactionFeedItemImage.tsx
src/transactions/feed/TransferFeedItem.tsx

Made a reusable component to create an icon with a badge and used for all icons in the tx feed
Manually
| Pending, send/receive | Nfts and swaps |
|:--------:|:--------:|
| <img src="https://github.com/valora-inc/wallet/assets/5062591/756a7902-3169-4371-875c-51dad8659425" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/5a5c1aae-9b9e-48bb-8fee-8be64843d941" width="250" /> | 
- Fixes ACT-105
Yes

feat(feed): include network icon in tx feed items

---

src/tokens/AssetList.tsx

Adds a minimum height to the `AnimatedSectionList` container styles to prevent the last item from being obscured.
https://github.com/valora-inc/wallet/assets/26950305/3390a615-e367-4dad-9fc5-c516280930b9
https://github.com/valora-inc/wallet/assets/26950305/cdcf7694-6180-42ff-937a-838cdba41047
https://github.com/valora-inc/wallet/assets/26950305/54d78cfd-27de-4577-9396-7198373f308f
https://github.com/valora-inc/wallet/assets/26950305/f165e3dc-f8a5-47cc-b841-9e92a4b2814f
- Tested locally on Android
- Fixes ACT-1116
Yes
N/A

fix: last item obscured when limited positions or tokens

---

src/components/LineItemRow.tsx
src/components/TokenTotalLineItem.tsx
src/escrow/__snapshots__/ReclaimPaymentConfirmationCard.test.tsx.snap
src/send/SendConfirmation.tsx
src/send/__snapshots__/SendConfirmation.test.tsx.snap

Adds the line item for local amount display of fees on the send confirmation screen.
| Before iOS stCelo | Before iOS ETH | After iOS stCELO | After iOS ETH |
| ---- | ---- | ---- | ---- |
| ![](https://github.com/valora-inc/wallet/assets/26950305/c53116f4-bd42-4ac9-8f97-03df7dfa2701 "iOS stCelo") | ![](https://github.com/valora-inc/wallet/assets/26950305/da1bcf00-05ab-4840-b1ff-215998feeec7 "iOS ETH") | ![](https://github.com/valora-inc/wallet/assets/26950305/efa83b76-c6ef-4e1d-946f-be232048b5fa "iOS stCelo Fees") | ![](https://github.com/valora-inc/wallet/assets/26950305/365d2fba-1388-4806-be15-541e49b66b4c "iOS ETH Fees") |
- Tested locally on Android
- Unit test snapshot updated
- Fixes ACT-1135
Yes
If a new NetworkId and/or Network are added in the future, the …

chore: add fees to send confirmation

---

package.json
src/analytics/ValoraAnalytics.ts
yarn.lock

Enables the use of [destination filters](https://docs.segmentapis.com/tag/Destination-Filters/) with Segment.
- Fixes ACT-1115
Yes
N/A

feat(segment): add destination filters

---

src/web3/networkConfig.ts

Small nit fix to baseUrls to avoid `//` in urls.
Tested locally on iOS
N/A
Yes

chore: remove trailing slash from base urls

---

e2e/src/usecases/HandleDeepLinkSend.js
e2e/src/usecases/SecureSend.js
e2e/src/usecases/Send.js
src/analytics/Properties.tsx
src/jumpstart/JumpstartEnterAmount.test.tsx
src/jumpstart/JumpstartEnterAmount.tsx
src/send/EnterAmount.test.tsx
src/send/EnterAmount.tsx
src/send/SendEnterAmount.test.tsx
src/send/SendEnterAmount.tsx
src/send/types.ts

Allows entering fiat amount with upto 2 decimal places. Automatically adds grouping separators to input
Unit tests. Tested manually on iOS and android with different separators
https://github.com/valora-inc/wallet/assets/5062591/e4f1f522-3572-4d80-83a5-b4683f17bbb6
- Fixes ACT-1142
Yes
N/A

feat(send): allow entering amount in fiat

---

src/send/EnterAmount.test.tsx
src/send/EnterAmount.tsx

Show a `-` and disable the input if token price is unavailable. [Figma](https://www.figma.com/file/URF0fqjWMR6ffWDOcFK8ic?type=design&node-id=4099-34977&mode=design#761048256)
Unit tests, manually by using an imported token which shouldn't have a price
- Part of ACT-1142
Yes
N/A

feat(send): disable fiat input if token price is unavailable

---

src/navigator/types.tsx
src/swap/SwapScreen.tsx

Adds the route param toTokenId to the SwapScreenWithBack screen allowing the use of a deep link to set the to tokenId.
This enables the creation of deep link which contains a swap pair or a target to token. 
Prerequisites:
- Remove `isSecureOrigin` from https://github.com/valora-inc/wallet/blob/main/src/app/saga.ts#L348 for local testing.
- Use iOS mainnetDev with `yarn dev:ios -e mainnetdev`
Tests urls:
- Swap pair: `celo://wallet/openScreen?screen=SwapScreenWithBack&fromTokenId=celo-mainnet:native&toTokenId=celo-mainnet:0x765de816845861e75a25fca122bb6898b8b1282a`
- From token: `celo://wallet/openScreen?screen=SwapScreenWithBack&fromTokenId=celo-mainnet:native`
- To token: `celo://wallet/openScreen?screen=SwapScreenWithBack&toTokenId=celo-mainnet:native`
- No tokens: …

feat: support deep link swap pairs and to tokenId

---

src/send/EnterAmount.test.tsx
src/send/EnterAmount.tsx
test/values.ts

- Only allow decimal separator for inputs, instead of both `,` and `.`
- Round token amount to decimals when converting from local amount
- Fixes ACT-1142
Yes
N/A

feat(send): better regex handling of amount inputs

---

src/statsig/index.ts

Logs are flooded with these when running E2E tests because the sdk runs in local mode and returns the default values
Manual
N/A
N/A
N/A

refactor(statsig): disable uninitialized logs on e2e tests

---

renovate.json5

Now that we've a merge queue and faster CI, we can try getting more PRs merged
Watch PRs after merging
N/A
N/A
N/A

chore(renovate): increase concurrent PR limit

---

src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/import/saga.test.ts
src/onboarding/registration/EnableBiometry.test.tsx
src/onboarding/steps.ts
src/pincode/PincodeSet.tsx
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/statsig/types.ts
test/RootStateSchema.json
test/schemas.ts

Moves `skipVerification` previously stored in app state to a Statsig Experiment; it appears this was originally put into app state so that it could be a/b tested. Now we're just using a different hook, `getExperimentParams`, instead of a `useSelector`.
- Tested locally on iOS using a Stable ID in Statsig.
- E2E tests in CI.
- Unit tests in CI.
- Fixes ACT-1163
Yes
N/A

feat: setup skip phone verification experiment

---

src/qrcode/QRScanner.tsx
src/send/utils.test.ts
src/send/utils.ts

send navigation was blocked on a `canSendTokensSelector` which uses a deprecated tokens selector that only checks celo tokens and returns true if the at least one celo network token has a balance > 0 and a local currency exchange rate is available. The new send flow can handle both these scenarios, and we want to navigate to the zero state send screen, so this check is removed
| <video src="https://github.com/valora-inc/wallet/assets/5062591/279b6b1e-e9ac-4974-832d-2b4c0612df69" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/625788c9-fd1b-48bc-9b30-e61afad1df40" /> | 
- Fixes ACT-1148
Yes

fix(qr): land on send screen when scanning with 0 balance

---

src/qrcode/utils.test.tsx
src/qrcode/utils.ts

just ignores the network prefix and reads the address
I considered trying to read and validate the network, but some things stopped me:
1. lack of any kind of plumbing for a 'default network' in the send flow to action upon the prefix. If we want to use it, should probably be another ticket and have specific UX guidelines
2. Lack of consistency for how other wallets mark their data.
| Wallet              | Celo | Ethereum |
| :---------------- | :------: | ----: |
| Metamask        |   ethereum:0x   | ethereum:0x |
| Coinbase           |  celo:0x   | ethereum:0x |
| SafeWallet    |  celo:0x   | ethereum:0x |
Sometimes the wallets mark L2 chains as their own (celo, optimism, arbitrum) and sometimes just label it 'ethereum'. This inconsistency makes it difficult to action upon.
Unit tested …

fix(qr-scanner): Allow data with network prefixes

---

e2e/src/Pin.spec.js
e2e/src/usecases/ChooseYourAdventure.js
e2e/src/usecases/NewAccountOnboarding.js
e2e/src/usecases/ResetAccount.js
e2e/src/usecases/Settings.js
e2e/src/usecases/Support.js

Noticed some e2e failures where a drawer is rendered instead of tab nav for tab tests. Seems like launch args don't get passed through. Setting newInstance to true so this always gets picked up
CI
N/A
N/A
N/A

test(e2e): ensure new instance whenever launch args are set

---

.github/workflows/check-translation-files-pr.yml
.github/workflows/check.yml
.github/workflows/e2e-pr.yml
.github/workflows/test.yml

Fixes a couple of things
1. Cancels in progress merge queue requests on outdated branches. We originally had this because we used only `head_ref` as the key, which is defined only for PR runs. But now we also have `ref_name`, which should be unique per merge queue PR
2. Run Test workflow on main. Sometimes we merge skipping the queue because of codecov/patch failures (or other reasons). In this case, subsequent PRs won't have a base to compare against because codecov never ran on the commit on main, leading to inconsistent results. 
CI
N/A
N/A
N/A

ci: cancel outdated merge queue requests, run test always on main

---

src/identity/actions.ts
src/identity/reducer.ts
src/identity/selectors.ts
src/pincode/authentication.test.ts
src/pincode/authentication.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/web3/contracts.test.ts
src/web3/contracts.ts
test/RootStateSchema.json
test/schemas.ts

As the title. I've done a detailed writeup [here](https://linear.app/valora/issue/RET-1067/error-while-swapping-private-key-not-found#comment-3729279a).
As a user who knows their pincode, I should always be able to perform a transaction and see my recovery phrase.
- Fixes RET-1067
Y
Y

fix(keychain): fix private key missing error

---

src/points/saga.test.ts
src/points/saga.ts

As the title.
n/a
- Related to RET-1044
Y
Y

fix(points): only fetch config if points are enabled

---

locales/base/translation.json
src/points/PointsHome.test.tsx
src/points/PointsHome.tsx

As the title. [Context](https://valora-app.slack.com/archives/C0684TXDR3K/p1713471273331519?thread_ts=1713256160.962269&cid=C0684TXDR3K).
When the activities defined in the app version has no overlap with the live points config:
- Fixes RET-1044
Y
Y

chore(points): add UI for no supported activities

---

package.json
yarn.lock

This is no longer needed. The custom fork only contained [2 commits](https://github.com/valora-inc/react-native-fs/commits/master/) by our team, both changes are now included in the latest version of `react-native-fs` (which we already have in the package.json).
n/a
- Related to RET-1058
Y

chore(deps): remove react-native-fs custom fork resolution

---

patches/react-native-fs+2.20.0.patch

The `react-native-fs` project is no longer maintained, and I don't have faith that a new version with the changes we need will be published. It seems like the maintainer of the project has changed but he is now publishing a fork rather than publishing from this project (context `https://github.com/itinance/react-native-fs/issues/1197`). The fork has a lot of [changes](https://github.com/itinance/react-native-fs/compare/master...birdofpreyru:react-native-fs:master) and it seems that most projects have _not_ yet migrated to this fork ([low downloads on npm](https://www.npmjs.com/package/@dr.pogodin/react-native-fs)). I don't want to make a decision now about which lib to migrate to and introduce more changes than necessary given the deadline for these privacy manifest changes. So this PR …

chore(deps): patch react-native-fs with privacy manifest

---

ios/PrivacyInfo.xcprivacy
ios/celo.xcodeproj/project.pbxproj

So I think that we _do_ need one of these. The contents are different to my [initial attempt](https://github.com/valora-inc/wallet/pull/5266), it now includes the user defaults api and is linked to the NotificationService plugin.
[Here](https://github.com/valora-inc/wallet/blob/main/ios/celo/AppDelegate.mm#L154) we are using the [user default API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401).
I've struggled to understand whether we need to declare on behalf of third party sdks. The [apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#overview) seem to say no (`If you use the API in your third-party SDK’s code, then you need to …

chore(iOS): declare privacy manifest

---

renovate.json5

As the title - related to #5297. We can't update firebase deps further until we decide what to do with `react-native-sms-retriever`.
n/a
Related to RET-1058
Y

chore(dep): disable automatic updates to firebase dependencies

---

src/dappsExplorer/TabDiscover.test.tsx
src/dappsExplorer/TabDiscover.tsx
src/home/TabHome.test.tsx
src/home/TabHome.tsx
src/navigator/TabNavigator.tsx
src/tokens/TabWallet.test.tsx
src/tokens/TabWallet.tsx

Renames:
- WalletHome -> TabHome
- Assets -> TabWallet
- DAppsExplorerScreenSearchFilter -> Discover
CI
- Part of ACT-1133
Yes
N/A

refactor(tabs): rename tab screen components

---

src/app/Debug.test.tsx
src/app/Debug.tsx
src/app/__snapshots__/Debug.test.tsx.snap

as the title, useful for overriding stable id based gates / experiments
Manually checked debug screen
N/A
N/A
N/A

chore: add statsig stable id to debug screen

---

src/components/NumberTicker.tsx
src/points/PointsHome.test.tsx
src/points/PointsHome.tsx

As the title. The approach was largely inspired by [a nice man on youtube](https://www.youtube.com/watch?v=nhshusc5ya0&list=PL7ycojg9_ZoJwnayMF8n-VlhdXnE_grdg&index=1).
I've added support for decimals in case we want to use this for the wallet balance. 
The ticker animation will run any time the value changes, so it will work automatically for when the points balance changes and the user remains on the screen.
The downside with animations is that there's a lot of smoke and mirrors that mess with the dom. For this ticker, we're basically animating columns of text up and down. From the dom it no longer looks like the actual balance and we lose the ability to assert on its value from the unit tests.
Without decimals:
https://github.com/valora-inc/wallet/assets/20150449/a9ce407e-544e-4a69-85c1 …

feat(points): add number ticker for balance

---

.github/scripts/uploadE2eBuildToEmerge.ts
.github/workflows/e2e-ios.yml

Some main runs fail to upload this because E2E-main runs are skipped if multiple PRs merge at the same time (or if some fail due to test flake). This ensures a commit on main always uploads a build to emerge.
More context here: https://valora-app.slack.com/archives/C02E2FE98P2/p1713968251987719
Watch CI run on merge queue
N/A
N/A
N/A

ci: upload detox build to emerge on merge queue runs

---

src/statsig/constants.ts
src/statsig/types.ts

Just setting up the gate in the code, will be used in subsequent PRs
N/A
- Fixes ACT-1183
Yes
N/A

feat: add stablecoin earn feature gate

---

locales/base/translation.json
src/analytics/Properties.tsx
src/statsig/constants.ts
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx
src/swap/SwapTransactionDetails.test.tsx
src/swap/SwapTransactionDetails.tsx
src/swap/types.ts
src/swap/useSwapQuote.ts

This PR allows enabling the swap fee via the remote config.
When enabled, the free Valora swap fee line item is hidden.
The details of the Valora fee are then displayed when hitting the info button of the exchange rate line item.
| Valora fee disabled | Valora fee enabled (0 fee from API) | Valora fee enabled (positive fee from API) |
|----------|----------|----------|
| ![image](https://github.com/valora-inc/wallet/assets/57791/6cded654-86bd-46eb-ab8d-da35076588bd)  | ![image](https://github.com/valora-inc/wallet/assets/57791/038fb3b4-d2cf-4d49-8325-40b6824038a8)   | ![image](https://github.com/valora-inc/wallet/assets/57791/576fcf93-b99a-4269-a387-fa009e10dedb)   |
| ![image](https://github.com/valora-inc/wallet/assets/57791/37ac4758-4d25-46a7-852a-c6b21ea44047) | …

feat(swap): enable app fee via remote config

---

src/dappsExplorer/TabDiscover.test.tsx
src/dappsExplorer/TabDiscover.tsx

Fixes an edge case where if dapps don't load the first time (or comes back as an empty list), navigating to the discover tab crashes the app. This is because we render the dapps section using a boolean condition (`categories.length && <SectionList />`) and if the array length is 0, it attempts to render `0`, which is outside of a Text component
Manually by setting dapps list to empty list and ensuring the app no longer crashes
N/A
Yes
N/A

fix(discover): fix a crash when dapp list is empty

---

ios/Podfile.lock
ios/celo.xcodeproj/project.pbxproj
package.json
renovate.json5
yarn.lock

Downgrades lottie to fix broken animations in 6.x.
- Tested locally in Android
N/A
Yes
N/A

build(deps): downgrade lottie until breaking changes are resolved

---

src/points/saga.test.ts
src/points/saga.ts

As the title. Rather than remembering to check the remote config in each saga, catch it all at the root level. We should not start talking to the points DB yet.
n/a
n/a
Y

fix(points): prevent sagas spawning if points are disabled

---

src/fiatExchanges/FiatExchangeCurrencyBottomSheet.test.tsx
src/fiatExchanges/FiatExchangeCurrencyBottomSheet.tsx

Crashes when token list is empty, which attempts to render a 0 outside of a `<Text>` component
Unit tests, manually by emptying token list
N/A
Yes
N/A

fix(cico): fix crash on bottom sheet when token list is empty

---

e2e/src/HomeFeed.spec.js
e2e/src/utils/utils.js

With the recent upgrade to Detox in #5375 [`getAttributes()`](https://wix.github.io/Detox/docs/api/actions#getattributes) now works with multiple elements on Android. With this change more tests that previously only ran on iOS can now be run on Android.
N/A
Yes
N/A

test(e2e): enable more tests on android with getAttribute changes

---

locales/base/translation.json
src/earn/EarnCta.test.tsx
src/earn/EarnCta.tsx

Per discussion [here](https://valora-app.slack.com/archives/C03D3K379FE/p1715039879602479?thread_ts=1715034723.546069&cid=C03D3K379FE)
Also consolidated translation strings
- Fixes ACT-1174
Yes
N/A

feat(earn): update cta description

---

src/earn/EarnCta.tsx

The marginBottom on touchable was causing the ripple to exceed only on the bottom. Wrapped in a View to apply margin
| <video src="https://github.com/valora-inc/wallet/assets/5062591/6b69a921-ab8b-4a8a-8193-a86b228bfa6c" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/c04e4581-6bf0-484a-800c-97ca9be195f3" /> | 
- Part of ACT-1174
Yes
N/A

fix(earn): ripple on android exceeds border

---

src/web3/networkConfig.ts

Fixes the casing, to lower case, for the address in `AAVE_ARB_USDC_TOKEN_ID_STAGING`.
N/A
Yes
N/A

fix: lower case token address for sepolia aave arb usdc in token id

---

src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/saga.test.ts
src/earn/saga.ts
src/earn/slice.test.ts
src/earn/slice.ts
src/earn/types.ts
src/redux/migrations.ts
src/redux/reducers.ts
src/redux/sagas.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Sets up earn reducer and actions for submitting deposit transaction. The actual submitting of transaction will be in a follow up PR
Unit tests
yes

feat(earn): redux setup for submitting deposit transaction

---

src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/selectors.ts

feat(earn): add loading state for deposit when tx is submitted

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/saga.test.ts
src/earn/saga.ts
src/viem/saga.ts
test/values.ts

Submits the deposit transactions, mostly based on the swap and jumpstart sagas
Unit tests, manually
- tx currently fails because of a gas limit issue, will make a follow up for this
- loading state is done in #5415 
Uploading earn-submit-tx.mp4…
Yes

feat(earn): implement deposit submit saga

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/statsig/constants.ts

As the title
Successful tx: https://sepolia.arbiscan.io/tx/0xe681a97041ad016ecfae008111285db3b14a60a5054abd5912109af2987245d0
https://arbiscan.io/tx/0x3a72d7edf302f4d88ae86dc42bbffd87b95d47ee9b4a1a0723ddee13cd30954f
https://github.com/valora-inc/wallet/assets/5062591/86a99157-d2c8-4c21-9196-640784d1ce9a
Yes

feat(earn): get gas padding from dynamic config

---

src/home/TabHome.test.tsx
src/home/TabHome.tsx
src/points/saga.test.ts
src/points/saga.ts
src/points/selectors.ts
src/points/slice.test.ts
src/points/slice.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

As the title, this PR:
1. adds a redux property that tracks the status of "track once" activities, which is updated after a points event is processed
2. ensure the track event for create-wallet is not fired again after successfully being processed
3. update tests and migrations
I opted not to hook up the create-wallet activity card status with redux because it'd be very confusing for the user in case of tracking failure.
n/a
- Fixes RET-1069
Y

fix(points): enable some activities to only be tracked once

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnActivePool.test.tsx
src/earn/EarnActivePool.tsx
src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/hooks.ts
src/navigator/types.tsx

Fetches and displays rewards on collect screen. Also hooks up the screen to the Exit Pool button on discover tab.
Loading -> display rewards (intentionally slowed down to show loading state)
https://github.com/valora-inc/wallet/assets/5062591/0d4442e0-7648-4aad-9a84-c8917a99fd23
Error state:
Yes

feat(earn): fetch rewards on collect screen

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts

As the title
Unit tests, manually by invoking this function
Yes

feat(earn): add function for preparing withdraw transactions

---

src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/hooks.ts
src/send/SendEnterAmount.test.tsx
test/utils.ts

Updates hook to prepare txs after rewards info is fetched and then use prepared txs to display gas fee on the collect screen
https://github.com/valora-inc/wallet/assets/5062591/52291d53-72c4-4a46-a964-f273cfc7698d
Yes

feat(earn): prepare transactions on the collect screen and display gas

---

src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/saga.test.ts
src/earn/saga.ts
src/earn/slice.test.ts
src/earn/slice.ts
src/earn/types.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Also changed from started -> loading to be consistent with other slices
Unit tests
Yes

feat(earn): redux setup for withdraw

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/selectors.ts
src/earn/types.ts

Dispatches the redux action on pressing the collect earnings button and fires analytics event
Unit tests
Yes

feat(earn): dispatch withdraw start on pressing collect

---

src/components/Button.tsx
src/components/ClipboardAwarePasteButton.tsx
src/import/ImportWallet.tsx
src/keylessBackup/KeylessBackupProgress.tsx
src/onboarding/registration/EnableBiometry.tsx
src/onboarding/registration/OnboardingRecoveryPhrase.tsx
src/onboarding/registration/RegulatoryTerms.tsx
src/onboarding/welcome/Welcome.tsx
src/verify/VerificationStartScreen.tsx

Update the onboarding buttons
unit/e2e tests pass
Manual Tests:
- N/A
Yes

feat(buttons): Change onboarding buttons to new design

---

src/statsig/constants.ts
src/statsig/types.ts

feature gate: https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/subsidize_stablecoin_earn_gas_fees
N/A
- Fixes #ACT-1190
Yes

feat(earn): Add feature gate for covering gas fees

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnActivePool.test.tsx
src/earn/EarnActivePool.tsx

Hooks up the deposit more button on the Earn cta to navigation and analytics.
- Part of ACT-1176
Yes

fix(earn): navigation to enter amount on deposit more tap

---

src/earn/EarnEnterAmount.tsx

On Android the header back button was displayed in the status bar this should fix that issue.
| Android Before | Android After |
| ![](https://github.com/valora-inc/wallet/assets/26950305/b941cac5-6644-4a1e-8832-ee9474efe67a "Android Before") | ![](https://github.com/valora-inc/wallet/assets/26950305/810f81fd-e695-4149-a061-2ac94bc17e72 "Android After") |
N/A
Yes

fix(earn): android header back button

---

src/analytics/Properties.tsx
src/earn/saga.test.ts
src/earn/saga.ts
src/swap/saga.ts
src/transactions/types.ts
src/transactions/utils.ts

Adding gas fields to analytics properties similar to swaps for the earn deposit transaction
Unit tests
N/A
Yes

feat(earn): add gas related analytics properties

---

src/earn/saga.test.ts
src/earn/saga.ts

Should help with https://valora-app.slack.com/archives/C04B61SJ6DS/p1716315055922759?thread_ts=1716314300.065339&cid=C04B61SJ6DS
Unit tests
- N/A
Y

feat(earn): fetch token balances after a tx is submitted

---

src/analytics/Properties.tsx
src/earn/EarnActivePool.test.tsx
src/earn/EarnActivePool.tsx
src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/earn/constants.ts
src/earn/saga.test.ts
src/earn/saga.ts

Use consistent naming, include some common properties in events
Unit tests
N/A
Yes

refactor(earn): consolidate analytics events

---

src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx

If feature flag set, strikethrough gas token amount, don't show gas fiat amount, show gas subsidized copy.
Unit tests updated/added.
Subsidize gas feature gate true:
Subsidize gas feature gate false:
- Fixes #ACT-1196
Yes

feat(earn): Withdraw screen gas subsidy update

---

src/components/NumberTicker.tsx
src/points/saga.test.ts
src/points/saga.ts

This PR fixes:
1. the points balance was outdated on the discover tab because the balance fetch was only triggered on the points home screen. now we also trigger a balance fetch on app mount.
2. also fetch points config on app mount (consolidate logic, was previously being fetched on home screen visit)
3. disable font scaling on the points balance because the font size is large already, and font scaling messes with the animation.
n/a
n/a
Y

fix(points): ensure balance is displayed timely and correctly

---

src/points/slice.test.ts
src/points/types.ts
src/swap/saga.test.ts
src/swap/saga.ts
src/transactions/saga.test.ts
src/transactions/saga.ts
test/RootStateSchema.json

The core points logic doesn't rely on the to and from tokens in a swap, these are only used for display purposes. Since we already have them in the wallet, it'd save a lot of work to just pass them to the backend (rather than deriving them again using the transactions and adding logic for creating the token id's on the backend)
n/a
- Related to RET-1034
Y

chore(points): send token ids with swap events

---

src/components/TokenBottomSheet.test.tsx
src/components/TokenBottomSheet.tsx
src/send/EnterAmount.tsx
src/swap/SwapScreen.tsx

All usages of token bottom sheet (Swap screen, send enter amount) uses the token balance item option. 
Unit tests, manually checking both Swap and Send flows
- Part of ACT-1170
Yes

refactor(token-bottom-sheet): remove deprecated option

---

src/points/saga.test.ts
src/points/saga.ts

Follow up PR to #5466 
1. Uses `spawn` to start sagas
`spawn` does not propagate errors to the parent, so if one of the spawned sagas will fail, this won't affect others -- effectively the same as when `safely` wrapper was used.
2.  Added simplified unit test to ensure the sagas are spawned only once during user session.
* Tested manually
* Added unit test
NA
Y
NA

fix(points): app mount sagas have not been running #2

---

src/components/TokenBottomSheet.test.tsx
src/components/TokenBottomSheet.tsx

This was added in https://github.com/valora-inc/wallet/pull/4242 when we were working towards multichain, but now there shouldn't be a need for multiple TokenBalance types
CI
N/A
Yes

refactor(token-bottom-sheet): remove unused generic

---

src/components/NumberTicker.tsx
src/points/PointsHome.tsx
src/points/saga.test.ts
src/points/saga.ts
src/points/selectors.ts

This PR fixes 2 things:
1. if a transaction is settled within the same app session, it is most likely also picked up by our internal transaction watcher. previously, this was causing 2 almost simultaneous requests to our track points event backend (no bad side effects except we don't really need that extra request)
2. ensure that the points balance animates on screen open
The balance animates on mount but not on refresh if the balance hasn't changed:
https://github.com/valora-inc/wallet/assets/20150449/408ce7bc-a5b2-4b5b-bab1-d8f7432e5e2e
The balance animates on refresh if the balance has changed (I mocked the balance to return 1 of 3 random balances):
https://github.com/valora-inc/wallet/assets/20150449/31d53994-0165-4860-903a-0d442655e40e
n/a
Y
If a new NetworkId and/or Network are …

fix(points): prevent multiple track requests, fix balance mount animation

---

src/account/Settings.tsx
src/navigator/Navigator.tsx

When the bottom sheet was opened on setting the header was shown in white instead of the same gray opaque seen on the rest of the screen. This PR fixes that on Android and iOS. 
| iOS Before | Android Before | iOS After | Android After |
| ----- | ----- | ----- | ----- |
| ![](https://github.com/valora-inc/wallet/assets/26950305/a22329e5-9b58-402c-97b5-cfa10e7799c6 "iOS Before") | ![](https://github.com/valora-inc/wallet/assets/26950305/b1c38381-a80a-423b-8d9b-2867b1ebf28c "Android Before") | ![](https://github.com/valora-inc/wallet/assets/26950305/0e54ddfe-7e8a-4be9-8a56-421ad65abc33 "iOS After") | ![](https://github.com/valora-inc/wallet/assets/26950305/07276b59-6f3e-4121-b477-00b58c46b464 "Android After") |
- Fixes ACT-1153
Yes
N/A

fix(settings): header shown as white when bottom sheet is open

---

locales/base/translation.json
src/components/FilterChipsCarousel.tsx
src/components/TokenBottomSheet.tsx
src/fiatExchanges/FiatExchangeCurrencyBottomSheet.test.tsx
src/fiatExchanges/FiatExchangeCurrencyBottomSheet.tsx
src/statsig/constants.ts
src/statsig/types.ts
src/tokens/hooks.test.tsx
src/tokens/selectors.ts
test/values.ts

Adds token filters for cash in flow only, gated by [statsig feature gate](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/show_cash_in_token_filters)
https://github.com/valora-inc/wallet/assets/5062591/ab18b07a-11df-4628-8305-cc43691fdba9
- Fixes ACT-1170
Yes

feat(cico): add token filters for cash in

---

e2e/src/usecases/FiatConnectTransferOut.js
package.json
yarn.lock

Resolves the [audit advisory](https://github.com/advisories/GHSA-grv7-fg5c-xmjg) for braces.
Updates e2e tests for Fiat Connect from #5532.
- Increase wait time for tx feed item to appear (60s doesn't seem enough)
- Remove back photo ID, which persona doesn't seem to request now
Tested in CI.
N/A
Yes 
N/A

ci: fix vulnerability check and e2e tests

---

src/send/EnterAmount.tsx

When pressing the max button a user would always get the error saying to enter a lower amount, this fixes it.
Explanation [here](https://valora-app.slack.com/archives/C02KBT0DAHJ/p1718034648230829).
CI
- N/A
Yes

fix(send): Fix bug where you can't send max amount

---

src/earn/EarnCta.test.tsx
src/earn/EarnCta.tsx

Looks like this was missed when adding the screen
CI, manually ensuring the cta navigates to the info screen
N/A
Yes

fix(earn): navigate to earn info screen from CTA

---

src/statsig/constants.ts
src/statsig/types.ts

Adds a feature gate for using CAB (Cloud Account Backup) screens in onboarding: [Statsig](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/gates/show_cab_in_onboarding).
N/A
- Fixes ACT-1231
Yes
N/A

chore: add feature gate for cab in onboarding

---

src/send/saga.test.ts
src/swap/saga.test.ts
src/viem/getLockableWallet.test.ts
src/viem/getLockableWallet.ts
src/viem/index.ts
src/viem/prepareTransactions.test.ts
src/viem/prepareTransactions.ts
src/viem/saga.test.ts
src/viem/saga.ts
src/web3/contracts.test.ts
src/web3/contracts.ts
src/web3/networkConfig.ts

In preparation for using syndicate's rpc node for earn transactions when gas is subsidized, update the viem functions to use a different rpc endpoint for both estimating gas and submitting transaction
CI, a follow up PR will have comprehensive testing
- Part of ACT-1194
Yes

feat(viem): support using valora rpc endpoint if gas is subsidized

---

scripts/sync_branding.sh
src/account/Education.tsx
src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
src/account/__snapshots__/Education.test.tsx.snap
src/account/__snapshots__/GoldEducation.test.tsx.snap

Adjust the button styles to match the new learn account key education: [Figma](https://www.figma.com/design/mthUlChSbWXXxLe2AV13Wd/Onboarding-2024?node-id=1-3&t=6oAJf921pKwnPmPe-0).
| iOS Before | iOS After |
| <video src="https://github.com/valora-inc/wallet/assets/26950305/f5e5fb71-8d60-432e-a641-e15c480c680f" /> | <video src="https://github.com/valora-inc/wallet/assets/26950305/1b745c68-e016-499c-9bb2-6f0c1c86c566" /> | 
Related Branding PR: https://github.com/valora-inc/valora-app-branding/pull/33
- Fixes ACT-1220
Yes
N/A

chore: adjust learn account key images and button styles

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/earn/saga.test.ts
src/earn/saga.ts

Based on the feature gate, enable gas subsidy when preparing and submitting earn transactions. Also dropped tenderly simulation for gas estimation because we can use syndicate's rpc for this instead of alchemy and they should succeed even without enough amount for gas. 
CI, manually by enabling feature gate (and overriding the rpc url with syndicate's url as the proxy isn't ready yet) and trying deposit and withdraw from wallets with no or low ETH and ensured gas is covered. 
https://github.com/valora-inc/wallet/assets/5062591/4d4688bb-c89e-4661-b976-8558e1bbd1c0
https://github.com/valora-inc/wallet/assets/5062591/9d63e052-b7a6-4ee1-a955-d3c88056bad0
- Fixes ACT-1194
Yes

feat(earn): enable gas subsidy for transactions

---

src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/earn/prepareTransactions.ts

- EarnEnterAmount - show spinner on button when tx is prepared
- EarnCollectScreen - disable button when showing spinner
| Screen | Before | After |
| EnterAmount | <video src="https://github.com/valora-inc/wallet/assets/5062591/00f97cd6-7701-426a-bc31-b06dcb3ad76a" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/f88ed460-c104-4532-a7e1-4b512ba9056e" /> |
| Collect | <video src="https://github.com/valora-inc/wallet/assets/5062591/12291d60-0f48-49b8-a234-78902d7ee3ef" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/22a0ec65-fe47-458b-b637-21f9f110b737" /> | 
N/A
Yes

fix(earn): show loading states when tx is prepared and submitted

---

src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/send/EnterAmount.test.tsx
src/send/EnterAmount.tsx

Discovered with `EarnEnterAmount.tsx`, but also present in `EnterAmount.tsx` when pressing max the local decimilar separator was not set correctly preventing users from being able to delete characters from the input amount.
N/A
Yes
N/A

fix(max): respect local decimal separator when setting max

---

locales/base/translation.json
src/earn/EarnApyAndAmount.tsx
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnEnterAmount.test.tsx

Fixes the display of the earn up to amount to display in the users selected local currency: [Slack Thread](https://valora-app.slack.com/archives/C04B61SJ6DS/p1718895183418909).
| iOS Before PHP | iOS After PHP |
| ![](https://github.com/valora-inc/wallet/assets/26950305/9305f436-ab5d-4521-8c5e-6eddb8ceacaf "iOS Before PHP") | ![](https://github.com/valora-inc/wallet/assets/26950305/c60253de-2a08-45a3-b308-15993d7e1eb5 "iOS After PHP") |
N/A
Yes
N/A

fix(earn-enter-amount): local earn up to amount

---

src/transactions/feed/queryHelper.ts

After ACT-1186 was merged the error `An internal error occurred:  [Error: Queue timeout before completed restoration]` was seen in the transaction feed. This appears to be due to multiple state updates from an asynchronous operation causing unnecessary re-renders.  As a solution, these state updates are now wrapped in a [`useCallback`](https://react.dev/reference/react/useCallback) hook.
- Partial ACT-1186
Yes
N/A

fix(transaction-feed): wrap state updates in useCallback

---

src/navigator/Navigator.tsx
src/nfts/NftMedia.tsx
src/nfts/NftsInfoCarousel.tsx

Follow up to #5566 where iOS's initial load of iOS could obscure the full screen controls. This also cleans up the navigation options and moves them into `src/nfts/NftsInfoCarousel.tsx`.
| iOS Before | iOS After |
| <video src="https://github.com/valora-inc/wallet/assets/26950305/f884e901-31d4-42e8-b2f7-b1b6dacb07ca" /> | <video src="https://github.com/valora-inc/wallet/assets/26950305/b55776a9-7e37-42fa-a261-e4e2d95bbb97" /> |
- N/A
Yes
N/A

fix(nft-video): initial load height on iOS

---

src/earn/EarnActivePool.tsx
src/earn/EarnApyAndAmount.tsx
src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/EarnCta.test.tsx
src/earn/EarnCta.tsx
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnEnterAmount.test.tsx
src/earn/hooks.ts
src/earn/saga.test.ts
src/earn/saga.ts
src/earn/selectors.ts
src/earn/slice.ts
src/earn/types.ts
src/home/GetStarted.test.tsx
src/home/GetStarted.tsx
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

Store APY in redux so going back doesn't use outdated values
- Fixes ACT-1205
Yes

feat(earn): consistent apy across screens

---

src/backup/BackupPhraseContainer.tsx
src/fiatconnect/kyc/KycPending.tsx
src/import/ImportWallet.tsx
src/navigator/Headers.tsx
src/navigator/Navigator.tsx
src/onboarding/ChooseYourAdventure.tsx
src/onboarding/registration/OnboardingRecoveryPhrase.tsx
src/onboarding/registration/ProtectWallet.tsx
src/pincode/PincodeSet.tsx
src/styles/colors.tsx
src/verify/VerificationCodeInputScreen.tsx
src/verify/VerificationStartScreen.tsx

Removes usages of onboardingBackground as background and sets color name to ivory for those places where it is used. Some screens such as `ChooseYourAdventure.tsx`, which relied on the background to display the buttons, now use a button background color.
| CYA iOS Before | CYA iOS After | Phrase iOS Before | Phrase iOS After |
| ----- | ----- | ----- | ----- | 
| ![](https://github.com/valora-inc/wallet/assets/26950305/78982487-e20b-4c3e-8613-8f9255980efc) | ![](https://github.com/valora-inc/wallet/assets/26950305/b330d563-205a-4806-a587-64ada57ca833) | ![](https://github.com/valora-inc/wallet/assets/26950305/746d58cf-fc87-4992-8c03-b5eba1c1388f) | ![](https://github.com/valora-inc/wallet/assets/26950305/35348657-3629-4305-b251-5ee1e551a193) |
N/A
Yes
N/A

chore: remove ivory onboarding background

---

ios/celo.xcodeproj/project.pbxproj

Since I got errors related to node's path when building from Xcode directly,
I noticed the way we're detecting node's path in Xcode build phases is inconsistent with what React Native 0.69+ does now.
RN now recommends using [`node_modules/react-native/scripts/xcode/with-environment.sh`](https://github.com/facebook/react-native/blob/06fc6f2beb9a6733ada7791dd91e2b9ec28d0c0e/packages/react-native/scripts/xcode/with-environment.sh) everywhere.
We had manually modified logic in several build phrase scripts, which were not doing the same thing. Leading to possibly using different node binaries between these different scripts.
Backported from https://github.com/valora-inc/troopo/pull/31
See also https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/
Since the diff is hard to …

chore: fix inconsistent node path in Xcode build scripts (#31)

---

src/points/PointsDiscoverCard.tsx

Remove the `imageResizeMode` style property:
* it is wrong, it should be `resizeMode`
* the value `cover` is [the default one](https://reactnative.dev/docs/image#resizemode), so this property is not needed at all
While not causing any harm to the users, it yields annoying RN error in dev mode:
Tested manually
- Related to RET-1103
Y
NA

fix(points): remove wrong and redundant image style property

---

src/icons/SwapArrows.tsx

The swap icon lost its stroke compared to [one in figma](https://www.figma.com/design/erFfzHvSTm5g1sjK6jWyEH/Working-Design-System-Components?node-id=317-135&t=iNHByjTAhOFLGYKN-0). This fixes it.
Context: https://valora-app.slack.com/archives/C0684TXDR3K/p1720545011018399
| Before fix | After fix | In Figma |
| ![image](https://github.com/valora-inc/wallet/assets/2737872/41834934-2382-4c4c-b529-6b85ad0a816f) | ![image](https://github.com/valora-inc/wallet/assets/2737872/0fc1cc45-9815-439d-a90c-d2a2ef591061) | <img width="64" alt="image" src="https://github.com/valora-inc/wallet/assets/2737872/b7bc2102-80f8-4dba-aaf8-c743d0f396f0"> | 
- Related to RET-1103
Y
NA

fix(points): add stroke to "swap" icon

---

src/components/BorderlessButton.tsx
src/components/FilterChipsCarousel.tsx
src/dapps/DappsScreen.tsx
src/dappsExplorer/DappCard.tsx
src/dappsExplorer/DiscoverDappsCard.tsx

[Context](https://valora-app.slack.com/archives/C0684TXDR3K/p1719510075150019) and [design](https://www.figma.com/design/FwRyq9HaKtZgywKVmIg0Zh/Discover-Page?node-id=1-3&t=uHdxyczMjeuYYBO2-0).
This PR only has styles changes. Also fixes the dapp filters appearing on more than 1 row. This PR breaks the dapp rankings styles but that is disabled and earmarked for deletion anyway. 
https://github.com/valora-inc/wallet/assets/20150449/7f1cd23b-8e5f-497a-88e9-174ad7afdf5a
n/a
yes

chore: update discover dapp and dapp filter styles

---

src/statsig/constants.ts
src/statsig/types.ts
src/swap/SwapAmountInput.tsx
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx

As the title, this PR includes:
- removing the buy experiment statsig variables
- removing the `updatedField` swap screen state variable and its references (it always has the value `Field.FROM` now) - the `updatedField` value is only changed on the `changeAmount` action.
- removing some tests about the buy flow
Unit tests pass, i can still swap
- Fixes RET-920
Y

chore: remove swap buy amount flow

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnCard.test.tsx
src/earn/EarnCard.tsx
src/earn/EarnCta.test.tsx
src/earn/EarnCta.tsx
src/earn/EarnEntrypoint.test.tsx
src/earn/EarnEntrypoint.tsx
src/earn/EarnInfoScreen.test.tsx
src/earn/EarnInfoScreen.tsx
src/navigator/types.tsx
src/statsig/constants.ts
src/statsig/types.ts

Sets up the statsig gate and shows the earn entrypoint card on the discover tab. Only changes the card for when there are no active pools. 
Also refactors the EarnInfoScreen to not take tokenId as a param because it is a generic screen.
[Figma](https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=4079-14115&t=VKwjwdsC2mZD4NcH-0)
- Part of ACT-1257
Yes

feat(earn): update earn discover card for multiple pools

---

locales/base/translation.json
src/earn/saga.test.ts
src/earn/saga.ts
src/earn/slice.test.ts
src/earn/slice.ts
src/earn/types.ts
src/points/ActivityCardSection.tsx
src/points/PointsHistoryBottomSheet.test.tsx
src/points/PointsHistoryBottomSheet.tsx
src/points/PointsHome.test.tsx
src/points/cardDefinitions.tsx
src/points/saga.test.ts
src/points/saga.ts
src/points/types.ts
test/RootStateSchema.json

For [RET-1090](https://linear.app/valora/issue/RET-1090/enable-points-for-deposit-into-earn-pool). Adds support for depositing into earn pools.
Manual and unit tested. See video below (excuse my laggy simulator!).
https://github.com/user-attachments/assets/38a8f8a1-5ac4-4c06-8ad1-ca4afd9563a8
- Fixes [RET-1090](https://linear.app/valora/issue/RET-1090/enable-points-for-deposit-into-earn-pool)
Yes.

feat(points): Support earning points for depositing into earn pool

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/analytics/types.ts
src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/jumpstart/JumpstartTransactionDetailsScreen.test.tsx
src/jumpstart/JumpstartTransactionDetailsScreen.tsx
src/jumpstart/usePrepareJumpstartTransactions.test.ts
src/jumpstart/usePrepareJumpstartTransactions.ts
src/swap/useSwapQuote.ts
src/viem/prepareTransactions.test.ts
src/viem/prepareTransactions.ts
src/walletConnect/saga.ts

When preparing a tx in the various flows, if it fails with insufficient gas, add an analytics event.
- Fixes ACT-1256
Yes

feat(analytics): add event for insufficient gas warnings

---

src/swap/useFilterChips.ts

As discussed at retro with Laura and Kayla.
n/a
n/a
n/a

chore(swap): remove 'popular' token filter as pre-selected

---

yarn.lock

https://github.com/advisories/GHSA-mpg4-rc92-vx8v
This vulnerability was blocking our CI.
- Tests pass
N/A
Yes

fix(deps): update fast-xml-parser to address CVE-2024-41818

---

src/jumpstart/JumpstartTransactionDetailsScreen.tsx
src/walletConnect/screens/ActionRequest.test.tsx
src/walletConnect/screens/ActionRequest.tsx
src/walletConnect/screens/EstimatedNetworkFee.test.tsx
src/walletConnect/screens/EstimatedNetworkFee.tsx

Extend `<EstimatedNetworkFee />` so it can show a loading state (while preparing transactions) and use multiple TXs to show the total estimated fee.
It also now uses `getEstimatedFee` instead of `getMaxGasFee`. 
So it's closer to the actual fee.
https://github.com/user-attachments/assets/e351f231-5885-435f-8555-07df348f9f48
Note: This video is just to show the loading state, this PR doesn't yet add it to the claim shortcut bottom sheet, it will be in another PR.
- Fixes RET-1108
Yes

feat: EstimatedNetworkFee with loading state and multiple TXs

---

src/statsig/constants.ts
src/statsig/index.test.ts
src/statsig/index.ts
src/statsig/types.ts

Unlike experiments and dynamic config, the feature gate sdk call `checkGate` doesn't take default params as an option. If the SDK is uninitialized it will always return `false`, so we should always model gates to default to false. The fallback default we currently have is only used in case of exceptions, which is a very unlikely scenario. This PR removes the default values and updates the checkGate exception handler to return false for all gates (except the 2 that currently defaults to true)
CI
- N/A
Yes

refactor(statsig): remove defaults for feature gates

---

src/transactions/actions.ts
src/transactions/reducer.test.ts
src/transactions/reducer.ts
src/transactions/saga.ts

[Context](https://github.com/valora-inc/wallet/pull/5677#discussion_r1696537447)
On receiving new transactions from blockchain-api, the redux state that stores transactions is updated via the reducer. We then kick off a saga that dispatches another action to remove corresponding standby transactions via another action. This PR removes that complexity and updates the standby transactions via the original action. Sagas should be reserved for asynchronous side effects. 
n/a
- Related to RET-1118
Y

refactor: consolidate redux state changes on update transactions

---

src/transactions/feed/TransactionFeed.tsx

This PR is a "quick fix" so I didn't bother with tests. I want to rework the transaction feed stuff because it's too complex and doesn't work well. There are a ton of rerenders constantly (possibly contributing to app slowness) and most of the issue stems from storing the fetched transactions in state which doesn't preserve the identity of the objects even if they change. It also means that fetched transactions are displayed right away, without being coordinated with other stored redux data.
The last part of this is really hard to work with. For pending cross chain swaps, any standby transaction should be augmented with the data (in effect, the standby transactions are the source of truth when available for pending transactions). With the current setup of the TransactionFeed, anything …

fix: prevent duplicate cross chain pending swap tx items

---

src/transactions/feed/TransactionFeed.tsx
src/transactions/feed/queryHelper.ts

Rerenders are not (usually) the enemy but this `allowedNetworks` array is used in a few dependency arrays for computations on the homefeed which is slow already. I noticed that the `allowedNetworks` array was always triggering updates (can tell by logging something in a useEffect or useMemo with only `allowedNetworks` in the dependency array, the logs are printed frequently) and i think it is because the array does not preserve its identity when returned from the `getAllowedNetworkIds` function. I wasn't sure if it's safe to only get the allowed networks on mount (in case this screen is never remounted and the dynamic config changes) so opted for a hacky string solution here.
When logging something in a useEffect or useMemo with only `allowedNetworks` in the dependency array, the log …

fix: ensure allowedNetworks does not trigger unnecessary rerenders

---

src/dapps/DappShortcutsRewards.test.tsx
src/dapps/DappShortcutsRewards.tsx
src/positions/saga.test.ts
src/positions/slice.ts

This change could be useful in the future to properly identify the position that triggered the shortcut.
For instance we could imagine the hooks backend could retrieve the full position from the id, to pass it to the `onTrigger` method of the shortcut. Giving additional context that could be needed.
- Fixes RET-1110
Yes

feat(shortcuts): include positionId when triggering shortcuts

---

src/transactions/feed/TransactionFeed.tsx
src/transactions/feed/queryHelper.ts

This was a suggestion in #5699 but it was merged before being addressed. This also fixes a bad trailing space that was left in the string, which causes a 400 response from blockchain-api.
n/a
n/a
Y

refactor: use useAllowedNetworks in a hook

---

src/components/TokenBottomSheet.tsx

A small style nitpick for the ripple on Android within the token bottom sheet component.
| Token Bottom Sheet Before (Swaps) | Token Bottom Sheet After (Swaps) |
| ![](https://github.com/user-attachments/assets/d7be98dc-3d91-47f6-b9e4-c0e59a9e4ba5 "Token Bottom Sheet Before (Swaps)") | ![](https://github.com/user-attachments/assets/51b77015-1a91-4336-86f6-dfa05047669a "Token Bottom Sheet After (Swaps)" ) |
N/A
Yes
N/A

fix: android ripple on token bottom sheet

---

ios/Podfile.lock
package.json
yarn.lock

Upgrades [react-native-screens to 3.33.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.33.0) which contains a fix for the [header shadow display issue](https://github.com/software-mansion/react-native-screens/issues/2212) on goBack.
| Android Before | Android After |
| ![](https://github.com/user-attachments/assets/ac4a0f71-c751-45d8-b852-adb79367f78a "Android Before") | ![](https://github.com/user-attachments/assets/ea165706-8dab-45b3-90a3-b2652014c1a6 "Android After") | 
- Fixes ACT-1335
- https://github.com/react-navigation/react-navigation/issues/12063#issuecomment-2264111850
Yes
N/A

fix(deps): upgrade react-native-screens to ^3.33.0

---

src/onboarding/ChooseYourAdventure.tsx

Nitpick style fix for possible text overflows for CYA cards.
| iOS Before | iOS After |
| ![](https://github.com/user-attachments/assets/da99c837-b316-4f7c-a97e-dc19fcd43e83 "iOS Before") | ![](https://github.com/user-attachments/assets/d7f6f3e0-91aa-4d1f-b2cc-3cb6c5992d30 "iOS After") |
- Fixes ACT-1033
Yes
N/A

fix: text overflow on CYA

---

src/transactions/feed/queryHelper.test.ts
src/transactions/feed/queryHelper.ts
src/transactions/reducer.ts

This PR fixes a couple of bugs:
1. when a cross chain swap is pending for a long time, the app vibrates periodically for no apparent reason
2. when a user restores their wallet and there is a pending cross chain swap, and it is actually completed, it will show completed in the app session but on subsequent app sessions, it always starts off as pending.
The root cause for both is due to the query helper attributing the cross chain swap as new or existing incorrectly. For the scenarios:
1. the pending cross chain swap isn't stored with the other received blockchain-api transactions (it is instead stored with the pending standby transactions) so every poll interval, we receive the pending tx from blockchain-api -> it's not in the redux store that we expect -> we count it as new and vibrate …

fix: handle received pending cross chain swaps correctly

---

e2e/src/Discover.spec.js
src/dappsExplorer/TabDiscover.tsx

As the title.
https://github.com/user-attachments/assets/b8fc9ddb-677f-45ae-9a12-e9ad0073bb5a
- Fixes RET-1166
Y

fix: scroll aware header on discover screen

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/points/PointsHome.test.tsx
src/points/PointsHome.tsx

As the title.
https://github.com/user-attachments/assets/f8cc7380-0b3e-495d-a249-ce1b37869ad8
- Fixes RET-1167
Y

feat: add info disclaimer on points screen

---

src/keylessBackup/KeylessBackupProgress.tsx

Change cta for restore back to "Restoring your wallet", fixing a bug introduced in #5611 
Manually restoring and checking the CTA
N/A
Yes
N/A

fix(cab): text on restore in progress screen

---

src/points/PointsHome.test.tsx
src/points/selectors.test.ts
src/points/selectors.ts

Hide live links activity when a user has no jumpstart tokens (or live links are disabled).
This is consistent with the send flow behavior when the live link option is not shown when a user has no jumpstart tokens.
If the user tries to create a jumpstart link without having the jumpstart tokens the app will crash.
Context: https://valora-app.slack.com/archives/C04B61SJ6DS/p1723075264724759
* Tested manually
* Updated unit test
NA
Y

fix(points): hide live links when user has no jumpstart tokens

---

src/account/Education.tsx
src/account/SupportContact.tsx
src/app/__snapshots__/ErrorScreen.test.tsx.snap
src/backup/BackupComplete.tsx
src/backup/__snapshots__/BackupComplete.test.tsx.snap
src/components/FullscreenCTA.tsx
src/components/ReviewHeader.tsx
src/components/__snapshots__/FullscreenCTA.test.tsx.snap
src/nfts/NftsInfoCarousel.tsx
src/onboarding/ChooseYourAdventure.tsx
src/onboarding/registration/ProtectWallet.tsx
src/onboarding/registration/RegulatoryTerms.tsx
src/pincode/Pincode.tsx
src/pincode/PincodeDisplay.tsx
src/styles/fonts.tsx
src/verify/VerificationStartScreen.tsx
src/walletConnect/screens/ConnectionTimedOut.tsx
src/walletConnect/screens/Logos.tsx

As the title. It seems like a straight replace for h1 -> titleMedium, this is what was asked for in RET-1165.
n/a
Related to RET-1174 
Y

chore: remove deprecated h1 font

---

src/swap/SwapScreen.tsx

Observed behavior: incompatible selection banner disappears only after the new quote is fetched
Expected behavior: incompatible selection banner disappears right after another token is selected
Context: https://valora-app.slack.com/archives/C04B61SJ6DS/p1723220851805809?thread_ts=1723219373.676809&cid=C04B61SJ6DS
The same applies for other quote-dependent banners as well:
* cross-chain fee warning
* decrease spend amount for gas
* non enough balance for gas
* show missing price impact
| ![before](https://github.com/user-attachments/assets/0853ff8a-01f4-4006-b6b0-dfaf2d923466) | ![after](https://github.com/user-attachments/assets/45d41d14-626e-4e08-8f4c-814a8650e41c) | 
NA
Y
If a new NetworkId and/or Network are added in the future, …

fix(swaps): hide incompatible selection banner on quote fetch

---

ios/celo/AppDelegate.mm

Fixes the network plugin not showing requests not showing in iOS on Fb Flipper by removing the explicit initialization in `AppDelegate.mm`.
https://github.com/facebook/flipper/issues/3945
Yes
N/A

fix: network requests in fb flipper

---

locales/base/translation.json
src/analytics/Properties.tsx
src/components/AddAssetsBottomSheet.tsx
src/earn/EarnAddCryptoBottomSheet.test.tsx
src/earn/EarnAddCryptoBottomSheet.tsx

As the title. This change makes it easier to implement a similar component for the points [design](https://www.figma.com/design/6sJ4fCxCptTybHB6ZZ7Pqi/Escrow-Feature?node-id=3341-3388&t=wNp4q9sJM0JyZxXQ-0).
The new component doesn't contain much logic so I didn't invest time in making unit tests.
n/a
- Related to RET-1177
Y

refactor: make generic add assets bottom sheet component

---

android/build.gradle

I was getting build issues for Android because I'm running Java 17.
Here's a fix.
See Slack [thread](https://valora-app.slack.com/archives/C025V1D6F3J/p1724415154485749?thread_ts=1723827073.858059&cid=C025V1D6F3J).

chore: fix Android build error when using Java > 11

---

src/earn/EarnHome.tsx

Use `color` instead of `colors`  in styles as `colors` is an invalid style prop that causes a warning.
N/A
Yes
N/A

fix: invalid style prop on earn home

---

src/viem/getLockableWallet.test.ts
src/viem/keychainAccountToAccount.test.ts
src/web3/KeychainLock.test.ts
src/web3/KeychainWallet.test.ts
test/values.ts

- Tests pass
- Related to RET-1182
Yes

test: move common private keys and related values to test/values

---

src/positions/saga.test.ts
src/positions/saga.ts

`hooks` repo `.crowdin.yml` ([here](https://github.com/valora-inc/hooks/blob/main/.crowdin.yml)) uses 2 letter code for language, update API header to use that. Same as `dapp-list`.
Unit tests updated
- Related to ACT-1331
Yes

fix: Use 2 letter code for hooks API language header

---

src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx
src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/viem/prepareTransactions.ts

Also fixes a small bug in earn prepare transactions with amount units.
CI
- Part of ACT-1342
Yes

refactor(earn): connect pool details to deposit screen

---

__mocks__/react-native-quick-crypto.ts
android/app/build.gradle
ios/Podfile.lock
metro.config.js
package.json
src/backup/utils.test.ts
src/backup/utils.ts
src/import/saga.ts
src/utils/account.ts
src/web3/saga.test.ts
src/web3/saga.ts
yarn.lock

Use https://github.com/margelo/react-native-quick-crypto to provide fast and secure crypto operations.
Note: We'll be able to gradually remove the following libs which are now redundant:
- `react-native-bip39`
-  `react-native-fast-crypto`
- `react-native-securerandom`
- `node-libs-react-native` and its own native deps (once ContractKit is removed)
- `react-native-crypto`
- `react-native-randombytes`
- Tests pass
- Manually
-  confirmed mnemonic generation and key derivation is as fast as before and uses the native implementation from the new library, on both iOS and Android
- importing some existing mnemonics works as before
- Part of RET-1185
Yes

refactor: use react-native-quick-crypto

---

android/build.gradle

Updates the Android SDK version to be Play Store compliant. I've opted to avoid updating the NDK version as a mismatch between the NDK version and the recommended NDK version for react-native can cause hard-to-diagnose bugs. React-native 0.73.x should also bump this version, but several issues with other dependencies and FB Flipper-related issues have caused complications.
- E2E tests in CI.
- Fixes ACT-1261
Yes
N/A

build(android): increase build tools and sdk version

---

package.json
src/utils/io.ts
yarn.lock

Replace left-over usage of `@ethereumjs/utils` with existing equivalent functions or with functions from `viem`
The only affected function is `uriDataFromJson` from `src/qrcode/schema.ts`.
All tests of this function from `src/qrcode/schema.test.ts` pass.
N/A
Yes

chore(deps): remove @ethereumjs/utils

---

package.json
src/account/SupportContact.tsx
src/send/hooks.test.tsx
src/send/hooks.ts
src/utils/phoneNumbers.ts
yarn.lock

Remove @valora/resolve-kit dependency, so we don't pull all its dependencies (`@celo` sdk, etc), since we just need the types.
N/A
Part of RET-1192
Yes

chore(deps): remove @valora/resolve-kit dependency

---

src/config.ts
src/fiatExchanges/SelectProvider.tsx

Adds a static config parameter to enable/disable fetching FiatConnect quotes.
- Fixes [RET-1145](https://linear.app/valora/issue/RET-1145/[fiatconnect]-make-fetching-fc-quotes-configurable-in-valora)
Yes

feat(config): Parameterize whether or not fiatconnect quotes are supported

---

src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx

Withdraw was incorrectly displayed when a user was not deposited in a pool. This PR fixes that.
N/A
Yes
N/A

fix: only show withdraw when deposited in pool

---

.env.alfajores
.env.alfajoresdev
.env.alfajoresnightly
.env.mainnet
.env.mainnetdev
.env.mainnetnightly

We previously ported onboarding params to be locally configured as preparation for MS development, but forgot to set the environment variables as to disable CPV in onboarding.
Manual tested.
Y

fix(onbaording): Disable CPV in onboarding

---

src/earn/EarnPoolInfoScreen.test.tsx

As the title.
Also fixes the following warning in the tests by updating the way we are using `MockedNavigator` in the tests.
```
Looks like you're passing an inline function for 'component' prop for the screen 'MockedScreen' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.
```
n/a
n/a
Y

fix: use mocked date in EarnPoolInfoScreen test

---

.github/workflows/e2e-ios.yml
fastlane/Fastfile

The new Emergetools indie plan is limited in the number of builds. Ignore errors for now until we decide what we want to do with it.
- Tests pass
N/A
Yes

ci: ignore emergetools errors

---

.github/workflows/release-fastlane-android.yml

Fixes the following error:
```
Run bundle exec fastlane android alfajoresnightly
bundler: failed to load command: fastlane (/home/runner/work/wallet/wallet/vendor/bundle/ruby/2.7.0/bin/fastlane)
/home/runner/work/wallet/wallet/vendor/bundle/ruby/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/erb_template_helper.rb:20:in `<module:Fastlane>': uninitialized constant Fastlane::OpenStruct (NameError)
from /home/runner/work/wallet/wallet/vendor/bundle/ruby/2.7.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/erb_template_helper.rb:1:in `<top (required)>'
```
Fix found in https://github.com/fastlane/fastlane/issues/21944
- Manually ran the [nightly workflow](https://github.com/valora-inc/wallet/actions/runs/10774509140)
See Slack [thread](https://valora-app.slack.com/archives/C02D08P412Q/p1725882 …

ci: fix fastlane error for android releases

---

src/points/ActivityCardSection.tsx
src/points/PointsHome.test.tsx

If multiple pools gate is enabled, navigate to EarnHome instead of Enter Amount screen.
Manually by testing navigation from points screen
N/A
Yes
N/A

fix(earn): navigate to earn home from points screen

---

e2e/scripts/utils.ts

In an effort to [remove Celo dependencies from our e2e tests](https://github.com/valora-inc/wallet/pull/5782), the way we check wallet balances was changed in a subtle way such that wallet balances were being returned as a map from token address to balance rather than token symbol to balance. This caused our funding script to silently stop working, despite never actually failing (it would just decide that the e2e wallets don't need any tokens, and succeed without attempting to send funds). This PR restores the original behavior, fixing the funding scripts.
Manual tested

fix(e2e): Fix funding script

---

renovate.json5

Upgrades `react-native-shake` have caused issues; adding to the Renovate ignore list. 
- [Closed PR from Renovate](https://github.com/valora-inc/wallet/pull/5240)
- [Merged PR from Renovate](https://github.com/valora-inc/wallet/pull/5962) - After closed PR.
N/A
N/A
Yes
N/A

fix(deps): add react-native-shake to renovate ignore list

---

src/config.ts
src/walletConnect/walletConnect.ts

As the title
n/a
- Related to RET-1157
Y

chore: move walletconnect universal link to config

---

src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/navigator/types.tsx

Part 1 of implementing swap and deposit on the enter amount screen. Adds token bottom sheet for selecting a swappable token. If only one token is eligible, defaults to it and no dropdown is shown. Preparing swap + deposit tx will be in a follow up PR
Unit tests, manual (by forcing swap-deposit flow)
https://github.com/user-attachments/assets/707fa7c2-10cb-484b-aad1-d0b9c566674d
- Part of ACT-1356
Yes

feat(earn): show swappable tokens on enter amount screen

---

src/analytics/types.ts
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts

Part 2 of swap + deposit. Builds on #5998. Update existing `prepareDepositTransactions` (renamed from `prepareSupplyTransactions`) to prepare either `deposit` or `swap-deposit` transactions. Displaying swap info will be in the next PR
CI, manual
- Part of ACT-1356
Yes

feat(earn): prepare swap + deposit transaction

---

.github/workflows/e2e-android.yml

Resolves an issue with Android e2e builds:
```text
[CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.
```
- Tested via Android CI.
N/A
Yes
N/A

build(deps): install ninja on android

---

src/points/PointsHome.tsx

Points actions were not closing the bottom sheet after CTA press after #5928 was merged: [Slack Thread](https://valora-app.slack.com/archives/C04B61SJ6DS/p1726675188635229).
N/A
Yes
N/A

fix: close bottom sheet prior to points onPress navigation

---

src/components/FilterChipsCarousel.tsx
src/components/TokenBottomSheet.tsx
src/earn/EarnHome.test.tsx
src/earn/EarnHome.tsx

per Kayla's request 
https://github.com/user-attachments/assets/0a03696e-5169-4c80-b766-4d58c5906c42
updated unit tests, manually tested.

feat(earn): remove token filter

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts

isNative is a required field on the triggerShortcut hook
Manually by preparing a swap + deposit tx w/ non native token (cusd -> usdt deposit)
- N/A
Y

fix(earn): ensure isNative is false and not undefined

---

.github/workflows/e2e-android.yml

We want to test against Android version provided in the the `android-api-level` parameter, but the build should always use the `compileSdkVersion` defined in the `build.gradle` file.
CI succeeds
Part of RET-1194
NA
NA

chore(ci): download Android platform matching the compile SDK version

---

src/earn/saga.test.ts
src/earn/saga.ts

Use the fromToken instead of the depositToken to identify approve tx (works for both deposit and swap-deposit)
Unit tests, manually doing swap deposit from ERC-20 token
- N/A
Yes

fix(earn): approve standby tx handling for swap-deposit

---

src/account/SupportContact.test.tsx
src/account/SupportContact.tsx
src/account/zendesk.test.ts
src/account/zendesk.ts

[Context](https://valora-app.slack.com/archives/C07KBTP7RC2/p1726606329650329) - the ask is to add the app name in the support request body and also add it as a zendesk property so that it can be tracked more easily.
n/a
n/a
Y

chore: add app name to support requests

---

src/earn/EarnPoolInfoScreen.tsx
src/keylessBackup/SignInWithEmail.tsx

Fixes two issues identified with the bottom sheets.
1. Dismisses bottom sheet on onboarding when a user skips cloud account backup.
2. Opens provider URLs in an external browser instead of behind the bottom sheet.
- Tested locally on Android
N/A
Yes
N/A

fix(bottom-sheets): earn url open and onboarding skip

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/positions/saga.ts

Uses the Statsig dynamic config to determine if swap fees should be waived.
Part of ACT-1379
Yes
N/A

fix(earn): use statsig dynamic config for app fee

---

__mocks__/react-native-config.ts
src/config.ts
src/web3/networkConfig.ts

This PR updates the network config file to use the APP_REGISTRY_NAME env variable for the auth headers in networkConfig.ts, to reduce the number of places we need to update the app name.
n/a
n/a
Y

chore: parameterise app name used in auth

---

.github/workflows/e2e-android.yml

Add an explicit step to accept all `sdkmanager` [licenses](https://developer.android.com/tools/sdkmanager#accept-licenses), so the subsequent tooling installations do not fail.
For instance, emulator installation with Android 28 will not fail like it did in this action:
https://github.com/valora-inc/wallet/actions/runs/10996847867/job/30569279072?pr=6031
CI succeeds
Related to RET-1194
NA
NA

chore(ci): accept all Android licenses

---

docs/connecting-dapps.md

Update the links since Valora is now [supported in rainbowkit](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%402.1.6) and the [rainbowkit-celo](https://github.com/celo-org/rainbowkit-celo?tab=readme-ov-file#migrating-away-from-rainbowkit-celo) is sunset.
Fixes #5983 
NA
NA

chore(docs): update rainbowkit recommendation

---

e2e/src/HomeFeed.spec.js
e2e/src/usecases/SecureSend.js

To unblock the CI pipeline temporarily disable the constantly failing E2E tests:
* **Home Feed**, as it is constantly failing after Blockscout discontinued their legacy GraphQL API
Context: https://valora-app.slack.com/archives/C025V1D6F3J/p1727427797940139
CI succeeds
NA
NA
NA

chore(ci): temp disable home feed

---

src/transactions/feed/queryHelper.ts

While debugging using someone's logs the other day, I found myself wading through tons of unnecessary lines of blockchain-api transaction responses. The response was being logged after every data fetch (every 10 seconds), which I think is unnecessary and bloats the stored file size.
n/a
n/a
Y

chore: remove logging of homefeed response

---

src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx

`totalDepositBalanceInCrypto` was being computed incorrectly if there were earningsItems where `includedInPoolBalance` is true and they are in a different token than the deposit token. Fixed this and added a test, also compute `totalDepositBalanceInLocalCurrency` using `totalDepositBalanceInCrypto` rather than doing another filter/reduce.
Updated unit tests and added new ones to prevent same bug in the future
- N/A
Current pools don't have any earningItems where `includedInPoolBalance` is true so no issue, there will be a bug for older versions for Beefy pools though if we separate out compound interest (will show incorrect value).

fix(earn): Compute total deposit amount correctly for EarnPoolInfoScreen

---

src/transactions/feed/EarnFeedItem.test.tsx
src/transactions/feed/EarnFeedItem.tsx
test/values.ts

Use the deposit out and withdraw in amounts in the tx feed item for earn deposit and withdraw instead of the deposit in and withdraw out amounts (which are the LP token amounts)
| <video src="https://github.com/user-attachments/assets/dae7b9dd-393d-4935-bf20-cc7d6cffb65c" /> | <video src="https://github.com/user-attachments/assets/d72b4cbf-71b7-4c45-b2e7-eace230cee92" /> | 
- Part of ACT-1397
Yes

fix(feed): use the right earn amount

---

src/navigator/Headers.tsx

Fixes an iOS 18 only issue where header is shown as `" "`
Tested on multiple versions across iOS and Android w/ @MuckT 
| <img src="https://github.com/user-attachments/assets/4b7521b1-762e-40c7-ab9b-7d78327d5238" width="250" /> | <img src="https://github.com/user-attachments/assets/b5c9aa75-3b0a-4fdf-ab6a-ddf35c1eeaaf" width="250" /> | 
- N/A
yes
N/A

fix(headers): use empty string for title

---

src/positions/saga.test.ts
src/positions/saga.ts
src/statsig/constants.ts
src/statsig/types.ts

and use in getEarnPositions query. Opted to have the default be the empty list and have the legacy default live in hooks ([here](https://github.com/valora-inc/hooks/pull/598)). That way if we need to change the legacy default we can and there won't be BC issues in the wallet (can just change on hooks side without release, goes to all versions).
Dynamic config: https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/dynamic_configs/supported_earn_pools
CI
- Fixes ACT-1367
Yes

feat(earn): Add earn_supported_pools dynamic config

---

src/earn/EarnCollectScreen.test.tsx
src/earn/EarnCollectScreen.tsx
src/earn/EarnPoolInfoScreen.test.tsx
test/values.ts

withdrawToken is not 1:1 with depositToken, need to convert withdrawToken balance to depositToken using pricePerShare
Without change (mismatch):
https://github.com/user-attachments/assets/160417bf-9047-4a63-ae16-5568c08a6861
With change (no mismatch):
https://github.com/user-attachments/assets/f4e01cd0-9005-4c99-a9b8-2a4d7e013fad
- Fixes N/A
Yes

fix(earn): Show correct fiat and token amount on earn collect screen

---

src/positions/selectors.ts
src/positions/types.ts
src/tokens/PositionItem.test.tsx
src/tokens/PositionItem.tsx
test/RootStateSchema.json
test/values.ts

If the positions corresponds to a pool, navigate to the pool info page, otherwise open an internal browser with `manageUrl`.
**Manual:**
EarnPosition:
https://github.com/user-attachments/assets/43e67b34-5b06-4cec-b34e-36adcb2e4f84
Position:
https://github.com/user-attachments/assets/be13ed9c-81bf-4cbe-bd17-c310076a1a3e
- Fixes ACT-1383
Yes

feat(positions): Make positions tappable

---

src/earn/EarnPoolInfoScreen.tsx

https://linear.app/valora/issue/ACT-1407/earn-pool-info-screen-ui-improvement
https://github.com/user-attachments/assets/2dd38a0d-a9b9-4f10-beb0-6d10cc310b0f
| Before |After |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1084f9f7-83d3-4fff-82cc-5df345e8f19b" width="250px"> | <img src="https://github.com/user-attachments/assets/2dd38a0d-a9b9-4f10-beb0-6d10cc310b0f" width="250px"> |
tested manually

fix(earn): fix wrapping and alignments on pool info screen

---

package.json
scripts/generate-release-notes.ts

Here's an improved version of a basic script I was using locally to generate release notes.
Features:
- generate release notes for both "main" and "patch" releases
- excludes cherry-picked commits from the previous release
- detects tag prefix so it also works for Mobile Stack (i.e. no hardcoded "valora")
- verbose mode by default showing what it does (see screenshot), printed to `stderr` so we can pipe `stdout` and get just the release notes
Example usages:
- `yarn generate-release-notes` this is the recommended usage
- `yarn generate-release-notes --lastTag valora-v1.94.2`
- `yarn generate-release-notes --lastTag valora-v1.94.2 --toRef someRef`
In the future, the plan is to use it from our release workflow to create the GitHub Release automatically.
We could also update the nightly …

chore: add script to generate release notes

---

src/home/TabHome.tsx
src/transactions/actions.ts
src/transactions/feed/TransactionFeedV2.test.tsx
src/transactions/feed/TransactionFeedV2.tsx
src/transactions/reducer.ts

4th PR of RET-1207. This implements the cleanup of confirmed stand by transactions that are already present in the feed. Currently, we keep confirmed transactions in `standByTransactions` even if they are present in the pagination data. This is unnecessary as it takes extra space from the persisted storage.
- changed the test that checks merging of pages with stand by transactions
- added test to check if the stand by transaction was correctly removed if it appeared in the pagination data
- Relates to RET-1207
Yes

chore(TransactionFeedV2): Cleanup stand by transactions in Transaction Feed V2

---

locales/base/translation.json
src/analytics/Properties.tsx
src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx
src/positions/types.ts
test/RootStateSchema.json

https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=7514-85993&node-type=instance&m=dev
https://linear.app/valora/issue/ACT-1406/daily-rate
* Daily yield rate in pool info screen when available
* small style fix to learn more link 
https://github.com/user-attachments/assets/9ad04f6c-a06c-4e49-9af5-a9d8c6a2d1f7
https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=7514-85993&node-type=instance&m=dev
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1a9e19cd-48c2-4eb9-ba67-23a864232343" width="250px"> | <img src="https://github.com/user-attachments/assets/05afb6d8-59c3-4786-b4f7-368828b1f667" width="250px"> |
Unit tests and manually verified
https://linear.app/valora/issue/ACT-1406/daily-rate

feat(earn): Show daily yield rate on the pool info screen if available

---

locales/base/translation.json
src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx
src/earn/SafetyCard.test.tsx
src/earn/SafetyCard.tsx
src/positions/types.ts
test/RootStateSchema.json

Part 1 of adding safety score section, showing details / bottom sheet will be in a follow up
unit tests, manually by opening beefy pool
- Part of ACT-1405
Yes

feat(earn): add safety card to pool info screen

---

.github/workflows/e2e-android.yml

Upload E2E test artifacts if an Android test was cancelled (e.g. due to timeout) for better visibility for debugging
CI
NA
NA
NA

chore(e2e): upload artifacts if an Android workflow was cancelled

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnPoolInfoScreen.tsx
src/earn/SafetyCard.test.tsx
src/earn/SafetyCard.tsx
src/positions/types.ts

Implement expandable container to show / hide risks in safety card
https://github.com/user-attachments/assets/97c55657-9980-4150-83a2-ab1ff2b4a334
- Part of ACT-1405
Yes

feat(earn): show risks in safety card on pool info screen

---

src/keylessBackup/SignInWithEmail.tsx

Applying the [fix](https://github.com/mobilestack-xyz/mobilestack-shefi/pull/15) that we made in the shefi project.
n/a
n/a
Y

fix: race condition that prevents recovery phrase from showing sometimes

---

src/dappsExplorer/DappFeaturedActions.tsx
src/earn/EarnActivePools.tsx
src/earn/poolInfoScreen/EarnPoolInfoScreen.tsx

Adjust the ripple for three components on Android:
- Learn more Link in Earn Pool Info Screen
- Reward Card on Discover
- Active Pools Card on Discover
| Learn More Before (Android) | Learn More After (Android) |
| ![](https://github.com/user-attachments/assets/a186e0ea-277a-43d4-a658-2cc69522519e) | ![](https://github.com/user-attachments/assets/bf376070-3430-4017-8561-10e6b6dc8034) | 
| Reward Card Before (Android) | Reward Card After (Android) |
| ![](https://github.com/user-attachments/assets/ad22fca5-5957-44e2-a669-c992afe35589) | ![](https://github.com/user-attachments/assets/24d54390-6942-4068-b8b9-71302d683cd9) |
| Active Pools Before (Android) | Active Pools After (Android) | 
| ![Screenshot 2024-10-21 at 12 04 …

fix(discover): misc android ripple bounds

---

src/home/TabHome.test.tsx
src/home/TabHome.tsx
src/statsig/types.ts

As the title.
While updating the TabHome tests, I noticed every test was throwing an act warning (below) so this PR also updates the tests to remove the errors.
```
Warning: An update to TransactionFeed inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
```
Tested via unit tests and manually.
n/a
Y

feat: add feature gate for zerion transaction feed

---

src/transactions/feed/TransactionFeedV2.test.tsx
src/transactions/feed/TransactionFeedV2.tsx

This PR fixes the merging process of pagination data with stand by transactions. Previously, there were still some stand by transactions that didn't get merged, specifically those that are older than the last transaction from pagination. This PR fixes that by merging all the stand by transactions that are "out of scope" of pagination at the very end of the feed.
Added test that checks proper merging for old stand by transactions
- Relates to RET-1207
Yes

chore(TransactionFeedV2): Merge old stand by transactions that are out of scope of pagination

---

src/account/__snapshots__/AccountKeyEducation.test.tsx.snap
src/account/__snapshots__/GoldEducation.test.tsx.snap
src/components/SegmentedControl.tsx
src/home/__snapshots__/NotificationBox.test.tsx.snap
src/keylessBackup/KeylessBackupIntro.tsx
src/keylessBackup/SignInWithEmail.tsx
src/onboarding/registration/OnboardingRecoveryPhrase.tsx
src/styles/progressDots.ts

Changes include:
- Segmented control defaults to black instead of accent (only used in QR scanner screen)
- Change black to accent in a few places in the CAB / recovery phrase flows
- Change "Sign in another way" from secondary to text button with TextButton
- Remove unused progress dots colors
Checked with design on all these
| Feature | Before | After |
| QR Scanner | <img src="https://github.com/user-attachments/assets/ded2095a-9ce1-4b2f-a25e-757a20f37395" width="250" /> | <img src="https://github.com/user-attachments/assets/99f55dea-dcf7-4591-946f-651ece88e9c7" width="250" /> |
| Onboarding recovery phrase | <img src="https://github.com/user-attachments/assets/e2d85808-ba47-4a8f-b40c-5fd363b9e48e" width="250" /> | <img …

fix: use the right colors

---

src/components/SettingsItem.tsx
src/components/__snapshots__/SettingsItem.test.tsx.snap

Ensured all switch use the custom switch component instead of the native one to be consistent.
| Platform | Before | After |
| iOS | <video src="https://github.com/user-attachments/assets/898a3822-e006-4db5-b131-28023e87c5d7" /> | <video src="https://github.com/user-attachments/assets/52f0ba2e-5c47-4f56-96f9-e801bb535a14" /> |
| Android | <video src="https://github.com/user-attachments/assets/739bc481-dd38-4a52-8e35-2e9b7ce852b2" /> | <video src="https://github.com/user-attachments/assets/5448464a-4824-4c6d-b009-387138834305" /> | 
- Part of ACT-1432
Yes
N/A

fix(settings): use the custom Switch component

---

src/fiatExchanges/quotes/ExternalQuote.test.ts
src/fiatExchanges/quotes/ExternalQuote.ts
src/fiatExchanges/utils.tsx

Relates to this change https://github.com/valora-inc/cloud-functions/commit/fa45ba6cf4855da36109e92f0d5bdaa44eef16e1
unit tests updated

feat(fiatExchanges): support url params on external quotes

---

src/transactions/api.ts
src/transactions/types.ts

We only want to query the non deprecated TX types for the new API.
- Tests pass
N/A
Yes

chore(feedV2): only query non deprecated types

---

locales/base/translation.json
src/transactions/feed/ClaimRewardFeedItem.test.tsx
src/transactions/feed/ClaimRewardFeedItem.tsx
src/transactions/feed/TransactionDetailsScreen.test.tsx
src/transactions/feed/TransactionDetailsScreen.tsx
src/transactions/feed/TransactionFeed.tsx
src/transactions/feed/TransactionFeedItemImage.tsx
src/transactions/feed/TransactionFeedV2.tsx
src/transactions/feed/detailContent/ClaimRewardContent.tsx
src/transactions/types.ts
test/RootStateSchema.json
test/values.ts

Introduce new generic type for the TX feed for claim reward.
`CLAIM_REWARD` replaces `EARN_CLAIM_REWARD`
Why?
1. This allows directly supporting more claim reward TXs, not only for Earn but also GoodDollar, etc.
2. We can do this now without too much effort and keep a "simple" backend implementation for the new `getWalletTransactions`
Similar to what was done in https://github.com/valora-inc/wallet/pull/6189
This is just for the new feed API with Zerion. 
- Tests pass
- Related to RET-1204
- Also see this Slack [thread](https://valora-app.slack.com/archives/C029Z1QMD7B/p1729847488933829) for context
Yes

feat(feedV2): generic claim reward type

---

src/analytics/Properties.tsx
src/transactions/feed/ClaimRewardFeedItem.test.tsx
src/transactions/feed/ClaimRewardFeedItem.tsx
src/transactions/feed/DepositOrWithdrawFeedItem.test.tsx
src/transactions/feed/DepositOrWithdrawFeedItem.tsx
src/transactions/feed/NftFeedItem.tsx
src/transactions/feed/SwapFeedItem.tsx
src/transactions/feed/TokenApprovalFeedItem.tsx
src/transactions/feed/TransferFeedItem.tsx

- Tests pass
See Slack [thread](https://valora-app.slack.com/archives/C02DY3RK79T/p1729846095107579).
Yes

chore: add `itemType` to `transaction_feed_item_select` event

---

src/transactions/feed/detailContent/DepositOrWithdrawContent.tsx

Oops, I inverted from/to in #6189
- Manually checked from/to are now as expected for swap and deposit.
Part of RET-1204
Yes

fix(feedV2): inverted swap from/to for deposits with swap

---

locales/base/translation.json
src/alert/AlertBanner.tsx
src/redux/sagas.ts
src/transactions/feed/TransactionFeedV2.tsx

This PR updates 2 small things related to the transaction feed:
1. update the error state for failure to fetch transactions from banner to toast. we switched from banner to toast in the balances fetch because the banner blocks the navigation buttons at the top and is not dismissable. i also updated the error message because "server connection failed" doesn't fit the voice of the app.
2. omit logging the payload of the transaction feed, this adds extra noise to the logs and the payload (example below) is unhelpful.
`DEBUG  [15:14:33.829Z] iPhone 15 Pro redux/saga@logger {"meta": {"RTK_autoBatch": true, "arg": {"endpointName": "transactionFeedV2", "forceRefetch": true, "originalArgs": [Object], "queryCacheKey": "transactionFeedV2({\"address\":\"0x1d21ee8eb9607f2484d814d83cd3b4714c44d105\",\" …

chore: reduce logging and update error UI for homefeed

---

src/dappsExplorer/DappCard.tsx
src/dappsExplorer/DiscoverDappsCard.tsx

The Explore Dapps Card before this PR had some strange behavior when trying to navigate to all Dapps in that a user must tap the small 'Explore All Dapps' text at the bottom and the ripples on Android were a bit boxy. The changes in touch behavior in this PR make interacting with the card more similar to other cards on the page and more initiative in general.
| Android Before | Android After | 
| ----- | ----- | 
| <video src="https://github.com/user-attachments/assets/2150fa97-e1a0-4a97-8bbe-9214a0d372ed" width="100%" height="auto" /> | <video src="https://github.com/user-attachments/assets/ca2873a3-8d4f-4a2b-a9fd-3ebca3f84239"  width="100%" height="auto" />) |
- N/A
Yes
N/A

fix(discover): make explore dapps card tap behavior intuitive

---

src/transactions/feed/TransactionFeedV2.tsx
src/transactions/selectors.ts
src/transactions/slice.ts

While working on a different feed issue, I've noticed there's a bug in storing the first page of the feed to the persisted storage. TLDR, currently it stores "raw" transactions from pagination, which are not merged with the stand by transactions. This still sometimes causes transactions to rearrange on the first load.
This fix moves updating of the feed from to component level. It contradicts the current [Redux-driven](https://redux.js.org/style-guide/#put-as-much-logic-as-possible-in-reducers) approach as it moves processing that can be managed on reducer level back to the component level but in order to make it follow that guideline we will need to:
- move `paginatedData` to Redux
- move `confirmedTransactions` construction to Redux
- keep `paginatedData` away from persisted storage …

fix(TransactionFeedV2): Fix persisted feed storing unmerged transactions

---

src/tokens/saga.test.ts
src/tokens/saga.ts
src/transactions/api.ts

Updating some query params for `getWalletTransactions` and `getWalletBalances`
Following the new accepted format done in https://github.com/valora-inc/blockchain-api/pull/766 and https://github.com/valora-inc/blockchain-api/pull/769.
It's slightly less verbose when looking at logs.
Also updated `getWalletTransactions` to only request networkIds enabled in statsig.
- Manually checked
- See also this Slack [thread](https://valora-app.slack.com/archives/C029Z1QMD7B/p1731057942380629?thread_ts=1731057749.819289&cid=C029Z1QMD7B)
Yes

chore: use comma separated query params and only query enabled networks

---

src/earn/poolInfoScreen/EarnPoolInfoScreen.tsx

Slight layout adjustment to keep the token icon and name on the same line.
| iOS | Android |
| ----- | ----- | 
| ![](https://github.com/user-attachments/assets/9c481c67-18b5-4eb2-9ce2-8a19b71e2366 "iOS") | ![](https://github.com/user-attachments/assets/39eacd18-69cc-461f-be69-bc5b5086d96e "Android") |
- Fixes ACT-1442
Yes
N/A

feat(earn-info): keep token icon and name on the same line

---

.github/scripts/checkKnipRegression.ts
src/fiatconnect/kyc/KycPending.tsx

Knip used to miss regression if there was no pair category on the base branch. This fixes it.
Context: https://github.com/valora-inc/wallet/pull/6235#pullrequestreview-2439866963
* CI
* Tested manually on this PR (see commits)
NA
Y
NA

chore(knip): enhance knip reliability

---

src/earn/EarnEntrypoint.tsx

- Sets the ripple above the image on Android to be consistent with other items on the screen.
- Uses [`react-native-fast-image`](https://github.com/DylanVann/react-native-fast-image) to display the background image for better performance.
| Android Before | Android After |
| ![](https://github.com/user-attachments/assets/f3f606f6-831a-4e14-bc72-e3ac70bb377f) | ![](https://github.com/user-attachments/assets/df05ac76-7d14-47e4-bd55-55729947cf6c) |
N/A
Yes
N/A

fix(earn): entry point performance and ripple

---

src/account/AccountKeyEducation.tsx
src/account/GoldEducation.tsx
src/navigator/Navigator.tsx
src/navigator/QRNavigator.tsx

After upgrading to react-native-screen v4 in #6217. Some header shifts were observed on iOS for screens using the `slide_from_bottom` animations. This PR removes those animations.
| iOS Before | iOS After |
| ---- | ---- |
| <video src="https://github.com/user-attachments/assets/e364d86a-7ddc-4055-8405-8669ac754ad8"/> | <video src="https://github.com/user-attachments/assets/460cdd09-f982-41c2-9ed9-95700124098e" /> |
Part of ACT-1326
Yes
N/A

fix(headers): remove animations causing header shift on ios

---

src/webview/WebViewScreen.tsx

After merging #6217, there is a residual whitespace after dismissing the keyboard in web views;  this PR removes that whitespace.
| Android Before | Android After | 
| ----- | ----- | 
| <video src="https://github.com/user-attachments/assets/ff6a2386-f8c6-4c17-bc52-4ac1d83620d9" />  | <video src="https://github.com/user-attachments/assets/ba1358fc-63f0-4b34-8cac-ccf7a9edbb95" /> |
N/A
Yes
N/A

fix: remove whitespace at bottom of web-view after keyboard dismiss

---

src/tokens/AssetList.tsx
src/transactions/feed/TransactionFeedV2.tsx

As the title:
1. on the Wallet tab, pull to refresh refreshes balances. the loader is also displayed for any background refreshes.
2. on the Home tab, pull to refresh refreshes only the transaction items. the loader is not displayed for background refreshes.
https://github.com/user-attachments/assets/b0a56779-e02c-4f2f-b5e9-08b2bd6dfd9a
- Fixes RET-1254
Y

feat: update pull to refresh functionality on wallet and home tabs

---

src/jumpstart/slice.ts
src/redux/store.ts

This PR fixes the jumpstart intro seen screen from being shown more than once. The jumpstart slice was part of the redux persist blacklist, now it is removed and the relevant state variables reset on rehydrate.
n/a
n/a
Y

fix: jumpstart intro should only be seen once

---

src/redux/store.test.ts
src/redux/store.ts
src/utils/time.ts

Currently, we have a mechanism in place to log the user's redux store size as an analytics event, however due to a bug in the logic, it only ever gets logged if a user keeps a session open for >24 hours. This PR updates the logic to ensure that the redux store size will be logged as soon as it's first available in a new session, and then subsequently every minute, whenever the full state is serialized.
Unit and manual tested.

fix(analytics): Send redux_store_size event regularly

---

src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx

As the title - this was a copy paste error, restoring it to the [previous logic](https://github.com/valora-inc/wallet/blob/7714ddffef3b08d252fa6e6595b4b4114eb7e28c/src/earn/EarnEnterAmount.tsx#L348).
Applying the max amount now matches the max amount displayed in the withdraw details.
https://github.com/user-attachments/assets/540854a7-9020-4208-930b-e0042c92a025
n/a
Y

fix: incorrect withdraw percentage amount

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/components/TokenBottomSheet.tsx
src/swap/SwapAmountInput.tsx
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx

As the title. Similar to #6240 
https://github.com/user-attachments/assets/8835b87b-7182-4391-b041-92ab70b1ffd1
- Fixes RET-1236
Y

feat: add enter amount percentages on swap screen

---

docs/connecting-dapps.md

MDX parsing with latest docusaurus fails:
```
Error: MDX compilation failed for file "/Users/jean/src/github.com/valora-inc/docs/submodules/wallet/docs/connecting-dapps.md"
Cause: Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)
Details:
{
"column": 27,
"message": "Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)",
"line": 9,
"name": "9:27",
"place": {
"line": 9,
"column": 27,
"offset": 634,
"_index": 0,
"_bufferIndex": 26
},
"reason": "Unexpected character `/` (U+002F) before local name, expected a character that can start a name, …
```

docs: fix link for mdx parsing

---

locales/base/translation.json
src/onboarding/registration/RegulatoryTerms.test.tsx
src/onboarding/registration/RegulatoryTerms.tsx
src/onboarding/welcome/Welcome.test.tsx
src/onboarding/welcome/Welcome.tsx
src/statsig/constants.ts
src/statsig/types.ts

Test experiment added to enum/constants so that CI can pass. With those being empty tests would fail, and looking at git history could not find a time when it was empty. This seemed like the easiest solution, and added a comment explaining.
CI
- Part of ACT-1443
Yes
- N/A

chore(cleanup): Remove onboarding_terms_and_conditions experiment

---

src/statsig/types.ts
src/transactions/feed/TransactionFeed.test.tsx
src/transactions/feed/TransactionFeed.tsx
src/transactions/feed/TransactionFeedV2.test.tsx
src/transactions/feed/TransactionFeedV2.tsx

Title
CI
- Part of ACT-1443
Yes
- N/A

chore(cleanup): Remove show_get_started feature gate

---

src/fiatExchanges/PaymentMethodSection.test.tsx
src/fiatExchanges/SelectProvider.test.tsx
src/fiatExchanges/SelectProvider.tsx
src/fiatExchanges/quotes/ExternalQuote.test.ts
src/fiatExchanges/quotes/ExternalQuote.ts
src/fiatExchanges/quotes/normalizeQuotes.test.ts
src/fiatExchanges/quotes/normalizeQuotes.ts
src/fiatExchanges/types.ts
src/fiatExchanges/utils.tsx
src/web3/networkConfig.ts
test/values.ts

Replace fetchProviders cloud function call with getCicoQuotes
CI - Unit test assertions have been retained for the most part
Manually by checking providers before and after
- Fixes ACT-1421
Yes
N/A

feat(fiatExchanges): use getCicoQuotes endpoint

---

locales/base/translation.json
src/earn/hooks.ts
src/earn/poolInfoScreen/BeforeDepositBottomSheet.test.tsx
src/earn/poolInfoScreen/BeforeDepositBottomSheet.tsx
src/earn/poolInfoScreen/EarnPoolInfoScreen.test.tsx
src/earn/poolInfoScreen/EarnPoolInfoScreen.tsx
src/earn/types.ts

Bottom sheet always shows when tapping deposit, options match designs
Unit tests updated / added
Manual tests (ignore + by deposit, it has been changed to the coins, see image at very bottom for coins icon)
| Case | Allbridge | Aave/Beefy | 
| -----| --------- | ----------- |
| Has deposit token, same chain and different chain | ![everythin-2](https://github.com/user-attachments/assets/e1e557fa-e2b3-4788-b4d3-975757ff368a) | ![everything-1](https://github.com/user-attachments/assets/b617683e-db62-48b4-9019-233fb231ed10) |
| Has deposit token and same chain | ![same-chain-1](https://github.com/user-attachments/assets/5aad2601-6131-494c-a924-0028c5c3559b) | ![same-chain-2](https://github.com/user-attachments/assets/07633c9c-61ee-4301-9805-511b276fdacf) |
| Has deposit token and different …

feat(earn): Update earn deposit entry point bottom sheet

---

__mocks__/@react-native-firebase/dynamic-links.ts
__mocks__/clevertap-react-native.ts
src/app/saga.ts
src/app/useDeepLinks.test.tsx
src/app/useDeepLinks.ts

Per this [update](https://github.com/CleverTap/clevertap-react-native/blob/2c2ab9664b9e83cde936d14b511896d7edd5ecdc/docs/callbackPayloadFormat.md?plain=1#L12) in clever tap docs, this likely slipped through on a clevertap package upgrade
Can't easily test CT push notifications with a dev build, but this has been working on Android, where the url was extracted correctly, and also confirmed with logging on iOS that the deeplink field is present at the top level of the event.
Also tested the 2 callbacks being called scenario by updating the code to call handleOpenUrl twice (one with isSecureOrigin: false and the other with true)  in the Linking event listener, the 2nd call mimics the call that would've been done by the CT push notification listener callback, and also introducing a delay in …

fix(deeplinks): get url from the correct field for CT events

---

src/priceHistory/saga.test.ts
src/priceHistory/saga.ts
src/web3/networkConfig.ts

Fetch price history from the new `https://api.mainnet.valora.xyz/getTokenPriceHistory` enpdoint instead of the blockchain-api.
* Tested manually
* Updated unit test
- Part of RET-1240
Y

chore(tokens): update price history endpoint

---

.github/workflows/e2e-main.yml

Follow up to #6031 
The Android API level must be specified not as a string but as a number, as is expected in [e2e-android.yml](https://github.com/valora-inc/wallet/blob/c6e23572ea8db100a3de9d65f0bae6d3f843b4c3/.github/workflows/e2e-android.yml#L7)
CI works
- Related to RET-1194
NA
NA

chore(ci): specify Android API level as number

---

src/analytics/Properties.tsx
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts
src/earn/saga.test.ts
src/earn/saga.ts
src/statsig/types.ts

Support cross chain swap and deposit behind a statsig feature gate. UI changes not in scope for this PR and will be in a follow up (showing cross chain fees, updating bottom sheet to no longer show cross chain swap as a separate option, showing cross chain fee error if not enough for gas)
Manually tested and ensured 
- Right tokens show up in the expected order (same chain first, then cross chain, by balance within each section)
- Tx submitted and executed sucessfully
https://github.com/user-attachments/assets/8a7fb73b-3f71-4b1d-97da-6e8f53435ec0
[Source chain tx](https://optimistic.etherscan.io/tx/0x22795465cdddbfc29d2cefba6056562401172b867be6dd1cc069e860e7c639cf)
[Destination chain tx](https://arbiscan.io/tx/0x9062beb6d00bc0ba29d9196eabb1cafa439cf689c47cf0fa2c0528a96532454e)
[Alexar …

feat(earn): support cross chain swap and deposit

---

src/earn/poolInfoScreen/BeforeDepositBottomSheet.test.tsx
src/earn/poolInfoScreen/BeforeDepositBottomSheet.tsx

Currently, cross chain swaps show up even if the cross chain swaps gate is off. This updates the before deposit bottom sheet to check for the gate before showing the cross chain swap option. Also simplified the booleans a bit to make it more readable and added more thorough tests
Unit tests
- Part of ACT-1507
Yes
N/A

refactor(earn): check allow X chain swaps gate when showing deposit options

---

src/points/PointsHistoryBottomSheet.test.tsx

As per the title. This change tweaks the test to not expect an exact string but to just check for a partial match.
Context: [thread](https://valora-app.slack.com/archives/C029Z1QMD7B/p1735811485840799)
GH run with an error: [run](https://github.com/valora-inc/wallet/actions/runs/12580445142/job/35062355717?pr=6247)
Tests pass
N/A
Yes

fix: new 2025 year causing one of the PointsHistoryBottomSheet tests to fail

---

locales/base/translation.json
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx

Adds estimated duration and bottom sheet, copied from swap screen
Manual, CI
https://github.com/user-attachments/assets/16c73702-c55b-4416-92c3-270ad5f22859
- Part of ACT-1507
Yes

feat(earn): add estimated duration for x chain swap and deposit

---

src/analytics/Properties.tsx
src/swap/SwapScreen.test.tsx
src/swap/SwapScreen.tsx
src/swap/SwapScreenV2.test.tsx
src/swap/SwapScreenV2.tsx
src/swap/saga.test.ts
src/swap/saga.ts

It is expected that each submitted same-chain swap should result either in success or an error. 
From an analytics perspective, the number of `swap_review_submit` events must equal the sum of `swap_execute_success` and `swap_execute_error` events.
Unfortunately, currently we have more `swap_reveiw_submit` events than the sum of success and error ones. It suggests that either we send duplicated submit events, or miss some success or error events.
This PR adds a `swapId` property shared between sequential swap events to ensure we can trace them in analytics.
Context: https://valora-app.slack.com/archives/C029Z1QMD7B/p1733859318155609
Updated unit tests
- Related to RET-1276
Y

chore(swap): track `swapId` for same-chain swap events

---

locales/base/translation.json

Remore redundant unused translation line.
No testing needed.
N/A
Yes

chore: remove redundant translation line

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/swap/saga.test.ts
src/swap/saga.ts

When the swap is cancelled by the user we [aren't tracking anything](https://github.com/valora-inc/wallet/blob/e72427d4ecad0f011fa859067adb3e78c3884d3f/src/swap/saga.ts#L297-L301). This fixes it.
After this fix, we can expect that the number of submitted same-chain swaps should equal to sum of successful, errored,  _and cancelled_ swaps.
A new event `swap_cancel` is introduced instead of reusing `swap_execute_error` to not contribute to the swap error count.
Updated unit test
- Related to RET-1276
Y

chore(swap): track swap cancel

---

src/components/TokenEnterAmount.test.tsx
src/components/TokenEnterAmount.tsx
src/swap/SwapScreenV2.tsx

This PR fixes SwapScreenV2 incorrect fiat calculations when entering amount in fiat.
P.S. This part will be covered with tests in the follow-up PR for the sake of not withholding the ability to patch the latest release as it appears to be more time-consuming.
https://github.com/user-attachments/assets/47e0c263-00c4-4ad3-b529-48839e28f70c
Fixes RET-1296
Yes

fix: swap amount in fiat is calculated wrong

---

src/analytics/AppAnalytics.test.ts
src/analytics/AppAnalytics.ts
src/config.ts
src/navigator/SettingsMenu.test.tsx
src/navigator/SettingsMenu.tsx
src/statsig/index.test.ts
src/statsig/index.ts

Before this, running the app without a STATSIG_API_KEY was throwing a bunch of errors. And crashing in dev mode in the settings.
See https://github.com/mobilestack-xyz/mobilestack-beefy/pull/2#issuecomment-2573675533
- Tests pass
- Part of RET-1284
Yes

feat: support running without a STATSIG_API_KEY

---

src/keylessBackup/SignInWithEmail.test.tsx
src/navigator/types.tsx
src/onboarding/steps.test.ts
src/onboarding/steps.ts
src/onboarding/success/OnboardingSuccessScreen.tsx
src/verify/VerificationCodeInputScreen.test.tsx
src/verify/VerificationCodeInputScreen.tsx
src/verify/VerificationStartScreen.test.tsx
src/verify/VerificationStartScreen.tsx

Instead of CYA being the last screen, make the success screen the last screen and have it navigate to CYA
Also, consolidate the next functions to make it more DRY and fixes a couple of bugs:
- if protect wallet is disabled, phone verification is never shown even if `skipVerification` is false.
- CAB sign in with email screen skips LinkPhoneNumber screen
Also, update CPV screen to use goToNextOnboardingScreen instead of directly going to the success screen. And fix a bug where the stack is broken after finishing phone verification from a non onboarding flow
Go through onboarding steps and break at different points and ensure success screen is shown.
Link phone number from settings, and ensure back doesn't go back to the phone verification code input screen
| Scenario | Before | After | …

fix(onboarding): ensure success screen is shown always at the end

---

e2e/src/usecases/OnRamps.js

Follow-up PR to prevent the test flake bypassing an issue seen in Detox e2e test builds on Android: the network select modal sometimes renders above the bottom sheet before selection.
Example video on Detox build
https://github.com/user-attachments/assets/343acd4a-986d-42e4-904f-6656acce8c62
Tested in CI.
https://github.com/valora-inc/wallet/pull/6407
Yes
N/A

test(e2e): bypass network select modal when served on reload

---

src/backup/QuizzBottom.tsx
src/components/CircleButton.tsx
src/components/CodeInput.tsx
src/components/CurrencyDisplay.tsx
src/components/DevSkipButton.tsx
src/components/ErrorMessageInline.tsx
src/components/PercentageIndicator.tsx
src/components/SmartTopAlert.tsx
src/dapps/DappShortcutsRewards.tsx
src/earn/poolInfoScreen/SafetyCard.tsx
src/fiatconnect/kyc/KycPending.tsx
src/icons/DataDown.tsx
src/icons/ThumbsUpIllustration.tsx
src/pincode/Pincode.tsx
src/priceHistory/PriceHistoryChart.tsx
src/shared/DisconnectBanner.tsx
src/styles/colors.tsx
src/swap/SwapAmountInput.tsx
src/tokens/TokenImport.tsx

This PR removes the following colors:
- error (replace with errorDark)
- ivory (replace with gray1)
- accentDisabled (since this is technically part of the colors, i just inlined the opacity in the 2 places that need it)
- goldBrand (it wasn't being used except in a loading indicator, which i changed to `accent` like most other loaders)
- infoLight (replace with successLight, it is part of the dapp claim shortcuts card and is not so important)
n/a
Y

chore(colors): remove some deprecated colors

---

src/account/SupportContact.tsx
src/backup/BackupQuiz.tsx
src/components/BottomSheetBase.tsx
src/components/SelectRecipientButton.tsx
src/components/Switch.tsx
src/components/TokenIcon.tsx
src/earn/poolInfoScreen/SafetyCard.test.tsx
src/earn/poolInfoScreen/SafetyCard.tsx
src/home/celebration/NftCelebration.tsx
src/keylessBackup/KeylessBackupPhoneInput.tsx
src/nfts/NftsInfoCarousel.tsx
src/send/EnterAmountOptions.tsx
src/styles/colors.tsx
src/styles/progressDots.ts
src/tokens/AssetList.tsx
src/transactions/UserSection.tsx
src/transactions/feed/NftFeedItem.tsx
src/walletConnect/screens/SessionRequest.tsx
src/webview/WebViewAndroidBottomSheet.tsx

Pretty straightforward, replace gray2 with:
- `backgroundTertiary` when used for backgrounds
- `disabled` for the safety indicators (i intend to rename this in the next PR)
- `bottomSheetHandle` for the bottom sheet
n/a
Y

refactor(colors): replace gray2 with semantic counterparts

---

src/icons/GradientIcon.tsx

As the title - to avoid hard coded "muted" colors here, I am using a semi transparent mask.
no visual changes
Y

fix(colors): avoid hard coded colors in GradientIcon

---

src/components/TokenEnterAmount.test.tsx
src/components/TokenEnterAmount.tsx

When phone number format settings are set to "1.234.567,89" – the number formatting is all over the place. The issue was an `unformatNumberForProcessing` function which was only expecting numbers that were formatted according to the phone's number format settings while SwapScreenV2 was using numbers sent by a prepare transaction quote which are formatted as a regular JS number ("1234567.89"). 
This PR fixes this issue.
N/A
Yes

fix: number is formatted wrong when a dot is a grouping separator

---

src/components/TokenEnterAmount.test.tsx
src/components/TokenEnterAmount.tsx

This PR fixes a bug that prevented local amount from being changed when the local currency symbol has more than 1 character. There are [quite a number of currencies](https://github.com/valora-inc/wallet/blob/753750ba710f12c9d9f2aa005c3d5a4a1e3a0704/src/localCurrency/consts.ts#L50-L95) that fit into this category.
Before:
https://github.com/user-attachments/assets/3aef688d-c5a5-4a87-b8d9-07072c387efd
After:
https://github.com/user-attachments/assets/de3a8e06-b3e5-41a2-a55d-8853955545de
n/a
Y

fix(enter amount): ensure that local amount can be updated always

---

knip.ts
src/components/ReviewTransaction.test.tsx
src/components/ReviewTransaction.tsx

This PR adds an initial structure for the new ReviewTransaction component that is supposed to be used as a common component for all the review screens. The implementation approach was inspired by the way components are utilizing composition in libraries like [shadcn/ui](https://ui.shadcn.com/docs/components/card) and [MUI](https://mui.com/material-ui/guides/composition/).
[Link to the design](https://www.figma.com/design/z88kTrIfLyddOCSiAp2dZV/Updates-for-Consistency?node-id=2487-40727&t=2uUaB4bMg2tpNaz0-4)
Added tests to test the initial configurable aspects of the component.
Relates to RET-1295
Yes

feat(ReviewTransaction): add initial structure for ReviewTransaction component

---

src/components/BottomSheetBase.tsx
src/components/SegmentedControl.tsx
src/components/Toast.tsx
src/components/TokenBalance.tsx
src/home/celebration/ConfettiCelebration.tsx
src/keylessBackup/KeylessBackupIntro.tsx
src/navigator/Navigator.tsx
src/navigator/QRNavigator.tsx
src/qrcode/NotAuthorizedView.tsx
src/qrcode/QRScanner.tsx
src/qrcode/QRTabBar.tsx
src/send/EnterAmountOptions.tsx
src/styles/colors.tsx
src/styles/styles.ts

This PR replaces `backgroundInverse` with other colors, since the concept is not really aligned with how Kayla is using the colors. Now we have:
1. `backgroundScrim` for bottom sheets and underlays
2. `qrTabBar` primary and secondary - these colors are specific to the QR tab segmented control and Kayla suggested that we are able to control them separately.
n/a
Y

refactor(colors): replace backgroundInverse with scrim and qr colors

---

src/icons/CircleArrowIcon.tsx
src/icons/HamburgerCard.tsx
src/styles/colors.tsx
src/styles/styles.ts

The `shadow` color isn't really used in designs by Kayla and doesn't make sense to keep in the palette. The two places it's used can be switched without much visual difference.
These are the two places that were changed, and proof they look okay (although the secure send content really needs to be updated)
Y

refactor(colors): remove shadow color

---

src/components/CircleButton.tsx
src/components/FilterChipsCarousel.tsx
src/components/SmallButton.test.tsx
src/components/SmallButton.tsx
src/components/SmartTopAlert.tsx
src/components/TokenBalance.tsx
src/fiatExchanges/PaymentMethodSection.tsx
src/fiatconnect/TransferStatusScreen.tsx
src/fiatconnect/kyc/KycPending.tsx
src/icons/CrossChainIndicator.tsx
src/icons/Error.tsx
src/onboarding/success/OnboardingSuccessScreen.tsx
src/positions/HooksPreviewModeBanner.tsx
src/recipients/RecipientItemV2.tsx
src/send/EnterAmountOptions.tsx
src/styles/colors.tsx
src/swap/SwapScreen.tsx
src/swap/SwapScreenV2.tsx

Replacing `contentInverse` since this isn't a useful semantic variable for design. Replaced with `contentTertiary` for content on colored backgrounds specifically, and re-evaluated the places that used contentInverse (for the filter chips and enter amount percentage chips, they were replaced with button colors since they should be thought of as buttons. for the swap arrows, use backgroundPrimary because it is the contrast that is needed)
No visual changes for valora
Y

refactor(colors): replace contentInverse

---

src/app/ErrorMessages.ts
src/fiatExchanges/saga.ts
src/firebase/firebase.ts
src/firebase/saga.ts
test/RootStateSchema.json

As the title - currently there are some error banners and logs that are incorrectly triggered.
n/a
- Related to RET-1289
Y

fix: ensure graceful handling of when Firebase is disabled

---

src/app/reducers.ts
src/app/saga.ts
src/earn/hooks.ts
src/earn/poolInfoScreen/EarnPoolInfoScreen.test.tsx
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx
src/home/TabHome.test.tsx
src/jumpstart/JumpstartIntro.test.tsx
src/jumpstart/JumpstartIntro.tsx
src/navigator/selectors.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/tokens/TokenDetails.test.tsx
src/tokens/TokenDetails.tsx
test/RootStateSchema.json
test/schemas.ts

As the title. Useful for apps that then don't need firebase.
n/a
- Related to RET-1289
Y

refactor: move swap feature flag from remote config to statsig

---

e2e/src/usecases/Send.js
src/components/TokenEnterAmount.test.tsx
src/components/TokenEnterAmount.tsx

This PR again tries to fix an ongoing issue with formatting number for TokenEnterAmount component when number format in phone settings is set to `1.234,5678`.
The issue was introduced by [previous attempt](https://github.com/valora-inc/wallet/pull/6428) to fix wrong formatting for Swap flow specifically. 
Previously, the issue was due to unformatting function only expecting numbers that are formatted according to the phone's settings. This caused an issue when on the Swap flow we set the value of "To" textfield with `replaceAmount` function using the value from the quote API response which was a JS-compatible number. This format differed for the users that had format set in settings to `1.234,5678` and caused the actual issue. But this introduced another issue with the wrong formatting …

fix: EnterAmount wrong formatting for "1.234,5678" formatted numbers

---

src/send/SendConfirmation.test.tsx
src/send/SendConfirmation.tsx

Wrong translation was used on the SendConfirmation screen.
N/A
Yes

fix: wrong translation used on SendConfirmation

---

package.json
yarn.lock

Addresses https://github.com/advisories/GHSA-vjh7-7g9h-fjfh
- Tests pass
- See also this Slack [thread](https://valora-app.slack.com/archives/C02N3AR2P2S/p1739800410198379)
Yes

chore(deps): ensure we pull elliptic >= 6.6.1

---

src/divviProtocol/registerReferral.test.ts
src/divviProtocol/registerReferral.ts

This PR ensures that the registration tx only contains protocolId's that the referrer is registered for. This prevents the prepared transaction from containing a protocolId that would cause the tx to revert (thereby blocking the rest of the transaction flow). A builder could be in this situation if they are developing before they are added to the registration contract.
Setting the referrer id to a random string or adding a random protocol id to the app config does not affect the transaction flow.
- Fixes RET-1318
Y

chore: handle referrer not registered in divvi integration

---

e2e/src/usecases/Assets.js
e2e/src/utils/retries.js
src/positions/saga.ts

- Disable positions in the e2e tests as it is introducing too much test flake.
- blacklist the getWalletTransactions endpoint to prevent the tests from hanging on the homefeed (example logs in [this message](https://valora-app.slack.com/archives/C02E2FE98P2/p1740488725090339))
- avoid testing the price chart (i am not sure if this is a real problem, but i did observe some evidence of hanging in [this workflow](https://github.com/valora-inc/wallet/actions/runs/13522535079/job/37784908521) so to unblock us quickly, seems like there's no harm in modifying the test to use a token that doesn't draw the price chart - there's no specific test covering the price chart anyway)
CI passes
n/a
Y

fix: quick fix for e2e test flake

---

src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/fiatconnect/index.test.ts
src/fiatconnect/index.ts
src/fiatconnect/saga.test.ts
src/fiatconnect/saga.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/statsig/types.ts
test/RootStateSchema.json
test/schemas.ts

- Removed `fiatConnectCashInEnabled` as it wasn't defined in Firebase therefore always evaluating to `false`
- Move `fiatConnectCashOutEnabled` to statsig with the same rules as in Firebase
All the tests pass
Relates to RET-1272
Yes

feat: Move fiat connect remote config from firebase to statsig

---

e2e/src/utils/retries.js

Sets the detox device blocklist at launch. Setting at launch is documented [here](https://wix.github.io/Detox/docs/api/device/#11-detoxurlblacklistregexinitialize-the-url-blacklist-at-app-launch).
- Tested locally using Network Link Conditioner with 'Very Bad Network' setting to simulate slow responses.
- Tested in CI by checking for a complete absence of logs, such as:
```Bash
The event "Network Request" is taking place with object: "URL: “https://api.mainnet.valora.xyz/fetchUserLocationData”"
The event "Network Request" is taking place with object: "URL: “[https://api.mainnet.valora.xyz/getTokensInfoWithPrices?networkIds=celo-mainnet,ethereum-mainnet,arbitrum-one,op-mainnet,base-mainnet”](https://api.mainnet.valora.xyz/getTokensInfoWithPrices?networkIds=celo-mainnet,ethereum-mainnet,arbi …
```

test(e2e): avoid waiting for https://api.mainnet.valora.xyz

---

package.json
yarn.lock

Reverts valora-inc/wallet#6519
The patch version upgrade of `react-native-qrcode-svg` causes apps to crash on app start, this PR reverts the upgrade.
The exact error is `Unhandled JS Exception: ReferenceError: Property 'TextEncoder' doesn't exist`, which is shown as an error warning on a simulator but it causes an app crash on a release build on a physical device. Inspecting (Testflight) app open on my physical device on app open, i see the following log: 
```
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes', reason: 'Unhandled JS Exception: ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes, stack:
anonymous@1:2489128
loadModuleImplementation@1:184055 …
```

fix: app crash on start due to bad TextEncoder reference

---

.eslintrc.js
index.tsx
package.json
scripts/generate-release-notes.ts
tsconfig.eslint.json

Running `yarn lint` was successful but wasn't actually doing any work since no path was provided.

fix: eslint not working

---

index.tsx

As the title
Verified that OTA translations are displayed instead of bundled app translations.
- Fixes ENG-196
Y

refactor: move ota translations to app config

---

eas.json

Fixes the following build error on EAS:
```
Running "yarn install" in /Users/expo/workingdir/build/ directory
yarn install v1.22.21
[1/5] Validating package.json...
error @valora/wallet@1.105.0: The engine "node" is incompatible with this module. Expected version "22.14.0". Got "20.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Unknown error. See logs of the Install dependencies build phase for more information.
```
We should probably add a CI check to ensure they always match, so Renovate updating it, won't break release builds (since it only updates it in `package.json`).

ci: fix node version for EAS

---

app.config.js

The simple truthiness check didn't work with a Sentry token environment variable, which led to release information not being uploaded to Sentry.
This PR introduces an explicit check for `undefined` or an empty string to unblock the release.
* Release build
NA
Y
NA

fix(sentry): fix sentry token presence check during build

---

eas.json

Automatically publish Android release to internal testers (similar how it's done to the Nightly builds).
Context: https://valora-app.slack.com/archives/C04B61SJ6DS/p1744191840449979?thread_ts=1744040995.224999&cid=C04B61SJ6DS
* Next release
NA
Y
NA

fix(release): automatically publish Android release to internal testers

---

app.config.js
index.tsx

With the switch to Expo, we missed the intent filters for App Links and `wc` scheme handling needed for WalletConnect to work.
- Checked the generated `AndroidManifest.xml` has the expected content:
```xml
<intent-filter>
<action android:name="android.intent.action.VIEW"/>
<category android:name="android.intent.category.DEFAULT"/>
<category android:name="android.intent.category.BROWSABLE"/>
<data android:scheme="celo"/>
<data android:scheme="wc"/>
<data android:scheme="co.clabs.valora"/>
<data android:scheme="exp+valora"/>
</intent-filter>
<intent-filter android:autoVerify="true" data-generated="true">
<action android:name="android.intent.action.VIEW"/>
<data android:scheme="https" android:host="valoraapp.com"/>
<data android:scheme="https" android:host="vlra.app"/>
<data …
```

fix(android): missing intent filters and wc scheme for walletconnect

---

.github/workflows/e2e-android.yml

Similar to the PR done in [Divvi/mobile](https://github.com/divvi-xyz/divvi-mobile): https://github.com/divvi-xyz/divvi-mobile/pull/213.
N/A
Yes
N/A

ci(e2e): unset android sdk root

---

eas.json

This is to fix the EAS build, following the node version upgrade by Renovate.

chore(release): fix EAS node version to match the one in package.json

---

app.config.js
package.json
yarn.lock

- Upgrades to `"@divvi/mobile": "^1.0.0-alpha.99"` for `@divvi/react-native-keychain` support.
- Upgrades to `"@sentry/react-native": "^6.20.0"`.
- Removes `@react-native-firebase/dynamic-links`.
- ENG-636
Yes
N/A

chore(deps): use divvi mobile alpha 99

---

app.config.js

This restores the behavior we had before the switching to expo: `android:allowBackup="false"`.
Note: I think we should follow up with more changes for future proofing this:
```xml
<application
android:allowBackup="false"
android:fullBackupContent="false"
android:dataExtractionRules="@xml/data_extraction_rules"
...>
```
See https://stackoverflow.com/a/71226351/158525
But it requires a config plugin. and the simple `allowBackup: false` in the expo config should be good enough.
- N/A
- Part of ENG-636
Yes

fix(android): keychain issues after reinstalling the app
