packages/mobile/src/geth/networkConfig.ts
packages/moonpay-auth/.firebaserc
packages/moonpay-auth/src/config.ts
packages/moonpay-auth/src/index.ts

Deploy cloud function to do Moonpay signing in staging environment.
N/A
Manually
- Closes https://github.com/celo-org/celo-monorepo/issues/7109 
Yes

Enable Moonpay in Staging

---

packages/mobile/ios/Podfile.lock
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/locales/en-US/consumerIncentives.json
packages/mobile/locales/es-419/consumerIncentives.json
packages/mobile/locales/pt-BR/consumerIncentives.json
packages/mobile/package.json
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
packages/mobile/src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
packages/mobile/src/consumerIncentives/__snapshots__/ConsumerIncentivesHomeScreen.test.tsx.snap
packages/mobile/src/consumerIncentives/contentFetcher.ts
packages/mobile/src/utils/contentTranslations.ts
yarn.lock

Some UI changes to the Consumer Incentives screen:
N/A
Manually
- Fixes #10
N/A

UI changes for Consumer Incentives screen

---

packages/notification-service/locales/en.json
packages/notification-service/locales/es.json
packages/notification-service/locales/pt.json
packages/notification-service/src/firebase.ts
packages/notification-service/test/firebase.test.ts

The copy for CELO transfers used to be the same as for cUSD transfers. Now it's different (see attached issue)
N/A
Yes
- Fixes #120
N/A

Change copy for CELO transfers

---

packages/mobile/src/fiatExchanges/ProviderOptionsScreen.test.tsx
packages/mobile/src/fiatExchanges/ProviderOptionsScreen.tsx

Re-enable Transak.
N/A
Yes
N/A
Yes

Re-enable Transak

---

packages/mobile/e2e/src/FundedAccount.spec.js
packages/mobile/e2e/src/usecases/Send.js
packages/mobile/e2e/src/utils/utils.js
packages/mobile/src/pincode/PincodeSet.tsx
packages/mobile/src/verify/VerificationEducationScreen.tsx

Fix account initialization in Hotfix PR

---

packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/package.json

Version bump to 1.12.2

---

packages/mobile/src/recipients/recipient.ts

Fix for toUpperCase error
No
No
- Fixes #241
Yes

Fix for toUpperCase error

---

.github/ISSUE_TEMPLATE/config.yml

Minor fix to issue-templates. Had the config saved as `.yaml` instead of `.yml`. Also allowed blank issues for until a new feature template is created.
N/A - Templates cannot be viewed on branches
N/A - No testing needed by QA; however, feedback on new templates will be gathered and implemented at a later date.

chore: update and rename config.yaml to config.yml

---

packages/mobile/e2e/src/usecases/HandleDeepLinkDappkit.js
packages/mobile/src/recipients/RecipientItem.tsx
packages/mobile/src/recipients/__snapshots__/RecipientItem.test.tsx.snap
packages/mobile/src/redux/sagas.ts
packages/mobile/src/send/__snapshots__/Send.test.tsx.snap
packages/mobile/src/verify/VerificationEducationScreen.tsx
packages/mobile/src/verify/saga.ts
packages/mobile/src/web3/dataEncryptionKey.ts

This PR includes 3 fixes:
- Continuous loading” indicator is show on phone number page when user kill & relaunch the app if user is on Phone number page -> The saga was not being initialized on time to handle actions. We now wait on the saga to be ready before firing actions.
- Unable to see phone number for contacts with multiple phone numbers -> We now show it.
- Enter pin” is asking every time when user kill & relaunch the app if user signup through create new account -> We now only try to register the key if the user has a balance, so this will likely not happen and if it does only once.
N/A
Manually on the simulator
- For the continuous loading indicator, create a new account and kill the app on the verification screen. Open it again and see that the loading indicator doesn't last …

P1 fixes for 1.14 release

---

packages/mobile/README.md

Remove the outdated image and touch up a bit

Minor mobile readme updates

---

packages/mobile/src/analytics/Events.tsx
packages/mobile/src/analytics/Properties.tsx
packages/mobile/src/identity/verification.ts
packages/mobile/src/verify/VerificationEducationScreen.tsx
packages/mobile/src/verify/saga.test.ts
packages/mobile/src/verify/saga.ts

Added more verification events and improved some of the error logging (still work to be done on that front)
N/A
- Fixes #
N/A

Add more verification events

---

.github/workflows/checks.yml

This PR implements the general tests check from CircleCI to GitHub Actions. Later PR will implement caching and other optimizations. 
This is replacing the CircleCI config. As long as it does the same thing and passes it doesn't need to be tested further.
No testing needed, just need to verify it passes.
- Implements #520.
GitHub Actions will be replacing CircleCI.

Add general test workflow

---

packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/locales/en-US/onboarding.json
packages/mobile/package.json

Merge back changes done only in https://github.com/celo-org/wallet/tree/release/wallet/1.16.2
- version bump
- Update wording on match making screen to comply with the Play Store user data privacy policy

[Wallet] Merge 1.16.2 release

---

packages/mobile/src/fiatExchanges/__snapshots__/ProviderOptionsScreen.test.tsx.snap
packages/mobile/src/home/NotificationBox.tsx

Changed NotificationBox to a functional component. No behavior changes were made.
N/A
Manually
Just check that the notification tray at the top of the home screen works properly.
- Fixes #925
N/A

Change NotificationBox to a functional component

---

packages/cloud-functions/src/bigQuery.ts
packages/cloud-functions/src/cico/logParser/parseEventLogs.ts
packages/cloud-functions/src/cico/rampWebhook.ts
packages/cloud-functions/src/cico/transakWebhook.schema.sql
packages/cloud-functions/src/cico/transakWebhook.ts
packages/cloud-functions/src/cico/xanpoolWebhook.ts
packages/cloud-functions/src/config.ts

This PR is for an event log parser that will take an input of locally saved Firebase function event logs, parse them, then store them in the appropriate BigQuery table. This is useful because sometimes the Firebase function webhook that should be parsing events fails so this ensures that we don't lose any data due to failures.
- Made the `config` file local friendly by adding optional chaining to params that aren't relevant to the parser
- Removed `BIGQUERY_PROVIDER_STATUS_TABLE` as it's no longer in use
Manually
N/A
- Fixes #927
Yes

CICO firebase function event log parser

---

CONTRIBUTING.md
README.md

The previous README.md was an amalgamation of relics from celo-org/celo-monorepo,
content for non-engineers, content for engineers, content for potential
contributors, ...
Target this README.md for engineers looking to use the code or contribute.

Update and simplify README.md

---

packages/mobile/Gemfile.lock
packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/package.json
packages/mobile/src/account/LicenseDisclaimer.txt

Merge Changes from 1.17.0 version updates back into main.
* 1.17.0
* 1.17.0 (new build)
Co-authored-by: Luna Graysen <luna.graysen@valoraapp.com>
This is backwards compatible

Merge Release/wallet/1.17.0

---

packages/mobile/Gemfile.lock
packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/package.json
packages/mobile/src/account/LicenseDisclaimer.txt

Merge Version Updates from Main into Release
* 1.17.0
* 1.17.0 (new build)
Co-authored-by: Luna Graysen <luna.graysen@valoraapp.com>

Merge Release/wallet/1.17.0 (#1005)

---

packages/mobile/README.md

small updates to README as I onboard
_Describe any minor or "drive-by" changes here._

 update readme

---

packages/mobile/fastlane/Fastfile

Merge in #1099 into release branch.

Fix Ruby Interpolation (Release Branch)

---

packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/package.json
packages/mobile/src/account/LicenseDisclaimer.txt

Version bump from 1.18.3 back into main

Tomm/version bump 1.18.3

---

.github/workflows/check.yml

Add caching to Vulnerability check.
No.
Yes.
N/A.
- #533.
N/A.

Add Yarn caching to Vulnerability check

---

.github/workflows/test.yml

Add Yarn caching to General and Mobile tests.
None.
Will be tested before merging.
N/A.
- #532.
- #531.
N/A.

Add Yarn caching to General and Mobile tests

---

packages/mobile/android/app/build.gradle
packages/mobile/android/gradle.properties
packages/mobile/ios/celo.xcodeproj/project.pbxproj
packages/mobile/package.json
packages/mobile/src/account/LicenseDisclaimer.txt

Pushing the version bump to 1.19
N/A
N/A
N/A
N/A
N/A

1.19 Version bump

---

packages/mobile/src/import/ImportWallet.test.tsx
packages/mobile/src/import/ImportWallet.tsx

As one of the few class components left in the wallet app, I made an attempt to convert the component into a functional component
Maunally tested

Converting `ImportWallet` screen into a functional component

---

packages/notification-service/.eslintrc.js
packages/notification-service/package.json
packages/notification-service/tsconfig.eslint.json
packages/notification-service/tslint.json

cc https://github.com/valora-inc/wallet/issues/784

Move notification-service from tslint to eslint

---

packages/mobile/fastlane/Fastfile

Updating the path to the certificate.
Updated the path in GCP secrets manager.
To be tested.
N/A.
Related to https://github.com/valora-inc/release-automation/pull/27. 
N/A.

Change p8 certificate path in Fastfile 

---

packages/mobile/src/analytics/ValoraAnalytics.ts
packages/mobile/src/analytics/selectors.test.ts
packages/mobile/src/analytics/selectors.ts

We don't want to collect the name since it's personal data.
Updated unit tests.
N/A
- Discussed on [Slack](https://valora-app.slack.com/archives/C02DY3RK79T/p1636370253017200)
Yes

Analytics: remove name from user properties

---

packages/mobile/README.md

Update docs around repo secrets for external contributors

---

.github/workflows/e2e-android.yml
.github/workflows/e2e-ios.yml
packages/mobile/e2e/scripts/fund-e2e-accounts.ts

Prevent e2e tests from running when the balance is too low.
N/A
Tested in CI - [Run with fail on low balance](https://github.com/valora-inc/wallet/runs/4544841078?check_suite_focus=true).
N/A
N/A
Yes

Fail E2E CI check if E2E wallet address balance is too low prior to running tests

---

packages/mobile/e2e/src/usecases/NewAccountOnboarding.js
packages/mobile/src/account/selectors.ts
packages/mobile/src/backup/BackupComplete.tsx
packages/mobile/src/backup/BackupIntroduction.tsx
packages/mobile/src/backup/__snapshots__/BackupComplete.test.tsx.snap
packages/mobile/src/backup/__snapshots__/BackupIntroduction.test.tsx.snap

This PR changes the `BackupComplete.tsx` to a functional component from a class based component.
- Added assert that the `BackComplete.tsx` screen is served during the onboarding e2e tests.
- Updated snapshots with new testID.
Tested locally and with e2e tests.
Complete the new account onboarding an ensure that the backup complete screen with "You're all set" screen is served.
N/A
Yes

Covert Backup Complete to Functional Component

---

packages/mobile/src/app/reducers.ts
packages/mobile/src/app/saga.ts
packages/mobile/src/firebase/firebase.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.e2e.ts
packages/mobile/src/firebase/remoteConfigValuesDefaults.ts
packages/mobile/test/schemas.ts

Closes https://github.com/valora-inc/wallet/issues/1616

Plumbing for dappListApiUri RemoteConfig

---

packages/mobile/src/account/LinkBankAccountScreen.tsx
packages/mobile/src/account/__snapshots__/LinkBankAccountScreen.test.tsx.snap

Since 'Approved' is the terminal state, 'Completed' just means the identity check is complete, but not the custom workflow.
na
snapshot test updated
run tests
na
na

fix: Persona KYC 'completed' should give 'in progress' screen

---

packages/mobile/src/account/SyncBankAccountScreen.test.tsx
packages/mobile/src/account/SyncBankAccountScreen.tsx

manual flow
does not need to be tested by QA

fix(sync-bank-accounts): Call dispatch correctly

---

packages/mobile/src/tokens/reducer.ts

Accidentally merged test code, this PR reverts that.
N/A
N/A
N/A

Remove test code that was merged by accident

---

packages/mobile/package.json
packages/mobile/src/recipients/RecipientPicker.tsx
yarn.lock

Use a nom (e.g., brian.nom) as the recipient when sending funds.

Update to latest version of resolve-kit

---

packages/mobile/src/dappsExplorer/DAppsExplorerScreen.tsx

See section style is bold like in the screenshot above.
- #1953
Yes

Tweak dapps section style

---

packages/mobile/src/navigator/Navigator.tsx

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
_Describe any minor or "drive-by" changes here._

logic simplification idea

---

packages/mobile/src/app/saga.test.ts
packages/mobile/src/app/saga.ts

Fixes an issue identified in valora-issue-reports: https://valora-app.slack.com/archives/C018VLA3YAK/p1646073886204589
Yarn test
The unit tests should be sufficient

fix(cash-in-success): Handle cash-in-success deeplinks with query parameters

---

packages/mobile/src/redux/migrations.test.ts
packages/mobile/src/redux/migrations.ts

Fixes a broken redux migration noted in slack here https://valora-app.slack.com/archives/C029Z1QMD7B/p1646175276299969
Added unit tests to the v35 => v36 Migration

fix(redux): fix typo in redux migration

---

packages/mobile/src/redux/migrations.test.ts
packages/mobile/src/redux/migrations.ts

Fixes a typo in the redux migration 
`yarn test`
Does not need to be tested by QA

fix(redux): fix redux migration bug

---

packages/mobile/src/account/BankAccounts.test.tsx
packages/mobile/src/account/BankAccounts.tsx

Adding a loader when request to fetch bank accounts is inflight
Fixes #2109 
unit tested

fix: add a loader while the bank accounts are loading

---

packages/mobile/src/onboarding/registration/EnableBiometry.test.tsx
packages/mobile/src/onboarding/registration/EnableBiometry.tsx

I fixed part of this bug in https://github.com/valora-inc/wallet/pull/2259 but did not notice that i needed to also fix for the case when biometrics was enabled.
Tested skip verification manually with biometrics enabled.
See that https://github.com/valora-inc/wallet/issues/2183 does not repro.
- Fixes https://github.com/valora-inc/wallet/issues/2183

fix bug with skip verification

---

packages/mobile/src/fiatconnect/index.test.ts
packages/mobile/src/fiatconnect/index.ts
packages/mobile/src/geth/networkConfig.ts

Added a helper to get fiatconnect providers from a cloud function
na
added unit tests
na (not user facing yet)
fixes #1979 
🟢

feat: fiatconnect providers getter

---

packages/mobile/locales/base/translation.json
packages/mobile/src/fiatExchanges/FiatExchangeAmount.tsx
packages/mobile/src/fiatExchanges/__snapshots__/FiatExchangeAmount.test.tsx.snap

fixes #2199 
Adding the currency to the header of add funds screen

copy change to add currency to add funds header

---

.github/workflows/e2e-faucet-balance.yml

Forgot the `runs-on` syntax in the GitHub Action Workflow in #2325
N/A
Tested in CI: https://github.com/valora-inc/wallet/actions/runs/2283801223
Does not need to be tested by QA.
N/A
Yes

Fix Fund E2E Accounts Runs On

---

src/analytics/Properties.tsx
src/fiatExchanges/ExternalExchanges.tsx

Title says it all...
N/A
N/A
N/A
- Fixes #1581 
N/A

Add cash in to tracked property when going to exchanges

---

locales/base/translation.json
src/invite/InviteAndSendModal.tsx
src/invite/saga.test.ts
src/invite/saga.ts
src/send/__snapshots__/SendConfirmation.test.tsx.snap
src/send/__snapshots__/SendConfirmationLegacy.test.tsx.snap

Based on Bugaplooza, we want to send a patch to the release v1.32.0 to update the invite rewards copies. thread -> https://valora-app.slack.com/archives/C018VLA3YAK/p1652902326599269
n/a
no need to test

update invite rewards copy

---

e2e/src/usecases/NewAccountPhoneVerification.js
locales/base/translation.json
src/verify/VerificationEducationScreen.tsx
src/verify/__snapshots__/VerificationEducationScreen.test.tsx.snap

Changing all instances of "confirm" to "connect" when in relation to phone verification for consistency with previous changes in the onboarding flow.

Update "confirm" to "connect" in verification flow 

---

locales/base/translation.json

Some copy updates to the CICO flow

Copy updates

---

locales/base/translation.json

Update to "Linked via {{providerName}}"

Update Connected via {{providerName}}

---

src/fiatExchanges/quotes/FiatConnectQuote.test.ts
src/fiatExchanges/quotes/FiatConnectQuote.ts
src/fiatconnect/ReviewScreen.test.tsx
src/fiatconnect/ReviewScreen.tsx
src/navigator/types.tsx

Use FiatConnectQuote class as a prop on the fiat connect review screen
N/A
Manually, unit tests
N/A. Screen not connected to any flow yet
- Fixes #2557 
N/A

refactor(FiatConnectReviewScreen): use NormalizedQuote class

---

src/services/ReactNativeLogger.ts

Also add a small refactor to avoid too much copy-pasta.
No testing is required.

Add a unix timestamp to console log messages

---

ios/celo.xcodeproj/project.pbxproj
locales/index.ts

As the title
N/A
N/A
You should be able to select Polish for the app language
N/A
N/A

Add Polish language support

---

src/walletConnect/screens/RequestContentRow.tsx

As above
N/A
Manually
As the repro steps in #2646
- Fixes #2646 
Yes

Add 'address copied' alert for dapp connect bottom sheet

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/verify/VerificationEducationScreen.tsx

Adding events for skipping phone verification in onboarding.
Manually went through onboarding on an emulator and saw events being fired correctly
N/A

chore(analytics): Add analytics events for skip verification button

---

.gitignore

title says it all
N/A
N/A
N/A
N/A
N/A

chore(gitignore): ignore brander Home asset

---

WALLET.md

Instructions for using flipper with android simulator 
N/A
N/A
N/A
N/A
N/A

docs(wallet): update flipper docs for android

---

locales/base/translation.json

from: Receive payments directly to your phone number
to: Connect your number to claim funds and connect to friends

Update "Connect number" home card copy

---

src/fiatconnect/saga.test.ts
src/fiatconnect/saga.ts

small refactor addressing feedbackhttps://github.com/valora-inc/wallet/pull/2757#discussion_r939447051
n/A

refactor(fiatconnect-saga): share code better for getting quotes

---

src/firebase/db-rules.json

For https://github.com/valora-inc/in-house-liquidity/pull/639/

chore(firebase): give ihl access to persona node in firebase

---

locales/base/translation.json
src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx
src/home/SendOrRequestBar.tsx

- Change button text to "Submit & Continue"
- Include button as part of scroll view (this doesn't make a difference currently, but if / when there are more input fields, it scrolls correctly to the field in focus)
https://user-images.githubusercontent.com/5062591/184046220-a9769403-b3fc-4677-a6de-b4e2dfa778df.mp4
N/A
Navigate to fiat details screen and ensure button is "Submit & Continue"
- Fixes ACT-181
Yes

fix(fiatconnect): fiat details screen button updates

---

e2e/src/Rewards.spec.js

Skips test that currently redirects to unpublished page.
N/A
Tested in CI.
QA - N/A
Reviewer - Check that iOS e2e tests are passing in CI.
N/A
Yes

test: skip learn more test on rewards as page is not published

---

locales/base/translation.json
src/app/ErrorMessages.ts
src/fiatconnect/FiatDetailsScreen.test.tsx
src/fiatconnect/FiatDetailsScreen.tsx
test/RootStateSchema.json

A few changes for legal https://linear.app/valora/issue/ACT-416/fiatconnect-copy-updates-for-legal
N/A
N/A

fix(cico): Fix some copy for fiatconnect account connecting

---

locales/base/translation.json
src/invite/InviteAndSendModal.tsx
src/invite/saga.ts
src/send/SendConfirmation.tsx

Last few things to get all the copy aligned according to design 
https://www.figma.com/file/DL6Huw867n1EZOVPJ2kNmp/Invite-Rewards?node-id=1748%3A37467
N/A
Manually with remote config on and off
N/A
N/A
yes

chore(invite-rewards): update rewards copy

---

package.json

This ensures packages with any sub dependency also use the git version
N/A
CI
N/A
N/A
yes

chore(deps): use resolution for securerandom

---

src/pincode/PincodeSet.tsx

Fixed the translation string to point to the [correct location](https://github.com/valora-inc/wallet/blob/main/locales/base/translation.json#L729)
n/a
https://linear.app/valora/issue/ACT-417/onboarding-experiment-trusted-guide

fix(pincode): fix translation string

---

.github/workflows/bump-app-version.yml
.github/workflows/check.yml
.github/workflows/e2e-ci.yml
.github/workflows/e2e-faucet-balance.yml
.github/workflows/test.yml
.github/workflows/update-licenses-disclaimer.yml

yarn install often fails due to some race conditions in prepare scripts.
some people found this to work https://github.com/yarnpkg/yarn/issues/6312#issuecomment-429685210
Jean's previous attempt on this was in #2435
na
if ci passes this is probly worth merging
na
na
na

ci(install): trying out fix for yarn install

---

src/analytics/ValoraAnalytics.ts

Made this consistent with other methods (track / identify)
N/A
Running locally
N/A
N/A
N/A

fix(analytics): isEnabled call on page, add debug log

---

src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

As the title, this PR just adds the remote config value.
N/A
N/A
N/A
Relates RET-384
N/A

chore: add remote config for CPV

---

src/in-house-liquidity/index.ts

Fixes 400 response from IHL endpoints that require this header
N/A
Manually running the app and selecting a quote that requires KYC
N/A
N/A
N/A

fix(ihl): cookie name

---

src/account/__mocks__/Persona.tsx
src/fiatconnect/KycLanding.test.tsx

fixes tests on Xiaoyao's dev branch

fix broken tests

---

src/verify/VerificationCodeInputScreen.test.tsx
src/verify/hooks.ts

Add client bundle id for https://valora-app.slack.com/archives/C044B8ULVC0/p1665055690215779
Add DEK public key for comment encryption
N/A
Updated tests, test verification manually
N/A
Relates RET-442
N/A

chore: augment request body of verifyPhoneNumber with extra params

---

src/recipients/RecipientItem.tsx
src/recipients/__snapshots__/RecipientItem.test.tsx.snap
src/send/__snapshots__/Send.test.tsx.snap

Before change:
After change:
N/A
Manually
N/A
N/A
Yes

fix: make contacts details on send screen vertically center

---

locales/base/translation.json

copy update to match latest designs [here](https://www.figma.com/file/bwIY7peeykI8K4wTrXs4iN/Fiat-Connect?node-id=1496%3A34736)
na
tested manually. looks like this:
na
na
na

chore(copy): update t&c copy for fiatconnect link account screen

---

src/swap/saga.test.ts
src/swap/saga.ts

Discussed here https://github.com/valora-inc/wallet/pull/2891#discussion_r990079161 - abstract contract kit logic to make the swaps saga easier to read.
Video of the changes working:
https://user-images.githubusercontent.com/20150449/195814464-ecb3e4e6-e66e-4c3a-8ee1-3b0eb3706ed1.mp4
N/A
Manually verified that swaps can be completed
NA
N/A
Yes

refactor: abstract swap transaction function

---

src/fiatconnect/KycLanding.tsx

Small changes to styling/ navigation to make the KycLanding page smoother
https://user-images.githubusercontent.com/8432644/196290127-69c723ec-a06f-4fa8-9b4c-9c0b8f1b3992.mp4
Manually went through the flow and it seemed much smoother
n/a
https://linear.app/valora/issue/ACT-463/tests-for-full-kyc-flow

fix(fiatconnect): Reduce flashes on KycLanding page

---

locales/base/translation.json
src/fiatExchanges/PaymentMethodSection.test.tsx
src/fiatExchanges/PaymentMethodSection.tsx
src/fiatconnect/TransferStatusScreen.test.tsx
src/fiatconnect/TransferStatusScreen.tsx

- Change mobile money settlement times per https://valora-app.slack.com/archives/C03D3K379FE/p1668556443279829?thread_ts=1668203863.235999&cid=C03D3K379FE
- Made string keys consistent (replaced add/withdraw with cashIn/cashOut)
N/A
N/A
N/A
Yes

refactor(fiatconnect): update some translation strings

---

locales/base/translation.json

copy updates for pending invite notifications

Chore: Update invite notifications copy

---

src/pincode/authentication.ts

This is to facilitate some other work on module resolution. I'm running into issues with this specific change.

Require pin blocklist at the module scope

---

babel.config.js
jest.config.js
locales/package.json
tsconfig.json

I should have included this in 0250f360542781ec3a27ac98cdefd738094c556c.

chore: change method of resolving `locales`

---

locales/base/translation.json

replace "Onvite" with "Invite"

chore: fix typo

---

package.json
yarn.lock

Flagged by depcheck
N/A
CI
N/A
N/A
yes

chore(deps): remove stream-browserify

---

e2e/src/usecases/FiatConnectTransferOut.js
src/fiatExchanges/PaymentMethodSection.tsx

This FC test could only handle cases where there were multiple Bank entries.
N/A

chore(e2e): Fix brittle e2e fc test

---

src/app/reducers.ts
src/app/saga.ts
src/app/selectors.ts
src/firebase/firebase.ts
src/firebase/remoteConfigValuesDefaults.e2e.ts
src/firebase/remoteConfigValuesDefaults.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
test/RootStateSchema.json
test/schemas.ts

chore: celo news remote config flag

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/exchange/CeloNewsFeed.test.tsx
src/exchange/CeloNewsFeed.tsx
src/exchange/CeloNewsFeedItem.test.tsx
src/exchange/CeloNewsFeedItem.tsx

Updated tests.
N/A
- RET-519
Yes

feat(celo-news): add analytics

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/components/EmptyView.tsx
src/exchange/CeloNewsFeed.test.tsx
src/exchange/CeloNewsFeed.tsx
src/web3/networkConfig.ts

Connect the Celo news feed to our API.
**loading + success**
https://user-images.githubusercontent.com/57791/208414473-88673824-0bb2-42ed-abc8-062c0f1f4325.mp4
**loading + error with retry**
https://user-images.githubusercontent.com/57791/208414532-7256d792-392c-4247-832a-128e657398a2.mp4
- Fixes RET-519
Yes

feat(celo-news): connect it to our API

---

package.json
yarn.lock

Flagged by depcheck. I believe this was used by Circle CI as cli tool at some point. https://github.com/valora-inc/wallet/commit/66b9459f3a365b8c3429fb3411058bd78b7340b0
CI
N/A
N/A

chore(dev-deps): remove codecov

---

package.json
yarn.lock

chore(dev-deps): remove react-native-debugger-open

---

.github/workflows/semantic-pr.yml

We decided to use semantic PR title as it can help with automated releases and changelog generation.
Already used in https://github.com/valora-inc/logging/pull/7 and https://github.com/valora-inc/typescript-app-starter/pull/51
N/A
Discussed on [Slack](https://valora-app.slack.com/archives/C025V1D6F3J/p1669991436336709).
N/A

chore: enforce semantic PR title

---

locales/base/translation.json

This is already shipped over the air but we should keep the base translations up to date.
n/a
n/a
Y

chore: update base translations for invite rewards banner

---

src/components/BottomSheetScrollView.tsx

Somewhere along the way I forgot to test this scenario :(
Fix this alignment:
N/A
Y

fix: dapps bottom sheet vertical alignment on phones with notch without scroll

---

locales/base/translation.json

You're offline. --> Error fetching tokens.
If you know their wallet address you can still send a payment or send an invite instead ->> You can still send a payment if you know their wallet address, or send an invite instead

chore: update English copy

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-task.md
.github/workflows/check.yml
.prettierignore
.watchmanconfig
CONTRIBUTING.md
SECURITY.md
WALLET.md
docs/connecting-dapps.md
docs/deeplinks.md
docs/watching-assets.mdx
e2e/README.md
package.json

Same as what we use in https://github.com/valora-inc/typescript-app-starter/blob/9a2ee96b7636985b975bf89d5f71834fe4ed2bc0/package.json#L18-L19

chore: use prettier on all supported files

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx

Title says it all
Unit tests
- Fixes part of ACT-707
Yes

chore(analytics): add events for home screen actions

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/home/ActionsCarousel.test.tsx
src/home/ActionsCarousel.tsx

Less number of metrics to add in statsig / mixpanel and we get breakdown for free
Unit tests
- ACT-707
Yes

refactor(analytics): use a single event for home actions

---

src/components/Card.tsx
src/components/MessagingCard.tsx
src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
src/home/ActionsCarousel.tsx
src/home/DappsCarousel.tsx
src/home/NotificationBox.tsx
src/home/__snapshots__/NotificationBox.test.tsx.snap
src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
src/paymentRequest/__snapshots__/IncomingPaymentRequestListItem.test.tsx.snap
src/paymentRequest/__snapshots__/IncomingPaymentRequestListScreen.test.tsx.snap
src/paymentRequest/__snapshots__/IncomingPaymentRequestSummaryNotification.test.tsx.snap
src/paymentRequest/__snapshots__/OutgoingPaymentRequestListItem.test.tsx.snap
src/paymentRequest/__snapshots__/OutgoingPaymentRequestListScreen.test.tsx.snap
src/paymentRequest/__snapshots__/OutgoingPaymentRequestSummaryNotification.test.tsx.snap

[Figma](https://www.figma.com/file/7kZwdJU5aSHwX6Ie0kjBgK/Core-Wallet-Experiments?node-id=1612-28778&t=nUlbVn8CYsYLa665-0)
[Figma with outline](https://www.figma.com/file/7kZwdJU5aSHwX6Ie0kjBgK/Core-Wallet-Experiments?node-id=1715-28994&t=NkwBiDgQnc5qR37n-0)
Also adjusted some padding. 
Home action variant (showing multiple cards):
https://user-images.githubusercontent.com/5062591/232155068-88d04834-e131-4543-be1a-886b8eec38dc.mp4
| iOS Control | Android |
| --- | ------- |
| <img src="https://user-images.githubusercontent.com/5062591/232155239-8287c250-24a4-432b-a583-f80722949770.png" alt="ios-outline-control.png" width="200"/> | <img src="https://user-images.githubusercontent.com/5062591/232155327-828c88b5-3930-479a-bbfc-0a3630faa728.png" …

feat(home): new shadows for home card, dapps

---

locales/base/translation.json

[Figma](https://www.figma.com/file/SH2DYOMuulfDM7Cqg4aVZm/Send%2FRequest-2023?node-id=1201-121&t=HlnZGar3aJVAwGhF-0)
Manual
| Before Phone verification | After phone verification, Contacts disabled |
| :---: | :---: |
| <img src="https://user-images.githubusercontent.com/5062591/234143825-6f7cb78d-586e-434b-b9c1-8dd75a8cacd4.png" width="200"/> | <img src="https://user-images.githubusercontent.com/5062591/234143822-596beb1f-bbe9-430d-af68-984fc0fa1bfc.png" width="200"/> |
- Fixes ACT-691
Y

chore(send): update banner text for connecting phone and contacts sync

---

src/walletConnect/walletConnect.ts

As the title. Hopefully this fixes some genuine timeout issues in regions where WC is slow.
n/a
- Fixes RET-703
y

chore: increase WC connection timeout

---

src/dappsExplorer/filter/DAppsExplorerScreenFilter.tsx
src/dappsExplorer/searchFilter/DAppsExplorerScreenSearchFilter.tsx

https://valora-app.slack.com/archives/C029Z1QMD7B/p1683217910189549
n/a
n/a
Y

chore: ensure dapp filters bounce on scroll over

---

src/dapps/saga.ts

Relates to https://github.com/valora-inc/wallet/pull/3696#discussion_r1183729437
n/a
n/a
n/a

chore: improve log comments for dapp list fetch

---

src/positions/saga.ts
src/web3/networkConfig.ts

Title says it all ;)
- Waiting for https://github.com/valora-inc/plugins-api/pull/47 to confirm
- N/A
Yes

chore: use load balancer url for getting positions + pass right network

---

renovate.json5

tweaking to make sure rebases, merges and new PRs only take place during non-work hours. see code comments for details
ci
na
na

chore(renovate): update config

---

src/analytics/Properties.tsx
src/swap/SwapReviewScreen.test.tsx
src/swap/SwapReviewScreen.tsx
src/swap/saga.test.ts
src/swap/saga.ts
src/swap/types.ts
test/RootStateSchema.json

This PR is:
* Adding more data to the analytics events of the swap flow.
* Including swap errors in Sentry.
Unit test
- Fixes RET-749
Yes

chore(swaps): Improving analytics events

---

src/account/SupportContact.test.tsx
src/account/SupportContact.tsx

Email validation was only supporting English emails - this should fix that.
- Unit tests updated.
- Fixes [SUP-82](https://linear.app/valora/issue/SUP-82/unable-to-submit-valora-bug-report-unrecognized-tld)
Yes

fix(support): email validation

---

src/fiatExchanges/SelectProvider.test.tsx

Small refactor on unit tests to mock src/statsig instead of statsig-react-native. These tests were written when this module directly integrated with statsig-react-native.
Unit tests
N/A
N/A

test(SelectProvider): refactor statsig mock

---

src/walletConnect/v2/saga.ts

Add support for Android native deeplinks.
- Fixes RET-773
Yes

feat(wc): handle android deeplinks

---

src/nfts/NftGallery.tsx

fix(nft-gallery): last item partially obstructed on devices with the home bar

---

locales/base/translation.json
src/dapps/DappShortcutsRewards.tsx
src/nfts/NftGallery.tsx

As the title - this is in the design and I missed it earlier.
Also fixes the nft gallery title style. <- unrelated but wanted to squeeze it in for the release, it's faster this way
https://github.com/valora-inc/wallet/assets/20150449/341050a0-4df8-4df2-a036-ff2e90a960aa
- Fixes RET-733
Y

feat: add confirming pill on dapp shortcut claim item

---

src/walletConnect/saga.test.ts
src/walletConnect/saga.ts
src/walletConnect/screens/ActionRequest.test.tsx

Title says it all ;)
N/A
N/A
Yes

fix(wc): extra slash in icon path

---

locales/base/translation.json
src/account/Settings.test.tsx
src/account/Settings.tsx
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/components/SettingsItem.test.tsx
src/components/SettingsItem.tsx
src/keylessBackup/utils.ts

Update settings item to match latest designs. Only includes setup and delete. In progress state is in a different issue
[Figma](https://www.figma.com/file/gGp6SVFWMbnSltkGzNzrpC/Wallet-Recovery?node-id=3604%3A30592&mode=dev)
Setup:
https://github.com/valora-inc/wallet/assets/5062591/a54719aa-019d-47dd-bf79-00dc784fcc32
Delete:
- Fixes ACT-765
Yes

feat(keyless-backup): settings item with setup and delete

---

src/analytics/Properties.tsx
src/onboarding/ChooseYourAdventure.test.tsx
src/onboarding/ChooseYourAdventure.tsx

title pretty self explanatory. did a little refactor to support it.
unit test modified
https://linear.app/valora/issue/ACT-872/add-cya-order-of-options-to-cya-later-event
n/a

chore(analytics): log adventure card order on the cya_later event

---

locales/base/translation.json
src/analytics/Properties.tsx
src/keylessBackup/SetUpKeylessBackup.test.tsx
src/keylessBackup/SetUpKeylessBackup.tsx
src/keylessBackup/SignInWithEmail.test.tsx
src/keylessBackup/SignInWithEmail.tsx
src/navigator/types.tsx
test/MockedNavigator.tsx

Added a prop for setup / restore
| Setup | Restore |
| <img src="https://github.com/valora-inc/wallet/assets/5062591/300277dd-6787-4e88-b2d2-4a954ea421d2" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/a3e67dd1-21f1-4298-aeb5-27b5798888fa" width="250" /> | 
N/A
N/A

feat(keyless-backup): update SignInWithEmail to support recovery

---

src/keylessBackup/KeylessBackupProgress.tsx

[Figma](https://www.figma.com/file/gGp6SVFWMbnSltkGzNzrpC/Wallet-Recovery?node-id=3604%3A31336&mode=dev)
Manually
| Status | Before | After |
| Completed | <img src="https://github.com/valora-inc/wallet/assets/5062591/4c844692-b93d-4d20-9de1-7d47900667da" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/c5bcce88-526e-42ae-819e-840d8c9fa5a1" width="250" /> |
| Failed | <img src="https://github.com/valora-inc/wallet/assets/5062591/db64ccce-7da2-48d4-939b-739e79489935" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/89ed62c8-cca4-45a7-a8b9-e3de3543213d" width="250" /> | 
N/A
N/A

fix(keyless-backup): small UI fix on status screen

---

src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/fiatExchanges/SelectProvider.test.tsx
src/fiatExchanges/SelectProvider.tsx

add information for figuring out how often and why few/no quotes appear for users trying to cash in
jest tests
- Fixes https://linear.app/valora/issue/ACT-900/select-provider-screen-additional-analytics
na

chore(analytics): add analytics to select providers screen

---

package.json
tsconfig.json
tsconfig.test.json
yarn.lock

Followup to the viem ticket where typescript was upgraded https://github.com/valora-inc/wallet/pull/4118#discussion_r1310788263

chore(deps): Upgrade typescript to latest

---

src/transactions/feed/queryHelper.ts

https://valora-app.slack.com/archives/C02N3AR2P2S/p1695236773457699

fix(nfts): Fix nft fragment in GraphQL query

---

e2e/src/utils/utils.js

Increases the wait for the cash in bottom sheet in E2E tests.
N/A
Yes

test(e2e): increase wait for cash in bottom sheet

---

src/consumerIncentives/ConsumerIncentivesHomeScreen.test.tsx
src/consumerIncentives/ConsumerIncentivesHomeScreen.tsx
src/home/NotificationBox.tsx
src/home/NotificationCenter.test.tsx
src/navigator/RewardsPill.test.tsx
src/navigator/RewardsPill.tsx
src/statsig/constants.ts
src/statsig/types.ts

The needed logic is described in the linear task.
Updated unit tests, manual testing
- Fixes RET-889
Y

chore: enable restricting supercharge promos

---

src/components/Button.tsx
src/tokens/TokenDetails.tsx

Small styling change based on [Nitya's input](https://www.figma.com/file/OE6RFzqXAMqU9ygHtNYyof?node-id=2793:2267&mode=dev#589139345). Updated action button to use one of the new fonts
Manual
| <img src="https://github.com/valora-inc/wallet/assets/5062591/c606b6de-be4f-49b8-a452-aaab348e0c47" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/84d6ee4a-919d-4684-9b20-7e7837021d12" width="250" /> | 
N/A
Yes

fix(token-details): font style for action button

---

src/swap/saga.test.ts
src/swap/saga.ts

As the title.
Can swap to and from Celo with 0x.
n/a
Y

fix: do not approve swap transaction for native sell token

---

android/build.gradle

As the title. 
https://valora-app.slack.com/archives/C025Q9QG8JG/p1697747488529579?thread_ts=1697615200.465099&cid=C025Q9QG8JG
n/a
n/a
Y

fix!: update minimum supported AndroidSDK to 24

---

src/swap/saga.ts
src/transactions/actions.ts
src/transactions/feed/detailContent/SwapContent.tsx
src/transactions/reducer.ts
src/transactions/saga.ts
src/viem/saga.test.ts
src/viem/saga.ts

As the title https://valora-app.slack.com/archives/C02898GN22V/p1698310629394759?thread_ts=1698304008.767299&cid=C02898GN22V
n/a
RET-894
Y

chore: remove redundant add tx hash to standby tx action

---

src/viem/prepareTransactions.test.ts

A proposal to add a few more tests to https://github.com/valora-inc/wallet/pull/4378

test(viem): add more test cases for prepareTransactions

---

renovate.json5

clarify why WC deps are ignored in renovate config
na
cc https://linear.app/valora/issue/ACT-962/wallet-connect-no-matching-sessions
na

docs: code comment on WC dep skip

---

src/tokens/TokenDetails.test.tsx
src/tokens/TokenDetails.tsx

Fix network param for Add action which was hardcoded to CELO
Unit tests
N/A
Yes

fix(token-details): set correct network param for Add action

---

src/analytics/docs.ts

answering question for Paula and updating docs
na
na
na

docs: explain fetch_balance

---

WALLET.md

Adding docs on reinstalling without building, cleaning derived data
N/A
N/A
N/A

docs(wallet): add docs on quick reinstall, deleting derived data

---

e2e/src/usecases/OffRamps.js

Context https://valora-app.slack.com/archives/C025V1D6F3J/p1701091664887459
Ci passes
n/a
Y

fix(CI): reduce number of expected offramp providers and exchanges

---

src/positions/saga.test.ts
src/positions/saga.ts

https://github.com/valora-inc/hooks/commit/4b6d61f76f101a6d7504bc2c1d99d885638f4016 facilitates more types of shortcuts. We expect at least one to be contributed soon.  The change in this PR will cause that shortcut to work in future versions of Valora.

chore: update hooks to call the v2/getShortcuts endpoint

---

src/home/ActionsCarousel.tsx
src/send/useFetchRecipientVerificationStatus.ts
src/statsig/constants.ts
src/statsig/types.ts

Remove use_new_recipient_screen gate and replace with use_new_send_flow
Manually by overriding the gate to both true and false and going through the flow
N/A
Yes

refactor(send): merge send flow feature gates

---

src/send/utils.test.ts
src/send/utils.ts

This feature fell through the cracks in send flow planning
Unit tests updated
yes

fix(send): support new send flow for QR Scan and pay deeplink

---

src/identity/contactMapping.test.ts
src/identity/contactMapping.ts

This is included in all identity-service requests
Unit tests
- Fixes ACT-994
Yes

feat(identity): add client platform and verison to save contacts request

---

locales/base/translation.json

chore: fix typos

---

src/walletConnect/saga.test.ts
src/walletConnect/saga.ts

`getViemWallet` imports the private key and hence requires the PIN / Biometrics unlock.
Since it was called before showing the WalletConnect request, it caused an unexpected experience for users.
I think we should refactor this as it's a bit unexpected compared to what was happening with ContractKit.
In the meantime, here's an alternative.
Note: Maybe I missed something but I didn't see the loading state of the WC request, and since we now make network requests, there's no visual feedback while this happens, until the signing bottom sheet is displayed. We can fix/investigate this separately.
- Manual tests:
**before**
https://github.com/valora-inc/wallet/assets/57791/7e9f618b-3e0f-4a2b-8dcf-962ee5172ab1
**after** …

fix(wc): PIN / Biometrics asked too early

---

package.json
yarn.lock

Use resolutions to force the version of follow-redirects to resolve CSV: https://github.com/advisories/GHSA-jchw-25xp-jwwc.
CI.
N/A
Yes

build(deps): resolution to use follow-redirects ^1.15.4

---

src/nfts/NftGallery.test.tsx
src/nfts/NftGallery.tsx
src/nfts/saga.test.tsx
src/nfts/saga.ts
src/nfts/slice.ts
src/nfts/types.ts
src/redux/migrations.ts
src/redux/store.test.ts
src/redux/store.ts
src/statsig/constants.ts
src/tokens/Assets.test.tsx
src/tokens/Assets.tsx
test/RootStateSchema.json
test/schemas.ts

Fetch nfts for all supported network ids from [dynamic config](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/dynamic_configs/multi_chain_features/preview/6DUt41gm1Tl6mQbi3LWqm)
Unit tests, manually by using an account with NFTs (thanks @MuckT )
https://github.com/valora-inc/wallet/assets/5062591/cbea165c-bb09-4c1d-ade5-2f8f92adec12
- Fixes ACT-1017
Yes

feat(nft): fetch for all supported networks

---

src/statsig/constants.ts
src/statsig/types.ts

This gate has no reference in code
CI
N/A
N/A

refactor(statsig): remove unused gate constant

---

src/tokens/Assets.tsx

- No more mixed items when switching between tabs in the assets screen
Slack [thread](https://valora-app.slack.com/archives/C04B61SJ6DS/p1706656376321169)
Yes

fix: display issues due to non unique keys for assets

---

src/web3/networkConfig.ts

had wrong base url
tested manually
https://arbiscan.io/tx/0xf29f70cec2261b0fee23b2c0e076d657378e033decfc70cc9194a1b3d6022e83 
na
na

fix(arbitrum): arbiscan link

---

src/icons/Attention.tsx

Fixes attention icon display.
Context: https://valora-app.slack.com/archives/C04B61SJ6DS/p1707152406115999
| ![image](https://github.com/valora-inc/wallet/assets/2737872/a070a327-1dae-4675-a745-832796d3e284) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-06 at 19 51 26](https://github.com/valora-inc/wallet/assets/2737872/e9f8e18a-fd43-43f7-ab04-551c1abab6f5) |
Tested manually
NA
Y

fix: fix attention icon display

---

src/swap/SwapScreen.test.tsx
src/swap/useFilterChips.ts

As the title
n/a
- Related to RET-984
Y

chore(swap): use NETWORK_NAMES for network filters

---

src/components/TokenBottomSheet.tsx

[Context](https://valora-app.slack.com/archives/C04B61SJ6DS/p1707757919681089)
The sticky header is no longer stuck to the wrong place sometimes when launching the bottom sheet.
- Relates to RET-984
Y
Y

fix: token bottom sheet sticky header position

---

locales/base/translation.json
src/account/Profile.tsx
src/account/__snapshots__/Profile.test.tsx.snap

As the title. [Context](https://valora-app.slack.com/archives/C025X4WJT09/p1708361413104609?thread_ts=1708360158.061109&cid=C025X4WJT09) 
n/a
Y

chore: add profile pic disclaimer

---

.github/workflows/semantic-pr.yml

Follow up to #4998, edits a trigger which was causing an error in [Semantic PR Title Check](https://github.com/valora-inc/wallet/actions/runs/8087407245).
N/A
N/A
N/A

ci: edit merge group from semantic pr check

---

.github/workflows/check-translation-files-pr.yml

Follow up to  #4999 & #4998 adds the last `merge_group`.
- Tested in CI.
N/A
N/A
N/A

ci: add merge group to check translation files

---

locales/base/translation.json
package.json
src/home/NotificationBox.test.tsx
src/home/NotificationBox.tsx
src/home/types.ts

fix(keylessBackup): add homecard for keyless backup

---

locales/base/translation.json
src/components/Dialog.tsx
src/components/TextButton.tsx
src/components/__snapshots__/Dialog.test.tsx.snap
src/escrow/__snapshots__/EscrowedPaymentListItem.test.tsx.snap
src/escrow/__snapshots__/EscrowedPaymentListScreen.test.tsx.snap
src/escrow/__snapshots__/EscrowedPaymentReminderSummaryNotification.test.tsx.snap
src/home/__snapshots__/NotificationBox.test.tsx.snap
src/notifications/__snapshots__/SummaryNotification.test.tsx.snap
src/onboarding/registration/ImportSelect.tsx
src/qrcode/__snapshots__/NotAuthorizedView.test.tsx.snap

* Update backup unavailable screen copy
* Backup introduction - update green titles to darker
* Update typography on zero balance
* Link your phone number text
Updating typography on a base component changed a lot of ancient snapshots that I don't think are worth going through

fix(keylessBackup): color/typography/copy nits

---

src/keylessBackup/KeylessBackupIntro.tsx
src/keylessBackup/KeylessBackupPhoneInput.tsx
src/keylessBackup/SignInWithEmail.tsx
src/keylessBackup/WalletSecurityPrimer.tsx

Uses the keyboard aware scroll view to prevent the keyboard from obscuring the 'continue' button when the phone number input is selected. Also sets SafeAreaView to `height: '100%'` instead of `flexGrow: 1` to prevent continue buttons from render off screen when large fonts are used as this can prevent users from advancing to the next screen.
| iOS Before | iOS After | Android Before | Android After| 
| ---- | ---- | ---- | ---- |
| ![](https://github.com/valora-inc/wallet/assets/26950305/affe652e-b51b-4317-84b2-1c7b16eca336) | ![](https://github.com/valora-inc/wallet/assets/26950305/9e21bad8-c657-448c-b48e-614b27e46d9c) | ![](https://github.com/valora-inc/wallet/assets/26950305/0b65d949-cfa6-4d82-afd9-ee79fa1f5dcd) | ![](https://github.com/valora-inc/wallet/assets/26950305/943b5ca3-e701-48 …

fix: prevent phone input number from being hidden behind keyboard

---

locales/base/translation.json

chore(jumpstart): update copy

---

locales/base/translation.json
src/analytics/docs.ts
src/icons/CheckBox.tsx
src/onboarding/welcome/Welcome.test.tsx
src/onboarding/welcome/Welcome.tsx

Updates the welcome screen to include a terms & conditions checkbox depending on the exp configuration
- [Figma](https://www.figma.com/file/mthUlChSbWXXxLe2AV13Wd/Onboarding-2024?type=design&node-id=2062-2326&mode=design&t=rxhrpZ0gIOfdH6yL-0)
- [statsig experiment](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/experiments/onboarding_terms_and_conditions/setup)
| iOS | Android |
| <video src="https://github.com/valora-inc/wallet/assets/5062591/25fd685f-640a-4a6d-89c3-0720a4ea33d9" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/c725b3dc-9e7b-4f01-a7b7-2a10f070bf3c" /> | 
- Fixes ACT-1162
Yes
N/A

feat(onboarding): add terms and conditions checkbox variant

---

e2e/src/CeloPage.spec.js
e2e/src/Discover.spec.js
e2e/src/HomeFeed.spec.js
e2e/src/Pin.spec.js
e2e/src/QRScanner.spec.js
e2e/src/usecases/Assets.js
e2e/src/usecases/ChooseYourAdventure.js
e2e/src/usecases/FiatConnectTransferOut.js
e2e/src/usecases/NewAccountOnboarding.js
e2e/src/usecases/NewAccountPhoneVerification.js
e2e/src/usecases/OffRamps.js
e2e/src/usecases/OnRamps.js
e2e/src/usecases/ResetAccount.js
e2e/src/usecases/RestoreAccountOnboarding.js
e2e/src/usecases/Send.js
e2e/src/usecases/Settings.js
e2e/src/usecases/Support.js

Follow up from #5318. Remove override that is no longer required
CI
- Part of ACT-1133
Yes
N/A

test(e2e): remove use_tab_navigator override

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/statsig/constants.ts
src/statsig/types.ts

Implements the deposit and review bottom sheet. Not integrated with any flow yet
Unit tests and manually integrating on an arbitrary screen (copy out of date)
| iOS | Android |
| <video src="https://github.com/valora-inc/wallet/assets/5062591/89475a60-8ba9-4843-8465-27f1eea07630" /> | <video src="https://github.com/valora-inc/wallet/assets/5062591/dade721d-ff29-4c65-94c2-e348136d6983" /> | 
Yes

feat(earn): add deposit bottom sheet

---

src/earn/EarnAddCryptoBottomSheet.tsx

Add in exchanges to the Transfer option of the Add Crypto bottom sheet
Manual test:
https://github.com/valora-inc/wallet/assets/140328381/de7ec117-4b44-4013-a7f1-e2c107064aa9
- Fixes #ACT-1177
Yes

feat(earn): Add exchanges to Add Crypto bottom sheet

---

.github/ISSUE_TEMPLATE/1-bug-report.md

We'll point any discord devs to file bug reports via GH going forward.
n/a
n/a
n/a
n/a

chore: update bug report issue template

---

locales/base/translation.json

- See slack [thread](https://valora-app.slack.com/archives/C0684TXDR3K/p1715871860339939?thread_ts=1715778214.825739&cid=C0684TXDR3K)
Yes

chore(swap): update app fee bottom sheet copy

---

locales/base/translation.json
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx

Adds copy and strikethrough gas fee if gas is subsidized
Unit test added.
Feature gate false (no change):
Feature gate true (strikethrough value, show copy):
- Fixes #ACT-1195
Yes

feat(earn): Review and deposit updates - gas subsidy

---

scripts/sync_branding.sh

As per the title updates the wallet branding sha.
Related PRs:
- https://github.com/valora-inc/valora-app-branding/pull/32
- https://github.com/valora-inc/valora-website/pull/568
N/A
- Part of ACT-1192
Yes
N/A

chore: update branding sha

---

e2e/src/usecases/FiatConnectTransferOut.js

Couple of fixes
- Increase wait time for tx feed item to appear (60s doesn't seem enough)
- Remove back photo ID, which persona doesn't seem to request now
CI
N/A
N/A
N/A

test(e2e): fix broken fiat connect test

---

scripts/sync_branding.sh
src/earn/EarnInfoScreen.tsx

- Uses the updated "Learn More" URL added in https://github.com/valora-inc/valora-app-branding/pull/36. 
- Increases font size on the page based on early feedback.
| iOS SE Before | iOS SE After | 
| ![](https://github.com/valora-inc/wallet/assets/26950305/acc4eddd-2073-4150-a065-34eb49a9cfd6 "iOS Before") | ![](https://github.com/valora-inc/wallet/assets/26950305/8c685da6-2b5b-464c-a248-194549b4ca72 "iOS After") |
Fixes ACT-1240
Yes
N/A

chore: update earn info screen

---

src/keylessBackup/KeylessBackupPhoneCodeInput.tsx
src/navigator/Navigator.tsx

Use custom header over nav header
| <img src="https://github.com/valora-inc/wallet/assets/5062591/7c889e91-7bcc-4417-91cf-8f8350cb6891" width="250" /> | <img src="https://github.com/valora-inc/wallet/assets/5062591/fac6b3dd-7bb7-4ccc-b602-74464b3f2906" width="250" /> | 
- Part of ACT-1232
Yes
N/A

fix(cab): grey out header when bottom sheet is open

---

locales/base/translation.json

Remove extra space from copy.
Context: https://valora-app.slack.com/archives/C04B61SJ6DS/p1719508165564309?thread_ts=1719507689.657979&cid=C04B61SJ6DS
Test manually
NA
Y
NA

fix(points): fix spacing issue

---

src/earn/prepareTransactions.test.ts
src/earn/prepareTransactions.ts

type(uint).max as amount withdraws max amount
https://github.com/valora-inc/wallet/assets/140328381/1898e259-91fe-4f42-8a99-fb271cb4603e
- Fixes #ACT-1248
Yes

fix(earn): Withdraw entire amount leaving no dust

---

locales/base/translation.json

chore: remove rocket emoji for compliance

---

src/points/ActivityCard.tsx

When the activity description has a quite long text, it does not wrap nicely. This fixes it.
| Issue | Fixed |
| ![image](https://github.com/user-attachments/assets/c97d68d8-6e49-4db6-a1ce-7ce74d6d1d83) | ![image](https://github.com/user-attachments/assets/fa091fbb-2574-4b0b-bf01-8f060c1f73a6) | 
NA
Y
NA

fix(points): fix activity card text wrap issue

---

src/earn/EarnInfoScreen.tsx
src/icons/CircledIcon.tsx

Also updated CircledIcon to a function component.
[Figma](https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=3992-4722&t=0UIxbMax1NwBgdFf-0)
| <img src="https://github.com/user-attachments/assets/e836199e-aa18-4f01-bb21-3156ce561690" width="250" /> | <img src="https://github.com/user-attachments/assets/d480e339-f79b-4726-9f75-2d8b80b67d15" width="250" /> | 
N/A
Yes

fix(earn): update earn info screen icon style

---

src/components/Button.test.tsx
src/components/Button.tsx
src/components/__snapshots__/Button.test.tsx.snap

Needed for buttons in the [earn multiple pool screens](https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=4079-14167&t=jZ5yP2u7JzfIGpuD-0), see #5650 for usage
CI
- Part of ACT-1257
Yes
N/A

refactor(button): support new button style and different text sizes

---

locales/base/translation.json
src/analytics/Events.tsx
src/analytics/Properties.tsx
src/analytics/docs.ts
src/earn/EarnActivePools.test.tsx
src/earn/EarnActivePools.tsx
src/earn/EarnCard.test.tsx
src/earn/EarnCard.tsx

[Figma](https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=4079-14167&t=0UIxbMax1NwBgdFf-0)
- Fixes ACT-1257
Yes

feat(earn): add active pools card for multiple pools

---

src/home/GetStarted.test.tsx
src/home/GetStarted.tsx

[Figma](https://www.figma.com/design/E1rC3MG74qEg5V4tvbeUnU/Stablecoin-Enablement?node-id=4502-4589&t=jZ5yP2u7JzfIGpuD-0)
- Fixes ACT-1257
Yes
N/A

feat(home): adjust get started for multiple pools

---

src/components/IconWithNetworkBadge.test.tsx
src/components/IconWithNetworkBadge.tsx
src/tokens/PositionIcon.tsx

...update IconWithNetworkBadge to have some configurable sizes.

refactor(PositionIcon): use IconWithNetworkBadge

---

src/account/Settings.tsx
src/account/Support.tsx
src/account/__snapshots__/Support.test.tsx.snap
src/backup/BackupIntroduction.tsx
src/language/Language.tsx
src/localCurrency/SelectLocalCurrency.tsx
src/walletConnect/screens/Sessions.tsx

As the title
n/a
- Fixes RET-1165
Y

fix: update screen titles to use typescale fonts

---

src/swap/saga.ts
src/tokens/saga.ts

chore: remove unused code

---

locales/base/translation.json

[Context](https://valora-app.slack.com/archives/C0684TXDR3K/p1722967353948639)
n/a
n/a
Y

chore(swap): update cross chain copy

---

WALLET.md

As the title.
n/a
- Related to RET-1156
Y

docs: update README for branding changes

---

src/components/multiSelect/MultiSelectBottomSheet.tsx

| | iOS | Android |
| Default | <img src="https://github.com/user-attachments/assets/1fd43e3d-4471-4a6d-9653-a76244e3ac66" width="250" /> | <img src="https://github.com/user-attachments/assets/0da87922-6f13-48f0-8c4f-7c8afe96ef31" width="250" /> |
| Many items | <img src="https://github.com/user-attachments/assets/85b474ec-41fe-45d5-8483-915d87f27aa3" width="250" /> | <img src="https://github.com/user-attachments/assets/b7cf078a-772d-4705-95c6-7dbe00f47dac" width="250" /> |
| Large font | <img src="https://github.com/user-attachments/assets/0a99a6c3-d12c-4a01-8e10-e1ad04783bff" width="250" /> | <img src="https://github.com/user-attachments/assets/2f4aa5f5-41d1-4536-9c62-60aa2615f125" width="250" /> |
- Fixes ACT-1330
N/A
If a new NetworkId and/or Network are …

fix(multi-select): increase max items in view

---

locales/base/translation.json
src/points/PointsHome.tsx

Designs [here](https://www.figma.com/design/rXBDplfMHHqYmuu6EkgMEo/Valora-Points?node-id=2124-11902&t=8SdX4wAwRvZrQeQs-0).
n/a
n/a
Y

chore: update points disclaimer copy

---

src/positions/saga.test.ts
src/positions/saga.ts

Title
Unit tests updated
Wasn't sure how to test e2e, since the translations files haven't been generated yet so any request to the hooks API would just use the fallback `base.json` file.
- Fixes ACT-1331
Yes

feat(earn): Add language to positions hooks request

---

src/utils/Countries.test.ts
src/utils/Countries.ts
src/utils/address.test.ts
src/utils/address.ts
src/utils/displayFormatting.ts
src/utils/ecies.test.ts
src/utils/ecies.ts
src/utils/getCountryEmoji.ts
src/utils/inputValidation.test.ts
src/utils/inputValidation.ts
src/utils/io.ts
src/utils/parsing.test.ts
src/utils/parsing.ts
src/utils/phoneNumber.test.ts
src/utils/phoneNumbers.ts
src/utils/sign-typed-data-utils.ts
src/utils/string.ts
src/web3/KeychainWallet.test.ts
src/web3/saga.test.ts

Follow-up PR to improve and cleanup commits 
N/A
- Relates to RET-1187
Yes

chore(deps): change reference GH links to immutable and replace "isValidChecksumAddress" to viem equivalent

---

README.md
RELEASES.md

Add release automation information to the README.
- Related to RET-1161
NA
NA

chore(ci): update readme

---

locales/base/translation.json
src/earn/EarnHome.tsx

https://valora-app.slack.com/archives/C03D3K379FE/p1725644092330379
- Tested locally
- N/A
Yes

fix(earn): Copy updates

---

src/home/ActionsCarousel.tsx
src/home/TabHome.test.tsx
src/home/TabHome.tsx
src/statsig/index.ts

Remove "Welcome" title from Home Tab
Adjust existing TabHome tests
- Relates to RET-1189
Yes

chore: remove "Welcome" title from Home Tab

---

ios/Podfile.lock
package.json
yarn.lock

Reverts valora-inc/wallet#5962

chore(deps): revert update dependency react-native-shake to ^5.6.2

---

src/analytics/Properties.tsx
src/earn/EarnEnterAmount.test.tsx
src/earn/EarnEnterAmount.tsx
src/earn/EarnPoolInfoScreen.tsx
src/earn/prepareTransactions.ts
src/earn/types.ts
src/earn/utils.ts
src/navigator/types.tsx

- Shared type for deposit mode
- Shared fn for getting swap to amount (useful for the bottom sheet)
- Remove wrapped Text to avoid double Text components
CI
- Part of ACT-1358
Yes

refactor(earn): misc deposit cleanup

---

ios/MobileStack.xcodeproj/project.pbxproj
src/components/LabelWithInfo.tsx
src/earn/EarnDepositBottomSheet.test.tsx
src/earn/EarnDepositBottomSheet.tsx
src/earn/EarnEnterAmount.tsx
src/earn/EarnPoolInfoScreen.tsx

* share code more for label and icon
* both label and info icon are touchable
* dismiss bottomsheet for webview openings
https://github.com/user-attachments/assets/0d36d450-5996-426f-b0bf-130fe08f27c3
https://github.com/user-attachments/assets/f7c28a05-b52a-4b49-b14f-597ac3ac80b2

fix(earn): clean up info icons

---

src/earn/EarnPoolInfoScreen.tsx

fix(earn): fix deposit label being cutoff

---

src/earn/saga.test.ts
src/earn/saga.ts
src/transactions/actions.ts
src/transactions/types.ts
test/RootStateSchema.json

title
https://github.com/user-attachments/assets/3b39f849-80b8-4f5c-ad9b-d94d1cedc067
Unit tests updated
- Fixes ACT-1361
Yes

feat(earn): Add pending transaction for EarnSwapDeposit

---

renovate.json5

Avoids root state schema changes in PRs like https://github.com/valora-inc/wallet/pull/6065 and https://github.com/valora-inc/wallet/pull/6066
N/A
N/A
N/A
N/A

chore(deps): group walletconnect dependencies

---

locales/base/translation.json
src/analytics/Properties.tsx
src/earn/EarnPoolInfoScreen.test.tsx
src/earn/EarnPoolInfoScreen.tsx
src/earn/SafetyCard.test.tsx
src/earn/SafetyCard.tsx

As the title
https://github.com/user-attachments/assets/12648e84-c6e0-4212-b602-c88d46d05887
- Fixes ACT-1405
Yes

feat(earn): add safety score bottom sheet

---

locales/base/translation.json
src/transactions/feed/DepositOrWithdrawFeedItem.test.tsx
src/transactions/feed/DepositOrWithdrawFeedItem.tsx
src/transactions/feed/TransactionDetailsScreen.test.tsx
src/transactions/feed/TransactionDetailsScreen.tsx
src/transactions/feed/detailContent/DepositOrWithdrawContent.tsx

Follow up to https://github.com/valora-inc/wallet/pull/6189 with small bugs that I noticed.
- Part of RET-1204
Yes

fix(feedV2): fix missing title, subtitle, localAmount for deposit and withdraw

---

src/keylessBackup/SignInWithEmail.test.tsx
src/keylessBackup/SignInWithEmail.tsx

See Slack thread [here](https://valora-app.slack.com/archives/C07KBTP7RC2/p1730734326274629).

fix(recovery): Fix CAB recovery bug

---

yarn.lock

Example error https://github.com/valora-inc/wallet/actions/runs/11894680060/job/33142458748?pr=6240
n/a
n/a
Y

chore: upgrade cross-spawn to address vulnerability alert

---

src/components/GradientBlock.tsx
src/icons/GradientIcon.tsx
src/points/PointsDiscoverCard.tsx
src/styles/colors.tsx

feat(points): Add gradient border to points pill

---

src/fiatExchanges/utils.tsx
src/web3/networkConfig.ts

As the title
CI
- Part of ACT-1421
Yes
N/A

refactor(fiatExchanges): remove fetchProviders references

---

src/app/saga.ts
src/app/useDeepLinks.ts

Adding additional logs on sources of deep links. 
CI
- Part of ACT-1469
Y
N/A

refactor(deeplinks): add additional logging

---

src/app/useDeepLinks.ts

As the title
N/A
- Part of ACT-1469
N/A
N/A

refactor(deeplinks): add more logs

---

src/earn/poolInfoScreen/BeforeDepositBottomSheet.tsx

chore(earn): Add comments explaining non trivial booleans in deposit bottom sheet

---

e2e/src/usecases/OnRamps.js

As per the title, add a static sleep to wait for the bottom sheet load: [Slack thread](https://valora-app.slack.com/archives/C025V1D6F3J/p1736432535238499).
Tested in CI.
N/A
Yes
N/A

test(e2e): add static sleep to wait for bottom sheet animation

---

src/earn/EarnEnterAmount.tsx

chore: Add in font to EarnEnterAmount text style

---

index.tsx

Enable some experimental settings to restore the Notification center, Invite, and Phone verification functionality.
* Visual assessment
NA
Y

fix: bring back the Notification center, Invite, and Phone verification

---

app.config.js
eas.json

Remove Alfajores app build settings as we discontinue the Alfajores releases.
CI
NA
NA
NA

chore(build): remove Alfajores build settings

---

app.config.js
knip.ts
package.json

* Install `@sentry/react-native` as a dependency following https://github.com/divvi-xyz/divvi-mobile/pull/196
* Revert #6620 as irrelevant
* Release build
NA
Y
NA

fix(sentry): install `@sentry/react-native` as a dependency

---

README.md

Removes the now invalid Test badge seen on the `README.md`.
N/A
N/A
N/A
N/A

docs(badge): remove invalid mobile test badge

---

yarn.lock

Update `form-data` to address https://github.com/advisories/GHSA-fjxv-7rqg-78g4
CI passes
N/A
Yes

fix(deps): update form-data

---

package.json
yarn.lock

Reverts changes to the splash screen to maintain gradient backgrounds.
N/A
Yes
N/A

fix(deps): revert changes to splash screen

---

app.config.js
index.tsx
package.json
plugins/withDesugaring.js
yarn.lock

This PR adds config for recaptcha.
Tested the phone verification and CAB restore flows on local ios / android builds (against the deployed cloud functions).
- Fixes ENG-442
Y

feat: add recaptcha for phone verification
